In [1]:
# Aula 3
import pandas as pd

In [3]:
# carregando dataset corretamente ==> neste caso usa o separador ';'.
data = pd.read_csv('./sample_data/GasPricesinBrazil_2004-2019.csv', sep=";")

In [4]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127.0,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5.0,2004.0
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387.0,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5.0,2004.0
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192.0,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5.0,2004.0
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162.0,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5.0,2004.0
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103.0,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5.0,2004.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52472,52472,2010-10-03,2010-10-09,NORTE,PARA,ÓLEO DIESEL,178.0,R$/l,2.073,0.111,...,2.400,0.235,0.054,1.838,0.044,1.765,1.9329,0.024,10.0,2010.0
52473,52473,2010-10-03,2010-10-09,NORTE,RONDONIA,ÓLEO DIESEL,103.0,R$/l,2.200,0.054,...,2.300,0.294,0.025,1.906,0.043,1.798,1.939,0.023,10.0,2010.0
52474,52474,2010-10-03,2010-10-09,NORTE,RORAIMA,ÓLEO DIESEL,34.0,R$/l,2.393,0.042,...,2.600,0.406,0.018,1.987,0.074,1.9,2.0875,0.037,10.0,2010.0
52475,52475,2010-10-03,2010-10-09,NORTE,TOCANTINS,ÓLEO DIESEL,59.0,R$/l,2.066,0.066,...,2.150,0.214,0.032,1.852,0.075,1.706,1.899,0.04,10.0,2010.0
52476,52476,2010-10-03,2010-10-09,SUDESTE,ESPIRITO SANTO,ÓLEO DIE,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir da Lista,PREÇO MÉDIO DE REVENDA (dólares)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127.0,R$/l,1.288,0.016,...,0.825,0.11,0.4201,0.9666,0.133,5.0,2004.0,DEFAULT,0,7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387.0,R$/l,1.162,0.114,...,0.763,0.088,0.5013,1.05,0.115,5.0,2004.0,DEFAULT,1,6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192.0,R$/l,1.389,0.097,...,0.97,0.095,0.5614,1.161,0.098,5.0,2004.0,DEFAULT,2,8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162.0,R$/l,1.262,0.070,...,0.83,0.119,0.5991,1.22242,0.143,5.0,2004.0,DEFAULT,3,7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103.0,R$/l,1.181,0.078,...,0.941,0.077,0.7441,1.0317,0.082,5.0,2004.0,DEFAULT,4,7.086

In [25]:
# Selecionando a linha 1 ===> observação de índice [1] do dataframe
data.iloc[1]

Unnamed: 0                                         1
DATA INICIAL                              2004-05-09
DATA FINAL                                2004-05-15
REGIÃO                                  CENTRO OESTE
ESTADO                                         GOIAS
PRODUTO                             ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                   387.0
UNIDADE DE MEDIDA                               R$/l
PREÇO MÉDIO REVENDA                            1.162
DESVIO PADRÃO REVENDA                          0.114
PREÇO MÍNIMO REVENDA                            0.89
PREÇO MÁXIMO REVENDA                           1.449
MARGEM MÉDIA REVENDA                           0.399
COEF DE VARIAÇÃO REVENDA                       0.098
PREÇO MÉDIO DISTRIBUIÇÃO                       0.763
DESVIO PADRÃO DISTRIBUIÇÃO                     0.088
PREÇO MÍNIMO DISTRIBUIÇÃO                     0.5013
PREÇO MÁXIMO DISTRIBUIÇÃO                       1.05
COEF DE VARIAÇÃO DISTRIBUIÇÃO                  0.115
MÊS                                              5.0
ANO                                           2004.0
coluna sem nocao                             DEFAULT
coluna a partir da Lista                           1
PREÇO MÉDIO DE REVENDA (dólares)               6.972
Name: 1, dtype: object

In [26]:
# selecionando as linhas de índice de 0 a 5 (incluso)
data.iloc[:6]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir da Lista,PREÇO MÉDIO DE REVENDA (dólares)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127.0,R$/l,1.288,0.016,...,0.825,0.11,0.4201,0.9666,0.133,5.0,2004.0,DEFAULT,0,7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387.0,R$/l,1.162,0.114,...,0.763,0.088,0.5013,1.05,0.115,5.0,2004.0,DEFAULT,1,6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192.0,R$/l,1.389,0.097,...,0.97,0.095,0.5614,1.161,0.098,5.0,2004.0,DEFAULT,2,8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162.0,R$/l,1.262,0.070,...,0.83,0.119,0.5991,1.22242,0.143,5.0,2004.0,DEFAULT,3,7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103.0,R$/l,1.181,0.078,...,0.941,0.077,0.7441,1.0317,0.082,5.0,2004.0,DEFAULT,4,7.086
5,5,2004-05-09,2004-05-15,NORDESTE,BAHIA,ETANOL HIDRATADO,408.0,R$/l,1.383,0.132,...,0.957,0.128,0.5686,1.35,0.134,5.0,2004.0,DEFAULT,5,8.298

In [27]:
# selecionando as linhas de índice de 10 a 15 (incluso)
data.iloc[10:16]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir da Lista,PREÇO MÉDIO DE REVENDA (dólares)
10,10,2004-05-09,2004-05-15,NORDESTE,PIAUI,ETANOL HIDRATADO,89.0,R$/l,1.573,0.134,...,1.079,0.078,0.8857,1.2499,0.072,5.0,2004.0,DEFAULT,10,9.438
11,11,2004-05-09,2004-05-15,NORDESTE,RIO GRANDE DO NORTE,ETANOL HIDRATADO,131.0,R$/l,1.276,0.116,...,0.944,0.078,0.7119,1.1386,0.083,5.0,2004.0,DEFAULT,11,7.656
12,12,2004-05-09,2004-05-15,NORDESTE,SERGIPE,ETANOL HIDRATADO,57.0,R$/l,1.301,0.109,...,0.98,0.052,0.8267,1.1059,0.053,5.0,2004.0,DEFAULT,12,7.806
13,13,2004-05-09,2004-05-15,NORTE,ACRE,ETANOL HIDRATADO,33.0,R$/l,1.805,0.134,...,1.116,0.171,0.767,1.2992,0.153,5.0,2004.0,DEFAULT,13,10.830
14,14,2004-05-09,2004-05-15,NORTE,AMAPA,ETANOL HIDRATADO,15.0,R$/l,1.785,0.035,...,1.373,0.167,0.8339,1.4912,0.122,5.0,2004.0,DEFAULT,14,10.710
15,15,2004-05-09,2004-05-15,NORTE,AMAZONAS,ETANOL HIDRATADO,53.0,R$/l,1.578,0.123,...,1.137,0.068,0.9515,1.2109,0.06,5.0,2004.0,DEFAULT,15,9.468

In [28]:
# selecionando as linhas/observações de índice 1, 5, 10, 15
data.iloc[[1, 5, 10, 15]]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir da Lista,PREÇO MÉDIO DE REVENDA (dólares)
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387.0,R$/l,1.162,0.114,...,0.763,0.088,0.5013,1.05,0.115,5.0,2004.0,DEFAULT,1,6.972
5,5,2004-05-09,2004-05-15,NORDESTE,BAHIA,ETANOL HIDRATADO,408.0,R$/l,1.383,0.132,...,0.957,0.128,0.5686,1.35,0.134,5.0,2004.0,DEFAULT,5,8.298
10,10,2004-05-09,2004-05-15,NORDESTE,PIAUI,ETANOL HIDRATADO,89.0,R$/l,1.573,0.134,...,1.079,0.078,0.8857,1.2499,0.072,5.0,2004.0,DEFAULT,10,9.438
15,15,2004-05-09,2004-05-15,NORTE,AMAZONAS,ETANOL HIDRATADO,53.0,R$/l,1.578,0.123,...,1.137,0.068,0.9515,1.2109,0.06,5.0,2004.0,DEFAULT,15,9.468

In [29]:
# selecionando as linhas/observações de índices 5, 1, 15, 10
data.iloc[[5, 1, 15, 10]]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir da Lista,PREÇO MÉDIO DE REVENDA (dólares)
5,5,2004-05-09,2004-05-15,NORDESTE,BAHIA,ETANOL HIDRATADO,408.0,R$/l,1.383,0.132,...,0.957,0.128,0.5686,1.35,0.134,5.0,2004.0,DEFAULT,5,8.298
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387.0,R$/l,1.162,0.114,...,0.763,0.088,0.5013,1.05,0.115,5.0,2004.0,DEFAULT,1,6.972
15,15,2004-05-09,2004-05-15,NORTE,AMAZONAS,ETANOL HIDRATADO,53.0,R$/l,1.578,0.123,...,1.137,0.068,0.9515,1.2109,0.06,5.0,2004.0,DEFAULT,15,9.468
10,10,2004-05-09,2004-05-15,NORDESTE,PIAUI,ETANOL HIDRATADO,89.0,R$/l,1.573,0.134,...,1.079,0.078,0.8857,1.2499,0.072,5.0,2004.0,DEFAULT,10,9.438

In [30]:
# retornar o valor da linha de índice 1, coluna 4 ('ESTADO')
data.iloc[1, 4]

'GOIAS'