In [85]:
!pip install -U plotly

1959.31s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: plotly in /home/youx/.local/lib/python3.10/site-packages (6.5.1)
Requirement already satisfied: packaging in /home/youx/.local/lib/python3.10/site-packages (from plotly) (25.0)
Requirement already satisfied: narwhals>=1.15.1 in /home/youx/.local/lib/python3.10/site-packages (from plotly) (2.15.0)

In [78]:
import pandas as pd
import plotly.express as px

In [79]:
df = pd.read_csv("tips.csv")

In [80]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

## Histogramas

In [81]:
px.histogram(df, x="total_bill", color="time", nbins=40,
            histnorm="probability density", marginal="box",
            title="Histograma da taxa paga no restaurante", color_discrete_sequence=["green", "orange"])

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'bingroup': 'x',
              'histnorm': 'probability density',
              'hovertemplate': 'time=Dinner<br>total_bill=%{x}<br>probability density=%{y}<extra></extra>',
              'legendgroup': 'Dinner',
              'marker': {'color': 'green', 'pattern': {'shape': ''}},
              'name': 'Dinner',
              'nbinsx': 40,
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('PQrXo3D9MECuR+F6FK4kQMP1KFyPAj' ... '6FqzZAUrgehevRMUBI4XoUrscyQA=='),
                    'dtype': 'f8'},
              'xaxis': 'x',
              'yaxis': 'y'},
             {'hovertemplate': 'time=Dinner<br>total_bill=%{x}<extra></extra>',
              'legendgroup': 'Dinner',
              'marker': {'color': 'green'},
              'name': 'Dinner',
              'notched': True,
              'showlegend': False,
              'type': 'box',
              'x': {'bdata': ('PQrXo3D9MECuR+F6FK4kQMP1KFyPAj' ... '6FqzZAUrgehevRMUBI4XoUrscyQA=='),
                    'dtype': 'f8'},
              'xaxis': 'x2',
              'yaxis': 'y2'},
             {'bingroup': 'x',
              'histnorm': 'probability density',
              'hovertemplate': 'time=Lunch<br>total_bill=%{x}<br>probability density=%{y}<extra></extra>',
              'legendgroup': 'Lunch',
              'marker': {'color': 'orange', 'pattern': {'shape': ''}},
              'name': 'Lunch',
              'nbinsx': 40,
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': {'bdata': ('MzMzMzMzO0DD9Shcj8I2QArXo3A9Sj' ... '0K1ypAhetRuB5FMECuR+F6FC4kQA=='),
                    'dtype': 'f8'},
              'xaxis': 'x',
              'yaxis': 'y'},
             {'hovertemplate': 'time=Lunch<br>total_bill=%{x}<extra></extra>',
              'legendgroup': 'Lunch',
              'marker': {'color': 'orange'},
              'name': 'Lunch',
              'notched': True,
              'showlegend': False,
              'type': 'box',
              'x': {'bdata': ('MzMzMzMzO0DD9Shcj8I2QArXo3A9Sj' ... '0K1ypAhetRuB5FMECuR+F6FC4kQA=='),
                    'dtype': 'f8'},
              'xaxis': 'x2',
              'yaxis': 'y2'}],
    'layout': {'barmode': 'relative',
               'legend': {'title': {'text': 'time'}, 'tracegroupgap': 0},
               'template': '...',
               'title': {'text': 'Histograma da taxa paga no restaurante'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'total_bill'}},
               'xaxis2': {'anchor': 'y2', 'domain': [0.0, 1.0], 'matches': 'x', 'showgrid': True, 'showticklabels': False},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 0.7326], 'title': {'text': 'probability density'}},
               'yaxis2': {'anchor': 'x2',
                          'domain': [0.7426, 1.0],
                          'matches': 'y2',
                          'showgrid': False,
                          'showline': False,
                          'showticklabels': False,
                          'ticks': ''}}
})

## Distribuição

In [82]:
import plotly.figure_factory as ff
import numpy as np

In [83]:
x1 = np.random.randn(1000)
x2 = np.random.randn(1000) + 5

In [91]:
ff.create_distplot([x1, x2], group_labels=["Normal 1", "Normal 2"])

ImportError: FigureFactory.create_distplot requires scipy

In [87]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [90]:
ff.create_distplot([ df["total_bill"], df["tip"] ], 
                group_labels=["Total bill", "tips"])

ImportError: FigureFactory.create_distplot requires scipy