In [122]:
# Aula 3
import pandas as pd

In [123]:
# carregando dataset corretamente ==> neste caso usa o separador ';'.
# It seems the separator is not ';', let's try to read the file without specifying a separator first to inspect the header.
data = pd.read_csv('./sample_data/GasPricesinBrazil_2004-2019.csv', sep=';')

In [124]:
data

      Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0      0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO ...
1      1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETA...
2      2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROS...
3      3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROS...
4      4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANO...
...                                                  ...
58722  59898,2013-07-14,2013-07-20,CENTRO OESTE,DISTR...
58723  59899,2013-07-14,2013-07-20,SUDESTE,ESPIRITO S...
58724  59900,2013-07-14,2013-07-20,CENTRO OESTE,GOIAS...
58725  59901,2013-07-14,2013-07-20,NORDESTE,MARANHAO,...
58726  59902,2013-07-14,2013-07-20,CENTRO OESTE,MATO ...

[58727 rows x 1 columns]

In [125]:
df = pd.DataFrame({ 'A': [1, 2, 3, 4],
                    'B': [10, 20, 30, 40],
                    'C': [100, 200, 300, 400]},
                    index=['Linha 1', 'Linha 2', 'Linha 3', 'Linha 4'])

In [126]:
df

         A   B    C
Linha 1  1  10  100
Linha 2  2  20  200
Linha 3  3  30  300
Linha 4  4  40  400

In [127]:
def nossa_soma(series):
  return series.sum() # retorna a soma de todos os valores de uma series

In [128]:
df['SOMA(A, B, C )'] = df.apply(nossa_soma, axis=1)
df

         A   B    C  SOMA(A, B, C )
Linha 1  1  10  100             111
Linha 2  2  20  200             222
Linha 3  3  30  300             333
Linha 4  4  40  400             444

In [129]:
df.loc['Linha 5'] = df.apply(nossa_soma, axis=0)
df

          A    B     C  SOMA(A, B, C )
Linha 1   1   10   100             111
Linha 2   2   20   200             222
Linha 3   3   30   300             333
Linha 4   4   40   400             444
Linha 5  10  100  1000            1110

In [132]:
df['MEDIA(A, B, C)'] = df[['A', 'B', 'C']].apply(lambda series: series.mean(), axis=1)
df

          A    B     C  SOMA(A, B, C )  MEDIA(A, B, C)
Linha 1   1   10   100             111            37.0
Linha 2   2   20   200             222            74.0
Linha 3   3   30   300             333           111.0
Linha 4   4   40   400             444           148.0
Linha 5  10  100  1000            1110           370.0

In [136]:
# aplica a lambda function abaixo para cada elemento da coluna
df['C * 2'] = df['C'].apply(lambda x: x * 2)
df

          A    B     C  SOMA(A, B, C )  MEDIA(A, B, C)  C * 2
Linha 1   1   10   100             111            37.0    200
Linha 2   2   20   200             222            74.0    400
Linha 3   3   30   300             333           111.0    600
Linha 4   4   40   400             444           148.0    800
Linha 5  10  100  1000            1110           370.0   2000

In [137]:
df['A * 2'] = df['A'] * 2
df

          A    B     C  SOMA(A, B, C )  MEDIA(A, B, C)  C * 2  A * 2
Linha 1   1   10   100             111            37.0    200      2
Linha 2   2   20   200             222            74.0    400      4
Linha 3   3   30   300             333           111.0    600      6
Linha 4   4   40   400             444           148.0    800      8
Linha 5  10  100  1000            1110           370.0   2000     20

In [138]:
df = pd.DataFrame({ 'A': [1, 2, 3, 4],
                    'B': [10, 20, 30, 40],
                    'C': [100, 200, 300, 400]},
                    index=['Linha 1', 'Linha 2', 'Linha 3', 'Linha 4'])
df

         A   B    C
Linha 1  1  10  100
Linha 2  2  20  200
Linha 3  3  30  300
Linha 4  4  40  400

In [142]:
# retorna um novo dataframe com todos os elementos ao quadrado,
# poderíamos usar uma função ao invés de uma lambda fuction
df.applymap(lambda x: x ** 2)

/tmp/ipython-input-929360223.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x ** 2)

          A     B       C
Linha 1   1   100   10000
Linha 2   4   400   40000
Linha 3   9   900   90000
Linha 4  16  1600  160000

In [144]:
nomes = pd.Series(['João', 'Maria', 'José', 'Ana'])
nomes

0     João
1    Maria
2     José
3      Ana
dtype: object

In [145]:
# retorna uma nova Series com todos os nomes com letras maiuscúlas,
# poderiamos usar uma função ao invés de uma lambda fuction
nomes.map(lambda x: x.upper())

0     JOÃO
1    MARIA
2     JOSÉ
3      ANA
dtype: object

In [146]:
nomes

0     João
1    Maria
2     José
3      Ana
dtype: object

In [ ]:
# O Pandas já fornece uma série de métodos para manipulação de string,
# Assim, poderiamos usar o códgio abaixo para obter o mesmo resultado.
nomes.str.upper()