In [1]:
# Aula 3
import pandas as pd

In [3]:
# carregando dataset corretamente ==> neste caso usa o separador ';'.
data = pd.read_csv('./sample_data/GasPricesinBrazil_2004-2019.csv', sep=";")

In [4]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127.0,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5.0,2004.0
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387.0,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5.0,2004.0
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192.0,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5.0,2004.0
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162.0,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5.0,2004.0
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103.0,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5.0,2004.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52472,52472,2010-10-03,2010-10-09,NORTE,PARA,ÓLEO DIESEL,178.0,R$/l,2.073,0.111,...,2.400,0.235,0.054,1.838,0.044,1.765,1.9329,0.024,10.0,2010.0
52473,52473,2010-10-03,2010-10-09,NORTE,RONDONIA,ÓLEO DIESEL,103.0,R$/l,2.200,0.054,...,2.300,0.294,0.025,1.906,0.043,1.798,1.939,0.023,10.0,2010.0
52474,52474,2010-10-03,2010-10-09,NORTE,RORAIMA,ÓLEO DIESEL,34.0,R$/l,2.393,0.042,...,2.600,0.406,0.018,1.987,0.074,1.9,2.0875,0.037,10.0,2010.0
52475,52475,2010-10-03,2010-10-09,NORTE,TOCANTINS,ÓLEO DIESEL,59.0,R$/l,2.066,0.066,...,2.150,0.214,0.032,1.852,0.075,1.706,1.899,0.04,10.0,2010.0
52476,52476,2010-10-03,2010-10-09,SUDESTE,ESPIRITO SANTO,ÓLEO DIE,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127.0,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5.0,2004.0
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387.0,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5.0,2004.0
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192.0,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5.0,2004.0
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162.0,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5.0,2004.0
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103.0,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5.0,2004.0

In [6]:
# Criando uma coluna a partir de um valor constante/default
# todas as linhas terão o mesmo valor para esta nova coluna
data['coluna sem nocao'] = 'DEFAULT'
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127.0,R$/l,1.288,0.016,...,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5.0,2004.0,DEFAULT
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387.0,R$/l,1.162,0.114,...,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5.0,2004.0,DEFAULT
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192.0,R$/l,1.389,0.097,...,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5.0,2004.0,DEFAULT
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162.0,R$/l,1.262,0.070,...,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5.0,2004.0,DEFAULT
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103.0,R$/l,1.181,0.078,...,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5.0,2004.0,DEFAULT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52472,52472,2010-10-03,2010-10-09,NORTE,PARA,ÓLEO DIESEL,178.0,R$/l,2.073,0.111,...,0.235,0.054,1.838,0.044,1.765,1.9329,0.024,10.0,2010.0,DEFAULT
52473,52473,2010-10-03,2010-10-09,NORTE,RONDONIA,ÓLEO DIESEL,103.0,R$/l,2.200,0.054,...,0.294,0.025,1.906,0.043,1.798,1.939,0.023,10.0,2010.0,DEFAULT
52474,52474,2010-10-03,2010-10-09,NORTE,RORAIMA,ÓLEO DIESEL,34.0,R$/l,2.393,0.042,...,0.406,0.018,1.987,0.074,1.9,2.0875,0.037,10.0,2010.0,DEFAULT
52475,52475,2010-10-03,2010-10-09,NORTE,TOCANTINS,ÓLEO DIESEL,59.0,R$/l,2.066,0.066,...,0.214,0.032,1.852,0.075,1.706,1.899,0.04,10.0,2010.0,DEFAULT
52476,52476,2010-10-03,2010-10-09,SUDESTE,ESPIRITO SANTO,ÓLEO DIE,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DEFAULT

In [7]:
data['coluna a partir da Lista'] = range(data.shape[0])

In [8]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir da Lista
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127.0,R$/l,1.288,0.016,...,0.012,0.825,0.11,0.4201,0.9666,0.133,5.0,2004.0,DEFAULT,0
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387.0,R$/l,1.162,0.114,...,0.098,0.763,0.088,0.5013,1.05,0.115,5.0,2004.0,DEFAULT,1
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192.0,R$/l,1.389,0.097,...,0.070,0.97,0.095,0.5614,1.161,0.098,5.0,2004.0,DEFAULT,2
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162.0,R$/l,1.262,0.070,...,0.055,0.83,0.119,0.5991,1.22242,0.143,5.0,2004.0,DEFAULT,3
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103.0,R$/l,1.181,0.078,...,0.066,0.941,0.077,0.7441,1.0317,0.082,5.0,2004.0,DEFAULT,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52472,52472,2010-10-03,2010-10-09,NORTE,PARA,ÓLEO DIESEL,178.0,R$/l,2.073,0.111,...,0.054,1.838,0.044,1.765,1.9329,0.024,10.0,2010.0,DEFAULT,52472
52473,52473,2010-10-03,2010-10-09,NORTE,RONDONIA,ÓLEO DIESEL,103.0,R$/l,2.200,0.054,...,0.025,1.906,0.043,1.798,1.939,0.023,10.0,2010.0,DEFAULT,52473
52474,52474,2010-10-03,2010-10-09,NORTE,RORAIMA,ÓLEO DIESEL,34.0,R$/l,2.393,0.042,...,0.018,1.987,0.074,1.9,2.0875,0.037,10.0,2010.0,DEFAULT,52474
52475,52475,2010-10-03,2010-10-09,NORTE,TOCANTINS,ÓLEO DIESEL,59.0,R$/l,2.066,0.066,...,0.032,1.852,0.075,1.706,1.899,0.04,10.0,2010.0,DEFAULT,52475
52476,52476,2010-10-03,2010-10-09,SUDESTE,ESPIRITO SANTO,ÓLEO DIE,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DEFAULT,52476

In [9]:
# não funciona porque a quantidade de elementos da lista ( a sertem atribuídos a nova coluna) é diferente
# da quantidade de linhas do dataframe
data['nao funciona'] = [1, 2, 3]

ValueError: Length of values (3) does not match length of index (52477)

In [10]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir da Lista
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127.0,R$/l,1.288,0.016,...,0.012,0.825,0.11,0.4201,0.9666,0.133,5.0,2004.0,DEFAULT,0
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387.0,R$/l,1.162,0.114,...,0.098,0.763,0.088,0.5013,1.05,0.115,5.0,2004.0,DEFAULT,1
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192.0,R$/l,1.389,0.097,...,0.070,0.97,0.095,0.5614,1.161,0.098,5.0,2004.0,DEFAULT,2
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162.0,R$/l,1.262,0.070,...,0.055,0.83,0.119,0.5991,1.22242,0.143,5.0,2004.0,DEFAULT,3
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103.0,R$/l,1.181,0.078,...,0.066,0.941,0.077,0.7441,1.0317,0.082,5.0,2004.0,DEFAULT,4

In [13]:
data['PREÇO MÉDIO DE REVENDA (dólares)'] = data['PREÇO MÉDIO REVENDA']  * 6.0

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir da Lista,PREÇO MÉDIO DE REVENDA (dólares)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127.0,R$/l,1.288,0.016,...,0.825,0.11,0.4201,0.9666,0.133,5.0,2004.0,DEFAULT,0,7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387.0,R$/l,1.162,0.114,...,0.763,0.088,0.5013,1.05,0.115,5.0,2004.0,DEFAULT,1,6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192.0,R$/l,1.389,0.097,...,0.97,0.095,0.5614,1.161,0.098,5.0,2004.0,DEFAULT,2,8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162.0,R$/l,1.262,0.070,...,0.83,0.119,0.5991,1.22242,0.143,5.0,2004.0,DEFAULT,3,7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103.0,R$/l,1.181,0.078,...,0.941,0.077,0.7441,1.0317,0.082,5.0,2004.0,DEFAULT,4,7.086
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52472,52472,2010-10-03,2010-10-09,NORTE,PARA,ÓLEO DIESEL,178.0,R$/l,2.073,0.111,...,1.838,0.044,1.765,1.9329,0.024,10.0,2010.0,DEFAULT,52472,12.438
52473,52473,2010-10-03,2010-10-09,NORTE,RONDONIA,ÓLEO DIESEL,103.0,R$/l,2.200,0.054,...,1.906,0.043,1.798,1.939,0.023,10.0,2010.0,DEFAULT,52473,13.200
52474,52474,2010-10-03,2010-10-09,NORTE,RORAIMA,ÓLEO DIESEL,34.0,R$/l,2.393,0.042,...,1.987,0.074,1.9,2.0875,0.037,10.0,2010.0,DEFAULT,52474,14.358
52475,52475,2010-10-03,2010-10-09,NORTE,TOCANTINS,ÓLEO DIESEL,59.0,R$/l,2.066,0.066,...,1.852,0.075,1.706,1.899,0.04,10.0,2010.0,DEFAULT,52475,12.396
52476,52476,2010-10-03,2010-10-09,SUDESTE,ESPIRITO SANTO,ÓLEO DIE,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DEFAULT,52476,NaN

In [14]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir da Lista,PREÇO MÉDIO DE REVENDA (dólares)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127.0,R$/l,1.288,0.016,...,0.825,0.11,0.4201,0.9666,0.133,5.0,2004.0,DEFAULT,0,7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387.0,R$/l,1.162,0.114,...,0.763,0.088,0.5013,1.05,0.115,5.0,2004.0,DEFAULT,1,6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192.0,R$/l,1.389,0.097,...,0.97,0.095,0.5614,1.161,0.098,5.0,2004.0,DEFAULT,2,8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162.0,R$/l,1.262,0.070,...,0.83,0.119,0.5991,1.22242,0.143,5.0,2004.0,DEFAULT,3,7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103.0,R$/l,1.181,0.078,...,0.941,0.077,0.7441,1.0317,0.082,5.0,2004.0,DEFAULT,4,7.086
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52472,52472,2010-10-03,2010-10-09,NORTE,PARA,ÓLEO DIESEL,178.0,R$/l,2.073,0.111,...,1.838,0.044,1.765,1.9329,0.024,10.0,2010.0,DEFAULT,52472,12.438
52473,52473,2010-10-03,2010-10-09,NORTE,RONDONIA,ÓLEO DIESEL,103.0,R$/l,2.200,0.054,...,1.906,0.043,1.798,1.939,0.023,10.0,2010.0,DEFAULT,52473,13.200
52474,52474,2010-10-03,2010-10-09,NORTE,RORAIMA,ÓLEO DIESEL,34.0,R$/l,2.393,0.042,...,1.987,0.074,1.9,2.0875,0.037,10.0,2010.0,DEFAULT,52474,14.358
52475,52475,2010-10-03,2010-10-09,NORTE,TOCANTINS,ÓLEO DIESEL,59.0,R$/l,2.066,0.066,...,1.852,0.075,1.706,1.899,0.04,10.0,2010.0,DEFAULT,52475,12.396
52476,52476,2010-10-03,2010-10-09,SUDESTE,ESPIRITO SANTO,ÓLEO DIE,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DEFAULT,52476,NaN