#Manipulação de Dados

Dataset: Gas Prices in Brazil: https://www.kaggle.com/matheusfreitag/gas-prices-in-brazil

Este dataset contém os registros dos preços médios semanais dos combustíveis do Brasil entre os anos de 2004 e 2019.
Cada amostra (registro/linha) consiste em um registro de preço aferido para um dado tipo de combustível em uma dada localidade do Brasil.
Alguns dos principais atributos (colunas) do dataset são: 'ESTADO', 'PRODUTO', 'NÚMERO DE POSTOS PESQUISADOS', 'PREÇO MÉDIO REVENDA'.

* O arquivo disponibilizado no Kaggle está no formato tsv. Embora o pandas consiga abrí-lo normalmente, convertemos tal arquivo para o formato CSV, que é um dos formatos mais utilizados, e mudamos seu separado para ';' apenas para mostrar algumas opções da função de carregamento.

## Importando o Dataset

Para carregar um dataset no formato csv,basta utilizar a função read_csv do pandas. Por padrão,ela considera ',' como separador

In [377]:
import pandas as pd

In [378]:
data = pd.read_csv('/content/sample_data/GasPricesinBrazil_2004-2019.csv')

In [379]:
data

       Unnamed: 0;DATA INICIAL;DATA FINAL;REGIÃO;ESTADO;PRODUTO;NÚMERO DE POSTOS PESQUISADOS;UNIDADE DE MEDIDA;PREÇO MÉDIO REVENDA;DESVIO PADRÃO REVENDA;PREÇO MÍNIMO REVENDA;PREÇO MÁXIMO REVENDA;MARGEM MÉDIA REVENDA;COEF DE VARIAÇÃO REVENDA;PREÇO MÉDIO DISTRIBUIÇÃO;DESVIO PADRÃO DISTRIBUIÇÃO;PREÇO MÍNIMO DISTRIBUIÇÃO;PREÇO MÁXIMO DISTRIBUIÇÃO;COEF DE VARIAÇÃO DISTRIBUIÇÃO;MÊS;ANO
0       0;2004-05-09;2004-05-15;CENTRO OESTE;DISTRITO ...
1       1;2004-05-09;2004-05-15;CENTRO OESTE;GOIAS;ETA...
2       2;2004-05-09;2004-05-15;CENTRO OESTE;MATO GROS...
3       3;2004-05-09;2004-05-15;CENTRO OESTE;MATO GROS...
4       4;2004-05-09;2004-05-15;NORDESTE;ALAGOAS;ETANO...
...                                                   ...
106818  106818;2019-06-23;2019-06-29;NORDESTE;RIO GRAN...
106819  106819;2019-06-23;2019-06-29;SUL;RIO GRANDE DO...
106820  106820;2019-06-23;2019-06-29;SUL;SANTA CATARIN...
106821  106821;2019-06-23;2019-06-29;SUDESTE;SAO PAULO...
106822  106822;2019-06-23;2019-06-29;NORDESTE;SERGIPE;...

[106823 rows x 1 columns]

In [380]:
data = pd.read_csv('/content/sample_data/GasPricesinBrazil_2004-2019.csv', sep=';')

In [381]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,3.690,0.818,0.018,2.756,0,2.756,2.756,0,6,2019
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,3.789,0.95,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,3.499,0.914,0.065,1.998,0,1.9981,1.9981,0,6,2019
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,3.699,1.179,0.001,2.518,0,2.5175,2.5175,0,6,2019

In [382]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

In [383]:
data.head(10)

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
5,5,2004-05-09,2004-05-15,NORDESTE,BAHIA,ETANOL HIDRATADO,408,R$/l,1.383,0.132,...,2.050,0.426,0.095,0.957,0.128,0.5686,1.35,0.134,5,2004
6,6,2004-05-09,2004-05-15,NORDESTE,CEARA,ETANOL HIDRATADO,278,R$/l,1.453,0.218,...,1.950,0.353,0.150,1.1,0.068,0.7332,1.294,0.062,5,2004
7,7,2004-05-09,2004-05-15,NORDESTE,MARANHAO,ETANOL HIDRATADO,105,R$/l,1.631,0.158,...,2.000,0.515,0.097,1.116,0.091,0.9923,1.36183,0.082,5,2004
8,8,2004-05-09,2004-05-15,NORDESTE,PARAIBA,ETANOL HIDRATADO,125,R$/l,1.284,0.130,...,1.699,0.353,0.101,0.931,0.072,0.7577,1.2972,0.077,5,2004
9,9,2004-05-09,2004-05-15,NORDESTE,PERNAMBUCO,ETANOL HIDRATADO,423,R$/l,1.224,0.141,...,1.700,0.277,0.115,0.947,0.091,0.5643,1.3541,0.096,5,2004

In [384]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 21 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Unnamed: 0                     106823 non-null  int64
 1   DATA INICIAL                   106823 non-null  object
 2   DATA FINAL                     106823 non-null  object
 3   REGIÃO                         106823 non-null  object
 4   ESTADO                         106823 non-null  object
 5   PRODUTO                        106823 non-null  object
 6   NÚMERO DE POSTOS PESQUISADOS   106823 non-null  int64
 7   UNIDADE DE MEDIDA              106823 non-null  object
 8   PREÇO MÉDIO REVENDA            106823 non-null  float64
 9   DESVIO PADRÃO REVENDA          106823 non-null  float64
 10  PREÇO MÍNIMO REVENDA           106823 non-null  float64
 11  PREÇO MÁXIMO REVENDA           106823 non-null  float64
 12  MARGEM MÉDIA REVENDA           106823 non-null  object
 13  COEF DE VARIAÇÃO REVENDA       106823 non-null  float64
 14  PREÇO MÉDIO DISTRIBUIÇÃO       106823 non-null  object
 15  DESVIO PADRÃO DISTRIBUIÇÃO     106823 non-null  object
 16  PREÇO MÍNIMO DISTRIBUIÇÃO      106823 non-null  object
 17  PREÇO MÁXIMO DISTRIBUIÇÃO      106823 non-null  object
 18  COEF DE VARIAÇÃO DISTRIBUIÇÃO  106823 non-null  object
 19  MÊS                            106823 non-null  int64
 20  ANO                            106823 non-null  int64
dtypes: float64(5), int64(4), object(12)
memory usage: 17.1+ MB

A primeira coluna da tabela, chamada 'Unnamed: 0', parece não significar nada. Na verdade, ela parece ser os índices da tabela, que foram salvos como uma coluna.
Veremos jajá como remover tal coluna.

Outro ponto é que, aparentemente, nenhum atributo/coluna possui valores nulos (null), uma vez que o número de registros do dataframe e os números de valores non-null é de 106823.
Mas, veremos que não é bem assim para esse caso.

#### 1.3.2 Data Frame

In [385]:
type(data)

pandas.core.frame.DataFrame

In [386]:
data.shape

(106823, 21)

In [387]:
print(f'O DataFrame possui {data.shape[0]} linhas/atributos e {data.shape[1]} colunas/atributos/variaveis')

O DataFrame possui 106823 linhas/atributos e 21 colunas/atributos/variaveis

## Criando um DataFrame

Podemos criar um DataFrame a partir de um dicionário, onde cada chave possui uma lista de elementos de igual tamanho.
As chaves representam as colunas e cada um dos valores de sua lista representa o valor da linha correspondente para aquela coluna.

In [388]:
alunos_df = pd.DataFrame({
    'nome': ['Luke Skywalker','Yoda','Palpatine'],
    'idade' : [16, 1000, 70],
    'peso': [70,15,60],
    'eh jedi':[True,True,False]
})

In [389]:
alunos_df

             nome  idade  peso  eh jedi
0  Luke Skywalker     16    70     True
1            Yoda   1000    15     True
2       Palpatine     70    60    False

In [390]:
alunos_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   nome     3 non-null      object
 1   idade    3 non-null      int64
 2   peso     3 non-null      int64
 3   eh jedi  3 non-null      bool
dtypes: bool(1), int64(2), object(1)
memory usage: 207.0+ bytes

## Renomeando as colunas de um DataFrame

===> O método DataFrame.columns retorna uma ";lista" com os nomes de todas as colunas do data frame.

In [391]:
alunos_df.columns

Index(['nome', 'idade', 'peso', 'eh jedi'], dtype='object')

In [392]:
type(alunos_df.columns)

pandas.core.indexes.base.Index

In [393]:
list(alunos_df.columns)

['nome', 'idade', 'peso', 'eh jedi']

Renomear colunas do data frame, utilize o metodo DataFreme.rename, que retorna uma copia do data frame com as colunas renomeadas:

In [394]:
alunos_df

             nome  idade  peso  eh jedi
0  Luke Skywalker     16    70     True
1            Yoda   1000    15     True
2       Palpatine     70    60    False

In [395]:
alunos_df_renomeado =  alunos_df.rename(columns={
    'nome' : 'nome completo',
    'idade': 'ID'
    })

In [396]:
alunos_df_renomeado

    nome completo    ID  peso  eh jedi
0  Luke Skywalker    16    70     True
1            Yoda  1000    15     True
2       Palpatine    70    60    False

In [397]:
alunos_df.rename(columns={'nome' : 'nome completo','idade': 'ID'},inplace=True)

In [398]:
alunos_df

    nome completo    ID  peso  eh jedi
0  Luke Skywalker    16    70     True
1            Yoda  1000    15     True
2       Palpatine    70    60    False

In [399]:
alunos_df.columns = ['NOME', 'IDADE', 'PESO', 'EH_JEDI']

In [400]:
alunos_df

             NOME  IDADE  PESO  EH_JEDI
0  Luke Skywalker     16    70     True
1            Yoda   1000    15     True
2       Palpatine     70    60    False

# 1.3.3 Series

In [401]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

In [402]:
data['ESTADO']

0            DISTRITO FEDERAL
1                       GOIAS
2                 MATO GROSSO
3          MATO GROSSO DO SUL
4                     ALAGOAS
                 ...
106818    RIO GRANDE DO NORTE
106819      RIO GRANDE DO SUL
106820         SANTA CATARINA
106821              SAO PAULO
106822                SERGIPE
Name: ESTADO, Length: 106823, dtype: object

In [403]:
data.ESTADO

0            DISTRITO FEDERAL
1                       GOIAS
2                 MATO GROSSO
3          MATO GROSSO DO SUL
4                     ALAGOAS
                 ...
106818    RIO GRANDE DO NORTE
106819      RIO GRANDE DO SUL
106820         SANTA CATARINA
106821              SAO PAULO
106822                SERGIPE
Name: ESTADO, Length: 106823, dtype: object

In [404]:
type(data['ESTADO'])

pandas.core.series.Series

In [405]:
data.iloc[1]

Unnamed: 0                                      1
DATA INICIAL                           2004-05-09
DATA FINAL                             2004-05-15
REGIÃO                               CENTRO OESTE
ESTADO                                      GOIAS
PRODUTO                          ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                  387
UNIDADE DE MEDIDA                            R$/l
PREÇO MÉDIO REVENDA                         1.162
DESVIO PADRÃO REVENDA                       0.114
PREÇO MÍNIMO REVENDA                         0.89
PREÇO MÁXIMO REVENDA                        1.449
MARGEM MÉDIA REVENDA                        0.399
COEF DE VARIAÇÃO REVENDA                    0.098
PREÇO MÉDIO DISTRIBUIÇÃO                    0.763
DESVIO PADRÃO DISTRIBUIÇÃO                  0.088
PREÇO MÍNIMO DISTRIBUIÇÃO                  0.5013
PREÇO MÁXIMO DISTRIBUIÇÃO                    1.05
COEF DE VARIAÇÃO DISTRIBUIÇÃO               0.115
MÊS                                             5
ANO                                          2004
Name: 1, dtype: object

In [406]:
type(data.iloc[1])

pandas.core.series.Series

## Criando uma Series

In [407]:
pd.Series([5.5,6.0,9.5], index=['prova 1', 'prova 2', 'prova 3'], name='Notas do Luke Skywalker')

prova 1    5.5
prova 2    6.0
prova 3    9.5
Name: Notas do Luke Skywalker, dtype: float64

### Atribuindo Dados

In [408]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

In [409]:
produto_view = data['PRODUTO']

In [410]:
produto_copy_bkp = data['PRODUTO'].copy()
produto_copy_bkp

0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...
106818                 GNV
106819                 GNV
106820                 GNV
106821                 GNV
106822                 GNV
Name: PRODUTO, Length: 106823, dtype: object

In [411]:
data['PRODUTO'] = 'Combustível'

In [412]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,Combustível,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,Combustível,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,Combustível,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,Combustível,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,Combustível,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

In [413]:
produto_copy_bkp

0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...
106818                 GNV
106819                 GNV
106820                 GNV
106821                 GNV
106822                 GNV
Name: PRODUTO, Length: 106823, dtype: object

In [414]:
produto_view

0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...
106818                 GNV
106819                 GNV
106820                 GNV
106821                 GNV
106822                 GNV
Name: PRODUTO, Length: 106823, dtype: object

Atribuindo listas ou series

In [415]:
nrows, ncols = data.shape
nrows, ncols

(106823, 21)

In [416]:
novos_produtos = [f'Produto {1}'for i in range(nrows)]
len(novos_produtos)

106823

In [417]:
data['PRODUTO'] = novos_produtos

In [418]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,Produto 1,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,Produto 1,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,Produto 1,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,Produto 1,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,Produto 1,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,Produto 1,7,R$/m3,3.574,0.065,...,3.690,0.818,0.018,2.756,0,2.756,2.756,0,6,2019
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,Produto 1,23,R$/m3,3.401,0.129,...,3.789,0.95,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,Produto 1,24,R$/m3,2.912,0.190,...,3.499,0.914,0.065,1.998,0,1.9981,1.9981,0,6,2019
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,Produto 1,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,Produto 1,4,R$/m3,3.697,0.005,...,3.699,1.179,0.001,2.518,0,2.5175,2.5175,0,6,2019

In [419]:
print(produto_view)
print('\n')
print(produto_copy_bkp)

0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...
106818                 GNV
106819                 GNV
106820                 GNV
106821                 GNV
106822                 GNV
Name: PRODUTO, Length: 106823, dtype: object


0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...
106818                 GNV
106819                 GNV
106820                 GNV
106821                 GNV
106822                 GNV
Name: PRODUTO, Length: 106823, dtype: object

In [420]:
data['PRODUTO'] = produto_copy_bkp

In [421]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,3.690,0.818,0.018,2.756,0,2.756,2.756,0,6,2019
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,3.789,0.95,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,3.499,0.914,0.065,1.998,0,1.9981,1.9981,0,6,2019
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,3.699,1.179,0.001,2.518,0,2.5175,2.5175,0,6,2019

In [422]:
data['coluna sem nocao'] = 'DEFAULT'
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,0.818,0.018,2.756,0,2.756,2.756,0,6,2019,DEFAULT
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,0.95,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019,DEFAULT
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,0.914,0.065,1.998,0,1.9981,1.9981,0,6,2019,DEFAULT
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019,DEFAULT
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,1.179,0.001,2.518,0,2.5175,2.5175,0,6,2019,DEFAULT

In [423]:
data['coluna a partir de lista'] = range(data.shape[0])

In [424]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,0.018,2.756,0,2.756,2.756,0,6,2019,DEFAULT,106818
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019,DEFAULT,106819
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,0.065,1.998,0,1.9981,1.9981,0,6,2019,DEFAULT,106820
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019,DEFAULT,106821
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,0.001,2.518,0,2.5175,2.5175,0,6,2019,DEFAULT,106822

In [425]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4

In [426]:
data['PRECO MEDIO DE REVENDA (dolares)'] = data['PREÇO MÉDIO REVENDA'] * 6.0

In [427]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0,7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2,8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4,7.086
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,2.756,0,2.756,2.756,0,6,2019,DEFAULT,106818,21.444
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,2.451,0.402,1.9842,2.8661,0.164,6,2019,DEFAULT,106819,20.406
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,1.998,0,1.9981,1.9981,0,6,2019,DEFAULT,106820,17.472
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,2.374,0.165,2.0179,2.5093,0.07,6,2019,DEFAULT,106821,18.120
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,2.518,0,2.5175,2.5175,0,6,2019,DEFAULT,106822,22.182

### 1.3.4 Índices

In [428]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0,7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2,8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4,7.086
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,2.756,0,2.756,2.756,0,6,2019,DEFAULT,106818,21.444
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,2.451,0.402,1.9842,2.8661,0.164,6,2019,DEFAULT,106819,20.406
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,1.998,0,1.9981,1.9981,0,6,2019,DEFAULT,106820,17.472
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,2.374,0.165,2.0179,2.5093,0.07,6,2019,DEFAULT,106821,18.120
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,2.518,0,2.5175,2.5175,0,6,2019,DEFAULT,106822,22.182

In [429]:
data.index

RangeIndex(start=0, stop=106823, step=1)

In [430]:
pesquisa_de_satisfacao = pd.DataFrame ({
    'bom' : [50,21, 100],
    'ruim' : [141, 2, 30],
    'pessimo' : [30,20, 1]

}, index=['XboxOne', 'Playstation04', 'Switch'])

In [431]:
pesquisa_de_satisfacao.head()

               bom  ruim  pessimo
XboxOne         50   141       30
Playstation04   21     2       20
Switch         100    30        1

In [432]:
pesquisa_de_satisfacao.index

Index(['XboxOne', 'Playstation04', 'Switch'], dtype='object')

# selecionando uma ou mais observações (Indexação)

In [433]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0,7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2,8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4,7.086

index-based selection (seleção baseada em índices)

iloc : seleciona elementos do Datafreme, baseado em seu índice(número)

In [434]:
data.iloc[1]

Unnamed: 0                                         1
DATA INICIAL                              2004-05-09
DATA FINAL                                2004-05-15
REGIÃO                                  CENTRO OESTE
ESTADO                                         GOIAS
PRODUTO                             ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                     387
UNIDADE DE MEDIDA                               R$/l
PREÇO MÉDIO REVENDA                            1.162
DESVIO PADRÃO REVENDA                          0.114
PREÇO MÍNIMO REVENDA                            0.89
PREÇO MÁXIMO REVENDA                           1.449
MARGEM MÉDIA REVENDA                           0.399
COEF DE VARIAÇÃO REVENDA                       0.098
PREÇO MÉDIO DISTRIBUIÇÃO                       0.763
DESVIO PADRÃO DISTRIBUIÇÃO                     0.088
PREÇO MÍNIMO DISTRIBUIÇÃO                     0.5013
PREÇO MÁXIMO DISTRIBUIÇÃO                       1.05
COEF DE VARIAÇÃO DISTRIBUIÇÃO                  0.115
MÊS                                                5
ANO                                             2004
coluna sem nocao                             DEFAULT
coluna a partir de lista                           1
PRECO MEDIO DE REVENDA (dolares)               6.972
Name: 1, dtype: object

Selecioando multiplas linhas

In [435]:
data.iloc[:6]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0,7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2,8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4,7.086
5,5,2004-05-09,2004-05-15,NORDESTE,BAHIA,ETANOL HIDRATADO,408,R$/l,1.383,0.132,...,0.957,0.128,0.5686,1.35,0.134,5,2004,DEFAULT,5,8.298

In [436]:
data.iloc[10:16]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
10,10,2004-05-09,2004-05-15,NORDESTE,PIAUI,ETANOL HIDRATADO,89,R$/l,1.573,0.134,...,1.079,0.078,0.8857,1.2499,0.072,5,2004,DEFAULT,10,9.438
11,11,2004-05-09,2004-05-15,NORDESTE,RIO GRANDE DO NORTE,ETANOL HIDRATADO,131,R$/l,1.276,0.116,...,0.944,0.078,0.7119,1.1386,0.083,5,2004,DEFAULT,11,7.656
12,12,2004-05-09,2004-05-15,NORDESTE,SERGIPE,ETANOL HIDRATADO,57,R$/l,1.301,0.109,...,0.98,0.052,0.8267,1.1059,0.053,5,2004,DEFAULT,12,7.806
13,13,2004-05-09,2004-05-15,NORTE,ACRE,ETANOL HIDRATADO,33,R$/l,1.805,0.134,...,1.116,0.171,0.767,1.2992,0.153,5,2004,DEFAULT,13,10.830
14,14,2004-05-09,2004-05-15,NORTE,AMAPA,ETANOL HIDRATADO,15,R$/l,1.785,0.035,...,1.373,0.167,0.8339,1.4912,0.122,5,2004,DEFAULT,14,10.710
15,15,2004-05-09,2004-05-15,NORTE,AMAZONAS,ETANOL HIDRATADO,53,R$/l,1.578,0.123,...,1.137,0.068,0.9515,1.2109,0.06,5,2004,DEFAULT,15,9.468

In [437]:
data.iloc[[1, 5, 10, 15]]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,6.972
5,5,2004-05-09,2004-05-15,NORDESTE,BAHIA,ETANOL HIDRATADO,408,R$/l,1.383,0.132,...,0.957,0.128,0.5686,1.35,0.134,5,2004,DEFAULT,5,8.298
10,10,2004-05-09,2004-05-15,NORDESTE,PIAUI,ETANOL HIDRATADO,89,R$/l,1.573,0.134,...,1.079,0.078,0.8857,1.2499,0.072,5,2004,DEFAULT,10,9.438
15,15,2004-05-09,2004-05-15,NORTE,AMAZONAS,ETANOL HIDRATADO,53,R$/l,1.578,0.123,...,1.137,0.068,0.9515,1.2109,0.06,5,2004,DEFAULT,15,9.468

In [438]:
data.iloc[[5,1,15,10]]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
5,5,2004-05-09,2004-05-15,NORDESTE,BAHIA,ETANOL HIDRATADO,408,R$/l,1.383,0.132,...,0.957,0.128,0.5686,1.35,0.134,5,2004,DEFAULT,5,8.298
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,6.972
15,15,2004-05-09,2004-05-15,NORTE,AMAZONAS,ETANOL HIDRATADO,53,R$/l,1.578,0.123,...,1.137,0.068,0.9515,1.2109,0.06,5,2004,DEFAULT,15,9.468
10,10,2004-05-09,2004-05-15,NORDESTE,PIAUI,ETANOL HIDRATADO,89,R$/l,1.573,0.134,...,1.079,0.078,0.8857,1.2499,0.072,5,2004,DEFAULT,10,9.438

In [439]:
data.iloc[1, 4]

'GOIAS'

Label-based selection(seleção baseadas em Rótulos)

loc : seleciiona elementos do Dataframe, baseado em seus rótulos

In [440]:
pesquisa_de_satisfacao

               bom  ruim  pessimo
XboxOne         50   141       30
Playstation04   21     2       20
Switch         100    30        1

In [441]:
pesquisa_de_satisfacao.iloc[0]

bom         50
ruim       141
pessimo     30
Name: XboxOne, dtype: int64

In [442]:
pesquisa_de_satisfacao.loc['XboxOne']

bom         50
ruim       141
pessimo     30
Name: XboxOne, dtype: int64

In [443]:
pesquisa_de_satisfacao.loc['Playstation04', 'ruim']

np.int64(2)

In [444]:
pesquisa_de_satisfacao.loc[['XboxOne','Switch']]
#selecionando as linhas de índices rotulados

         bom  ruim  pessimo
XboxOne   50   141       30
Switch   100    30        1

In [445]:
pesquisa_de_satisfacao[['bom', 'pessimo']]

               bom  pessimo
XboxOne         50       30
Playstation04   21       20
Switch         100        1

In [446]:
pesquisa_de_satisfacao.loc[:, ['bom', 'pessimo']]

               bom  pessimo
XboxOne         50       30
Playstation04   21       20
Switch         100        1

In [447]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0,7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2,8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4,7.086

In [448]:
data.iloc[1]

Unnamed: 0                                         1
DATA INICIAL                              2004-05-09
DATA FINAL                                2004-05-15
REGIÃO                                  CENTRO OESTE
ESTADO                                         GOIAS
PRODUTO                             ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                     387
UNIDADE DE MEDIDA                               R$/l
PREÇO MÉDIO REVENDA                            1.162
DESVIO PADRÃO REVENDA                          0.114
PREÇO MÍNIMO REVENDA                            0.89
PREÇO MÁXIMO REVENDA                           1.449
MARGEM MÉDIA REVENDA                           0.399
COEF DE VARIAÇÃO REVENDA                       0.098
PREÇO MÉDIO DISTRIBUIÇÃO                       0.763
DESVIO PADRÃO DISTRIBUIÇÃO                     0.088
PREÇO MÍNIMO DISTRIBUIÇÃO                     0.5013
PREÇO MÁXIMO DISTRIBUIÇÃO                       1.05
COEF DE VARIAÇÃO DISTRIBUIÇÃO                  0.115
MÊS                                                5
ANO                                             2004
coluna sem nocao                             DEFAULT
coluna a partir de lista                           1
PRECO MEDIO DE REVENDA (dolares)               6.972
Name: 1, dtype: object

In [449]:
data.loc[1]

Unnamed: 0                                         1
DATA INICIAL                              2004-05-09
DATA FINAL                                2004-05-15
REGIÃO                                  CENTRO OESTE
ESTADO                                         GOIAS
PRODUTO                             ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                     387
UNIDADE DE MEDIDA                               R$/l
PREÇO MÉDIO REVENDA                            1.162
DESVIO PADRÃO REVENDA                          0.114
PREÇO MÍNIMO REVENDA                            0.89
PREÇO MÁXIMO REVENDA                           1.449
MARGEM MÉDIA REVENDA                           0.399
COEF DE VARIAÇÃO REVENDA                       0.098
PREÇO MÉDIO DISTRIBUIÇÃO                       0.763
DESVIO PADRÃO DISTRIBUIÇÃO                     0.088
PREÇO MÍNIMO DISTRIBUIÇÃO                     0.5013
PREÇO MÁXIMO DISTRIBUIÇÃO                       1.05
COEF DE VARIAÇÃO DISTRIBUIÇÃO                  0.115
MÊS                                                5
ANO                                             2004
coluna sem nocao                             DEFAULT
coluna a partir de lista                           1
PRECO MEDIO DE REVENDA (dolares)               6.972
Name: 1, dtype: object

## selecionando um ou mais atributos (colunas)

In [450]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0,7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2,8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4,7.086

In [451]:
data['ESTADO']

0            DISTRITO FEDERAL
1                       GOIAS
2                 MATO GROSSO
3          MATO GROSSO DO SUL
4                     ALAGOAS
                 ...
106818    RIO GRANDE DO NORTE
106819      RIO GRANDE DO SUL
106820         SANTA CATARINA
106821              SAO PAULO
106822                SERGIPE
Name: ESTADO, Length: 106823, dtype: object

In [452]:
data.ESTADO

0            DISTRITO FEDERAL
1                       GOIAS
2                 MATO GROSSO
3          MATO GROSSO DO SUL
4                     ALAGOAS
                 ...
106818    RIO GRANDE DO NORTE
106819      RIO GRANDE DO SUL
106820         SANTA CATARINA
106821              SAO PAULO
106822                SERGIPE
Name: ESTADO, Length: 106823, dtype: object

In [453]:
data.loc[:, 'ESTADO']

0            DISTRITO FEDERAL
1                       GOIAS
2                 MATO GROSSO
3          MATO GROSSO DO SUL
4                     ALAGOAS
                 ...
106818    RIO GRANDE DO NORTE
106819      RIO GRANDE DO SUL
106820         SANTA CATARINA
106821              SAO PAULO
106822                SERGIPE
Name: ESTADO, Length: 106823, dtype: object

In [454]:
data['DATA INICIAL']

0         2004-05-09
1         2004-05-09
2         2004-05-09
3         2004-05-09
4         2004-05-09
             ...
106818    2019-06-23
106819    2019-06-23
106820    2019-06-23
106821    2019-06-23
106822    2019-06-23
Name: DATA INICIAL, Length: 106823, dtype: object

In [455]:
data[['PRODUTO','ESTADO', 'REGIÃO']]

                 PRODUTO               ESTADO        REGIÃO
0       ETANOL HIDRATADO     DISTRITO FEDERAL  CENTRO OESTE
1       ETANOL HIDRATADO                GOIAS  CENTRO OESTE
2       ETANOL HIDRATADO          MATO GROSSO  CENTRO OESTE
3       ETANOL HIDRATADO   MATO GROSSO DO SUL  CENTRO OESTE
4       ETANOL HIDRATADO              ALAGOAS      NORDESTE
...                  ...                  ...           ...
106818               GNV  RIO GRANDE DO NORTE      NORDESTE
106819               GNV    RIO GRANDE DO SUL           SUL
106820               GNV       SANTA CATARINA           SUL
106821               GNV            SAO PAULO       SUDESTE
106822               GNV              SERGIPE      NORDESTE

[106823 rows x 3 columns]

#Removendo um atributo(coluna) do Data frame

In [456]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0,7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2,8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4,7.086

In [457]:
del data['Unnamed: 0']

In [458]:
data

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,...,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0,7.728
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,...,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,6.972
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,...,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2,8.334
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,...,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,7.572
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,...,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4,7.086
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,3.499,...,2.756,0,2.756,2.756,0,6,2019,DEFAULT,106818,21.444
106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,3.230,...,2.451,0.402,1.9842,2.8661,0.164,6,2019,DEFAULT,106819,20.406
106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,2.699,...,1.998,0,1.9981,1.9981,0,6,2019,DEFAULT,106820,17.472
106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,...,2.374,0.165,2.0179,2.5093,0.07,6,2019,DEFAULT,106821,18.120
106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,3.689,...,2.518,0,2.5175,2.5175,0,6,2019,DEFAULT,106822,22.182

# Salvando um Data frame

In [459]:
data.to_csv('/content/GasPricesinBrazil_2004-2019_preprocessado.csv', index=False)

#1.8 Seleção Condicional: Filtrando amostras
Durante nossas análise exploratórias, frequentemente filtraremos nossas amostras, a partir de certas condições, para fins de análise mais específica.
Existem algumas maneiras de fazermos tal filtragem. Antes disso, vamos carregar nosso dataset pré-processado que salvamos no item anterior.

In [460]:
data.to_csv('/content/GasPricesinBrazil_2004-2019_preprocessado.csv', index=False)

In [461]:
data.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,...,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0,7.728
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,...,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,6.972
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,...,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2,8.334
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,...,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,7.572
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,...,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4,7.086

In [462]:
data['ESTADO'].unique()

array(['DISTRITO FEDERAL', 'GOIAS', 'MATO GROSSO', 'MATO GROSSO DO SUL',
       'ALAGOAS', 'BAHIA', 'CEARA', 'MARANHAO', 'PARAIBA', 'PERNAMBUCO',
       'PIAUI', 'RIO GRANDE DO NORTE', 'SERGIPE', 'ACRE', 'AMAPA',
       'AMAZONAS', 'PARA', 'RONDONIA', 'RORAIMA', 'TOCANTINS',
       'ESPIRITO SANTO', 'MINAS GERAIS', 'RIO DE JANEIRO', 'SAO PAULO',
       'PARANA', 'RIO GRANDE DO SUL', 'SANTA CATARINA'], dtype=object)

#Selecionando apenas os preços dos Postos de São Paulo
==> Alternativa 1: Seleção Condicional (Comparações diretas)
O código abaixo retorna uma Series ('array') de booleans, com o número de linhas (amostras) do Data Frame, que informa os registros de preços dos postos do estado de São Paulo (True).

In [463]:
data['ESTADO'] == 'SAO PAULO'

0         False
1         False
2         False
3         False
4         False
          ...
106818    False
106819    False
106820    False
106821     True
106822    False
Name: ESTADO, Length: 106823, dtype: bool

In [464]:
selecao = data['ESTADO'] == 'SAO PAULO'

In [465]:
selecao

0         False
1         False
2         False
3         False
4         False
          ...
106818    False
106819    False
106820    False
106821     True
106822    False
Name: ESTADO, Length: 106823, dtype: bool

In [466]:
type(selecao)

pandas.core.series.Series

In [467]:
selecao.shape

(106823,)

Para filtrarmos os registros de postos do estado de São Paulo

In [468]:
data[selecao]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,...,0.57,0.056,0.4271,1.4123,0.098,5,2004,DEFAULT,23,4.608
50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,...,0.576,0.05,0.43204,0.9724,0.087,5,2004,DEFAULT,50,4.596
77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,0.620,...,0.614,0.063,0.34951,1.412,0.103,5,2004,DEFAULT,77,4.938
104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,0.639,...,0.671,0.075,0.3398,1.0669,0.112,5,2004,DEFAULT,104,5.322
131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,0.669,...,0.689,0.072,0.47797,1.0669,0.104,6,2004,DEFAULT,131,5.364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106724,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL,863,R$/l,3.448,0.156,3.099,...,3.047,0.097,2.8599,3.3481,0.032,6,2019,DEFAULT,106724,20.688
106751,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL S10,1277,R$/l,3.574,0.169,3.199,...,3.123,0.111,2.885,3.491,0.036,6,2019,DEFAULT,106751,21.444
106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,3.769,...,3.713,0.097,3.52,4.0892,0.026,6,2019,DEFAULT,106778,24.852
106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,50.000,...,49.214,5.071,40.19,72,0.103,6,2019,DEFAULT,106805,401.358
106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,...,2.374,0.165,2.0179,2.5093,0.07,6,2019,DEFAULT,106821,18.120

In [469]:
data.loc[selecao]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,...,0.57,0.056,0.4271,1.4123,0.098,5,2004,DEFAULT,23,4.608
50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,...,0.576,0.05,0.43204,0.9724,0.087,5,2004,DEFAULT,50,4.596
77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,0.620,...,0.614,0.063,0.34951,1.412,0.103,5,2004,DEFAULT,77,4.938
104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,0.639,...,0.671,0.075,0.3398,1.0669,0.112,5,2004,DEFAULT,104,5.322
131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,0.669,...,0.689,0.072,0.47797,1.0669,0.104,6,2004,DEFAULT,131,5.364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106724,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL,863,R$/l,3.448,0.156,3.099,...,3.047,0.097,2.8599,3.3481,0.032,6,2019,DEFAULT,106724,20.688
106751,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL S10,1277,R$/l,3.574,0.169,3.199,...,3.123,0.111,2.885,3.491,0.036,6,2019,DEFAULT,106751,21.444
106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,3.769,...,3.713,0.097,3.52,4.0892,0.026,6,2019,DEFAULT,106778,24.852
106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,50.000,...,49.214,5.071,40.19,72,0.103,6,2019,DEFAULT,106805,401.358
106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,...,2.374,0.165,2.0179,2.5093,0.07,6,2019,DEFAULT,106821,18.120

#==> Alternativa 2: Utilizando o método query
query filtra linhas de um DataFrame baseado em uma query (pergunta).

In [470]:
data.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,...,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0,7.728
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,...,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,6.972
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,...,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2,8.334
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,...,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,7.572
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,...,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4,7.086

In [471]:
data.query('ESTADO  == "SAO PAULO"')

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,...,0.57,0.056,0.4271,1.4123,0.098,5,2004,DEFAULT,23,4.608
50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,...,0.576,0.05,0.43204,0.9724,0.087,5,2004,DEFAULT,50,4.596
77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,0.620,...,0.614,0.063,0.34951,1.412,0.103,5,2004,DEFAULT,77,4.938
104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,0.639,...,0.671,0.075,0.3398,1.0669,0.112,5,2004,DEFAULT,104,5.322
131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,0.669,...,0.689,0.072,0.47797,1.0669,0.104,6,2004,DEFAULT,131,5.364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106724,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL,863,R$/l,3.448,0.156,3.099,...,3.047,0.097,2.8599,3.3481,0.032,6,2019,DEFAULT,106724,20.688
106751,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL S10,1277,R$/l,3.574,0.169,3.199,...,3.123,0.111,2.885,3.491,0.036,6,2019,DEFAULT,106751,21.444
106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,3.769,...,3.713,0.097,3.52,4.0892,0.026,6,2019,DEFAULT,106778,24.852
106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,50.000,...,49.214,5.071,40.19,72,0.103,6,2019,DEFAULT,106805,401.358
106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,...,2.374,0.165,2.0179,2.5093,0.07,6,2019,DEFAULT,106821,18.120

In [472]:
postos_sp = data.query('ESTADO  == "SAO PAULO"')

In [473]:
postos_sp

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,...,0.57,0.056,0.4271,1.4123,0.098,5,2004,DEFAULT,23,4.608
50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,...,0.576,0.05,0.43204,0.9724,0.087,5,2004,DEFAULT,50,4.596
77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,0.620,...,0.614,0.063,0.34951,1.412,0.103,5,2004,DEFAULT,77,4.938
104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,0.639,...,0.671,0.075,0.3398,1.0669,0.112,5,2004,DEFAULT,104,5.322
131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,0.669,...,0.689,0.072,0.47797,1.0669,0.104,6,2004,DEFAULT,131,5.364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106724,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL,863,R$/l,3.448,0.156,3.099,...,3.047,0.097,2.8599,3.3481,0.032,6,2019,DEFAULT,106724,20.688
106751,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL S10,1277,R$/l,3.574,0.169,3.199,...,3.123,0.111,2.885,3.491,0.036,6,2019,DEFAULT,106751,21.444
106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,3.769,...,3.713,0.097,3.52,4.0892,0.026,6,2019,DEFAULT,106778,24.852
106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,50.000,...,49.214,5.071,40.19,72,0.103,6,2019,DEFAULT,106805,401.358
106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,...,2.374,0.165,2.0179,2.5093,0.07,6,2019,DEFAULT,106821,18.120

In [474]:
type(postos_sp)

pandas.core.frame.DataFrame

In [475]:
postos_sp.shape

(4263, 23)

In [476]:
postos_sp.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,...,0.57,0.056,0.4271,1.4123,0.098,5,2004,DEFAULT,23,4.608
50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,...,0.576,0.05,0.43204,0.9724,0.087,5,2004,DEFAULT,50,4.596
77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,0.620,...,0.614,0.063,0.34951,1.412,0.103,5,2004,DEFAULT,77,4.938
104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,0.639,...,0.671,0.075,0.3398,1.0669,0.112,5,2004,DEFAULT,104,5.322
131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,0.669,...,0.689,0.072,0.47797,1.0669,0.104,6,2004,DEFAULT,131,5.364

In [477]:
postos_sp.reset_index(drop=True)

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
0,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,...,0.57,0.056,0.4271,1.4123,0.098,5,2004,DEFAULT,23,4.608
1,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,...,0.576,0.05,0.43204,0.9724,0.087,5,2004,DEFAULT,50,4.596
2,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,0.620,...,0.614,0.063,0.34951,1.412,0.103,5,2004,DEFAULT,77,4.938
3,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,0.639,...,0.671,0.075,0.3398,1.0669,0.112,5,2004,DEFAULT,104,5.322
4,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,0.669,...,0.689,0.072,0.47797,1.0669,0.104,6,2004,DEFAULT,131,5.364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4258,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL,863,R$/l,3.448,0.156,3.099,...,3.047,0.097,2.8599,3.3481,0.032,6,2019,DEFAULT,106724,20.688
4259,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL S10,1277,R$/l,3.574,0.169,3.199,...,3.123,0.111,2.885,3.491,0.036,6,2019,DEFAULT,106751,21.444
4260,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,3.769,...,3.713,0.097,3.52,4.0892,0.026,6,2019,DEFAULT,106778,24.852
4261,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,50.000,...,49.214,5.071,40.19,72,0.103,6,2019,DEFAULT,106805,401.358
4262,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,...,2.374,0.165,2.0179,2.5093,0.07,6,2019,DEFAULT,106821,18.120

In [478]:
postos_sp

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,...,0.57,0.056,0.4271,1.4123,0.098,5,2004,DEFAULT,23,4.608
50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,...,0.576,0.05,0.43204,0.9724,0.087,5,2004,DEFAULT,50,4.596
77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,0.620,...,0.614,0.063,0.34951,1.412,0.103,5,2004,DEFAULT,77,4.938
104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,0.639,...,0.671,0.075,0.3398,1.0669,0.112,5,2004,DEFAULT,104,5.322
131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,0.669,...,0.689,0.072,0.47797,1.0669,0.104,6,2004,DEFAULT,131,5.364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106724,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL,863,R$/l,3.448,0.156,3.099,...,3.047,0.097,2.8599,3.3481,0.032,6,2019,DEFAULT,106724,20.688
106751,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL S10,1277,R$/l,3.574,0.169,3.199,...,3.123,0.111,2.885,3.491,0.036,6,2019,DEFAULT,106751,21.444
106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,3.769,...,3.713,0.097,3.52,4.0892,0.026,6,2019,DEFAULT,106778,24.852
106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,50.000,...,49.214,5.071,40.19,72,0.103,6,2019,DEFAULT,106805,401.358
106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,...,2.374,0.165,2.0179,2.5093,0.07,6,2019,DEFAULT,106821,18.120

In [479]:
postos_sp.reset_index(drop=True, inplace=True)

In [480]:
postos_sp

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
0,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,...,0.57,0.056,0.4271,1.4123,0.098,5,2004,DEFAULT,23,4.608
1,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,...,0.576,0.05,0.43204,0.9724,0.087,5,2004,DEFAULT,50,4.596
2,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,0.620,...,0.614,0.063,0.34951,1.412,0.103,5,2004,DEFAULT,77,4.938
3,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,0.639,...,0.671,0.075,0.3398,1.0669,0.112,5,2004,DEFAULT,104,5.322
4,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,0.669,...,0.689,0.072,0.47797,1.0669,0.104,6,2004,DEFAULT,131,5.364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4258,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL,863,R$/l,3.448,0.156,3.099,...,3.047,0.097,2.8599,3.3481,0.032,6,2019,DEFAULT,106724,20.688
4259,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL S10,1277,R$/l,3.574,0.169,3.199,...,3.123,0.111,2.885,3.491,0.036,6,2019,DEFAULT,106751,21.444
4260,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,3.769,...,3.713,0.097,3.52,4.0892,0.026,6,2019,DEFAULT,106778,24.852
4261,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,50.000,...,49.214,5.071,40.19,72,0.103,6,2019,DEFAULT,106805,401.358
4262,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,...,2.374,0.165,2.0179,2.5093,0.07,6,2019,DEFAULT,106821,18.120

In [481]:
postos_sp = data.query('ESTADO  == "SAO PAULO"').reset_index(drop=True)

In [482]:
postos_sp

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
0,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,...,0.57,0.056,0.4271,1.4123,0.098,5,2004,DEFAULT,23,4.608
1,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,...,0.576,0.05,0.43204,0.9724,0.087,5,2004,DEFAULT,50,4.596
2,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,0.620,...,0.614,0.063,0.34951,1.412,0.103,5,2004,DEFAULT,77,4.938
3,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,0.639,...,0.671,0.075,0.3398,1.0669,0.112,5,2004,DEFAULT,104,5.322
4,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,0.669,...,0.689,0.072,0.47797,1.0669,0.104,6,2004,DEFAULT,131,5.364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4258,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL,863,R$/l,3.448,0.156,3.099,...,3.047,0.097,2.8599,3.3481,0.032,6,2019,DEFAULT,106724,20.688
4259,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL S10,1277,R$/l,3.574,0.169,3.199,...,3.123,0.111,2.885,3.491,0.036,6,2019,DEFAULT,106751,21.444
4260,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,3.769,...,3.713,0.097,3.52,4.0892,0.026,6,2019,DEFAULT,106778,24.852
4261,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,50.000,...,49.214,5.071,40.19,72,0.103,6,2019,DEFAULT,106805,401.358
4262,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,...,2.374,0.165,2.0179,2.5093,0.07,6,2019,DEFAULT,106821,18.120

Selecionando registros de postos do Rio de Janeiro com Preços acima de 2 reais

In [483]:
data.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,...,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0,7.728
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,...,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,6.972
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,...,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2,8.334
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,...,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,7.572
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,...,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4,7.086

In [484]:
data['ESTADO'] == 'RIO DE JANEIRO'

0         False
1         False
2         False
3         False
4         False
          ...
106818    False
106819    False
106820    False
106821    False
106822    False
Name: ESTADO, Length: 106823, dtype: bool

In [485]:
data['PREÇO MÉDIO REVENDA'] >2.0

0         False
1         False
2         False
3         False
4         False
          ...
106818     True
106819     True
106820     True
106821     True
106822     True
Name: PREÇO MÉDIO REVENDA, Length: 106823, dtype: bool

In [486]:
selecao = (data['ESTADO'] == 'RIO DE JANEIRO') & (data['PREÇO MÉDIO REVENDA'] >2.0)

In [487]:
selecao

0         False
1         False
2         False
3         False
4         False
          ...
106818    False
106819    False
106820    False
106821    False
106822    False
Length: 106823, dtype: bool

Note que o resultado da seleção continua sendo uma Series de booleans com o mesmo número de linhas/amostras do DataFrame, de modo que cada linha possuirá um valor booleano indicando se o posto é do Rio de Janeiro e o preço aferido do combustível é maior que 2 reais (True) ou não.

O símbolo & significa AND na comparação. Essa nomenclatura do python/pandas é diferente das nomenclaturas tradicionais (&&).
Similarmente:

| representa o OR (não é ||)
~ representa o NOT (não é !)

In [488]:
data[selecao]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
2501,2006-02-26,2006-03-04,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,881,R$/l,2.028,0.148,1.589,...,1.806,0.11,1.31,2.1358,0.061,2,2006,DEFAULT,2501,12.168
2528,2006-03-05,2006-03-11,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,889,R$/l,2.125,0.149,1.779,...,1.839,0.117,1.438,2.2801,0.064,3,2006,DEFAULT,2528,12.750
2555,2006-03-12,2006-03-18,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,902,R$/l,2.163,0.138,1.799,...,1.895,0.134,1.43,2.3454,0.071,3,2006,DEFAULT,2555,12.978
2582,2006-03-19,2006-03-25,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,898,R$/l,2.166,0.146,1.760,...,1.935,0.14,1.438,2.2925,0.072,3,2006,DEFAULT,2582,12.996
2609,2006-03-26,2006-04-01,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,890,R$/l,2.172,0.143,1.789,...,1.963,0.133,1.438,2.2513,0.068,3,2006,DEFAULT,2609,13.032
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106718,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,ÓLEO DIESEL,212,R$/l,3.569,0.166,3.179,...,3.102,0.119,2.886,3.5162,0.038,6,2019,DEFAULT,106718,21.414
106745,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,ÓLEO DIESEL S10,335,R$/l,3.697,0.187,3.279,...,3.197,0.127,2.9772,3.5388,0.04,6,2019,DEFAULT,106745,22.182
106772,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,422,R$/l,4.928,0.165,4.599,...,4.39,0.097,4.2,4.618,0.022,6,2019,DEFAULT,106772,29.568
106799,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GLP,221,R$/13Kg,65.010,5.812,50.000,...,47.535,3.934,39,58.2,0.083,6,2019,DEFAULT,106799,390.060
106817,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GNV,124,R$/m3,3.111,0.260,2.799,...,2.404,0.174,2.126,2.7909,0.072,6,2019,DEFAULT,106817,18.666

Alternativamente, poderíamos usar o método query para fazermos tal seleção. Porém, isso não é possível especificamente para esse caso, pois o rótulo da coluna 'PREÇO MÉDIO REVENDA' possui caracteres inválidos para o método (cedilha, acentos)

In [489]:
data.query('ESTADO  == "RIO DE JANEIRO" or ESTADO == "SAO PAULO"')

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
22,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,952,R$/l,1.098,0.154,0.740,...,0.786,0.173,0.326,1.263,0.22,5,2004,DEFAULT,22,6.588
23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,...,0.57,0.056,0.4271,1.4123,0.098,5,2004,DEFAULT,23,4.608
49,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,948,R$/l,1.092,0.157,0.740,...,0.808,0.175,0.3257,1.2921,0.217,5,2004,DEFAULT,49,6.552
50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,...,0.576,0.05,0.43204,0.9724,0.087,5,2004,DEFAULT,50,4.596
76,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,973,R$/l,1.103,0.140,0.770,...,0.822,0.166,0.38909,1.1859,0.202,5,2004,DEFAULT,76,6.618
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,3.769,...,3.713,0.097,3.52,4.0892,0.026,6,2019,DEFAULT,106778,24.852
106799,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GLP,221,R$/13Kg,65.010,5.812,50.000,...,47.535,3.934,39,58.2,0.083,6,2019,DEFAULT,106799,390.060
106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,50.000,...,49.214,5.071,40.19,72,0.103,6,2019,DEFAULT,106805,401.358
106817,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GNV,124,R$/m3,3.111,0.260,2.799,...,2.404,0.174,2.126,2.7909,0.072,6,2019,DEFAULT,106817,18.666
106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,...,2.374,0.165,2.0179,2.5093,0.07,6,2019,DEFAULT,106821,18.120

Aprofundando mais ainda

A primeira comparação (data['ESTADO'] == 'RIO DE JANEIRO') checa, linha a linha (amostra a amostra) do DataFrame, quais são aquelas cujo o estado é RIO DE JANEIRO. Nenhuma averiguação de preços é feita nesse momento. Como resultado, temos uma Series de booleans que responde apenas a essa "pergunta" feita.

A segunda comparação (data['PREÇO MÉDIO REVENDA'] > 2) checa, linha a linha (amostra a amostra) do DataFrame, quais são os registro cujo preço do combustível é maior que 2 reais. Note que essa comparação checará os postos de TODOS os estados. Como resultado, temos uma Series de booleans que responde apenas a essa "pergunta" feita.

Por fim, as duas "perguntas" são unidas pelo AND (&) que retorna a "pergunta completa" que fizemos.

Alguns podem argumentar que tal abordagem é ineficiente, uma vez que, para cada condição ("pergunta"), estamos varrendo todas as linhas do DataFrame.
O Pandas tenta otimizar isso ao máximo por de trás dos panos. Mas, de fato, de tivermos um dataset muito grande (centenas de milhares de linhas), tal abordagem se tornará lenta.

In [490]:
selecao_1 = data['ESTADO'] == 'RIO DE JANEIRO'
postos_rj = data[selecao_1]
postos_rj

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
22,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,952,R$/l,1.098,0.154,0.740,...,0.786,0.173,0.326,1.263,0.22,5,2004,DEFAULT,22,6.588
49,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,948,R$/l,1.092,0.157,0.740,...,0.808,0.175,0.3257,1.2921,0.217,5,2004,DEFAULT,49,6.552
76,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,973,R$/l,1.103,0.140,0.770,...,0.822,0.166,0.38909,1.1859,0.202,5,2004,DEFAULT,76,6.618
103,2004-05-30,2004-06-05,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,955,R$/l,1.149,0.156,0.799,...,0.849,0.188,0.3453,1.3667,0.221,5,2004,DEFAULT,103,6.894
130,2004-06-06,2004-06-12,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,966,R$/l,1.165,0.154,0.830,...,0.911,0.198,0.4,1.3667,0.217,6,2004,DEFAULT,130,6.990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106718,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,ÓLEO DIESEL,212,R$/l,3.569,0.166,3.179,...,3.102,0.119,2.886,3.5162,0.038,6,2019,DEFAULT,106718,21.414
106745,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,ÓLEO DIESEL S10,335,R$/l,3.697,0.187,3.279,...,3.197,0.127,2.9772,3.5388,0.04,6,2019,DEFAULT,106745,22.182
106772,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,422,R$/l,4.928,0.165,4.599,...,4.39,0.097,4.2,4.618,0.022,6,2019,DEFAULT,106772,29.568
106799,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GLP,221,R$/13Kg,65.010,5.812,50.000,...,47.535,3.934,39,58.2,0.083,6,2019,DEFAULT,106799,390.060
106817,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GNV,124,R$/m3,3.111,0.260,2.799,...,2.404,0.174,2.126,2.7909,0.072,6,2019,DEFAULT,106817,18.666

In [491]:
selecao_2 = postos_rj['PREÇO MÉDIO REVENDA'] > 2
selecao_2

22        False
49        False
76        False
103       False
130       False
          ...
106718     True
106745     True
106772     True
106799     True
106817     True
Name: PREÇO MÉDIO REVENDA, Length: 4263, dtype: bool

In [492]:
postos_rj_preco_maior_que_2 = postos_rj[selecao_2]
postos_rj_preco_maior_que_2

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
2501,2006-02-26,2006-03-04,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,881,R$/l,2.028,0.148,1.589,...,1.806,0.11,1.31,2.1358,0.061,2,2006,DEFAULT,2501,12.168
2528,2006-03-05,2006-03-11,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,889,R$/l,2.125,0.149,1.779,...,1.839,0.117,1.438,2.2801,0.064,3,2006,DEFAULT,2528,12.750
2555,2006-03-12,2006-03-18,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,902,R$/l,2.163,0.138,1.799,...,1.895,0.134,1.43,2.3454,0.071,3,2006,DEFAULT,2555,12.978
2582,2006-03-19,2006-03-25,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,898,R$/l,2.166,0.146,1.760,...,1.935,0.14,1.438,2.2925,0.072,3,2006,DEFAULT,2582,12.996
2609,2006-03-26,2006-04-01,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,890,R$/l,2.172,0.143,1.789,...,1.963,0.133,1.438,2.2513,0.068,3,2006,DEFAULT,2609,13.032
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106718,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,ÓLEO DIESEL,212,R$/l,3.569,0.166,3.179,...,3.102,0.119,2.886,3.5162,0.038,6,2019,DEFAULT,106718,21.414
106745,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,ÓLEO DIESEL S10,335,R$/l,3.697,0.187,3.279,...,3.197,0.127,2.9772,3.5388,0.04,6,2019,DEFAULT,106745,22.182
106772,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,422,R$/l,4.928,0.165,4.599,...,4.39,0.097,4.2,4.618,0.022,6,2019,DEFAULT,106772,29.568
106799,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GLP,221,R$/13Kg,65.010,5.812,50.000,...,47.535,3.934,39,58.2,0.083,6,2019,DEFAULT,106799,390.060
106817,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GNV,124,R$/m3,3.111,0.260,2.799,...,2.404,0.174,2.126,2.7909,0.072,6,2019,DEFAULT,106817,18.666

Selecionando registros de postos de São Paulo ou do Rio de Janeiro com Gasolina Comum acima de 2 reais
Podemos fazer a solução do "jeito mais lento", percorrendo o DataFrame inteiro múltiplas vezes:

In [493]:
data.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,...,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0,7.728
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,...,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,6.972
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,...,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2,8.334
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,...,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,7.572
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,...,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4,7.086

In [494]:
selecao1 = (data['ESTADO'] == 'SAO PAULO') | (data['ESTADO'] == 'RIO DE JANEIRO')
selecao2 = (data['PRODUTO'] == 'GASOLINA COMUM')
selecao3 = (data['PREÇO MÉDIO REVENDA'] > 2)

selecaofinal = selecao1 & selecao2 & selecao3

In [495]:
selecaofinal

0         False
1         False
2         False
3         False
4         False
          ...
106818    False
106819    False
106820    False
106821    False
106822    False
Length: 106823, dtype: bool

In [496]:
data_filtrado = data[selecaofinal]
data_filtrado

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
12086,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1071,R$/l,2.045,0.109,1.700,...,1.791,0.047,1.6363,1.9594,0.026,5,2004,DEFAULT,12086,12.270
12113,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1055,R$/l,2.040,0.113,1.700,...,1.788,0.049,1.5943,1.99651,0.027,5,2004,DEFAULT,12113,12.240
12140,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1091,R$/l,2.042,0.108,1.700,...,1.79,0.046,1.63596,2.2137,0.026,5,2004,DEFAULT,12140,12.252
12167,2004-05-30,2004-06-05,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1055,R$/l,2.053,0.111,1.730,...,1.802,0.055,1.64,2.21425,0.031,5,2004,DEFAULT,12167,12.318
12194,2004-06-06,2004-06-12,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1091,R$/l,2.063,0.107,1.760,...,1.816,0.054,1.64,2.32425,0.03,6,2004,DEFAULT,12194,12.378
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106479,2019-06-09,2019-06-15,SUDESTE,SAO PAULO,GASOLINA COMUM,1643,R$/l,4.210,0.177,3.759,...,3.785,0.096,3.52,4.1007,0.025,6,2019,DEFAULT,106479,25.260
106623,2019-06-16,2019-06-22,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,418,R$/l,4.927,0.160,4.599,...,4.383,0.1,4.1972,4.6239,0.023,6,2019,DEFAULT,106623,29.562
106629,2019-06-16,2019-06-22,SUDESTE,SAO PAULO,GASOLINA COMUM,1635,R$/l,4.168,0.177,3.679,...,3.725,0.096,3.502,4.0892,0.026,6,2019,DEFAULT,106629,25.008
106772,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,422,R$/l,4.928,0.165,4.599,...,4.39,0.097,4.2,4.618,0.022,6,2019,DEFAULT,106772,29.568
106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,3.769,...,3.713,0.097,3.52,4.0892,0.026,6,2019,DEFAULT,106778,24.852

In [497]:
print(data_filtrado['ESTADO'].unique())
print(data_filtrado['PRODUTO'].unique())

['RIO DE JANEIRO' 'SAO PAULO']
['GASOLINA COMUM']

In [498]:
selecao1 = (data['ESTADO'] == 'SAO PAULO') | (data['ESTADO'] == 'RIO DE JANEIRO')
postos_sp_rj = data[selecao1]
postos_sp_rj

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
22,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,952,R$/l,1.098,0.154,0.740,...,0.786,0.173,0.326,1.263,0.22,5,2004,DEFAULT,22,6.588
23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,0.590,...,0.57,0.056,0.4271,1.4123,0.098,5,2004,DEFAULT,23,4.608
49,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,948,R$/l,1.092,0.157,0.740,...,0.808,0.175,0.3257,1.2921,0.217,5,2004,DEFAULT,49,6.552
50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,0.590,...,0.576,0.05,0.43204,0.9724,0.087,5,2004,DEFAULT,50,4.596
76,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,973,R$/l,1.103,0.140,0.770,...,0.822,0.166,0.38909,1.1859,0.202,5,2004,DEFAULT,76,6.618
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,3.769,...,3.713,0.097,3.52,4.0892,0.026,6,2019,DEFAULT,106778,24.852
106799,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GLP,221,R$/13Kg,65.010,5.812,50.000,...,47.535,3.934,39,58.2,0.083,6,2019,DEFAULT,106799,390.060
106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,50.000,...,49.214,5.071,40.19,72,0.103,6,2019,DEFAULT,106805,401.358
106817,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GNV,124,R$/m3,3.111,0.260,2.799,...,2.404,0.174,2.126,2.7909,0.072,6,2019,DEFAULT,106817,18.666
106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,...,2.374,0.165,2.0179,2.5093,0.07,6,2019,DEFAULT,106821,18.120

In [499]:
selecao2 = (postos_sp_rj['PRODUTO'] == 'GASOLINA COMUM')
gasolina_sp_rj = postos_sp_rj[selecao2]
gasolina_sp_rj

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
12086,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1071,R$/l,2.045,0.109,1.700,...,1.791,0.047,1.6363,1.9594,0.026,5,2004,DEFAULT,12086,12.270
12087,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,GASOLINA COMUM,4107,R$/l,1.891,0.101,1.570,...,1.656,0.064,1.38,1.944,0.039,5,2004,DEFAULT,12087,11.346
12113,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1055,R$/l,2.040,0.113,1.700,...,1.788,0.049,1.5943,1.99651,0.027,5,2004,DEFAULT,12113,12.240
12114,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,GASOLINA COMUM,4133,R$/l,1.888,0.101,1.540,...,1.655,0.063,1.38,1.9319,0.038,5,2004,DEFAULT,12114,11.328
12140,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1091,R$/l,2.042,0.108,1.700,...,1.79,0.046,1.63596,2.2137,0.026,5,2004,DEFAULT,12140,12.252
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106479,2019-06-09,2019-06-15,SUDESTE,SAO PAULO,GASOLINA COMUM,1643,R$/l,4.210,0.177,3.759,...,3.785,0.096,3.52,4.1007,0.025,6,2019,DEFAULT,106479,25.260
106623,2019-06-16,2019-06-22,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,418,R$/l,4.927,0.160,4.599,...,4.383,0.1,4.1972,4.6239,0.023,6,2019,DEFAULT,106623,29.562
106629,2019-06-16,2019-06-22,SUDESTE,SAO PAULO,GASOLINA COMUM,1635,R$/l,4.168,0.177,3.679,...,3.725,0.096,3.502,4.0892,0.026,6,2019,DEFAULT,106629,25.008
106772,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,422,R$/l,4.928,0.165,4.599,...,4.39,0.097,4.2,4.618,0.022,6,2019,DEFAULT,106772,29.568
106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,3.769,...,3.713,0.097,3.52,4.0892,0.026,6,2019,DEFAULT,106778,24.852

In [500]:
selecao3 = (gasolina_sp_rj['PREÇO MÉDIO REVENDA'] > 2)
gasolina_sp_rj2 = gasolina_sp_rj[selecao3]
gasolina_sp_rj2

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
12086,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1071,R$/l,2.045,0.109,1.700,...,1.791,0.047,1.6363,1.9594,0.026,5,2004,DEFAULT,12086,12.270
12113,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1055,R$/l,2.040,0.113,1.700,...,1.788,0.049,1.5943,1.99651,0.027,5,2004,DEFAULT,12113,12.240
12140,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1091,R$/l,2.042,0.108,1.700,...,1.79,0.046,1.63596,2.2137,0.026,5,2004,DEFAULT,12140,12.252
12167,2004-05-30,2004-06-05,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1055,R$/l,2.053,0.111,1.730,...,1.802,0.055,1.64,2.21425,0.031,5,2004,DEFAULT,12167,12.318
12194,2004-06-06,2004-06-12,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1091,R$/l,2.063,0.107,1.760,...,1.816,0.054,1.64,2.32425,0.03,6,2004,DEFAULT,12194,12.378
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106479,2019-06-09,2019-06-15,SUDESTE,SAO PAULO,GASOLINA COMUM,1643,R$/l,4.210,0.177,3.759,...,3.785,0.096,3.52,4.1007,0.025,6,2019,DEFAULT,106479,25.260
106623,2019-06-16,2019-06-22,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,418,R$/l,4.927,0.160,4.599,...,4.383,0.1,4.1972,4.6239,0.023,6,2019,DEFAULT,106623,29.562
106629,2019-06-16,2019-06-22,SUDESTE,SAO PAULO,GASOLINA COMUM,1635,R$/l,4.168,0.177,3.679,...,3.725,0.096,3.502,4.0892,0.026,6,2019,DEFAULT,106629,25.008
106772,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,422,R$/l,4.928,0.165,4.599,...,4.39,0.097,4.2,4.618,0.022,6,2019,DEFAULT,106772,29.568
106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,3.769,...,3.713,0.097,3.52,4.0892,0.026,6,2019,DEFAULT,106778,24.852

In [501]:
data.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,...,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0,7.728
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,...,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,6.972
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,...,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2,8.334
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,...,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,7.572
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,...,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4,7.086

In [502]:
selecao = (data['ANO'] == 2008) | (data['ANO']== 2010) | (data['ANO'] == 2012)
data[selecao]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
5098,2008-01-06,2008-01-12,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,80,R$/l,1.806,0.082,1.709,...,1.516,0.061,1.3892,1.6157,0.04,1,2008,DEFAULT,5098,10.836
5099,2008-01-06,2008-01-12,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,255,R$/l,1.616,0.100,1.470,...,1.323,0.05,1.2242,1.6173,0.038,1,2008,DEFAULT,5099,9.696
5100,2008-01-06,2008-01-12,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,142,R$/l,1.581,0.095,1.390,...,1.303,0.073,1.14,1.45,0.056,1,2008,DEFAULT,5100,9.486
5101,2008-01-06,2008-01-12,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,133,R$/l,1.831,0.046,1.680,...,1.449,0.044,1.3247,1.5514,0.03,1,2008,DEFAULT,5101,10.986
5102,2008-01-06,2008-01-12,NORDESTE,ALAGOAS,ETANOL HIDRATADO,97,R$/l,1.699,0.098,1.530,...,1.5,0.062,1.39,1.7689,0.041,1,2008,DEFAULT,5102,10.194
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55754,2012-12-30,2013-01-05,NORDESTE,RIO GRANDE DO NORTE,GNV,17,R$/m3,1.891,0.015,1.860,...,1.425,0.098,1.2657,1.4789,0.069,12,2012,DEFAULT,55754,11.346
55755,2012-12-30,2013-01-05,SUL,RIO GRANDE DO SUL,GNV,34,R$/m3,1.980,0.040,1.919,...,1.414,0.028,1.3997,1.4608,0.02,12,2012,DEFAULT,55755,11.880
55756,2012-12-30,2013-01-05,SUL,SANTA CATARINA,GNV,41,R$/m3,2.003,0.034,1.879,...,-,-,-,-,-,12,2012,DEFAULT,55756,12.018
55757,2012-12-30,2013-01-05,SUDESTE,SAO PAULO,GNV,82,R$/m3,1.598,0.199,1.399,...,1.201,0.182,0.8354,1.535,0.152,12,2012,DEFAULT,55757,9.588
55758,2012-12-30,2013-01-05,NORDESTE,SERGIPE,GNV,11,R$/m3,1.847,0.033,1.790,...,1.343,0.178,1.1253,1.543,0.133,12,2012,DEFAULT,55758,11.082

In [503]:
lista_de_anos = [2008,2010,2012]

In [504]:
selecao = data['ANO'].isin(lista_de_anos)
selecao

0         False
1         False
2         False
3         False
4         False
          ...
106818    False
106819    False
106820    False
106821    False
106822    False
Name: ANO, Length: 106823, dtype: bool

In [505]:
data.query('ANO in @lista_de_anos')

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
5098,2008-01-06,2008-01-12,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,80,R$/l,1.806,0.082,1.709,...,1.516,0.061,1.3892,1.6157,0.04,1,2008,DEFAULT,5098,10.836
5099,2008-01-06,2008-01-12,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,255,R$/l,1.616,0.100,1.470,...,1.323,0.05,1.2242,1.6173,0.038,1,2008,DEFAULT,5099,9.696
5100,2008-01-06,2008-01-12,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,142,R$/l,1.581,0.095,1.390,...,1.303,0.073,1.14,1.45,0.056,1,2008,DEFAULT,5100,9.486
5101,2008-01-06,2008-01-12,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,133,R$/l,1.831,0.046,1.680,...,1.449,0.044,1.3247,1.5514,0.03,1,2008,DEFAULT,5101,10.986
5102,2008-01-06,2008-01-12,NORDESTE,ALAGOAS,ETANOL HIDRATADO,97,R$/l,1.699,0.098,1.530,...,1.5,0.062,1.39,1.7689,0.041,1,2008,DEFAULT,5102,10.194
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55754,2012-12-30,2013-01-05,NORDESTE,RIO GRANDE DO NORTE,GNV,17,R$/m3,1.891,0.015,1.860,...,1.425,0.098,1.2657,1.4789,0.069,12,2012,DEFAULT,55754,11.346
55755,2012-12-30,2013-01-05,SUL,RIO GRANDE DO SUL,GNV,34,R$/m3,1.980,0.040,1.919,...,1.414,0.028,1.3997,1.4608,0.02,12,2012,DEFAULT,55755,11.880
55756,2012-12-30,2013-01-05,SUL,SANTA CATARINA,GNV,41,R$/m3,2.003,0.034,1.879,...,-,-,-,-,-,12,2012,DEFAULT,55756,12.018
55757,2012-12-30,2013-01-05,SUDESTE,SAO PAULO,GNV,82,R$/m3,1.598,0.199,1.399,...,1.201,0.182,0.8354,1.535,0.152,12,2012,DEFAULT,55757,9.588
55758,2012-12-30,2013-01-05,NORDESTE,SERGIPE,GNV,11,R$/m3,1.847,0.033,1.790,...,1.343,0.178,1.1253,1.543,0.133,12,2012,DEFAULT,55758,11.082

#Iterando com DataFrames
For-each DataFrame.iterrows() (LENTO ==> apenas indicado para iterar pequenos conjunto de dados)

In [506]:
for index,row in data.head(10).iterrows():
  print(f'indice {index} ==> {row['ESTADO']}')

indice 0 ==> DISTRITO FEDERAL
indice 1 ==> GOIAS
indice 2 ==> MATO GROSSO
indice 3 ==> MATO GROSSO DO SUL
indice 4 ==> ALAGOAS
indice 5 ==> BAHIA
indice 6 ==> CEARA
indice 7 ==> MARANHAO
indice 8 ==> PARAIBA
indice 9 ==> PERNAMBUCO

#2. Preparação dos dados

In [507]:
data

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,...,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0,7.728
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,...,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1,6.972
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,...,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2,8.334
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,...,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,7.572
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,...,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4,7.086
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,3.499,...,2.756,0,2.756,2.756,0,6,2019,DEFAULT,106818,21.444
106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,3.230,...,2.451,0.402,1.9842,2.8661,0.164,6,2019,DEFAULT,106819,20.406
106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,2.699,...,1.998,0,1.9981,1.9981,0,6,2019,DEFAULT,106820,17.472
106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,...,2.374,0.165,2.0179,2.5093,0.07,6,2019,DEFAULT,106821,18.120
106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,3.689,...,2.518,0,2.5175,2.5175,0,6,2019,DEFAULT,106822,22.182

2.1 Removendo amostras com valores vazios (null / nan) no dataset

In [508]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 23 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   DATA INICIAL                      106823 non-null  object
 1   DATA FINAL                        106823 non-null  object
 2   REGIÃO                            106823 non-null  object
 3   ESTADO                            106823 non-null  object
 4   PRODUTO                           106823 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS      106823 non-null  int64
 6   UNIDADE DE MEDIDA                 106823 non-null  object
 7   PREÇO MÉDIO REVENDA               106823 non-null  float64
 8   DESVIO PADRÃO REVENDA             106823 non-null  float64
 9   PREÇO MÍNIMO REVENDA              106823 non-null  float64
 10  PREÇO MÁXIMO REVENDA              106823 non-null  float64
 11  MARGEM MÉDIA REVENDA              106823 non-null  object
 12  COEF DE VARIAÇÃO REVENDA          106823 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO          106823 non-null  object
 14  DESVIO PADRÃO DISTRIBUIÇÃO        106823 non-null  object
 15  PREÇO MÍNIMO DISTRIBUIÇÃO         106823 non-null  object
 16  PREÇO MÁXIMO DISTRIBUIÇÃO         106823 non-null  object
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO     106823 non-null  object
 18  MÊS                               106823 non-null  int64
 19  ANO                               106823 non-null  int64
 20  coluna sem nocao                  106823 non-null  object
 21  coluna a partir de lista          106823 non-null  int64
 22  PRECO MEDIO DE REVENDA (dolares)  106823 non-null  float64
dtypes: float64(6), int64(4), object(13)
memory usage: 18.7+ MB

2.2 Conversão de tipos de atributos
O pandas automaticamente reconhece os tipos de dados de cada coluna.
Porém, existem alguns atributos que estão com seus tipos errados: P. ex., "PREÇO MÉDIO DISTRIBUIÇÃO" deveria ser float64 e não object.
Nestes casos, muito provavelmente algumas amostras têm um string ao invés de um número para tais atributos.

Os atributos "DATA INICIAL" e "DATA FINAL" deveriam ser do tipo datetime.

Em outros casos, alguns atributos categóricos são objects, mas poderiam ter o tipo category, que é um tipo especial do pandas.
Este tipo é necessário para se utilizar algumas funções específicas do pandas.
Não converteremos para este tipo por ora.

In [509]:
data_pre = data.copy()

### Datas

In [510]:
data_pre['DATA INICIAL'] = pd.to_datetime(data_pre['DATA INICIAL'])
data_pre['DATA FINAL'] = pd.to_datetime(data_pre['DATA FINAL'])

In [511]:
data_pre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 23 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   DATA INICIAL                      106823 non-null  datetime64[ns]
 1   DATA FINAL                        106823 non-null  datetime64[ns]
 2   REGIÃO                            106823 non-null  object
 3   ESTADO                            106823 non-null  object
 4   PRODUTO                           106823 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS      106823 non-null  int64
 6   UNIDADE DE MEDIDA                 106823 non-null  object
 7   PREÇO MÉDIO REVENDA               106823 non-null  float64
 8   DESVIO PADRÃO REVENDA             106823 non-null  float64
 9   PREÇO MÍNIMO REVENDA              106823 non-null  float64
 10  PREÇO MÁXIMO REVENDA              106823 non-null  float64
 11  MARGEM MÉDIA REVENDA              106823 non-null  object
 12  COEF DE VARIAÇÃO REVENDA          106823 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO          106823 non-null  object
 14  DESVIO PADRÃO DISTRIBUIÇÃO        106823 non-null  object
 15  PREÇO MÍNIMO DISTRIBUIÇÃO         106823 non-null  object
 16  PREÇO MÁXIMO DISTRIBUIÇÃO         106823 non-null  object
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO     106823 non-null  object
 18  MÊS                               106823 non-null  int64
 19  ANO                               106823 non-null  int64
 20  coluna sem nocao                  106823 non-null  object
 21  coluna a partir de lista          106823 non-null  int64
 22  PRECO MEDIO DE REVENDA (dolares)  106823 non-null  float64
dtypes: datetime64[ns](2), float64(6), int64(4), object(11)
memory usage: 18.7+ MB

### Dado numericos

In [512]:
for atributo in ['MARGEM MÉDIA REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO', 'DESVIO PADRÃO DISTRIBUIÇÃO', 'PREÇO MÍNIMO DISTRIBUIÇÃO', 'PREÇO MÁXIMO DISTRIBUIÇÃO', 'COEF DE VARIAÇÃO DISTRIBUIÇÃO']:
 data_pre[atributo] = pd.to_numeric(data_pre[atributo], errors='coerce')

In [513]:
data_pre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 23 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   DATA INICIAL                      106823 non-null  datetime64[ns]
 1   DATA FINAL                        106823 non-null  datetime64[ns]
 2   REGIÃO                            106823 non-null  object
 3   ESTADO                            106823 non-null  object
 4   PRODUTO                           106823 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS      106823 non-null  int64
 6   UNIDADE DE MEDIDA                 106823 non-null  object
 7   PREÇO MÉDIO REVENDA               106823 non-null  float64
 8   DESVIO PADRÃO REVENDA             106823 non-null  float64
 9   PREÇO MÍNIMO REVENDA              106823 non-null  float64
 10  PREÇO MÁXIMO REVENDA              106823 non-null  float64
 11  MARGEM MÉDIA REVENDA              103392 non-null  float64
 12  COEF DE VARIAÇÃO REVENDA          106823 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO          103423 non-null  float64
 14  DESVIO PADRÃO DISTRIBUIÇÃO        103423 non-null  float64
 15  PREÇO MÍNIMO DISTRIBUIÇÃO         103423 non-null  float64
 16  PREÇO MÁXIMO DISTRIBUIÇÃO         103423 non-null  float64
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO     103423 non-null  float64
 18  MÊS                               106823 non-null  int64
 19  ANO                               106823 non-null  int64
 20  coluna sem nocao                  106823 non-null  object
 21  coluna a partir de lista          106823 non-null  int64
 22  PRECO MEDIO DE REVENDA (dolares)  106823 non-null  float64
dtypes: datetime64[ns](2), float64(12), int64(4), object(5)
memory usage: 18.7+ MB

##Limpeza de Dados

In [514]:
mask = data_pre['PREÇO MÉDIO DISTRIBUIÇÃO'].isnull()

In [515]:
data_pre[mask]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
1903,2005-09-25,2005-10-01,NORTE,PARA,ETANOL HIDRATADO,2,R$/l,1.694,0.283,1.690,...,NaN,NaN,NaN,NaN,NaN,9,2005,DEFAULT,1903,10.164
1958,2005-10-09,2005-10-15,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.000,0.000,2.000,...,NaN,NaN,NaN,NaN,NaN,10,2005,DEFAULT,1958,12.000
2012,2005-10-23,2005-10-29,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.277,0.023,2.250,...,NaN,NaN,NaN,NaN,NaN,10,2005,DEFAULT,2012,13.662
2497,2006-02-26,2006-03-04,NORTE,RORAIMA,ETANOL HIDRATADO,11,R$/l,2.182,0.040,2.100,...,NaN,NaN,NaN,NaN,NaN,2,2006,DEFAULT,2497,13.092
3199,2006-08-27,2006-09-02,NORTE,RORAIMA,ETANOL HIDRATADO,22,R$/l,2.285,0.068,1.980,...,NaN,NaN,NaN,NaN,NaN,8,2006,DEFAULT,3199,13.710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106664,2019-06-16,2019-06-22,SUDESTE,MINAS GERAIS,GNV,5,R$/m3,3.445,0.147,3.347,...,NaN,NaN,NaN,NaN,NaN,6,2019,DEFAULT,106664,20.670
106666,2019-06-16,2019-06-22,SUL,PARANA,GNV,7,R$/m3,3.132,0.295,3.049,...,NaN,NaN,NaN,NaN,NaN,6,2019,DEFAULT,106666,18.792
106811,2019-06-23,2019-06-29,SUDESTE,ESPIRITO SANTO,GNV,4,R$/m3,3.299,0.005,3.290,...,NaN,NaN,NaN,NaN,NaN,6,2019,DEFAULT,106811,19.794
106813,2019-06-23,2019-06-29,SUDESTE,MINAS GERAIS,GNV,6,R$/m3,3.548,0.100,3.495,...,NaN,NaN,NaN,NaN,NaN,6,2019,DEFAULT,106813,21.288
106815,2019-06-23,2019-06-29,SUL,PARANA,GNV,1,R$/m3,3.290,0.000,3.290,...,NaN,NaN,NaN,NaN,NaN,6,2019,DEFAULT,106815,19.740

In [516]:
data[mask]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
1903,2005-09-25,2005-10-01,NORTE,PARA,ETANOL HIDRATADO,2,R$/l,1.694,0.283,1.690,...,-,-,-,-,-,9,2005,DEFAULT,1903,10.164
1958,2005-10-09,2005-10-15,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.000,0.000,2.000,...,-,-,-,-,-,10,2005,DEFAULT,1958,12.000
2012,2005-10-23,2005-10-29,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.277,0.023,2.250,...,-,-,-,-,-,10,2005,DEFAULT,2012,13.662
2497,2006-02-26,2006-03-04,NORTE,RORAIMA,ETANOL HIDRATADO,11,R$/l,2.182,0.040,2.100,...,-,-,-,-,-,2,2006,DEFAULT,2497,13.092
3199,2006-08-27,2006-09-02,NORTE,RORAIMA,ETANOL HIDRATADO,22,R$/l,2.285,0.068,1.980,...,-,-,-,-,-,8,2006,DEFAULT,3199,13.710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106664,2019-06-16,2019-06-22,SUDESTE,MINAS GERAIS,GNV,5,R$/m3,3.445,0.147,3.347,...,-,-,-,-,-,6,2019,DEFAULT,106664,20.670
106666,2019-06-16,2019-06-22,SUL,PARANA,GNV,7,R$/m3,3.132,0.295,3.049,...,-,-,-,-,-,6,2019,DEFAULT,106666,18.792
106811,2019-06-23,2019-06-29,SUDESTE,ESPIRITO SANTO,GNV,4,R$/m3,3.299,0.005,3.290,...,-,-,-,-,-,6,2019,DEFAULT,106811,19.794
106813,2019-06-23,2019-06-29,SUDESTE,MINAS GERAIS,GNV,6,R$/m3,3.548,0.100,3.495,...,-,-,-,-,-,6,2019,DEFAULT,106813,21.288
106815,2019-06-23,2019-06-29,SUL,PARANA,GNV,1,R$/m3,3.290,0.000,3.290,...,-,-,-,-,-,6,2019,DEFAULT,106815,19.740

Várias amostras possuem a string '-' em algumas colunas ao invés de um número de fato. Ou seja, não há aferições destes atributos para estas amostras.



Poderíamos preencher os valores NaN com um valor padrão. Para isso, basta usar o método .fillna.

In [517]:
data_pre_fill = data_pre.fillna(0)
data_pre_fill

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.190,...,0.825,0.110,0.4201,0.96660,0.133,5,2004,DEFAULT,0,7.728
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.890,...,0.763,0.088,0.5013,1.05000,0.115,5,2004,DEFAULT,1,6.972
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.180,...,0.970,0.095,0.5614,1.16100,0.098,5,2004,DEFAULT,2,8.334
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.090,...,0.830,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,7.572
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.050,...,0.941,0.077,0.7441,1.03170,0.082,5,2004,DEFAULT,4,7.086
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,3.499,...,2.756,0.000,2.7560,2.75600,0.000,6,2019,DEFAULT,106818,21.444
106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,3.230,...,2.451,0.402,1.9842,2.86610,0.164,6,2019,DEFAULT,106819,20.406
106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,2.699,...,1.998,0.000,1.9981,1.99810,0.000,6,2019,DEFAULT,106820,17.472
106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,2.699,...,2.374,0.165,2.0179,2.50930,0.070,6,2019,DEFAULT,106821,18.120
106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,3.689,...,2.518,0.000,2.5175,2.51750,0.000,6,2019,DEFAULT,106822,22.182

In [518]:
data_pre_fill[mask]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
1903,2005-09-25,2005-10-01,NORTE,PARA,ETANOL HIDRATADO,2,R$/l,1.694,0.283,1.690,...,0.0,0.0,0.0,0.0,0.0,9,2005,DEFAULT,1903,10.164
1958,2005-10-09,2005-10-15,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.000,0.000,2.000,...,0.0,0.0,0.0,0.0,0.0,10,2005,DEFAULT,1958,12.000
2012,2005-10-23,2005-10-29,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.277,0.023,2.250,...,0.0,0.0,0.0,0.0,0.0,10,2005,DEFAULT,2012,13.662
2497,2006-02-26,2006-03-04,NORTE,RORAIMA,ETANOL HIDRATADO,11,R$/l,2.182,0.040,2.100,...,0.0,0.0,0.0,0.0,0.0,2,2006,DEFAULT,2497,13.092
3199,2006-08-27,2006-09-02,NORTE,RORAIMA,ETANOL HIDRATADO,22,R$/l,2.285,0.068,1.980,...,0.0,0.0,0.0,0.0,0.0,8,2006,DEFAULT,3199,13.710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106664,2019-06-16,2019-06-22,SUDESTE,MINAS GERAIS,GNV,5,R$/m3,3.445,0.147,3.347,...,0.0,0.0,0.0,0.0,0.0,6,2019,DEFAULT,106664,20.670
106666,2019-06-16,2019-06-22,SUL,PARANA,GNV,7,R$/m3,3.132,0.295,3.049,...,0.0,0.0,0.0,0.0,0.0,6,2019,DEFAULT,106666,18.792
106811,2019-06-23,2019-06-29,SUDESTE,ESPIRITO SANTO,GNV,4,R$/m3,3.299,0.005,3.290,...,0.0,0.0,0.0,0.0,0.0,6,2019,DEFAULT,106811,19.794
106813,2019-06-23,2019-06-29,SUDESTE,MINAS GERAIS,GNV,6,R$/m3,3.548,0.100,3.495,...,0.0,0.0,0.0,0.0,0.0,6,2019,DEFAULT,106813,21.288
106815,2019-06-23,2019-06-29,SUL,PARANA,GNV,1,R$/m3,3.290,0.000,3.290,...,0.0,0.0,0.0,0.0,0.0,6,2019,DEFAULT,106815,19.740

In [519]:
data_pre_fill = data_pre.fillna(value={
    'PREÇO MÉDIO DISTRIBUIÇÃO': 10,
    'DESVIO PADRÃO DISTRIBUIÇÃO':20,
    'PREÇO MÍNIMO DISTRIBUIÇÃO': 30,
    'PREÇO MÁXIMO DISTRIBUIÇÃO': 'vazio'
})

In [520]:
data_pre_fill[mask]

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
1903,2005-09-25,2005-10-01,NORTE,PARA,ETANOL HIDRATADO,2,R$/l,1.694,0.283,1.690,...,10.0,20.0,30.0,vazio,NaN,9,2005,DEFAULT,1903,10.164
1958,2005-10-09,2005-10-15,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.000,0.000,2.000,...,10.0,20.0,30.0,vazio,NaN,10,2005,DEFAULT,1958,12.000
2012,2005-10-23,2005-10-29,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.277,0.023,2.250,...,10.0,20.0,30.0,vazio,NaN,10,2005,DEFAULT,2012,13.662
2497,2006-02-26,2006-03-04,NORTE,RORAIMA,ETANOL HIDRATADO,11,R$/l,2.182,0.040,2.100,...,10.0,20.0,30.0,vazio,NaN,2,2006,DEFAULT,2497,13.092
3199,2006-08-27,2006-09-02,NORTE,RORAIMA,ETANOL HIDRATADO,22,R$/l,2.285,0.068,1.980,...,10.0,20.0,30.0,vazio,NaN,8,2006,DEFAULT,3199,13.710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106664,2019-06-16,2019-06-22,SUDESTE,MINAS GERAIS,GNV,5,R$/m3,3.445,0.147,3.347,...,10.0,20.0,30.0,vazio,NaN,6,2019,DEFAULT,106664,20.670
106666,2019-06-16,2019-06-22,SUL,PARANA,GNV,7,R$/m3,3.132,0.295,3.049,...,10.0,20.0,30.0,vazio,NaN,6,2019,DEFAULT,106666,18.792
106811,2019-06-23,2019-06-29,SUDESTE,ESPIRITO SANTO,GNV,4,R$/m3,3.299,0.005,3.290,...,10.0,20.0,30.0,vazio,NaN,6,2019,DEFAULT,106811,19.794
106813,2019-06-23,2019-06-29,SUDESTE,MINAS GERAIS,GNV,6,R$/m3,3.548,0.100,3.495,...,10.0,20.0,30.0,vazio,NaN,6,2019,DEFAULT,106813,21.288
106815,2019-06-23,2019-06-29,SUL,PARANA,GNV,1,R$/m3,3.290,0.000,3.290,...,10.0,20.0,30.0,vazio,NaN,6,2019,DEFAULT,106815,19.740

Por mais que a função fillna seja interessante e útil em muitos casos, no problema em questão estamos interessados em analisar precisamente, p. ex., o 'PREÇO MÉDIO DISTRIBUIÇÃO'.
A fim de não termos valores sintéticos gerados pelo fillna, que possam atrapalhar nossa análise, iremos remover (drop) todas as amostras que possuem qualquer valor NaN para quaisquer atributos/colunas.

Para isso, basta utilizarmos o método dropna.

In [521]:
data_pre.dropna(inplace=True)

In [522]:
data_pre.info()

<class 'pandas.core.frame.DataFrame'>
Index: 103392 entries, 0 to 106822
Data columns (total 23 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   DATA INICIAL                      103392 non-null  datetime64[ns]
 1   DATA FINAL                        103392 non-null  datetime64[ns]
 2   REGIÃO                            103392 non-null  object
 3   ESTADO                            103392 non-null  object
 4   PRODUTO                           103392 non-null  object
 5   NÚMERO DE POSTOS PESQUISADOS      103392 non-null  int64
 6   UNIDADE DE MEDIDA                 103392 non-null  object
 7   PREÇO MÉDIO REVENDA               103392 non-null  float64
 8   DESVIO PADRÃO REVENDA             103392 non-null  float64
 9   PREÇO MÍNIMO REVENDA              103392 non-null  float64
 10  PREÇO MÁXIMO REVENDA              103392 non-null  float64
 11  MARGEM MÉDIA REVENDA              103392 non-null  float64
 12  COEF DE VARIAÇÃO REVENDA          103392 non-null  float64
 13  PREÇO MÉDIO DISTRIBUIÇÃO          103392 non-null  float64
 14  DESVIO PADRÃO DISTRIBUIÇÃO        103392 non-null  float64
 15  PREÇO MÍNIMO DISTRIBUIÇÃO         103392 non-null  float64
 16  PREÇO MÁXIMO DISTRIBUIÇÃO         103392 non-null  float64
 17  COEF DE VARIAÇÃO DISTRIBUIÇÃO     103392 non-null  float64
 18  MÊS                               103392 non-null  int64
 19  ANO                               103392 non-null  int64
 20  coluna sem nocao                  103392 non-null  object
 21  coluna a partir de lista          103392 non-null  int64
 22  PRECO MEDIO DE REVENDA (dolares)  103392 non-null  float64
dtypes: datetime64[ns](2), float64(12), int64(4), object(5)
memory usage: 18.9+ MB

In [523]:
data_pre.to_csv('/content/GasPricesinBrazil_2004-2019_final.csv')

### Estatísticas Descritivas

In [524]:
data_final = pd.read_csv('/content/GasPricesinBrazil_2004-2019_final.csv')

In [525]:
data_final

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.825,0.110,0.4201,0.96660,0.133,5,2004,DEFAULT,0,7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.763,0.088,0.5013,1.05000,0.115,5,2004,DEFAULT,1,6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.970,0.095,0.5614,1.16100,0.098,5,2004,DEFAULT,2,8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.830,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.941,0.077,0.7441,1.03170,0.082,5,2004,DEFAULT,4,7.086
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103387,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,2.756,0.000,2.7560,2.75600,0.000,6,2019,DEFAULT,106818,21.444
103388,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,2.451,0.402,1.9842,2.86610,0.164,6,2019,DEFAULT,106819,20.406
103389,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,1.998,0.000,1.9981,1.99810,0.000,6,2019,DEFAULT,106820,17.472
103390,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,2.374,0.165,2.0179,2.50930,0.070,6,2019,DEFAULT,106821,18.120
103391,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,2.518,0.000,2.5175,2.51750,0.000,6,2019,DEFAULT,106822,22.182

O Pandas fornecem algumas funções/métodos ue computam certas estatísticas descritivas.

describe: exibe várias estatísticas descritivas para os atributos de um dataframe ou para uma Series.

In [526]:
data_final.describe()

,Unnamed: 0,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
count,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000
mean,52973.958682,240.511935,10.784472,0.652589,9.334931,12.458686,2.225151,0.045749,8.559322,0.559441,7.414814,9.805621,0.046640,6.485067,2011.737001,52973.958682,64.706834
std,30968.261500,408.039174,17.685852,1.346422,15.024383,20.801190,4.375085,0.024488,13.603686,1.256914,11.681366,15.933999,0.042114,3.442155,4.410491,30968.261500,106.115110
min,0.000000,1.000000,0.766000,0.000000,0.590000,0.999000,0.001000,0.000000,0.506000,0.000000,0.325700,0.599200,0.000000,1.000000,2004.000000,0.000000,4.596000
25%,25964.750000,47.000000,2.073000,0.073000,1.900000,2.330000,0.282000,0.030000,1.795000,0.047000,1.674400,1.945600,0.021000,4.000000,2008.000000,25964.750000,12.438000
50%,52661.500000,108.000000,2.723000,0.115000,2.509000,3.000000,0.383000,0.042000,2.335000,0.077000,2.220000,2.507050,0.031000,6.000000,2012.000000,52661.500000,16.338000
75%,79918.250000,251.000000,3.745000,0.190000,3.490000,4.150000,0.560000,0.058000,3.307000,0.151000,3.142800,3.520000,0.061000,9.000000,2016.000000,79918.250000,22.470000
max,106822.000000,4167.000000,99.357000,10.748000,90.000000,120.000000,36.847000,0.262000,83.137000,18.385000,83.000000,94.500000,0.780000,12.000000,2019.000000,106822.000000,596.142000

In [528]:
data_final['PREÇO MÉDIO REVENDA'].describe()

count    103392.000000
mean         10.784472
std          17.685852
min           0.766000
25%           2.073000
50%           2.723000
75%           3.745000
max          99.357000
Name: PREÇO MÉDIO REVENDA, dtype: float64

In [527]:
data_final.describe()['PREÇO MÉDIO REVENDA']

count    103392.000000
mean         10.784472
std          17.685852
min           0.766000
25%           2.073000
50%           2.723000
75%           3.745000
max          99.357000
Name: PREÇO MÉDIO REVENDA, dtype: float64

In [529]:
stats = data_final.describe()
stats

,Unnamed: 0,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
count,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000
mean,52973.958682,240.511935,10.784472,0.652589,9.334931,12.458686,2.225151,0.045749,8.559322,0.559441,7.414814,9.805621,0.046640,6.485067,2011.737001,52973.958682,64.706834
std,30968.261500,408.039174,17.685852,1.346422,15.024383,20.801190,4.375085,0.024488,13.603686,1.256914,11.681366,15.933999,0.042114,3.442155,4.410491,30968.261500,106.115110
min,0.000000,1.000000,0.766000,0.000000,0.590000,0.999000,0.001000,0.000000,0.506000,0.000000,0.325700,0.599200,0.000000,1.000000,2004.000000,0.000000,4.596000
25%,25964.750000,47.000000,2.073000,0.073000,1.900000,2.330000,0.282000,0.030000,1.795000,0.047000,1.674400,1.945600,0.021000,4.000000,2008.000000,25964.750000,12.438000
50%,52661.500000,108.000000,2.723000,0.115000,2.509000,3.000000,0.383000,0.042000,2.335000,0.077000,2.220000,2.507050,0.031000,6.000000,2012.000000,52661.500000,16.338000
75%,79918.250000,251.000000,3.745000,0.190000,3.490000,4.150000,0.560000,0.058000,3.307000,0.151000,3.142800,3.520000,0.061000,9.000000,2016.000000,79918.250000,22.470000
max,106822.000000,4167.000000,99.357000,10.748000,90.000000,120.000000,36.847000,0.262000,83.137000,18.385000,83.000000,94.500000,0.780000,12.000000,2019.000000,106822.000000,596.142000

In [533]:
stats[['PREÇO MÉDIO REVENDA','DESVIO PADRÃO REVENDA', 'PREÇO MÍNIMO REVENDA']]

       PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA
count        103392.000000          103392.000000         103392.000000
mean             10.784472               0.652589              9.334931
std              17.685852               1.346422             15.024383
min               0.766000               0.000000              0.590000
25%               2.073000               0.073000              1.900000
50%               2.723000               0.115000              2.509000
75%               3.745000               0.190000              3.490000
max              99.357000              10.748000             90.000000

In [534]:
data_final[['PREÇO MÉDIO REVENDA','DESVIO PADRÃO REVENDA', 'PREÇO MÍNIMO REVENDA']].describe()

       PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  PREÇO MÍNIMO REVENDA
count        103392.000000          103392.000000         103392.000000
mean             10.784472               0.652589              9.334931
std              17.685852               1.346422             15.024383
min               0.766000               0.000000              0.590000
25%               2.073000               0.073000              1.900000
50%               2.723000               0.115000              2.509000
75%               3.745000               0.190000              3.490000
max              99.357000              10.748000             90.000000

In [535]:
stats

,Unnamed: 0,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
count,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000,103392.000000
mean,52973.958682,240.511935,10.784472,0.652589,9.334931,12.458686,2.225151,0.045749,8.559322,0.559441,7.414814,9.805621,0.046640,6.485067,2011.737001,52973.958682,64.706834
std,30968.261500,408.039174,17.685852,1.346422,15.024383,20.801190,4.375085,0.024488,13.603686,1.256914,11.681366,15.933999,0.042114,3.442155,4.410491,30968.261500,106.115110
min,0.000000,1.000000,0.766000,0.000000,0.590000,0.999000,0.001000,0.000000,0.506000,0.000000,0.325700,0.599200,0.000000,1.000000,2004.000000,0.000000,4.596000
25%,25964.750000,47.000000,2.073000,0.073000,1.900000,2.330000,0.282000,0.030000,1.795000,0.047000,1.674400,1.945600,0.021000,4.000000,2008.000000,25964.750000,12.438000
50%,52661.500000,108.000000,2.723000,0.115000,2.509000,3.000000,0.383000,0.042000,2.335000,0.077000,2.220000,2.507050,0.031000,6.000000,2012.000000,52661.500000,16.338000
75%,79918.250000,251.000000,3.745000,0.190000,3.490000,4.150000,0.560000,0.058000,3.307000,0.151000,3.142800,3.520000,0.061000,9.000000,2016.000000,79918.250000,22.470000
max,106822.000000,4167.000000,99.357000,10.748000,90.000000,120.000000,36.847000,0.262000,83.137000,18.385000,83.000000,94.500000,0.780000,12.000000,2019.000000,106822.000000,596.142000

In [536]:
stats.loc[['min','max','mean']]

,Unnamed: 0,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
min,0.000000,1.000000,0.766000,0.000000,0.590000,0.999000,0.001000,0.000000,0.506000,0.000000,0.325700,0.599200,0.00000,1.000000,2004.000000,0.000000,4.596000
max,106822.000000,4167.000000,99.357000,10.748000,90.000000,120.000000,36.847000,0.262000,83.137000,18.385000,83.000000,94.500000,0.78000,12.000000,2019.000000,106822.000000,596.142000
mean,52973.958682,240.511935,10.784472,0.652589,9.334931,12.458686,2.225151,0.045749,8.559322,0.559441,7.414814,9.805621,0.04664,6.485067,2011.737001,52973.958682,64.706834

mean, std, min, etc: cada uma das estatísticas do describe podem ser computadas individualmente:

In [537]:
data_final['PREÇO MÍNIMO REVENDA'].min()

0.59

In [541]:
mean = data_final['PREÇO MÍNIMO REVENDA'].mean()
std = data_final['PREÇO MÍNIMO DISTRIBUIÇÃO'].std()
print(f'A média dos preços mínimos de revenda é {mean:.2f} +- {std:.2f}')

A média dos preços mínimos de revenda é 9.33 +- 11.68

In [542]:
data_final['ESTADO']

0            DISTRITO FEDERAL
1                       GOIAS
2                 MATO GROSSO
3          MATO GROSSO DO SUL
4                     ALAGOAS
                 ...
103387    RIO GRANDE DO NORTE
103388      RIO GRANDE DO SUL
103389         SANTA CATARINA
103390              SAO PAULO
103391                SERGIPE
Name: ESTADO, Length: 103392, dtype: object

In [543]:
sorted(data_final['ESTADO'].unique())

['ACRE',
 'ALAGOAS',
 'AMAPA',
 'AMAZONAS',
 'BAHIA',
 'CEARA',
 'DISTRITO FEDERAL',
 'ESPIRITO SANTO',
 'GOIAS',
 'MARANHAO',
 'MATO GROSSO',
 'MATO GROSSO DO SUL',
 'MINAS GERAIS',
 'PARA',
 'PARAIBA',
 'PARANA',
 'PERNAMBUCO',
 'PIAUI',
 'RIO DE JANEIRO',
 'RIO GRANDE DO NORTE',
 'RIO GRANDE DO SUL',
 'RONDONIA',
 'RORAIMA',
 'SANTA CATARINA',
 'SAO PAULO',
 'SERGIPE',
 'TOCANTINS']

In [544]:
data_final['ESTADO'].value_counts()

ESTADO
BAHIA                  4263
RIO DE JANEIRO         4262
SAO PAULO              4261
RIO GRANDE DO SUL      4249
PARAIBA                4240
PERNAMBUCO             4236
SERGIPE                4202
SANTA CATARINA         4164
MINAS GERAIS           4142
ESPIRITO SANTO         4079
MATO GROSSO DO SUL     4076
ALAGOAS                4020
RIO GRANDE DO NORTE    3999
CEARA                  3964
PARANA                 3902
AMAZONAS               3713
MATO GROSSO            3703
PARA                   3477
MARANHAO               3470
ACRE                   3463
RORAIMA                3457
TOCANTINS              3453
GOIAS                  3449
RONDONIA               3441
PIAUI                  3394
DISTRITO FEDERAL       3317
AMAPA                  2996
Name: count, dtype: int64

In [545]:
data_final['ESTADO'].value_counts().to_frame()

                     count
ESTADO
BAHIA                 4263
RIO DE JANEIRO        4262
SAO PAULO             4261
RIO GRANDE DO SUL     4249
PARAIBA               4240
PERNAMBUCO            4236
SERGIPE               4202
SANTA CATARINA        4164
MINAS GERAIS          4142
ESPIRITO SANTO        4079
MATO GROSSO DO SUL    4076
ALAGOAS               4020
RIO GRANDE DO NORTE   3999
CEARA                 3964
PARANA                3902
AMAZONAS              3713
MATO GROSSO           3703
PARA                  3477
MARANHAO              3470
ACRE                  3463
RORAIMA               3457
TOCANTINS             3453
GOIAS                 3449
RONDONIA              3441
PIAUI                 3394
DISTRITO FEDERAL      3317
AMAPA                 2996

## 4. Executando funções para cada item de um DataFrame ou Series
Uma alternativa ao for-loop que vimos anteriormente e que é lento, é usarmos funções próprias do pandas que aplicam/mapeiam uma dada função a todos os elementos de um DataFrame ou Series, retornando novos elementos "transformados".

In [546]:
df = pd.DataFrame({ 'A': [1, 2, 3, 4],
                    'B': [10, 20, 30, 40],
                    'C': [100, 200, 300, 400]},
                     index=['Linha 1', 'Linha 2', 'Linha 3', 'Linha 4'])

In [547]:
df

         A   B    C
Linha 1  1  10  100
Linha 2  2  20  200
Linha 3  3  30  300
Linha 4  4  40  400

In [548]:
def nossa_soma(linha):
  return linha.sum()

In [550]:
df['SOMA(A,B,C)'] = df.apply(nossa_soma,axis=1)
df

         A   B    C  SOMA(A,B,C)
Linha 1  1  10  100          111
Linha 2  2  20  200          222
Linha 3  3  30  300          333
Linha 4  4  40  400          444

In [552]:
df.loc['LINHA 5'] = df.apply(nossa_soma, axis=0)
df

          A    B     C  SOMA(A,B,C)
Linha 1   1   10   100          111
Linha 2   2   20   200          222
Linha 3   3   30   300          333
Linha 4   4   40   400          444
LINHA 5  20  200  2000         2220

In [556]:
df['MEDIA(A,B,C)'] = df[['A','B','C']].apply(lambda nossa_soma: nossa_soma.mean(), axis=1)
df

          A    B     C  SOMA(A,B,C)  MEDIA(A,B,C)
Linha 1   1   10   100          111          37.0
Linha 2   2   20   200          222          74.0
Linha 3   3   30   300          333         111.0
Linha 4   4   40   400          444         148.0
LINHA 5  20  200  2000         2220         740.0

In [558]:
df['C * 2'] = df['C'].apply(lambda x : x *2 )
df

          A    B     C  SOMA(A,B,C)  MEDIA(A,B,C)  C * 2
Linha 1   1   10   100          111          37.0    200
Linha 2   2   20   200          222          74.0    400
Linha 3   3   30   300          333         111.0    600
Linha 4   4   40   400          444         148.0    800
LINHA 5  20  200  2000         2220         740.0   4000

applymap(): usado para aplicar uma função para cada elemento (element-wise) de um DataFrame.

In [559]:
df = pd.DataFrame({ 'A': [1, 2, 3, 4],
                    'B': [10, 20, 30, 40],
                    'C': [100, 200, 300, 400]},
                     index=['Linha 1', 'Linha 2', 'Linha 3', 'Linha 4'])
df

         A   B    C
Linha 1  1  10  100
Linha 2  2  20  200
Linha 3  3  30  300
Linha 4  4  40  400

In [560]:
df.applymap(lambda x: x **2)

/tmp/ipython-input-1081273538.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x **2)

          A     B       C
Linha 1   1   100   10000
Linha 2   4   400   40000
Linha 3   9   900   90000
Linha 4  16  1600  160000

map(): usado para aplicar uma função para cada elemento (element-wise) de uma Series.

In [562]:
nomes = pd.Series(['Joao', 'Maria', 'Alice'])

In [563]:
nomes.map(lambda x : x.upper())

0     JOAO
1    MARIA
2    ALICE
dtype: object

In [564]:
nomes.str.upper()

0     JOAO
1    MARIA
2    ALICE
dtype: object

## 5. Agrupamento
groupby: Usado para criar grupo de elementos (e.x., baseado nos valores de um atributo).
Funções podem então ser aplicadas para os elementos de cada grupo, de modo que os resultados de cada grupo são combinados.

In [565]:
data_final.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.825,0.110,0.4201,0.96660,0.133,5,2004,DEFAULT,0,7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.763,0.088,0.5013,1.05000,0.115,5,2004,DEFAULT,1,6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.970,0.095,0.5614,1.16100,0.098,5,2004,DEFAULT,2,8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.830,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.941,0.077,0.7441,1.03170,0.082,5,2004,DEFAULT,4,7.086

In [567]:
 grupos = data_final.groupby('REGIÃO')
 grupos

In [568]:
grupos.groups

{'CENTRO OESTE': [0, 1, 2, 3, 27, 28, 29, 30, 54, 55, 56, 57, 81, 82, 83, 84, 108, 109, 110, 111, 135, 136, 137, 138, 162, 163, 164, 165, 189, 190, 191, 192, 216, 217, 218, 219, 243, 244, 245, 246, 270, 271, 272, 273, 297, 298, 299, 300, 324, 325, 326, 327, 351, 352, 353, 354, 378, 379, 380, 381, 405, 406, 407, 408, 432, 433, 434, 435, 459, 460, 461, 462, 486, 487, 488, 489, 513, 514, 515, 516, 540, 541, 542, 543, 567, 568, 569, 570, 594, 595, 596, 597, 621, 622, 623, 624, 648, 649, 650, 651, ...], 'NORDESTE': [4, 5, 6, 7, 8, 9, 10, 11, 12, 31, 32, 33, 34, 35, 36, 37, 38, 39, 58, 59, 60, 61, 62, 63, 64, 65, 66, 85, 86, 87, 88, 89, 90, 91, 92, 93, 112, 113, 114, 115, 116, 117, 118, 119, 120, 139, 140, 141, 142, 143, 144, 145, 146, 147, 166, 167, 168, 169, 170, 171, 172, 173, 174, 193, 194, 195, 196, 197, 198, 199, 200, 201, 220, 221, 222, 223, 224, 225, 226, 227, 228, 247, 248, 249, 250, 251, 252, 253, 254, 255, 274, 275, 276, 277, 278, 279, 280, 281, 282, 301, ...], 'NORTE': [13, 14, 15, 16, 17, 18, 19, 40, 41, 42, 43, 44, 45, 46, 67, 68, 69, 70, 71, 72, 73, 94, 95, 96, 97, 98, 99, 100, 121, 122, 123, 124, 125, 126, 127, 148, 149, 150, 151, 152, 153, 154, 175, 176, 177, 178, 179, 180, 181, 202, 203, 204, 205, 206, 207, 208, 229, 230, 231, 232, 233, 234, 235, 256, 257, 258, 259, 260, 261, 262, 283, 284, 285, 286, 287, 288, 289, 310, 311, 312, 313, 314, 315, 316, 337, 338, 339, 340, 341, 342, 343, 364, 365, 366, 367, 368, 369, 370, 391, 392, ...], 'SUDESTE': [20, 21, 22, 23, 47, 48, 49, 50, 74, 75, 76, 77, 101, 102, 103, 104, 128, 129, 130, 131, 155, 156, 157, 158, 182, 183, 184, 185, 209, 210, 211, 212, 236, 237, 238, 239, 263, 264, 265, 266, 290, 291, 292, 293, 317, 318, 319, 320, 344, 345, 346, 347, 371, 372, 373, 374, 398, 399, 400, 401, 425, 426, 427, 428, 452, 453, 454, 455, 479, 480, 481, 482, 506, 507, 508, 509, 533, 534, 535, 536, 560, 561, 562, 563, 587, 588, 589, 590, 614, 615, 616, 617, 641, 642, 643, 644, 668, 669, 670, 671, ...], 'SUL': [24, 25, 26, 51, 52, 53, 78, 79, 80, 105, 106, 107, 132, 133, 134, 159, 160, 161, 186, 187, 188, 213, 214, 215, 240, 241, 242, 267, 268, 269, 294, 295, 296, 321, 322, 323, 348, 349, 350, 375, 376, 377, 402, 403, 404, 429, 430, 431, 456, 457, 458, 483, 484, 485, 510, 511, 512, 537, 538, 539, 564, 565, 566, 591, 592, 593, 618, 619, 620, 645, 646, 647, 672, 673, 674, 699, 700, 701, 726, 727, 728, 753, 754, 755, 780, 781, 782, 807, 808, 809, 834, 835, 836, 861, 862, 863, 888, 889, 890, 915, ...]}

In [569]:
grupos.indices

{'CENTRO OESTE': array([     0,      1,      2, ..., 103363, 103364, 103383]),
 'NORDESTE': array([     4,      5,      6, ..., 103385, 103387, 103391]),
 'NORTE': array([    13,     14,     15, ..., 103374, 103375, 103379]),
 'SUDESTE': array([    20,     21,     22, ..., 103377, 103386, 103390]),
 'SUL': array([    24,     25,     26, ..., 103376, 103388, 103389])}

In [571]:
grupos.describe()

             Unnamed: 0                                                       \
                  count          mean           std   min       25%      50%
REGIÃO
CENTRO OESTE    14545.0  52794.848127  31380.202472   0.0  24647.00  53023.0
NORDESTE        35788.0  53022.749022  30768.203891   4.0  26854.25  51922.5
NORTE           24000.0  52735.865958  31714.571691  13.0  23526.75  54011.5
SUDESTE         16744.0  53281.350334  30332.349374  20.0  28253.75  52127.5
SUL             12315.0  53089.777913  30437.425938  24.0  27716.50  51968.0

                                NÚMERO DE POSTOS PESQUISADOS              ...  \
                  75%       max                        count        mean  ...
REGIÃO                                                                    ...
CENTRO OESTE  80299.0  106812.0                      14545.0  144.898453  ...
NORDESTE      79910.5  106822.0                      35788.0  124.721834  ...
NORTE         80343.5  106807.0                      24000.0   67.835958  ...
SUDESTE       79401.5  106821.0                      16744.0  726.068024  ...
SUL           79332.5  106820.0                      12315.0  366.266423  ...

             coluna a partir de lista            \
                                  75%       max
REGIÃO
CENTRO OESTE                  80299.0  106812.0
NORDESTE                      79910.5  106822.0
NORTE                         80343.5  106807.0
SUDESTE                       79401.5  106821.0
SUL                           79332.5  106820.0

             PRECO MEDIO DE REVENDA (dolares)                                \
                                        count       mean         std    min
REGIÃO
CENTRO OESTE                          14545.0  73.798239  119.704635  6.582
NORDESTE                              35788.0  57.352477   95.933090  5.850
NORTE                                 24000.0  75.798516  117.827109  7.356
SUDESTE                               16744.0  58.969309   97.709682  4.596
SUL                                   12315.0  61.526326  101.423263  5.532


                 25%     50%     75%      max
REGIÃO
CENTRO OESTE  12.684  16.866  23.166  596.142
NORDESTE      11.886  15.744  21.480  477.780
NORTE         14.292  17.982  25.386  523.620
SUDESTE       11.262  15.321  21.435  475.152
SUL           11.940  15.582  21.318  432.528

[5 rows x 136 columns]

In [573]:
grupos.min()

,Unnamed: 0,DATA INICIAL,DATA FINAL,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
REGIÃO,,,,,,,,,,,,,,,,,,,,,
CENTRO OESTE,0,2004-05-09,2004-05-15,DISTRITO FEDERAL,ETANOL HIDRATADO,1,R$/13Kg,1.097,0.0,0.87,...,0.737,0.0,0.38790,0.8359,0.0,1,2004,DEFAULT,0,6.582
NORDESTE,4,2004-05-09,2004-05-15,ALAGOAS,ETANOL HIDRATADO,1,R$/13Kg,0.975,0.0,0.79,...,0.586,0.0,0.36320,0.5992,0.0,1,2004,DEFAULT,4,5.850
NORTE,13,2004-05-09,2004-05-15,ACRE,ETANOL HIDRATADO,1,R$/13Kg,1.226,0.0,1.05,...,0.674,0.0,0.51022,0.9612,0.0,1,2004,DEFAULT,13,7.356
SUDESTE,20,2004-05-09,2004-05-15,ESPIRITO SANTO,ETANOL HIDRATADO,1,R$/13Kg,0.766,0.0,0.59,...,0.506,0.0,0.32570,0.7822,0.0,1,2004,DEFAULT,20,4.596
SUL,24,2004-05-09,2004-05-15,PARANA,ETANOL HIDRATADO,1,R$/13Kg,0.922,0.0,0.73,...,0.667,0.0,0.43000,0.7044,0.0,1,2004,DEFAULT,24,5.532

In [574]:
grupos.max()

,Unnamed: 0,DATA INICIAL,DATA FINAL,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
REGIÃO,,,,,,,,,,,,,,,,,,,,,
CENTRO OESTE,106812,2019-06-23,2019-06-29,MATO GROSSO DO SUL,ÓLEO DIESEL S10,766,R$/m3,99.357,9.711,90.0,...,83.137,18.385,83.00,94.50,0.419,12,2019,DEFAULT,106812,596.142
NORDESTE,106822,2019-06-23,2019-06-29,SERGIPE,ÓLEO DIESEL S10,625,R$/m3,79.630,10.748,75.0,...,59.411,13.435,55.35,89.90,0.608,12,2019,DEFAULT,106822,477.780
NORTE,106807,2019-06-23,2019-06-29,TOCANTINS,ÓLEO DIESEL S10,383,R$/m3,87.270,10.675,85.0,...,72.428,12.428,72.39,88.00,0.368,12,2019,DEFAULT,106807,523.620
SUDESTE,106821,2019-06-23,2019-06-29,SAO PAULO,ÓLEO DIESEL S10,4167,R$/m3,79.192,9.632,60.0,...,53.944,7.165,46.93,76.05,0.780,12,2019,DEFAULT,106821,475.152
SUL,106820,2019-06-23,2019-06-29,SANTA CATARINA,ÓLEO DIESEL S10,1416,R$/m3,72.088,10.270,65.0,...,54.802,8.716,47.38,74.00,0.435,12,2019,DEFAULT,106820,432.528

In [575]:
data_final.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.825,0.110,0.4201,0.96660,0.133,5,2004,DEFAULT,0,7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.763,0.088,0.5013,1.05000,0.115,5,2004,DEFAULT,1,6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.970,0.095,0.5614,1.16100,0.098,5,2004,DEFAULT,2,8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.830,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.941,0.077,0.7441,1.03170,0.082,5,2004,DEFAULT,4,7.086

In [580]:
grupos = data_final.groupby(['REGIÃO','PRODUTO'])
grupos

In [581]:
grupos.groups

{('CENTRO OESTE', 'ETANOL HIDRATADO'): [0, 1, 2, 3, 27, 28, 29, 30, 54, 55, 56, 57, 81, 82, 83, 84, 108, 109, 110, 111, 135, 136, 137, 138, 162, 163, 164, 165, 189, 190, 191, 192, 216, 217, 218, 219, 243, 244, 245, 246, 270, 271, 272, 273, 297, 298, 299, 300, 324, 325, 326, 327, 351, 352, 353, 354, 378, 379, 380, 381, 405, 406, 407, 408, 432, 433, 434, 435, 459, 460, 461, 462, 486, 487, 488, 489, 513, 514, 515, 516, 540, 541, 542, 543, 567, 568, 569, 570, 594, 595, 596, 597, 621, 622, 623, 624, 648, 649, 650, 651, ...], ('CENTRO OESTE', 'GASOLINA COMUM'): [11980, 11981, 11982, 11983, 12007, 12008, 12009, 12010, 12034, 12035, 12036, 12037, 12061, 12062, 12063, 12064, 12088, 12089, 12090, 12091, 12115, 12116, 12117, 12118, 12142, 12143, 12144, 12145, 12169, 12170, 12171, 12172, 12196, 12197, 12198, 12199, 12223, 12224, 12225, 12226, 12250, 12251, 12252, 12253, 12277, 12278, 12279, 12280, 12304, 12305, 12306, 12307, 12331, 12332, 12333, 12334, 12358, 12359, 12360, 12361, 12385, 12386, 12387, 12388, 12412, 12413, 12414, 12415, 12439, 12440, 12441, 12442, 12466, 12467, 12468, 12469, 12493, 12494, 12495, 12496, 12520, 12521, 12522, 12523, 12547, 12548, 12549, 12550, 12574, 12575, 12576, 12577, 12601, 12602, 12603, 12604, 12628, 12629, 12630, 12631, ...], ('CENTRO OESTE', 'GLP'): [24019, 24020, 24021, 24022, 24046, 24047, 24048, 24049, 24073, 24074, 24075, 24076, 24100, 24101, 24102, 24103, 24127, 24128, 24129, 24130, 24154, 24155, 24156, 24157, 24181, 24182, 24183, 24184, 24208, 24209, 24210, 24211, 24235, 24236, 24237, 24238, 24262, 24263, 24264, 24265, 24289, 24290, 24291, 24292, 24316, 24317, 24318, 24319, 24343, 24344, 24345, 24346, 24370, 24371, 24372, 24373, 24397, 24398, 24399, 24400, 24424, 24425, 24426, 24427, 24451, 24452, 24453, 24454, 24478, 24479, 24480, 24481, 24505, 24506, 24507, 24508, 24532, 24533, 24534, 24535, 24558, 24559, 24560, 24561, 24585, 24586, 24587, 24588, 24612, 24613, 24614, 24615, 24639, 24640, 24641, 24642, 24666, 24667, 24668, 24669, ...], ('CENTRO OESTE', 'GNV'): [35892, 35907, 35922, 35937, 35952, 35967, 35982, 35997, 36012, 36027, 36042, 36057, 36072, 36087, 36102, 36117, 36132, 36147, 36162, 36177, 36192, 36207, 36222, 36237, 36252, 36267, 36283, 36298, 36313, 36329, 36345, 36360, 36375, 36390, 36405, 36420, 36436, 36451, 36466, 36481, 36495, 36510, 36525, 36541, 36557, 36572, 36588, 36604, 36620, 36635, 36650, 36665, 36680, 36695, 36710, 36725, 36740, 36755, 36770, 36785, 36800, 36815, 36830, 36845, 36860, 36875, 36890, 36918, 36932, 36948, 36962, 36991, 37006, 37021, 37037, 37053, 37068, 37084, 37100, 37116, 37132, 37148, 37164, 37180, 37196, 37212, 37228, 37244, 37259, 37275, 37291, 37307, 37323, 37339, 37355, 37371, 37387, 37403, 37419, 37435, ...], ('CENTRO OESTE', 'ÓLEO DIESEL'): [42612, 42613, 42614, 42615, 42639, 42640, 42641, 42642, 42666, 42667, 42668, 42669, 42693, 42694, 42695, 42696, 42720, 42721, 42722, 42723, 42747, 42748, 42749, 42750, 42774, 42775, 42776, 42777, 42801, 42802, 42803, 42804, 42828, 42829, 42830, 42831, 42855, 42856, 42857, 42858, 42882, 42883, 42884, 42885, 42909, 42910, 42911, 42912, 42936, 42937, 42938, 42939, 42963, 42964, 42965, 42966, 42990, 42991, 42992, 42993, 43017, 43018, 43019, 43020, 43044, 43045, 43046, 43047, 43071, 43072, 43073, 43074, 43098, 43099, 43100, 43101, 43125, 43126, 43127, 43128, 43152, 43153, 43154, 43155, 43179, 43180, 43181, 43182, 43206, 43207, 43208, 43209, 43233, 43234, 43235, 43236, 43260, 43261, 43262, 43263, ...], ('CENTRO OESTE', 'ÓLEO DIESEL S10'): [54834, 54835, 54973, 54975, 54976, 55117, 55119, 55120, 55260, 55262, 55264, 55265, 55405, 55407, 55408, 55549, 55551, 55552, 55692, 55694, 55695, 55835, 55837, 55838, 55981, 55983, 55984, 56128, 56130, 56131, 56276, 56278, 56279, 56421, 56423, 56424, 56566, 56568, 56569, 56711, 56713, 56714, 56854, 56856, 56858, 56859, 57002, 57004, 57006, 57007, 57148, 57150, 57152, 57153, 57293, 57295, 57297, 57298, 57440, 57442, 57444, 57445, 57586, 57588, 57590, 57591, 57732, 57734, 57736, 57737, 57879, 57881, 57883, 57884, 58027, 58029, 58030, 58174, 58176, 58177, 58317, 58319, 58320, 58461, 58463, 58464, 58607, 58609, 58610, 58750, 58752, 58753, 58894, 58896, 58897, 59040, 59042, 59043, 59184, 59186, ...], ('NORDESTE', 'ETANOL HIDRATADO'): [4, 5, 6, 7, 8, 9, 10, 11, 12, 31, 32, 33, 34, 35, 36, 37, 38, 39, 58, 59, 60, 61, 62, 63, 64, 65, 66, 85, 86, 87, 88, 89, 90, 91, 92, 93, 112, 113, 114, 115, 116, 117, 118, 119, 120, 139, 140, 141, 142, 143, 144, 145, 146, 147, 166, 167, 168, 169, 170, 171, 172, 173, 174, 193, 194, 195, 196, 197, 198, 199, 200, 201, 220, 221, 222, 223, 224, 225, 226, 227, 228, 247, 248, 249, 250, 251, 252, 253, 254, 255, 274, 275, 276, 277, 278, 279, 280, 281, 282, 301, ...], ('NORDESTE', 'GASOLINA COMUM'): [11984, 11985, 11986, 11987, 11988, 11989, 11990, 11991, 11992, 12011, 12012, 12013, 12014, 12015, 12016, 12017, 12018, 12019, 12038, 12039, 12040, 12041, 12042, 12043, 12044, 12045, 12046, 12065, 12066, 12067, 12068, 12069, 12070, 12071, 12072, 12073, 12092, 12093, 12094, 12095, 12096, 12097, 12098, 12099, 12100, 12119, 12120, 12121, 12122, 12123, 12124, 12125, 12126, 12127, 12146, 12147, 12148, 12149, 12150, 12151, 12152, 12153, 12154, 12173, 12174, 12175, 12176, 12177, 12178, 12179, 12180, 12181, 12200, 12201, 12202, 12203, 12204, 12205, 12206, 12207, 12208, 12227, 12228, 12229, 12230, 12231, 12232, 12233, 12234, 12235, 12254, 12255, 12256, 12257, 12258, 12259, 12260, 12261, 12262, 12281, ...], ('NORDESTE', 'GLP'): [24023, 24024, 24025, 24026, 24027, 24028, 24029, 24030, 24031, 24050, 24051, 24052, 24053, 24054, 24055, 24056, 24057, 24058, 24077, 24078, 24079, 24080, 24081, 24082, 24083, 24084, 24085, 24104, 24105, 24106, 24107, 24108, 24109, 24110, 24111, 24112, 24131, 24132, 24133, 24134, 24135, 24136, 24137, 24138, 24139, 24158, 24159, 24160, 24161, 24162, 24163, 24164, 24165, 24166, 24185, 24186, 24187, 24188, 24189, 24190, 24191, 24192, 24193, 24212, 24213, 24214, 24215, 24216, 24217, 24218, 24219, 24220, 24239, 24240, 24241, 24242, 24243, 24244, 24245, 24246, 24247, 24266, 24267, 24268, 24269, 24270, 24271, 24272, 24273, 24274, 24293, 24294, 24295, 24296, 24297, 24298, 24299, 24300, 24301, 24320, ...], ('NORDESTE', 'GNV'): [35893, 35894, 35895, 35896, 35897, 35898, 35899, 35908, 35909, 35910, 35911, 35912, 35913, 35914, 35923, 35924, 35925, 35926, 35927, 35928, 35929, 35938, 35939, 35940, 35941, 35942, 35943, 35944, 35953, 35954, 35955, 35956, 35957, 35958, 35959, 35968, 35969, 35970, 35971, 35972, 35973, 35974, 35983, 35984, 35985, 35986, 35987, 35988, 35989, 35998, 35999, 36000, 36001, 36002, 36003, 36004, 36013, 36014, 36015, 36016, 36017, 36018, 36019, 36028, 36029, 36030, 36031, 36032, 36033, 36034, 36043, 36044, 36045, 36046, 36047, 36048, 36049, 36058, 36059, 36060, 36061, 36062, 36063, 36064, 36073, 36074, 36075, 36076, 36077, 36078, 36079, 36088, 36089, 36090, 36091, 36092, 36093, 36094, 36103, 36104, ...], ('NORDESTE', 'ÓLEO DIESEL'): [42616, 42617, 42618, 42619, 42620, 42621, 42622, 42623, 42624, 42643, 42644, 42645, 42646, 42647, 42648, 42649, 42650, 42651, 42670, 42671, 42672, 42673, 42674, 42675, 42676, 42677, 42678, 42697, 42698, 42699, 42700, 42701, 42702, 42703, 42704, 42705, 42724, 42725, 42726, 42727, 42728, 42729, 42730, 42731, 42732, 42751, 42752, 42753, 42754, 42755, 42756, 42757, 42758, 42759, 42778, 42779, 42780, 42781, 42782, 42783, 42784, 42785, 42786, 42805, 42806, 42807, 42808, 42809, 42810, 42811, 42812, 42813, 42832, 42833, 42834, 42835, 42836, 42837, 42838, 42839, 42840, 42859, 42860, 42861, 42862, 42863, 42864, 42865, 42866, 42867, 42886, 42887, 42888, 42889, 42890, 42891, 42892, 42893, 42894, 42913, ...], ('NORDESTE', 'ÓLEO DIESEL S10'): [54702, 54703, 54706, 54707, 54829, 54831, 54832, 54833, 54839, 54840, 54842, 54847, 54968, 54970, 54971, 54974, 54979, 54981, 54982, 54984, 54989, 55112, 55114, 55115, 55118, 55123, 55125, 55126, 55128, 55133, 55256, 55258, 55259, 55263, 55268, 55270, 55271, 55273, 55278, 55400, 55402, 55403, 55406, 55411, 55413, 55414, 55416, 55421, 55544, 55546, 55547, 55550, 55555, 55557, 55558, 55560, 55565, 55687, 55689, 55690, 55693, 55698, 55700, 55701, 55703, 55708, 55830, 55832, 55833, 55836, 55841, 55843, 55844, 55846, 55852, 55976, 55978, 55979, 55982, 55987, 55989, 55990, 55992, 55998, 56122, 56125, 56126, 56129, 56134, 56136, 56137, 56139, 56145, 56270, 56273, 56274, 56277, 56282, 56284, 56285, ...], ('NORTE', 'ETANOL HIDRATADO'): [13, 14, 15, 16, 17, 18, 19, 40, 41, 42, 43, 44, 45, 46, 67, 68, 69, 70, 71, 72, 73, 94, 95, 96, 97, 98, 99, 100, 121, 122, 123, 124, 125, 126, 127, 148, 149, 150, 151, 152, 153, 154, 175, 176, 177, 178, 179, 180, 181, 202, 203, 204, 205, 206, 207, 208, 229, 230, 231, 232, 233, 234, 235, 256, 257, 258, 259, 260, 261, 262, 283, 284, 285, 286, 287, 288, 289, 310, 311, 312, 313, 314, 315, 316, 337, 338, 339, 340, 341, 342, 343, 364, 365, 366, 367, 368, 369, 370, 391, 392, ...], ('NORTE', 'GASOLINA COMUM'): [11993, 11994, 11995, 11996, 11997, 11998, 11999, 12020, 12021, 12022, 12023, 12024, 12025, 12026, 12047, 12048, 12049, 12050, 12051, 12052, 12053, 12074, 12075, 12076, 12077, 12078, 12079, 12080, 12101, 12102, 12103, 12104, 12105, 12106, 12107, 12128, 12129, 12130, 12131, 12132, 12133, 12134, 12155, 12156, 12157, 12158, 12159, 12160, 12161, 12182, 12183, 12184, 12185, 12186, 12187, 12188, 12209, 12210, 12211, 12212, 12213, 12214, 12215, 12236, 12237, 12238, 12239, 12240, 12241, 12242, 12263, 12264, 12265, 12266, 12267, 12268, 12269, 12290, 12291, 12292, 12293, 12294, 12295, 12296, 12317, 12318, 12319, 12320, 12321, 12322, 12323, 12344, 12345, 12346, 12347, 12348, 12349, 12350, 12371, 12372, ...], ('NORTE', 'GLP'): [24032, 24033, 24034, 24035, 24036, 24037, 24038, 24059, 24060, 24061, 24062, 24063, 24064, 24065, 24086, 24087, 24088, 24089, 24090, 24091, 24092, 24113, 24114, 24115, 24116, 24117, 24118, 24119, 24140, 24141, 24142, 24143, 24144, 24145, 24146, 24167, 24168, 24169, 24170, 24171, 24172, 24173, 24194, 24195, 24196, 24197, 24198, 24199, 24200, 24221, 24222, 24223, 24224, 24225, 24226, 24227, 24248, 24249, 24250, 24251, 24252, 24253, 24254, 24275, 24276, 24277, 24278, 24279, 24280, 24281, 24302, 24303, 24304, 24305, 24306, 24307, 24308, 24329, 24330, 24331, 24332, 24333, 24334, 24335, 24356, 24357, 24358, 24359, 24360, 24361, 24362, 24383, 24384, 24385, 24386, 24387, 24388, 24389, 24410, 24411, ...], ('NORTE', 'GNV'): [36940, 37029, 37045, 37076, 37092, 37108, 37124, 37140, 37156, 37172, 37188, 37204, 37220, 37236, 37267, 37283, 37299, 37315, 37331, 37347, 37363, 37379, 37395, 37411, 37427, 37443, 37459, 37475, 37491, 37507, 37524, 37540, 37556, 37572, 37589, 37606, 37622, 37639, 37655, 37671, 37687, 37704, 37721, 37752, 37768, 37783, 37799, 37816, 37833, 37849, 37865, 37882, 37898, 37914, 37931, 37947, 37963, 37979, 37995, 38011, 38027, 38043, 38059, 38075, 38091, 38122, 38169, 38202, 38218, 38235, 38252, 38269, 38302, 38319, 38336, 38369, 38402, 38434, 38466, 39051, 39082, 39099, 39553, 39628, 39644, 40219, 40574, 40634, 40663, 40694, 41442, 42148, 42235, 42350, 42379, 42394, 42423, 42438, 42466, 42537, ...], ('NORTE', 'ÓLEO DIESEL'): [42625, 42626, 42627, 42628, 42629, 42630, 42631, 42652, 42653, 42654, 42655, 42656, 42657, 42658, 42679, 42680, 42681, 42682, 42683, 42684, 42685, 42706, 42707, 42708, 42709, 42710, 42711, 42712, 42733, 42734, 42735, 42736, 42737, 42738, 42739, 42760, 42761, 42762, 42763, 42764, 42765, 42766, 42787, 42788, 42789, 42790, 42791, 42792, 42793, 42814, 42815, 42816, 42817, 42818, 42819, 42820, 42841, 42842, 42843, 42844, 42845, 42846, 42847, 42868, 42869, 42870, 42871, 42872, 42873, 42874, 42895, 42896, 42897, 42898, 42899, 42900, 42901, 42922, 42923, 42924, 42925, 42926, 42927, 42928, 42949, 42950, 42951, 42952, 42953, 42954, 42955, 42976, 42977, 42978, 42979, 42980, 42981, 42982, 43003, 43004, ...], ('NORTE', 'ÓLEO DIESEL S10'): [54705, 54709, 54830, 54837, 54844, 54969, 54978, 54986, 55111, 55113, 55122, 55130, 55257, 55267, 55275, 55399, 55401, 55410, 55418, 55422, 55543, 55545, 55554, 55562, 55566, 55686, 55688, 55697, 55705, 55709, 55829, 55831, 55840, 55848, 55849, 55853, 55975, 55977, 55986, 55994, 55995, 55999, 56121, 56123, 56124, 56133, 56141, 56142, 56146, 56269, 56271, 56272, 56281, 56289, 56290, 56294, 56414, 56416, 56417, 56426, 56434, 56435, 56439, 56559, 56561, 56562, 56571, 56579, 56580, 56584, 56704, 56706, 56707, 56716, 56724, 56725, 56729, 56848, 56850, 56851, 56861, 56869, 56870, 56874, 56996, 56998, 56999, 57009, 57017, 57018, 57022, 57142, 57144, 57145, 57155, 57163, 57164, 57168, 57287, 57289, ...], ('SUDESTE', 'ETANOL HIDRATADO'): [20, 21, 22, 23, 47, 48, 49, 50, 74, 75, 76, 77, 101, 102, 103, 104, 128, 129, 130, 131, 155, 156, 157, 158, 182, 183, 184, 185, 209, 210, 211, 212, 236, 237, 238, 239, 263, 264, 265, 266, 290, 291, 292, 293, 317, 318, 319, 320, 344, 345, 346, 347, 371, 372, 373, 374, 398, 399, 400, 401, 425, 426, 427, 428, 452, 453, 454, 455, 479, 480, 481, 482, 506, 507, 508, 509, 533, 534, 535, 536, 560, 561, 562, 563, 587, 588, 589, 590, 614, 615, 616, 617, 641, 642, 643, 644, 668, 669, 670, 671, ...], ('SUDESTE', 'GASOLINA COMUM'): [12000, 12001, 12002, 12003, 12027, 12028, 12029, 12030, 12054, 12055, 12056, 12057, 12081, 12082, 12083, 12084, 12108, 12109, 12110, 12111, 12135, 12136, 12137, 12138, 12162, 12163, 12164, 12165, 12189, 12190, 12191, 12192, 12216, 12217, 12218, 12219, 12243, 12244, 12245, 12246, 12270, 12271, 12272, 12273, 12297, 12298, 12299, 12300, 12324, 12325, 12326, 12327, 12351, 12352, 12353, 12354, 12378, 12379, 12380, 12381, 12405, 12406, 12407, 12408, 12432, 12433, 12434, 12435, 12459, 12460, 12461, 12462, 12486, 12487, 12488, 12489, 12513, 12514, 12515, 12516, 12540, 12541, 12542, 12543, 12567, 12568, 12569, 12570, 12594, 12595, 12596, 12597, 12621, 12622, 12623, 12624, 12648, 12649, 12650, 12651, ...], ('SUDESTE', 'GLP'): [24039, 24040, 24041, 24042, 24066, 24067, 24068, 24069, 24093, 24094, 24095, 24096, 24120, 24121, 24122, 24123, 24147, 24148, 24149, 24150, 24174, 24175, 24176, 24177, 24201, 24202, 24203, 24204, 24228, 24229, 24230, 24231, 24255, 24256, 24257, 24258, 24282, 24283, 24284, 24285, 24309, 24310, 24311, 24312, 24336, 24337, 24338, 24339, 24363, 24364, 24365, 24366, 24390, 24391, 24392, 24393, 24417, 24418, 24419, 24420, 24444, 24445, 24446, 24447, 24471, 24472, 24473, 24474, 24498, 24499, 24500, 24501, 24525, 24526, 24527, 24528, 24551, 24552, 24553, 24554, 24578, 24579, 24580, 24581, 24605, 24606, 24607, 24608, 24632, 24633, 24634, 24635, 24659, 24660, 24661, 24662, 24686, 24687, 24688, 24689, ...], ('SUDESTE', 'GNV'): [35900, 35901, 35902, 35903, 35915, 35916, 35917, 35918, 35930, 35931, 35932, 35933, 35945, 35946, 35947, 35948, 35960, 35961, 35962, 35963, 35975, 35976, 35977, 35978, 35990, 35991, 35992, 35993, 36005, 36006, 36007, 36008, 36020, 36021, 36022, 36023, 36035, 36036, 36037, 36038, 36050, 36051, 36052, 36053, 36065, 36066, 36067, 36068, 36080, 36081, 36082, 36083, 36095, 36096, 36097, 36098, 36110, 36111, 36112, 36113, 36125, 36126, 36127, 36128, 36140, 36141, 36142, 36143, 36155, 36156, 36157, 36158, 36170, 36171, 36172, 36173, 36185, 36186, 36187, 36188, 36200, 36201, 36202, 36203, 36215, 36216, 36217, 36218, 36230, 36231, 36232, 36233, 36245, 36246, 36247, 36248, 36260, 36261, 36262, 36263, ...], ('SUDESTE', 'ÓLEO DIESEL'): [42632, 42633, 42634, 42635, 42659, 42660, 42661, 42662, 42686, 42687, 42688, 42689, 42713, 42714, 42715, 42716, 42740, 42741, 42742, 42743, 42767, 42768, 42769, 42770, 42794, 42795, 42796, 42797, 42821, 42822, 42823, 42824, 42848, 42849, 42850, 42851, 42875, 42876, 42877, 42878, 42902, 42903, 42904, 42905, 42929, 42930, 42931, 42932, 42956, 42957, 42958, 42959, 42983, 42984, 42985, 42986, 43010, 43011, 43012, 43013, 43037, 43038, 43039, 43040, 43064, 43065, 43066, 43067, 43091, 43092, 43093, 43094, 43118, 43119, 43120, 43121, 43145, 43146, 43147, 43148, 43172, 43173, 43174, 43175, 43199, 43200, 43201, 43202, 43226, 43227, 43228, 43229, 43253, 43254, 43255, 43256, 43280, 43281, 43282, 43283, ...], ('SUDESTE', 'ÓLEO DIESEL S10'): [54704, 54711, 54836, 54841, 54846, 54972, 54977, 54983, 54988, 55116, 55121, 55127, 55132, 55261, 55266, 55272, 55277, 55404, 55409, 55415, 55420, 55548, 55553, 55559, 55564, 55691, 55696, 55702, 55707, 55834, 55839, 55845, 55851, 55980, 55985, 55991, 55997, 56127, 56132, 56138, 56144, 56275, 56280, 56286, 56292, 56420, 56425, 56431, 56437, 56565, 56570, 56576, 56582, 56710, 56715, 56721, 56727, 56855, 56860, 56866, 56872, 57003, 57008, 57014, 57020, 57149, 57154, 57160, 57166, 57294, 57299, 57305, 57311, 57441, 57446, 57452, 57458, 57587, 57592, 57598, 57604, 57733, 57738, 57744, 57750, 57880, 57885, 57891, 57897, 58026, 58031, 58037, 58043, 58173, 58178, 58184, 58190, 58316, 58321, 58327, ...], ('SUL', 'ETANOL HIDRATADO'): [24, 25, 26, 51, 52, 53, 78, 79, 80, 105, 106, 107, 132, 133, 134, 159, 160, 161, 186, 187, 188, 213, 214, 215, 240, 241, 242, 267, 268, 269, 294, 295, 296, 321, 322, 323, 348, 349, 350, 375, 376, 377, 402, 403, 404, 429, 430, 431, 456, 457, 458, 483, 484, 485, 510, 511, 512, 537, 538, 539, 564, 565, 566, 591, 592, 593, 618, 619, 620, 645, 646, 647, 672, 673, 674, 699, 700, 701, 726, 727, 728, 753, 754, 755, 780, 781, 782, 807, 808, 809, 834, 835, 836, 861, 862, 863, 888, 889, 890, 915, ...], ('SUL', 'GASOLINA COMUM'): [12004, 12005, 12006, 12031, 12032, 12033, 12058, 12059, 12060, 12085, 12086, 12087, 12112, 12113, 12114, 12139, 12140, 12141, 12166, 12167, 12168, 12193, 12194, 12195, 12220, 12221, 12222, 12247, 12248, 12249, 12274, 12275, 12276, 12301, 12302, 12303, 12328, 12329, 12330, 12355, 12356, 12357, 12382, 12383, 12384, 12409, 12410, 12411, 12436, 12437, 12438, 12463, 12464, 12465, 12490, 12491, 12492, 12517, 12518, 12519, 12544, 12545, 12546, 12571, 12572, 12573, 12598, 12599, 12600, 12625, 12626, 12627, 12652, 12653, 12654, 12679, 12680, 12681, 12706, 12707, 12708, 12733, 12734, 12735, 12760, 12761, 12762, 12787, 12788, 12789, 12814, 12815, 12816, 12841, 12842, 12843, 12868, 12869, 12870, 12895, ...], ('SUL', 'GLP'): [24043, 24044, 24045, 24070, 24071, 24072, 24097, 24098, 24099, 24124, 24125, 24126, 24151, 24152, 24153, 24178, 24179, 24180, 24205, 24206, 24207, 24232, 24233, 24234, 24259, 24260, 24261, 24286, 24287, 24288, 24313, 24314, 24315, 24340, 24341, 24342, 24367, 24368, 24369, 24394, 24395, 24396, 24421, 24422, 24423, 24448, 24449, 24450, 24475, 24476, 24477, 24502, 24503, 24504, 24529, 24530, 24531, 24555, 24556, 24557, 24582, 24583, 24584, 24609, 24610, 24611, 24636, 24637, 24638, 24663, 24664, 24665, 24690, 24691, 24692, 24716, 24717, 24718, 24743, 24744, 24745, 24770, 24771, 24772, 24797, 24798, 24799, 24824, 24825, 24826, 24851, 24852, 24853, 24878, 24879, 24880, 24905, 24906, 24907, 24932, ...], ('SUL', 'GNV'): [35904, 35905, 35906, 35919, 35920, 35921, 35934, 35935, 35936, 35949, 35950, 35951, 35964, 35965, 35966, 35979, 35980, 35981, 35994, 35995, 35996, 36009, 36010, 36011, 36024, 36025, 36026, 36039, 36040, 36041, 36054, 36055, 36056, 36069, 36070, 36071, 36084, 36085, 36086, 36099, 36100, 36101, 36114, 36115, 36116, 36129, 36130, 36131, 36144, 36145, 36146, 36159, 36160, 36161, 36174, 36175, 36176, 36189, 36190, 36191, 36204, 36205, 36206, 36219, 36220, 36221, 36234, 36235, 36236, 36249, 36250, 36251, 36264, 36265, 36266, 36280, 36281, 36282, 36295, 36296, 36297, 36310, 36311, 36312, 36326, 36327, 36328, 36342, 36343, 36344, 36357, 36358, 36359, 36372, 36373, 36374, 36387, 36388, 36389, 36402, ...], ('SUL', 'ÓLEO DIESEL'): [42636, 42637, 42638, 42663, 42664, 42665, 42690, 42691, 42692, 42717, 42718, 42719, 42744, 42745, 42746, 42771, 42772, 42773, 42798, 42799, 42800, 42825, 42826, 42827, 42852, 42853, 42854, 42879, 42880, 42881, 42906, 42907, 42908, 42933, 42934, 42935, 42960, 42961, 42962, 42987, 42988, 42989, 43014, 43015, 43016, 43041, 43042, 43043, 43068, 43069, 43070, 43095, 43096, 43097, 43122, 43123, 43124, 43149, 43150, 43151, 43176, 43177, 43178, 43203, 43204, 43205, 43230, 43231, 43232, 43257, 43258, 43259, 43284, 43285, 43

In [584]:
grupos['PREÇO MÉDIO REVENDA'].mean()

REGIÃO        PRODUTO
CENTRO OESTE  ETANOL HIDRATADO     2.135670
              GASOLINA COMUM       3.077476
              GLP                 48.176747
              GNV                  1.856312
              ÓLEO DIESEL          2.481286
              ÓLEO DIESEL S10      3.294752
NORDESTE      ETANOL HIDRATADO     2.320266
              GASOLINA COMUM       3.001887
              GLP                 41.966090
              GNV                  1.881722
              ÓLEO DIESEL          2.346950
              ÓLEO DIESEL S10      3.041966
NORTE         ETANOL HIDRATADO     2.511624
              GASOLINA COMUM       3.149501
              GLP                 47.065572
              GNV                  2.084399
              ÓLEO DIESEL          2.571048
              ÓLEO DIESEL S10      3.316231
SUDESTE       ETANOL HIDRATADO     2.163621
              GASOLINA COMUM       3.000565
              GLP                 42.081544
              GNV                  1.716074
              ÓLEO DIESEL          2.339699
              ÓLEO DIESEL S10      3.056194
SUL           ETANOL HIDRATADO     2.268156
              GASOLINA COMUM       2.972569
              GLP                 43.490318
              GNV                  1.865612
              ÓLEO DIESEL          2.332293
              ÓLEO DIESEL S10      2.981775
Name: PREÇO MÉDIO REVENDA, dtype: float64

In [585]:
grupos['PREÇO MÉDIO REVENDA'].describe()

                                count       mean        std     min       25%  \
REGIÃO       PRODUTO
CENTRO OESTE ETANOL HIDRATADO  3122.0   2.135670   0.561465   1.162   1.71400
             GASOLINA COMUM    3134.0   3.077476   0.615290   1.936   2.66725
             GLP               3098.0  48.176747  15.204045  28.791  37.33300
             GNV                847.0   1.856312   0.423861   1.097   1.56900
             ÓLEO DIESEL       3134.0   2.481286   0.626930   1.435   2.03300
             ÓLEO DIESEL S10   1210.0   3.294752   0.421234   2.305   2.92425
NORDESTE     ETANOL HIDRATADO  7046.0   2.320266   0.604374   1.181   1.82500
             GASOLINA COMUM    7063.0   3.001887   0.640696   1.949   2.58400
             GLP               6410.0  41.966090  12.063743  28.367  33.22875
             GNV               5176.0   1.881722   0.522996   0.975   1.59600
             ÓLEO DIESEL       7061.0   2.346950   0.605705   1.313   1.90000
             ÓLEO DIESEL S10   3032.0   3.041966   0.441550   2.130   2.60000
NORTE        ETANOL HIDRATADO  5177.0   2.511624   0.646781   1.226   2.03300
             GASOLINA COMUM    5464.0   3.149501   0.641249   1.995   2.70475
             GLP               5327.0  47.065572  14.553748  28.086  36.32950
             GNV                243.0   2.084399   0.622229   1.399   1.39900
             ÓLEO DIESEL       5465.0   2.571048   0.650994   1.450   2.08600
             ÓLEO DIESEL S10   2324.0   3.316231   0.529044   2.193   2.88300
SUDESTE      ETANOL HIDRATADO  3137.0   2.163621   0.651486   0.766   1.69200
             GASOLINA COMUM    3140.0   3.000565   0.698573   1.888   2.50200
             GLP               3137.0  42.081544  11.524738  28.026  33.63600
             GNV               2841.0   1.716074   0.462098   0.996   1.42400
             ÓLEO DIESEL       3140.0   2.339699   0.588641   1.356   1.87600
             ÓLEO DIESEL S10   1349.0   3.056194   0.418396   2.180   2.65000
SUL          ETANOL HIDRATADO  2353.0   2.268156   0.702877   0.922   1.72100
             GASOLINA COMUM    2354.0   2.972569   0.623557   1.961   2.54300
             GLP               2343.0  43.490318  11.640755  29.440  34.79250
             GNV               1899.0   1.865612   0.490703   1.168   1.49900
             ÓLEO DIESEL       2354.0   2.332293   0.527845   1.374   1.95100
             ÓLEO DIESEL S10   1012.0   2.981775   0.365470   2.151   2.66300

                                   50%       75%     max
REGIÃO       PRODUTO
CENTRO OESTE ETANOL HIDRATADO   2.0005   2.47900   3.598
             GASOLINA COMUM     2.8565   3.45975   4.963
             GLP               42.8385  55.90425  99.357
             GNV                1.7490   2.16800   3.239
             ÓLEO DIESEL        2.2465   3.01900   4.162
             ÓLEO DIESEL S10    3.3540   3.61900   4.200
NORDESTE     ETANOL HIDRATADO   2.1860   2.67000   3.927
             GASOLINA COMUM     2.7410   3.42450   4.951
             GLP               36.8550  48.35100  79.630
             GNV                1.8005   2.01125   3.811
             ÓLEO DIESEL        2.0820   2.86700   4.010
             ÓLEO DIESEL S10    3.0865   3.33800   4.027
NORTE        ETANOL HIDRATADO   2.3390   2.89600   4.102
             GASOLINA COMUM     2.9330   3.58475   5.362
             GLP               42.3110  54.07500  87.270
             GNV                2.0600   2.65000   3.240
             ÓLEO DIESEL        2.3390   3.08200   4.774
             ÓLEO DIESEL S10    3.3155   3.65300   4.878
SUDESTE      ETANOL HIDRATADO   2.0430   2.56700   4.115
             GASOLINA COMUM     2.7930   3.45150   5.119
             GLP               38.2800  49.25900  79.192
             GNV                1.6630   1.90400   3.399
             ÓLEO DIESEL        2.0825   2.82500   3.994
             ÓLEO DIESEL S10    3.0910   3.38600   4.080
SUL          ETANOL HIDRATADO   2.1130   2.60100   4.287
             GASOLINA COMUM     2.7315   3.34225   4.953
             GLP               39.9760  48.73350  72.088
             GNV                1.7020   2.15950   3.476
             ÓLEO DIESEL        2.0900   2.78450   3.800
             ÓLEO DIESEL S10    2.9910   3.25200   3.815

agg: agrega (roda) uma série de funções para os elementos de um dataframe ou de grupos de um dataframe.

In [587]:
df = pd.DataFrame([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [None,None, None]],
                  columns=['A', 'B', 'C'])
df

     A    B    C
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0
3  NaN  NaN  NaN

In [588]:
df.agg([sum, min])

/tmp/ipython-input-1226331895.py:1: FutureWarning: The provided callable <built-in function sum> is currently using Series.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.agg([sum, min])
/tmp/ipython-input-1226331895.py:1: FutureWarning: The provided callable <built-in function min> is currently using Series.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.agg([sum, min])

        A     B     C
sum  12.0  15.0  18.0
min   1.0   2.0   3.0

In [589]:
grupos = data_final.groupby('REGIÃO')
grupos

In [590]:
grupos['PREÇO MÉDIO REVENDA'].agg([min, max])

/tmp/ipython-input-3977787304.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  grupos['PREÇO MÉDIO REVENDA'].agg([min, max])
/tmp/ipython-input-3977787304.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  grupos['PREÇO MÉDIO REVENDA'].agg([min, max])

                min     max
REGIÃO
CENTRO OESTE  1.097  99.357
NORDESTE      0.975  79.630
NORTE         1.226  87.270
SUDESTE       0.766  79.192
SUL           0.922  72.088

## 6. Ordenação

In [591]:
notas = pd.DataFrame({
    'nome': ['João', 'Maria', 'José', 'Alice'],
    'idade': [20, 21, 19, 20],
    'nota_final': [5.0, 10.0, 6.0, 10.0]
})
notas

    nome  idade  nota_final
0   João     20         5.0
1  Maria     21        10.0
2   José     19         6.0
3  Alice     20        10.0

.sort_values(): ordena valores ao longo de um eixo.

In [592]:
notas.sort_values(by='nota_final', ascending=False)

    nome  idade  nota_final
1  Maria     21        10.0
3  Alice     20        10.0
2   José     19         6.0
0   João     20         5.0

In [595]:
notas.sort_values(by=['nota_final', 'nome'], ascending=[False, True])

    nome  idade  nota_final
3  Alice     20        10.0
1  Maria     21        10.0
2   José     19         6.0
0   João     20         5.0

Ordena os registros, primeiramente, pela coluna 'nota_final' em ordem descrente.
Então, reordena os registros "empatados", ou seja, com a mesma nota final, em ordem alfabética (ordem crescente).

In [596]:
notas

    nome  idade  nota_final
0   João     20         5.0
1  Maria     21        10.0
2   José     19         6.0
3  Alice     20        10.0

In [597]:
notas.sort_values(by=['nota_final', 'nome'], ascending=[False, True], inplace=True)

In [598]:
notas

    nome  idade  nota_final
3  Alice     20        10.0
1  Maria     21        10.0
2   José     19         6.0
0   João     20         5.0

#7. Exercícios

Vamos aplicar os conceitos que vimos em alguns exercícios.
Para isso, utilizaremos o dataset de preços de combustíveis no Brasil.

Como há apenas medições de janeiro a junho para o ano de 2019, resolvemos remover os dados deste ano da análise.

In [599]:
data_final

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.825,0.110,0.4201,0.96660,0.133,5,2004,DEFAULT,0,7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.763,0.088,0.5013,1.05000,0.115,5,2004,DEFAULT,1,6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.970,0.095,0.5614,1.16100,0.098,5,2004,DEFAULT,2,8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.830,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.941,0.077,0.7441,1.03170,0.082,5,2004,DEFAULT,4,7.086
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103387,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,2.756,0.000,2.7560,2.75600,0.000,6,2019,DEFAULT,106818,21.444
103388,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,2.451,0.402,1.9842,2.86610,0.164,6,2019,DEFAULT,106819,20.406
103389,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,1.998,0.000,1.9981,1.99810,0.000,6,2019,DEFAULT,106820,17.472
103390,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,2.374,0.165,2.0179,2.50930,0.070,6,2019,DEFAULT,106821,18.120
103391,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,2.518,0.000,2.5175,2.51750,0.000,6,2019,DEFAULT,106822,22.182

como há apens medições de janeiro para o ano de 2019,resolvemos remover os dados deste ano da analise

In [600]:
data_final.query('ANO != 2019')

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.825,0.110,0.4201,0.96660,0.133,5,2004,DEFAULT,0,7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.763,0.088,0.5013,1.05000,0.115,5,2004,DEFAULT,1,6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.970,0.095,0.5614,1.16100,0.098,5,2004,DEFAULT,2,8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.830,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.941,0.077,0.7441,1.03170,0.082,5,2004,DEFAULT,4,7.086
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99734,103063,2018-12-30,2019-01-05,SUDESTE,RIO DE JANEIRO,GNV,122,R$/m3,3.080,0.262,...,2.381,0.161,2.1670,2.86970,0.068,12,2018,DEFAULT,103063,18.480
99735,103064,2018-12-30,2019-01-05,NORDESTE,RIO GRANDE DO NORTE,GNV,10,R$/m3,3.465,0.060,...,2.706,0.000,2.7059,2.70590,0.000,12,2018,DEFAULT,103064,20.790
99736,103065,2018-12-30,2019-01-05,SUL,RIO GRANDE DO SUL,GNV,16,R$/m3,3.402,0.103,...,2.106,0.249,1.8775,2.37240,0.118,12,2018,DEFAULT,103065,20.412
99737,103066,2018-12-30,2019-01-05,SUL,SANTA CATARINA,GNV,15,R$/m3,2.944,0.124,...,2.274,0.283,1.8738,2.27400,0.124,12,2018,DEFAULT,103066,17.664
99738,103067,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,GNV,41,R$/m3,2.353,0.451,...,1.886,0.250,1.6400,2.33200,0.133,12,2018,DEFAULT,103067,14.118

In [601]:
df = data_final.query('ANO != 2019')

In [602]:
df

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.825,0.110,0.4201,0.96660,0.133,5,2004,DEFAULT,0,7.728
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.763,0.088,0.5013,1.05000,0.115,5,2004,DEFAULT,1,6.972
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.970,0.095,0.5614,1.16100,0.098,5,2004,DEFAULT,2,8.334
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.830,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3,7.572
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.941,0.077,0.7441,1.03170,0.082,5,2004,DEFAULT,4,7.086
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99734,103063,2018-12-30,2019-01-05,SUDESTE,RIO DE JANEIRO,GNV,122,R$/m3,3.080,0.262,...,2.381,0.161,2.1670,2.86970,0.068,12,2018,DEFAULT,103063,18.480
99735,103064,2018-12-30,2019-01-05,NORDESTE,RIO GRANDE DO NORTE,GNV,10,R$/m3,3.465,0.060,...,2.706,0.000,2.7059,2.70590,0.000,12,2018,DEFAULT,103064,20.790
99736,103065,2018-12-30,2019-01-05,SUL,RIO GRANDE DO SUL,GNV,16,R$/m3,3.402,0.103,...,2.106,0.249,1.8775,2.37240,0.118,12,2018,DEFAULT,103065,20.412
99737,103066,2018-12-30,2019-01-05,SUL,SANTA CATARINA,GNV,15,R$/m3,2.944,0.124,...,2.274,0.283,1.8738,2.27400,0.124,12,2018,DEFAULT,103066,17.664
99738,103067,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,GNV,41,R$/m3,2.353,0.451,...,1.886,0.250,1.6400,2.33200,0.133,12,2018,DEFAULT,103067,14.118

#7.1 Qual a proporção de postos pesquisados para cada combustível em cada região

In [603]:
grupos = df.groupby('PRODUTO')
grupos

In [604]:
grupos['REGIÃO'].value_counts()

PRODUTO           REGIÃO
ETANOL HIDRATADO  NORDESTE        6821
                  NORTE           5021
                  SUDESTE         3039
                  CENTRO OESTE    3022
                  SUL             2278
GASOLINA COMUM    NORDESTE        6838
                  NORTE           5289
                  SUDESTE         3040
                  CENTRO OESTE    3034
                  SUL             2279
GLP               NORDESTE        6185
                  NORTE           5152
                  SUDESTE         3037
                  CENTRO OESTE    2998
                  SUL             2268
GNV               NORDESTE        5030
                  SUDESTE         2772
                  SUL             1847
                  CENTRO OESTE     825
                  NORTE            233
ÓLEO DIESEL       NORDESTE        6836
                  NORTE           5290
                  SUDESTE         3040
                  CENTRO OESTE    3034
                  SUL             2279
ÓLEO DIESEL S10   NORDESTE        2807
                  NORTE           2149
                  SUDESTE         1249
                  CENTRO OESTE    1110
                  SUL              937
Name: count, dtype: int64

7.2 Como os preços da Gasolina Comum em São Paulo variaram em 2018?

In [614]:
gasolinasp = df.query('PRODUTO == "GASOLINA COMUM" and ESTADO == "SAO PAULO" and ANO == 2018')
gasolinasp

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
92319,95351,2018-01-07,2018-01-13,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,3.988,0.156,...,3.577,0.104,2.9900,3.9510,0.029,1,2018,DEFAULT,95351,23.928
92465,95502,2018-01-14,2018-01-20,SUDESTE,SAO PAULO,GASOLINA COMUM,1648,R$/l,4.002,0.155,...,3.590,0.102,2.9900,3.9014,0.028,1,2018,DEFAULT,95502,24.012
92610,95654,2018-01-21,2018-01-27,SUDESTE,SAO PAULO,GASOLINA COMUM,1648,R$/l,4.006,0.160,...,3.596,0.102,2.9900,3.9014,0.028,1,2018,DEFAULT,95654,24.036
92755,95806,2018-01-28,2018-02-03,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.019,0.156,...,3.596,0.107,2.9240,3.9537,0.030,1,2018,DEFAULT,95806,24.114
92901,95958,2018-02-04,2018-02-10,SUDESTE,SAO PAULO,GASOLINA COMUM,1646,R$/l,4.004,0.157,...,3.588,0.102,2.9900,3.9537,0.028,2,2018,DEFAULT,95958,24.024
93048,96109,2018-02-11,2018-02-17,SUDESTE,SAO PAULO,GASOLINA COMUM,1640,R$/l,4.014,0.153,...,3.570,0.097,2.9900,3.8899,0.027,2,2018,DEFAULT,96109,24.084
93192,96259,2018-02-18,2018-02-24,SUDESTE,SAO PAULO,GASOLINA COMUM,1637,R$/l,4.008,0.161,...,3.563,0.097,2.9900,3.8910,0.027,2,2018,DEFAULT,96259,24.048
93339,96411,2018-02-25,2018-03-03,SUDESTE,SAO PAULO,GASOLINA COMUM,1638,R$/l,3.992,0.164,...,3.570,0.106,2.9900,3.9549,0.030,2,2018,DEFAULT,96411,23.952
93487,96563,2018-03-04,2018-03-10,SUDESTE,SAO PAULO,GASOLINA COMUM,1637,R$/l,3.970,0.161,...,3.583,0.110,2.9900,4.0687,0.031,3,2018,DEFAULT,96563,23.820
93634,96715,2018-03-11,2018-03-17,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.003,0.155,...,3.593,0.104,2.9900,4.2590,0.029,3,2018,DEFAULT,96715,24.018
93778,96866,2018-03-18,2018-03-24,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,3.988,0.154,...,3.588,0.108,2.9900,4.2590,0.030,3,2018,DEFAULT,96866,23.928
93924,97017,2018-03-25,2018-03-31,SUDESTE,SAO PAULO,GASOLINA COMUM,1643,R$/l,3.992,0.159,...,3.624,0.110,3.3200,3.9743,0.030,3,2018,DEFAULT,97017,23.952
94070,97168,2018-04-01,2018-04-07,SUDESTE,SAO PAULO,GASOLINA COMUM,1646,R$/l,4.007,0.171,...,3.630,0.113,2.9900,3.9682,0.031,4,2018,DEFAULT,97168,24.042
94215,97319,2018-04-08,2018-04-14,SUDESTE,SAO PAULO,GASOLINA COMUM,1646,R$/l,4.008,0.161,...,3.629,0.102,2.9900,3.9747,0.028,4,2018,DEFAULT,97319,24.048
94361,97471,2018-04-15,2018-04-21,SUDESTE,SAO PAULO,GASOLINA COMUM,1645,R$/l,4.006,0.159,...,3.632,0.102,2.9900,3.9312,0.028,4,2018,DEFAULT,97471,24.036
94508,97622,2018-04-22,2018-04-28,SUDESTE,SAO PAULO,GASOLINA COMUM,1643,R$/l,4.035,0.168,...,3.625,0.098,3.0599,4.0060,0.027,4,2018,DEFAULT,97622,24.210
94656,97773,2018-04-29,2018-05-05,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.005,0.158,...,3.625,0.103,2.9900,4.0060,0.028,4,2018,DEFAULT,97773,24.030
94804,97924,2018-05-06,2018-05-12,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.032,0.171,...,3.656,0.095,3.2758,3.8875,0.026,5,2018,DEFAULT,97924,24.192
94951,98074,2018-05-13,2018-05-19,SUDESTE,SAO PAULO,GASOLINA COMUM,1643,R$/l,4.056,0.160,...,3.690,0.107,2.9900,3.9461,0.029,5,2018,DEFAULT,98074,24.336
95098,98225,2018-05-20,2018-05-26,SUDESTE,SAO PAULO,GASOLINA COMUM,1619,R$/l,4.196,0.187,...,3.793,0.130,2.9900,4.1181,0.034,5,2018,DEFAULT,98225,25.176
95211,98371,2018-05-27,2018-06-02,SUDESTE,SAO PAULO,GASOLINA COMUM,102,R$/l,4.502,0.199,...,3.862,0.087,3.5800,3.9500,0.023,5,2018,DEFAULT,98371,27.012
95342,98517,2018-06-03,2018-06-09,SUDESTE,SAO PAULO,GASOLINA COMUM,1560,R$/l,4.416,0.155,...,3.873,0.096,3.3016,4.4394,0.025,6,2018,DEFAULT,98517,26.496
95486,98670,2018-06-10,2018-06-16,SUDESTE,SAO PAULO,GASOLINA COMUM,1616,R$/l,4.349,0.150,...,3.866,0.090,3.5200,4.4394,0.023,6,2018,DEFAULT,98670,26.094
95633,98821,2018-06-17,2018-06-23,SUDESTE,SAO PAULO,GASOLINA COMUM,1646,R$/l,4.326,0.157,...,3.849,0.102,3.5403,4.1678,0.027,6,2018,DEFAULT,98821,25.956
95779,98972,2018-06-24,2018-06-30,SUDESTE,SAO PAULO,GASOLINA COMUM,1643,R$/l,4.274,0.167,...,3.808,0.107,3.5403,4.1786,0.028,6,2018,DEFAULT,98972,25.644
95922,99122,2018-07-01,2018-07-07,SUDESTE,SAO PAULO,GASOLINA COMUM,1637,R$/l,4.272,0.178,...,3.804,0.110,3.5200,4.1069,0.029,7,2018,DEFAULT,99122,25.632
96069,99271,2018-07-08,2018-07-14,SUDESTE,SAO PAULO,GASOLINA COMUM,1640,R$/l,4.259,0.168,...,3.837,0.119,2.9900,4.1993,0.031,7,2018,DEFAULT,99271,25.554
96217,99422,2018-07-15,2018-07-21,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,4.268,0.171,...,3.863,0.110,3.5200,4.2560,0.028,7,2018,DEFAULT,99422,25.608
96362,99573,2018-07-22,2018-07-28,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.241,0.175,...,3.840,0.108,3.5400,4.1596,0.028,7,2018,DEFAULT,99573,25.446
96507,99725,2018-07-29,2018-08-04,SUDESTE,SAO PAULO,GASOLINA COMUM,1639,R$/l,4.235,0.182,...,3.808,0.107,3.4900,4.0900,0.028,7,2018,DEFAULT,99725,25.410
96651,99876,2018-08-05,2018-08-11,SUDESTE,SAO PAULO,GASOLINA COMUM,1640,R$/l,4.221,0.192,...,3.797,0.109,3.4900,4.1010,0.029,8,2018,DEFAULT,99876,25.326
96799,100027,2018-08-12,2018-08-18,SUDESTE,SAO PAULO,GASOLINA COMUM,1646,R$/l,4.208,0.189,...,3.766,0.103,3.5000,4.0380,0.027,8,2018,DEFAULT,100027,25.248
96943,100177,2018-08-19,2018-08-25,SUDESTE,SAO PAULO,GASOLINA COMUM,1643,R$/l,4.189,0.189,...,3.779,0.105,3.5050,4.0871,0.028,8,2018,DEFAULT,100177,25.134
97086,100326,2018-08-26,2018-09-01,SUDESTE,SAO PAULO,GASOLINA COMUM,1638,R$/l,4.224,0.185,...,3.840,0.116,3.5300,4.1800,0.030,8,2018,DEFAULT,100326,25.344
97230,100477,2018-09-02,2018-09-08,SUDESTE,SAO PAULO,GASOLINA COMUM,1640,R$/l,4.296,0.189,...,3.890,0.128,3.5150,4.2094,0.033,9,2018,DEFAULT,100477,25.776
97378,100628,2018-09-09,2018-09-15,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,4.409,0.174,...,3.992,0.120,3.5400,4.3950,0.030,9,2018,DEFAULT,100628,26.454
97527,100780,2018-09-16,2018-09-22,SUDESTE,SAO PAULO,GASOLINA COMUM,1639,R$/l,4.414,0.175,...,4.021,0.120,3.5400,4.3313,0.030,9,2018,DEFAULT,100780,26.484
97675,100930,2018-09-23,2018-09-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1639,R$/l,4.476,0.172,...,4.055,0.113,3.6950,4.5510,0.028,9,2018,DEFAULT,100930,26.856
97820,101079,2018-09-30,2018-10-06,SUDESTE,SAO PAULO,GASOLINA COMUM,1639,R$/l,4.469,0.178,...,4.060,0.116,3.6950,4.4800,0.029,9,2018,DEFAULT,101079,26.814
97965,101228,2018-10-07,2018-10-13,SUDESTE,SAO PAULO,GASOLINA COMUM,1643,R$/l,4.499,0.181,...,4.085,0.122,3.7600,4.3978,0.030,10,2018,DEFAULT,101228,26.994
98112,101378,2018-10-14,2018-10-20,SUDESTE,SAO PAULO,GASOLINA COMUM,1645,R$/l,4.512,0.180,...,4.078,0.125,3.5990,4.3900,0.031,10,2018,DEFAULT,101378,27.072
98259,101529,2018-10-21,2018-10-27,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,4.506,0.176,...,4.074,0.112,3.6025,4.4135,0.027,10,2018,DEFAULT,101529,27.036
98401,101679,2018-10-28,2018-11-03,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,4.490,0.180,...,4.028,0.122,3.7300,4.4135,0.030,10,2018,DEFAULT,101679,26.940
98545,101828,2018-11-04,2018-11-10,SUDESTE,SAO PAULO,GASOLINA COMUM,1645,R$/l,4.452,0.190,...,3.913,0.127,3.5700,4.4990,0.032,11,2018,DEFAULT,101828,26.712
98689,101977,2018-11-11,2018-11-17,SUDESTE,SAO PAULO,GASOLINA COMUM,1643,R$/l,4.377,0.209,...,3.849,0.144,3.5000,4.4990,0.037,11,2018,DEFAULT,101977,26.262
98831,102127,2018-11-18,2018-11-24,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,4.332,0.195,...,3.747,0.113,3.4600,4.2552,0.030,11,2018,DEFAULT,102127,25.992
98977,102276,2018-11-25,2018-12-01,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,4.291,0.216,...,3.702,0.119,3.3500,4.1213,0.032,11,2018,DEFAULT,102276,25.746
99122,102426,2018-12-02,2018-12-08,SUDESTE,SAO PAULO,GASOLINA COMUM,1648,R$/l,4.187,0.213,...,3.622,0.117,3.3400,4.0849,0.032,12,2018,DEFAULT,102426,25.122
99266,102575,2018-12-09,2018-12-15,SUDESTE,SAO PAULO,GASOLINA COMUM,1649,R$/l,4.148,0.212,...,3.615,0.119,3.3400,4.0849,0.033,12,2018,DEFAULT,102575,24.888
99410,102724,2018-12-16,2018-12-22,SUDESTE,SAO PAULO,GASOLINA COMUM,1637,R$/l,4.129,0.201,...,3.639,0.110,3.3500,3.9892,0.030,12,2018,DEFAULT,102724,24.774
99553,102874,2018-12-23,2018-12-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,4.129,0.201,...,3.645,0.107,3.3500,3.9892,0.029,12,2018,DEFAULT,102874,24.774
99698,103025,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,GASOLINA COMUM,1643,R$/l,4.113,0.201,...,3.610,0.100,3.3500,3.9585,0.028,12,2018,DEFAULT,103025,24.678

### ESTATÍSTICAS DESCRITIVAS

In [615]:
gasolinasp.describe()

,Unnamed: 0,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
count,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.00000,52.000000,52.000000,52.000000,52.0,52.000000,52.000000
mean,99196.096154,1610.211538,4.202769,0.175500,3.671500,4.975750,0.442481,0.041750,3.760288,0.109654,3.31295,4.139454,0.029096,6.615385,2018.0,99196.096154,25.216615
std,2279.595314,213.627432,0.180672,0.017955,0.163808,0.211198,0.063271,0.003965,0.163664,0.010712,0.26684,0.195897,0.002460,3.470627,0.0,2279.595314,1.084032
min,95351.000000,102.000000,3.970000,0.150000,3.369000,4.499000,0.366000,0.034000,3.563000,0.087000,2.92400,3.887500,0.023000,1.000000,2018.0,95351.000000,23.820000
25%,97281.250000,1639.000000,4.008000,0.159750,3.499000,4.899000,0.404500,0.039000,3.620250,0.102000,2.99000,3.965775,0.028000,4.000000,2018.0,97281.250000,24.048000
50%,99196.500000,1642.000000,4.202000,0.173000,3.679000,4.999000,0.421500,0.040000,3.756500,0.108000,3.35000,4.095500,0.029000,7.000000,2018.0,99196.500000,25.212000
75%,101116.250000,1644.000000,4.336250,0.189000,3.784000,5.099000,0.470250,0.044000,3.862250,0.116250,3.53250,4.259000,0.030000,9.250000,2018.0,101116.250000,26.017500
max,103025.000000,1649.000000,4.512000,0.216000,3.969000,5.299000,0.640000,0.051000,4.085000,0.144000,3.76000,4.551000,0.037000,12.000000,2018.0,103025.000000,27.072000

In [616]:
gasolinasp['PREÇO MÉDIO REVENDA'].describe()

count    52.000000
mean      4.202769
std       0.180672
min       3.970000
25%       4.008000
50%       4.202000
75%       4.336250
max       4.512000
Name: PREÇO MÉDIO REVENDA, dtype: float64

7.3 Como os preços da Gasolina Comum e do Etanol em São Paulo variaram em 2018?

In [618]:
df.query('(PRODUTO == "GASOLINA COMUM"or PRODUTO =="ETANOL HIDRATADO") and ESTADO == "SAO PAULO" and ANO == 2018')

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem nocao,coluna a partir de lista,PRECO MEDIO DE REVENDA (dolares)
92238,95270,2018-01-07,2018-01-13,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1664,R$/l,2.833,0.139,...,2.495,0.092,2.1842,2.8833,0.037,1,2018,DEFAULT,95270,16.998
92319,95351,2018-01-07,2018-01-13,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,3.988,0.156,...,3.577,0.104,2.9900,3.9510,0.029,1,2018,DEFAULT,95351,23.928
92384,95421,2018-01-14,2018-01-20,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1661,R$/l,2.868,0.134,...,2.537,0.087,2.2600,2.8471,0.034,1,2018,DEFAULT,95421,17.208
92465,95502,2018-01-14,2018-01-20,SUDESTE,SAO PAULO,GASOLINA COMUM,1648,R$/l,4.002,0.155,...,3.590,0.102,2.9900,3.9014,0.028,1,2018,DEFAULT,95502,24.012
92529,95573,2018-01-21,2018-01-27,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1662,R$/l,2.874,0.135,...,2.550,0.095,1.6900,2.9722,0.037,1,2018,DEFAULT,95573,17.244
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99410,102724,2018-12-16,2018-12-22,SUDESTE,SAO PAULO,GASOLINA COMUM,1637,R$/l,4.129,0.201,...,3.639,0.110,3.3500,3.9892,0.030,12,2018,DEFAULT,102724,24.774
99472,102793,2018-12-23,2018-12-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1662,R$/l,2.644,0.163,...,2.339,0.094,2.0067,2.7443,0.040,12,2018,DEFAULT,102793,15.864
99553,102874,2018-12-23,2018-12-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,4.129,0.201,...,3.645,0.107,3.3500,3.9892,0.029,12,2018,DEFAULT,102874,24.774
99617,102944,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1661,R$/l,2.643,0.161,...,2.340,0.097,1.9072,2.7957,0.041,12,2018,DEFAULT,102944,15.858
99698,103025,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,GASOLINA COMUM,1643,R$/l,4.113,0.201,...,3.610,0.100,3.3500,3.9585,0.028,12,2018,DEFAULT,103025,24.678

In [619]:
gasolinasp['PREÇO MÉDIO REVENDA'].describe().to_frame()

       PREÇO MÉDIO REVENDA
count            52.000000
mean              4.202769
std               0.180672
min               3.970000
25%               4.008000
50%               4.202000
75%               4.336250
max               4.512000

In [621]:
gasolinasp.groupby('PRODUTO')['PREÇO MÉDIO REVENDA'].describe()

                count      mean       std   min    25%    50%      75%    max
PRODUTO
GASOLINA COMUM   52.0  4.202769  0.180672  3.97  4.008  4.202  4.33625  4.512