## **Pandas Essencial**
**Prof. Dr. Samuel Martins (@hisamuka @xavecoding)** <br/>
xavecoding: https://youtube.com/c/xavecoding <br/>

Neste tutorial, vamos aprender o essencial da biblioteca _Pandas_ para manipulação de dados.<br/><br/>

<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.

### Pacotes usados neste Notebook

In [2]:
# pacotes usados neste notebook
import pandas as pd

<h1>Manipulação de Dados com Pandas</h1><hr/>

<h2>1. Manipulação Básica de Datasets</h2>
<hr/>

**Dataset**: Gas Prices in Brazil: https://www.kaggle.com/matheusfreitag/gas-prices-in-brazil <br/>

Este dataset contém os **registros dos preços médios semanais dos combustíveis do Brasil entre os anos de 2004 e 2019**. <br/>
Cada *amostra (registro/linha)* consiste em um registro de preço aferido para um dado tipo de combustível em uma dada localidade do Brasil. <br/>
Alguns dos principais *atributos* (colunas) do dataset são: 'ESTADO', 'PRODUTO', 'NÚMERO DE POSTOS PESQUISADOS', 'PREÇO MÉDIO REVENDA'.


\* O arquivo disponibilizado no Kaggle está no formato *tsv*. Embora o _pandas_ consiga abrí-lo normalmente, convertemos tal arquivo para o formato *CSV*, que é um dos formatos mais utilizados, e mudamos seu separado para ';' apenas para mostrar algumas opções da função de carregamento.

### 1.1. Importando o Dataset
Para carregar um dataset no formato csv, basta utilizar a função `read_csv` do pandas. Por padrão, ela considera _','_ como separador.

In [5]:
data = pd.read_csv('/content/GasPricesinBrazil_2004-2019.csv')

In [10]:
data

,Unnamed: 0;DATA INICIAL;DATA FINAL;REGIÃO;ESTADO;PRODUTO;NÚMERO DE POSTOS PESQUISADOS;UNIDADE DE MEDIDA;PREÇO MÉDIO REVENDA;DESVIO PADRÃO REVENDA;PREÇO MÍNIMO REVENDA;PREÇO MÁXIMO REVENDA;MARGEM MÉDIA REVENDA;COEF DE VARIAÇÃO REVENDA;PREÇO MÉDIO DISTRIBUIÇÃO;DESVIO PADRÃO DISTRIBUIÇÃO;PREÇO MÍNIMO DISTRIBUIÇÃO;PREÇO MÁXIMO DISTRIBUIÇÃO;COEF DE VARIAÇÃO DISTRIBUIÇÃO;MÊS;ANO,coluna sem noção
0,0;2004-05-09;2004-05-15;CENTRO OESTE;DISTRITO ...,DEFAULT
1,1;2004-05-09;2004-05-15;CENTRO OESTE;GOIAS;ETA...,DEFAULT
2,2;2004-05-09;2004-05-15;CENTRO OESTE;MATO GROS...,DEFAULT
3,3;2004-05-09;2004-05-15;CENTRO OESTE;MATO GROS...,DEFAULT
4,4;2004-05-09;2004-05-15;NORDESTE;ALAGOAS;ETANO...,DEFAULT
...,...,...
106818,106818;2019-06-23;2019-06-29;NORDESTE;RIO GRAN...,DEFAULT
106819,106819;2019-06-23;2019-06-29;SUL;RIO GRANDE DO...,DEFAULT
106820,106820;2019-06-23;2019-06-29;SUL;SANTA CATARIN...,DEFAULT
106821,106821;2019-06-23;2019-06-29;SUDESTE;SAO PAULO...,DEFAULT
106822,106822;2019-06-23;2019-06-29;NORDESTE;SERGIPE;...,DEFAULT

O dataset não foi carregado corretamente pois o separador utilizado seu arquivo CSV era ';' e não a ','. <br/>
Vamos então carregá-lo corretamente:

In [6]:
#carregando o dataset corretamente ==> neste caso, usa o separador ';'
data = pd.read_csv('/content/GasPricesinBrazil_2004-2019.csv', sep=';')

In [13]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,3.690,0.818,0.018,2.756,0,2.756,2.756,0,6,2019
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,3.789,0.95,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,3.499,0.914,0.065,1.998,0,1.9981,1.9981,0,6,2019
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,3.699,1.179,0.001,2.518,0,2.5175,2.5175,0,6,2019

### 1.2. Exibindo as primeiras linhas do Dataset
A função `.head()` exibe as 5 primeiras linhas do dataset/tabela/Data Frame.

In [14]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

In [15]:
#exibe as 10 primeiras linhas do dataframe
data.head(10)

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
5,5,2004-05-09,2004-05-15,NORDESTE,BAHIA,ETANOL HIDRATADO,408,R$/l,1.383,0.132,...,2.050,0.426,0.095,0.957,0.128,0.5686,1.35,0.134,5,2004
6,6,2004-05-09,2004-05-15,NORDESTE,CEARA,ETANOL HIDRATADO,278,R$/l,1.453,0.218,...,1.950,0.353,0.150,1.1,0.068,0.7332,1.294,0.062,5,2004
7,7,2004-05-09,2004-05-15,NORDESTE,MARANHAO,ETANOL HIDRATADO,105,R$/l,1.631,0.158,...,2.000,0.515,0.097,1.116,0.091,0.9923,1.36183,0.082,5,2004
8,8,2004-05-09,2004-05-15,NORDESTE,PARAIBA,ETANOL HIDRATADO,125,R$/l,1.284,0.130,...,1.699,0.353,0.101,0.931,0.072,0.7577,1.2972,0.077,5,2004
9,9,2004-05-09,2004-05-15,NORDESTE,PERNAMBUCO,ETANOL HIDRATADO,423,R$/l,1.224,0.141,...,1.700,0.277,0.115,0.947,0.091,0.5643,1.3541,0.096,5,2004

### 1.3 Informações do Dataset e Elementos Chave

### 1.3.1 Informações gerais sobre o Dataset

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 21 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Unnamed: 0                     106823 non-null  int64
 1   DATA INICIAL                   106823 non-null  object
 2   DATA FINAL                     106823 non-null  object
 3   REGIÃO                         106823 non-null  object
 4   ESTADO                         106823 non-null  object
 5   PRODUTO                        106823 non-null  object
 6   NÚMERO DE POSTOS PESQUISADOS   106823 non-null  int64
 7   UNIDADE DE MEDIDA              106823 non-null  object
 8   PREÇO MÉDIO REVENDA            106823 non-null  float64
 9   DESVIO PADRÃO REVENDA          106823 non-null  float64
 10  PREÇO MÍNIMO REVENDA           106823 non-null  float64
 11  PREÇO MÁXIMO REVENDA           106823 non-null  float64
 12  MARGEM MÉDIA REVENDA           106823 non-null  object
 13  COEF DE VARIAÇÃO REVENDA       106823 non-null  float64
 14  PREÇO MÉDIO DISTRIBUIÇÃO       106823 non-null  object
 15  DESVIO PADRÃO DISTRIBUIÇÃO     106823 non-null  object
 16  PREÇO MÍNIMO DISTRIBUIÇÃO      106823 non-null  object
 17  PREÇO MÁXIMO DISTRIBUIÇÃO      106823 non-null  object
 18  COEF DE VARIAÇÃO DISTRIBUIÇÃO  106823 non-null  object
 19  MÊS                            106823 non-null  int64
 20  ANO                            106823 non-null  int64
dtypes: float64(5), int64(4), object(12)
memory usage: 17.1+ MB

A primeira coluna da tabela, chamada _'Unnamed: 0'_, parece não significar nada. Na verdade, ela parece ser os **índices** da tabela, que foram salvos como uma _coluna_.<br/>
Veremos jajá como **remover tal coluna**.

Outro ponto é que, aparentemente, nenhum atributo/coluna possui valores nulos (_null_), uma vez que o número de registros do dataframe e os números de valores _non-null_ é de **106823**. <br/>
Mas, veremos que não é bem assim para esse caso.

### 1.3.2 Data Frame
Todo dataset carregado (dados estruturados) é um `Data Frame`: 'Tabela' bi-dimensional, de tamanho mutável, com dados potencialmente heterogêneos. <br/>

In [17]:
type(data)

pandas.core.frame.DataFrame

Podemos acessar as **dimensões do Data Frame** (número de linhas x número de colunas) utilizando o atributo `.shape` do Data Frame.

In [18]:
data.shape

(106823, 21)

In [19]:
print(f'O Dataframe possui {data.shape[0]} linhas/observações /registros e {data.shape[1]} colunas/atributos/variáveis.')

O Dataframe possui 106823 linhas/observações /registros e 21 colunas/atributos/variáveis.

#### **Criando um DataFrame**

Podemos criar um DataFrame a partir de um _dicionário_, onde cada **chave** possui uma **lista de elementos de igual tamanho**.<br/>
As **chaves** representam as **colunas** e **cada um dos valores de sua lista** representa o **valor da linha** correspondente para aquela coluna.

In [20]:
personagens_df = pd.DataFrame({
    'nome': ['Luke Skywalker', 'Yoda', 'Palpatine'],
    'idade': [16, 1000, 70],
    'peso': [70, 15, 60],
    'eh jedi': [True, True, False]  # o nome das colunas podem ter espaços
})

In [21]:
personagens_df

             nome  idade  peso  eh jedi
0  Luke Skywalker     16    70     True
1            Yoda   1000    15     True
2       Palpatine     70    60    False

In [22]:
personagens_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   nome     3 non-null      object
 1   idade    3 non-null      int64
 2   peso     3 non-null      int64
 3   eh jedi  3 non-null      bool
dtypes: bool(1), int64(2), object(1)
memory usage: 207.0+ bytes

#### **VEJA MAIS**
Criando um Data Frame a partir de um dicionário: https://www.geeksforgeeks.org/how-to-create-dataframe-from-dictionary-in-python-pandas/

#### **Renomeando as colunas de um DataFrame**
**===>** O método `DataFrame.columns` retorna uma ";lista" com os **nomes de todas as colunas** do data frame.

In [23]:
personagens_df.columns

Index(['nome', 'idade', 'peso', 'eh jedi'], dtype='object')

In [24]:
type(personagens_df.columns)

pandas.core.indexes.base.Index

In [25]:
list(personagens_df.columns)

['nome', 'idade', 'peso', 'eh jedi']

<br/>

**===>** Para **renomear colunas** do data frame, utilize o método `DataFrame.rename`, que retorna uma _cópia_ do data frame com as as colunas renomeadas:

In [26]:
personagens_df

             nome  idade  peso  eh jedi
0  Luke Skywalker     16    70     True
1            Yoda   1000    15     True
2       Palpatine     70    60    False

In [27]:
personagens_df_renomeado = personagens_df.rename(columns={
    'nome': 'Nome completo', #renomeia a coluna de nome 'nome' para 'Nome completo'
    'idade': 'Idade',
})

In [28]:
personagens_df_renomeado

    Nome completo  Idade  peso  eh jedi
0  Luke Skywalker     16    70     True
1            Yoda   1000    15     True
2       Palpatine     70    60    False

In [29]:
personagens_df

             nome  idade  peso  eh jedi
0  Luke Skywalker     16    70     True
1            Yoda   1000    15     True
2       Palpatine     70    60    False

Para renomear o _próprio_ data frame em questão, utilize o parâmetro `inplace=True`:

In [30]:
personagens_df.rename(columns={'nome': 'Nome completo','idade': 'Idade'}, inplace=True)

In [31]:
personagens_df

    Nome completo  Idade  peso  eh jedi
0  Luke Skywalker     16    70     True
1            Yoda   1000    15     True
2       Palpatine     70    60    False

<br/>

**===>** Uma outra forma de **renomear todas as listas** de um data frame é passar uma _lista_ com os novos nomes das colunas para o atributo `DataFrame.columns`:

In [32]:
personagens_df.columns

Index(['Nome completo', 'Idade', 'peso', 'eh jedi'], dtype='object')

In [33]:
personagens_df.columns = ['NOME', 'IDADE', 'PESO', 'EH_JEDI']

In [34]:
personagens_df

             NOME  IDADE  PESO  EH_JEDI
0  Luke Skywalker     16    70     True
1            Yoda   1000    15     True
2       Palpatine     70    60    False

### 1.3.3 Series

Array uni-dimensional com os dados e rótulos de um eixo.

In [35]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

In [36]:
#selecionando uma coluna inteira
data['ESTADO']

0            DISTRITO FEDERAL
1                       GOIAS
2                 MATO GROSSO
3          MATO GROSSO DO SUL
4                     ALAGOAS
                 ...
106818    RIO GRANDE DO NORTE
106819      RIO GRANDE DO SUL
106820         SANTA CATARINA
106821              SAO PAULO
106822                SERGIPE
Name: ESTADO, Length: 106823, dtype: object

In [37]:
# selecionando uma coluna inteira
# está forma de acesso só funciona para colunas com nomes sem aspas, acentos, etc (caracteres inválidos)
data.ESTADO

0            DISTRITO FEDERAL
1                       GOIAS
2                 MATO GROSSO
3          MATO GROSSO DO SUL
4                     ALAGOAS
                 ...
106818    RIO GRANDE DO NORTE
106819      RIO GRANDE DO SUL
106820         SANTA CATARINA
106821              SAO PAULO
106822                SERGIPE
Name: ESTADO, Length: 106823, dtype: object

In [38]:
type(data['ESTADO'])

pandas.core.series.Series

In [39]:
# selecionando a observação indexada no índice [1] do dataframe
data.iloc[1]

Unnamed: 0                                      1
DATA INICIAL                           2004-05-09
DATA FINAL                             2004-05-15
REGIÃO                               CENTRO OESTE
ESTADO                                      GOIAS
PRODUTO                          ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                  387
UNIDADE DE MEDIDA                            R$/l
PREÇO MÉDIO REVENDA                         1.162
DESVIO PADRÃO REVENDA                       0.114
PREÇO MÍNIMO REVENDA                         0.89
PREÇO MÁXIMO REVENDA                        1.449
MARGEM MÉDIA REVENDA                        0.399
COEF DE VARIAÇÃO REVENDA                    0.098
PREÇO MÉDIO DISTRIBUIÇÃO                    0.763
DESVIO PADRÃO DISTRIBUIÇÃO                  0.088
PREÇO MÍNIMO DISTRIBUIÇÃO                  0.5013
PREÇO MÁXIMO DISTRIBUIÇÃO                    1.05
COEF DE VARIAÇÃO DISTRIBUIÇÃO               0.115
MÊS                                             5
ANO                                          2004
Name: 1, dtype: object

In [40]:
type(data.iloc[1])

pandas.core.series.Series

#### **Criando uma Series**

Podemos criar um DataFrame a partir de uma lista de elementos.

In [41]:
pd.Series([5.5,6.0,9.5])

0    5.5
1    6.0
2    9.5
dtype: float64

In [42]:
pd.Series([5.5,6.0,9.5], index=['prova 1', 'prova 2', 'projeto'], name='Notas dos Luke Skywalker')

prova 1    5.5
prova 2    6.0
projeto    9.5
Name: Notas dos Luke Skywalker, dtype: float64

Podemos alterar o **nome dos índices** (veremos melhor jajá) e o **nome da Series** (o que ela representa):

#### **VEJA MAIS**
https://pandas.pydata.org/pandas-docs/stable/user_guide/dsintro.html

### 1.3.4 Atribuindo Dados

#### 1.3.4.1 Atribuindo constantes

In [43]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

In [44]:
produto_view = data['PRODUTO'] # a series retornada referente á coluna não é uma copia mas sim uma referêrencia a coluna do dataframe
produto_view

0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...
106818                 GNV
106819                 GNV
106820                 GNV
106821                 GNV
106822                 GNV
Name: PRODUTO, Length: 106823, dtype: object

In [45]:
produto_copy_bkp = data['PRODUTO'].copy() # retorna uma cópia da coluna 'PRODUTO'
produto_copy_bkp

0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...
106818                 GNV
106819                 GNV
106820                 GNV
106821                 GNV
106822                 GNV
Name: PRODUTO, Length: 106823, dtype: object

In [46]:
data['PRODUTO'] = 'Combustivel' # a series retornada referente á coluna não é uma copia mas sim uma referencia/view a coluna do datafream

In [47]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,Combustivel,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,Combustivel,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,Combustivel,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,Combustivel,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,Combustivel,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

In [48]:
produto_view

0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...
106818                 GNV
106819                 GNV
106820                 GNV
106821                 GNV
106822                 GNV
Name: PRODUTO, Length: 106823, dtype: object

In [49]:
produto_copy_bkp

0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...
106818                 GNV
106819                 GNV
106820                 GNV
106821                 GNV
106822                 GNV
Name: PRODUTO, Length: 106823, dtype: object

#### 1.3.4.2 Atribuindo listas ou series

In [50]:
nrows, ncols = data.shape
nrows, ncols

(106823, 21)

In [51]:
novos_produtos = [f'Produto {i}' for i in range(nrows)]
len(novos_produtos)

106823

In [52]:
# a quantidade de elementos da lista 'novo_produtos' é igual ao número de linhas do dataframe
data['PRODUTO'] = novos_produtos

In [53]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,Produto 0,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,Produto 1,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,Produto 2,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,Produto 3,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,Produto 4,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,Produto 106818,7,R$/m3,3.574,0.065,...,3.690,0.818,0.018,2.756,0,2.756,2.756,0,6,2019
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,Produto 106819,23,R$/m3,3.401,0.129,...,3.789,0.95,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,Produto 106820,24,R$/m3,2.912,0.190,...,3.499,0.914,0.065,1.998,0,1.9981,1.9981,0,6,2019
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,Produto 106821,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,Produto 106822,4,R$/m3,3.697,0.005,...,3.699,1.179,0.001,2.518,0,2.5175,2.5175,0,6,2019

In [54]:
print(produto_view)
print('\n')
print(produto_copy_bkp)

0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...
106818                 GNV
106819                 GNV
106820                 GNV
106821                 GNV
106822                 GNV
Name: PRODUTO, Length: 106823, dtype: object


0         ETANOL HIDRATADO
1         ETANOL HIDRATADO
2         ETANOL HIDRATADO
3         ETANOL HIDRATADO
4         ETANOL HIDRATADO
                ...
106818                 GNV
106819                 GNV
106820                 GNV
106821                 GNV
106822                 GNV
Name: PRODUTO, Length: 106823, dtype: object

In [55]:
# voltando para os produtos originais
data['PRODUTO'] = produto_copy_bkp # produto_copy_bkp é uma series

In [56]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,3.690,0.818,0.018,2.756,0,2.756,2.756,0,6,2019
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,3.789,0.95,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,3.499,0.914,0.065,1.998,0,1.9981,1.9981,0,6,2019
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,3.699,1.179,0.001,2.518,0,2.5175,2.5175,0,6,2019

#### 1.3.4.3 Criando novas colunas
Para **criar uma nova coluna** em um data frame, basta atribuirmos uma _lista/Series de valores_ a uma **nova 'chave'** do data frame. <br/>

**PS:** A _quantidade de valores_ da lista precisa ser **igual** ao _número de linhas/registros_ do data frame.

In [57]:
# criando uma coluna a partir de um valor constante/default
# todas as linhas terão o mesmo valor para esta nova coluna
data['coluna sem noção'] = 'DEFAULT'
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem noção
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,0.818,0.018,2.756,0,2.756,2.756,0,6,2019,DEFAULT
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,0.95,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019,DEFAULT
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,0.914,0.065,1.998,0,1.9981,1.9981,0,6,2019,DEFAULT
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019,DEFAULT
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,1.179,0.001,2.518,0,2.5175,2.5175,0,6,2019,DEFAULT

In [59]:
data['coluna a partir de lista'] = range(data.shape[0])

In [60]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem noção,coluna a partir de lista
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,0.018,2.756,0,2.756,2.756,0,6,2019,DEFAULT,106818
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019,DEFAULT,106819
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,0.065,1.998,0,1.9981,1.9981,0,6,2019,DEFAULT,106820
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019,DEFAULT,106821
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,0.001,2.518,0,2.5175,2.5175,0,6,2019,DEFAULT,106822

In [61]:
# não funciona pq a quantidade de elementos da lista (a serem atríbuidos a nova coluna) é diferente
# da quantidade de linhas do dataframe
data['não funciona'] = [1,2,3]

ValueError: Length of values (3) does not match length of index (106823)

<br/>

Outro exemplo:

In [62]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem noção,coluna a partir de lista
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4

In [58]:
data['PREÇO MÉDIO REVENDA (dólares)'] = data['PREÇO MÉDIO REVENDA'] * 6.0

In [63]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem noção,coluna a partir de lista
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,0.018,2.756,0,2.756,2.756,0,6,2019,DEFAULT,106818
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019,DEFAULT,106819
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,0.065,1.998,0,1.9981,1.9981,0,6,2019,DEFAULT,106820
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019,DEFAULT,106821
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,0.001,2.518,0,2.5175,2.5175,0,6,2019,DEFAULT,106822

**PS:** Obviamente, a lógica correta em converter o preço dos combustíveis em reais para dólares não é considerar uma taxa de câmbio fixa, uma vez que cada preço foi aferido em um momento diferente.

### 1.3.4 Índices

Todo Data Frame possui **índices**, que não são considerado colunas da tabela. Tais índices são comumente **númericos**, de 0 a num_linhas-1, mas também podem ser **textuais (rótulos/labels)**.

In [64]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem noção,coluna a partir de lista
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,0.018,2.756,0,2.756,2.756,0,6,2019,DEFAULT,106818
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019,DEFAULT,106819
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,0.065,1.998,0,1.9981,1.9981,0,6,2019,DEFAULT,106820
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019,DEFAULT,106821
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,0.001,2.518,0,2.5175,2.5175,0,6,2019,DEFAULT,106822

In [65]:
data.index

RangeIndex(start=0, stop=106823, step=1)

Use `list(data.index)` ou `data.index.to_list()` para converter um RangeIndex para uma python list.

#### **Exemplo de Data Frame com Índices Textuais (labels)**

In [9]:
pesquisa_de_satisfacao = pd.DataFrame({
    'bom': [50, 21, 100],
    'ruim': [131, 2, 30],
    'pessimo': [30, 20, 1]
}, index=['XboxOne', 'Playstation4', 'Switch'])

In [10]:
pesquisa_de_satisfacao.head()

              bom  ruim  pessimo
XboxOne        50   131       30
Playstation4   21     2       20
Switch        100    30        1

In [69]:
pesquisa_de_satisfacao.index

Index(['XboxOne', 'Playstation4', 'Switch'], dtype='object')

### 1.4 Selecionando uma ou mais amostras (Indexação)

#### **==>  Index-based selection (seleção baseada em Índices)**
Mostrando linhas específicas de um DataFrame:

`iloc`: seleciona elementos do Dataframe, baseado em seu **índice (número)** --> row-first, column-second

**Selecionando uma amostra/linha:**

In [71]:
# selecionando a linha 1 ==> observação de indice do dataframe
data.iloc[1]

Unnamed: 0                                      1
DATA INICIAL                           2004-05-09
DATA FINAL                             2004-05-15
REGIÃO                               CENTRO OESTE
ESTADO                                      GOIAS
PRODUTO                          ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                  387
UNIDADE DE MEDIDA                            R$/l
PREÇO MÉDIO REVENDA                         1.162
DESVIO PADRÃO REVENDA                       0.114
PREÇO MÍNIMO REVENDA                         0.89
PREÇO MÁXIMO REVENDA                        1.449
MARGEM MÉDIA REVENDA                        0.399
COEF DE VARIAÇÃO REVENDA                    0.098
PREÇO MÉDIO DISTRIBUIÇÃO                    0.763
DESVIO PADRÃO DISTRIBUIÇÃO                  0.088
PREÇO MÍNIMO DISTRIBUIÇÃO                  0.5013
PREÇO MÁXIMO DISTRIBUIÇÃO                    1.05
COEF DE VARIAÇÃO DISTRIBUIÇÃO               0.115
MÊS                                             5
ANO                                          2004
coluna sem noção                          DEFAULT
coluna a partir de lista                        1
Name: 1, dtype: object

**Selecionando múltiplias amostras/linhas:**

In [72]:
# selecionando as linhas de indice de 0 a 5 (incluso)
data.iloc[:6]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem noção,coluna a partir de lista
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4
5,5,2004-05-09,2004-05-15,NORDESTE,BAHIA,ETANOL HIDRATADO,408,R$/l,1.383,0.132,...,0.095,0.957,0.128,0.5686,1.35,0.134,5,2004,DEFAULT,5

In [73]:
# selecionando as linhas de índice de 10 a 15 (incluso)
data.iloc[10:16]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem noção,coluna a partir de lista
10,10,2004-05-09,2004-05-15,NORDESTE,PIAUI,ETANOL HIDRATADO,89,R$/l,1.573,0.134,...,0.085,1.079,0.078,0.8857,1.2499,0.072,5,2004,DEFAULT,10
11,11,2004-05-09,2004-05-15,NORDESTE,RIO GRANDE DO NORTE,ETANOL HIDRATADO,131,R$/l,1.276,0.116,...,0.091,0.944,0.078,0.7119,1.1386,0.083,5,2004,DEFAULT,11
12,12,2004-05-09,2004-05-15,NORDESTE,SERGIPE,ETANOL HIDRATADO,57,R$/l,1.301,0.109,...,0.084,0.98,0.052,0.8267,1.1059,0.053,5,2004,DEFAULT,12
13,13,2004-05-09,2004-05-15,NORTE,ACRE,ETANOL HIDRATADO,33,R$/l,1.805,0.134,...,0.074,1.116,0.171,0.767,1.2992,0.153,5,2004,DEFAULT,13
14,14,2004-05-09,2004-05-15,NORTE,AMAPA,ETANOL HIDRATADO,15,R$/l,1.785,0.035,...,0.020,1.373,0.167,0.8339,1.4912,0.122,5,2004,DEFAULT,14
15,15,2004-05-09,2004-05-15,NORTE,AMAZONAS,ETANOL HIDRATADO,53,R$/l,1.578,0.123,...,0.078,1.137,0.068,0.9515,1.2109,0.06,5,2004,DEFAULT,15

In [75]:
# selecionando as linhas/observações de indice 1,5,10,15
data.iloc[[1, 5, 10, 15]]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem noção,coluna a partir de lista
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1
5,5,2004-05-09,2004-05-15,NORDESTE,BAHIA,ETANOL HIDRATADO,408,R$/l,1.383,0.132,...,0.095,0.957,0.128,0.5686,1.35,0.134,5,2004,DEFAULT,5
10,10,2004-05-09,2004-05-15,NORDESTE,PIAUI,ETANOL HIDRATADO,89,R$/l,1.573,0.134,...,0.085,1.079,0.078,0.8857,1.2499,0.072,5,2004,DEFAULT,10
15,15,2004-05-09,2004-05-15,NORTE,AMAZONAS,ETANOL HIDRATADO,53,R$/l,1.578,0.123,...,0.078,1.137,0.068,0.9515,1.2109,0.06,5,2004,DEFAULT,15

In [76]:
# selecionando as linhas/observações de índice 5,1,15,10
data.iloc[[5, 1, 15, 10]]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem noção,coluna a partir de lista
5,5,2004-05-09,2004-05-15,NORDESTE,BAHIA,ETANOL HIDRATADO,408,R$/l,1.383,0.132,...,0.095,0.957,0.128,0.5686,1.35,0.134,5,2004,DEFAULT,5
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1
15,15,2004-05-09,2004-05-15,NORTE,AMAZONAS,ETANOL HIDRATADO,53,R$/l,1.578,0.123,...,0.078,1.137,0.068,0.9515,1.2109,0.06,5,2004,DEFAULT,15
10,10,2004-05-09,2004-05-15,NORDESTE,PIAUI,ETANOL HIDRATADO,89,R$/l,1.573,0.134,...,0.085,1.079,0.078,0.8857,1.2499,0.072,5,2004,DEFAULT,10

In [77]:
# retornar o valor da linha de indice, coluna 4 ('ESTADO)
data.iloc[1, 4]

'GOIAS'

In [ ]:
# e assim por diante!

#### **==>  Label-based selection (seleção baseadas em Rótulos)**

`loc`: seleciona elementos do Dataframe, baseado em seus **rótulos** --> row-first, column-second

In [11]:
pesquisa_de_satisfacao

              bom  ruim  pessimo
XboxOne        50   131       30
Playstation4   21     2       20
Switch        100    30        1

In [79]:
# retorna a linha de indice 0 (implicito) ==> usando o iloc
pesquisa_de_satisfacao.iloc[0]

bom         50
ruim       131
pessimo     30
Name: XboxOne, dtype: int64

In [80]:
# retorna o valor da linha de índice 0 (implícito) e coluna de índice (implícito) ==> usando o ilocc
pesquisa_de_satisfacao.iloc[0, 1]

np.int64(131)

In [83]:
# retorna a linha cujo o rótulo do índice é 'XboxOne'
pesquisa_de_satisfacao.loc['XboxOne']

bom         50
ruim       131
pessimo     30
Name: XboxOne, dtype: int64

In [12]:
# NÃO FUNCIONA ==> iloc tentando acessar índices com rótulos
pesquisa_de_satisfacao.iloc['XboxOne']

TypeError: Cannot index by location index with a non-integer key

In [87]:
# NÃO FUNCIONA ==> loc tentando acessar índices rotulados com números
pesquisa_de_satisfacao.loc[0]

KeyError: 0

In [91]:
pesquisa_de_satisfacao

              bom  ruim  pessimo
XboxOne        50   131       30
Playstation4   21     2       20
Switch        100    30        1

In [14]:
# retorna o valor da linha 'Playstation4', coluna 'ruim'
pesquisa_de_satisfacao.loc['Playstation4', 'ruim']

np.int64(2)

In [96]:
# selecionando as linhas de índices rotulados, 'XboxOne', 'Switch'
pesquisa_de_satisfacao.loc[['XboxOne', 'Switch']]

         bom  ruim  pessimo
XboxOne   50   131       30
Switch   100    30        1

In [97]:
# retorna todas as linhas e apenas as colunas com rótulos 'bom' e 'péssimo'
pesquisa_de_satisfacao[['bom', 'pessimo']]

              bom  pessimo
XboxOne        50       30
Playstation4   21       20
Switch        100        1

In [98]:
# retorna todas as linhas e apenas as colunas com rótulos 'bom' e 'péssimo'
pesquisa_de_satisfacao.loc[:, ['bom', 'pessimo']]

              bom  pessimo
XboxOne        50       30
Playstation4   21       20
Switch        100        1

In [99]:
data.iloc[1]

Unnamed: 0                                      1
DATA INICIAL                           2004-05-09
DATA FINAL                             2004-05-15
REGIÃO                               CENTRO OESTE
ESTADO                                      GOIAS
PRODUTO                          ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                  387
UNIDADE DE MEDIDA                            R$/l
PREÇO MÉDIO REVENDA                         1.162
DESVIO PADRÃO REVENDA                       0.114
PREÇO MÍNIMO REVENDA                         0.89
PREÇO MÁXIMO REVENDA                        1.449
MARGEM MÉDIA REVENDA                        0.399
COEF DE VARIAÇÃO REVENDA                    0.098
PREÇO MÉDIO DISTRIBUIÇÃO                    0.763
DESVIO PADRÃO DISTRIBUIÇÃO                  0.088
PREÇO MÍNIMO DISTRIBUIÇÃO                  0.5013
PREÇO MÁXIMO DISTRIBUIÇÃO                    1.05
COEF DE VARIAÇÃO DISTRIBUIÇÃO               0.115
MÊS                                             5
ANO                                          2004
coluna sem noção                          DEFAULT
coluna a partir de lista                        1
Name: 1, dtype: object

In [100]:
data.loc[1]

Unnamed: 0                                      1
DATA INICIAL                           2004-05-09
DATA FINAL                             2004-05-15
REGIÃO                               CENTRO OESTE
ESTADO                                      GOIAS
PRODUTO                          ETANOL HIDRATADO
NÚMERO DE POSTOS PESQUISADOS                  387
UNIDADE DE MEDIDA                            R$/l
PREÇO MÉDIO REVENDA                         1.162
DESVIO PADRÃO REVENDA                       0.114
PREÇO MÍNIMO REVENDA                         0.89
PREÇO MÁXIMO REVENDA                        1.449
MARGEM MÉDIA REVENDA                        0.399
COEF DE VARIAÇÃO REVENDA                    0.098
PREÇO MÉDIO DISTRIBUIÇÃO                    0.763
DESVIO PADRÃO DISTRIBUIÇÃO                  0.088
PREÇO MÍNIMO DISTRIBUIÇÃO                  0.5013
PREÇO MÁXIMO DISTRIBUIÇÃO                    1.05
COEF DE VARIAÇÃO DISTRIBUIÇÃO               0.115
MÊS                                             5
ANO                                          2004
coluna sem noção                          DEFAULT
coluna a partir de lista                        1
Name: 1, dtype: object

### 1.5 Selecionando um ou mais atributos (colunas)

In [101]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO,coluna sem noção,coluna a partir de lista
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004,DEFAULT,0
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004,DEFAULT,1
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004,DEFAULT,2
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004,DEFAULT,3
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004,DEFAULT,4

In [102]:
# retornando a coluna/atributo 'ESTADO'
data['ESTADO']

0            DISTRITO FEDERAL
1                       GOIAS
2                 MATO GROSSO
3          MATO GROSSO DO SUL
4                     ALAGOAS
                 ...
106818    RIO GRANDE DO NORTE
106819      RIO GRANDE DO SUL
106820         SANTA CATARINA
106821              SAO PAULO
106822                SERGIPE
Name: ESTADO, Length: 106823, dtype: object

In [103]:
data.ESTADO

0            DISTRITO FEDERAL
1                       GOIAS
2                 MATO GROSSO
3          MATO GROSSO DO SUL
4                     ALAGOAS
                 ...
106818    RIO GRANDE DO NORTE
106819      RIO GRANDE DO SUL
106820         SANTA CATARINA
106821              SAO PAULO
106822                SERGIPE
Name: ESTADO, Length: 106823, dtype: object

In [104]:
data.loc[:, 'ESTADO']

0            DISTRITO FEDERAL
1                       GOIAS
2                 MATO GROSSO
3          MATO GROSSO DO SUL
4                     ALAGOAS
                 ...
106818    RIO GRANDE DO NORTE
106819      RIO GRANDE DO SUL
106820         SANTA CATARINA
106821              SAO PAULO
106822                SERGIPE
Name: ESTADO, Length: 106823, dtype: object

In [ ]:
# a forma de acesso de colunas por .NOME_DA_COLUNA só funciona se
# NOME_DA_COLUNA não possui caracteres inválidos (espaços, acentos, cedilha ...)
#não funciona
#data.DATA INICIAL

In [19]:
# para colunas cujos rótulos possuem caracteres inválidos,
# apenas a seleção via string é válida
data['DATA INICIAL']

0         2004-05-09
1         2004-05-09
2         2004-05-09
3         2004-05-09
4         2004-05-09
             ...
106818    2019-06-23
106819    2019-06-23
106820    2019-06-23
106821    2019-06-23
106822    2019-06-23
Name: DATA INICIAL, Length: 106823, dtype: object

In [18]:
# selecionando múltiplas colunas: 'PRODUTO', 'ESTADO', 'REGIÃO'
data[['PRODUTO', 'ESTADO', 'REGIÃO']]

                 PRODUTO               ESTADO        REGIÃO
0       ETANOL HIDRATADO     DISTRITO FEDERAL  CENTRO OESTE
1       ETANOL HIDRATADO                GOIAS  CENTRO OESTE
2       ETANOL HIDRATADO          MATO GROSSO  CENTRO OESTE
3       ETANOL HIDRATADO   MATO GROSSO DO SUL  CENTRO OESTE
4       ETANOL HIDRATADO              ALAGOAS      NORDESTE
...                  ...                  ...           ...
106818               GNV  RIO GRANDE DO NORTE      NORDESTE
106819               GNV    RIO GRANDE DO SUL           SUL
106820               GNV       SANTA CATARINA           SUL
106821               GNV            SAO PAULO       SUDESTE
106822               GNV              SERGIPE      NORDESTE

[106823 rows x 3 columns]

Como o rótulo da coluna 'DATA INICIAL' **possui espaço**, não é possível acessá-la como método: `data.DATA INICIAL`

### 1.6 Removendo um Atributo (Coluna) do Data Frame

Como vimos anteriormente, o atributo 'Unnamed: 0' parece ser um **ruído** em nosso dataset. Desta maneira, vamos eliminá-lo,

In [17]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

In [108]:
# deleta/remove in-place (pu seja, no proprio dataframe) a coluna de rótulo 'Unnamed: 0'
del data ['Unnamed: 0']

In [16]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,3.690,0.818,0.018,2.756,0,2.756,2.756,0,6,2019
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,3.789,0.95,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,3.499,0.914,0.065,1.998,0,1.9981,1.9981,0,6,2019
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,3.699,1.179,0.001,2.518,0,2.5175,2.5175,0,6,2019

In [22]:
del data['coluna sem noção']
del data['coluna a partir de lista']
del data['PREÇO MÉDIO REVENDA (doláres)']

KeyError: 'coluna sem noção'

In [111]:
data.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

### 1.7 Salvando um Data Frame

Para salvarmos um Data Frame para um **arquivo CSV**, basta usarmos o método `.to_csv`. <br/>
Por padrão, esse método **salva os índices da tabela como uma coluna no CSV**.<br/>
Como no geral tais índices são números de 0 a n-1, não há necessidade para isso (veja que removemos anteriormente a coluna 'Unnamed: 0' que foi justamente esse caso).<br/>
Desta forma, utilize o parâmetro: `index=False`.

Por padrão, o método utilizará a ',' como separador das colunas. Caso queira alterá-lo, utilize o parâmetro `sep`.

In [23]:
data.to_csv('/content/GasPricesinBrazil_2004-2019.csv', index=False)

### 1.8 Seleção Condicional: Filtrando amostras

Durante nossas análise exploratórias, frequentemente filtraremos nossas amostras, a partir de certas **condições**, para fins de análise mais específica. <br/>
Existem algumas maneiras de fazermos tal filtragem. Antes disso, vamos carregar nosso dataset pré-processado que salvamos no item anterior.

In [24]:
data = pd.read_csv('/content/GasPricesinBrazil_2004-2019.csv')

In [114]:
data.head()

,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,1.19,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,0.89,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,1.18,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,1.09,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,1.05,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

In [25]:
# Mostra todos os estados cujos os preços dos combustiveis foram aferidos
# Mais tecnicamente, mostra os valores únicos presentes para o atributo/coluna 'ESTADO'.
data['ESTADO'].unique()

array(['DISTRITO FEDERAL', 'GOIAS', 'MATO GROSSO', 'MATO GROSSO DO SUL',
       'ALAGOAS', 'BAHIA', 'CEARA', 'MARANHAO', 'PARAIBA', 'PERNAMBUCO',
       'PIAUI', 'RIO GRANDE DO NORTE', 'SERGIPE', 'ACRE', 'AMAPA',
       'AMAZONAS', 'PARA', 'RONDONIA', 'RORAIMA', 'TOCANTINS',
       'ESPIRITO SANTO', 'MINAS GERAIS', 'RIO DE JANEIRO', 'SAO PAULO',
       'PARANA', 'RIO GRANDE DO SUL', 'SANTA CATARINA'], dtype=object)

#### **Selecionando apenas os preços dos Postos de São Paulo**

##### **==> Alternativa 1: Seleção Condicional (Comparações diretas)**

O código abaixo retorna uma ***Series ('array') de booleans***, com o número de linhas (amostras) do Data Frame, que informa os registros de preços dos postos do _estado de São Paulo_ (True).

In [26]:
# faz uma comparação elemento a elemento da series, retornando uma serie de booleans
data['ESTADO'] == 'SAO PAULO'

0         False
1         False
2         False
3         False
4         False
          ...
106818    False
106819    False
106820    False
106821     True
106822    False
Name: ESTADO, Length: 106823, dtype: bool

In [27]:
# salvando esta Series de booleans em uma variavel
selecao = data['ESTADO'] == 'SAO PAULO'

In [121]:
selecao

0         False
1         False
2         False
3         False
4         False
          ...
106818    False
106819    False
106820    False
106821     True
106822    False
Name: ESTADO, Length: 106823, dtype: bool

In [28]:
type(selecao)

pandas.core.series.Series

In [29]:
selecao.shape

(106823,)

In [30]:
data.shape

(106823, 21)

Para **filtrarmos** os registros de postos do estado de São Paulo:

In [32]:
data[selecao]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
23,23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,...,1.150,0.198,0.111,0.57,0.056,0.4271,1.4123,0.098,5,2004
50,50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,...,1.150,0.19,0.108,0.576,0.05,0.43204,0.9724,0.087,5,2004
77,77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,...,1.199,0.209,0.086,0.614,0.063,0.34951,1.412,0.103,5,2004
104,104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,...,1.359,0.216,0.085,0.671,0.075,0.3398,1.0669,0.112,5,2004
131,131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,...,1.199,0.205,0.079,0.689,0.072,0.47797,1.0669,0.104,6,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106724,106724,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL,863,R$/l,3.448,0.156,...,4.220,0.401,0.045,3.047,0.097,2.8599,3.3481,0.032,6,2019
106751,106751,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL S10,1277,R$/l,3.574,0.169,...,4.320,0.451,0.047,3.123,0.111,2.885,3.491,0.036,6,2019
106778,106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,...,4.999,0.429,0.044,3.713,0.097,3.52,4.0892,0.026,6,2019
106805,106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,...,89.900,17.679,0.091,49.214,5.071,40.19,72,0.103,6,2019
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019

O resultado é um Data Frame com _apenas_ os registros desejados após a **filtragem**.<br/>
Podemos ainda utilizar o método `loc` para o mesmo fim:

In [33]:
data.loc[selecao]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
23,23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,...,1.150,0.198,0.111,0.57,0.056,0.4271,1.4123,0.098,5,2004
50,50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,...,1.150,0.19,0.108,0.576,0.05,0.43204,0.9724,0.087,5,2004
77,77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,...,1.199,0.209,0.086,0.614,0.063,0.34951,1.412,0.103,5,2004
104,104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,...,1.359,0.216,0.085,0.671,0.075,0.3398,1.0669,0.112,5,2004
131,131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,...,1.199,0.205,0.079,0.689,0.072,0.47797,1.0669,0.104,6,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106724,106724,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL,863,R$/l,3.448,0.156,...,4.220,0.401,0.045,3.047,0.097,2.8599,3.3481,0.032,6,2019
106751,106751,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL S10,1277,R$/l,3.574,0.169,...,4.320,0.451,0.047,3.123,0.111,2.885,3.491,0.036,6,2019
106778,106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,...,4.999,0.429,0.044,3.713,0.097,3.52,4.0892,0.026,6,2019
106805,106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,...,89.900,17.679,0.091,49.214,5.071,40.19,72,0.103,6,2019
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019

##### **==> Alternativa 2: Utilizando o método `query`**

`query` filtra linhas de um DataFrame baseado em uma **query (pergunta)**.

In [34]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

In [35]:
data.query('ESTADO == "SAO PAULO"')

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
23,23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,...,1.150,0.198,0.111,0.57,0.056,0.4271,1.4123,0.098,5,2004
50,50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,...,1.150,0.19,0.108,0.576,0.05,0.43204,0.9724,0.087,5,2004
77,77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,...,1.199,0.209,0.086,0.614,0.063,0.34951,1.412,0.103,5,2004
104,104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,...,1.359,0.216,0.085,0.671,0.075,0.3398,1.0669,0.112,5,2004
131,131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,...,1.199,0.205,0.079,0.689,0.072,0.47797,1.0669,0.104,6,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106724,106724,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL,863,R$/l,3.448,0.156,...,4.220,0.401,0.045,3.047,0.097,2.8599,3.3481,0.032,6,2019
106751,106751,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL S10,1277,R$/l,3.574,0.169,...,4.320,0.451,0.047,3.123,0.111,2.885,3.491,0.036,6,2019
106778,106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,...,4.999,0.429,0.044,3.713,0.097,3.52,4.0892,0.026,6,2019
106805,106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,...,89.900,17.679,0.091,49.214,5.071,40.19,72,0.103,6,2019
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019

<br/>

Uma boa prática é **salvar o Data Frame filtrado em uma nova variável**. Isso simplifica a complexidade do código para futuras análise feita para os postos de São Paulo.

In [36]:
postos_sp = data.query('ESTADO == "SAO PAULO"')

In [37]:
postos_sp

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
23,23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,...,1.150,0.198,0.111,0.57,0.056,0.4271,1.4123,0.098,5,2004
50,50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,...,1.150,0.19,0.108,0.576,0.05,0.43204,0.9724,0.087,5,2004
77,77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,...,1.199,0.209,0.086,0.614,0.063,0.34951,1.412,0.103,5,2004
104,104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,...,1.359,0.216,0.085,0.671,0.075,0.3398,1.0669,0.112,5,2004
131,131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,...,1.199,0.205,0.079,0.689,0.072,0.47797,1.0669,0.104,6,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106724,106724,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL,863,R$/l,3.448,0.156,...,4.220,0.401,0.045,3.047,0.097,2.8599,3.3481,0.032,6,2019
106751,106751,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL S10,1277,R$/l,3.574,0.169,...,4.320,0.451,0.047,3.123,0.111,2.885,3.491,0.036,6,2019
106778,106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,...,4.999,0.429,0.044,3.713,0.097,3.52,4.0892,0.026,6,2019
106805,106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,...,89.900,17.679,0.091,49.214,5.071,40.19,72,0.103,6,2019
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019

In [38]:
type(postos_sp)

pandas.core.frame.DataFrame

In [39]:
postos_sp.shape

(4263, 21)

In [40]:
postos_sp

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
23,23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,...,1.150,0.198,0.111,0.57,0.056,0.4271,1.4123,0.098,5,2004
50,50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,...,1.150,0.19,0.108,0.576,0.05,0.43204,0.9724,0.087,5,2004
77,77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,...,1.199,0.209,0.086,0.614,0.063,0.34951,1.412,0.103,5,2004
104,104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,...,1.359,0.216,0.085,0.671,0.075,0.3398,1.0669,0.112,5,2004
131,131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,...,1.199,0.205,0.079,0.689,0.072,0.47797,1.0669,0.104,6,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106724,106724,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL,863,R$/l,3.448,0.156,...,4.220,0.401,0.045,3.047,0.097,2.8599,3.3481,0.032,6,2019
106751,106751,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL S10,1277,R$/l,3.574,0.169,...,4.320,0.451,0.047,3.123,0.111,2.885,3.491,0.036,6,2019
106778,106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,...,4.999,0.429,0.044,3.713,0.097,3.52,4.0892,0.026,6,2019
106805,106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,...,89.900,17.679,0.091,49.214,5.071,40.19,72,0.103,6,2019
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019

In [41]:
postos_sp.reset_index()

,index,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,23,23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,...,1.150,0.198,0.111,0.57,0.056,0.4271,1.4123,0.098,5,2004
1,50,50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,...,1.150,0.19,0.108,0.576,0.05,0.43204,0.9724,0.087,5,2004
2,77,77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,...,1.199,0.209,0.086,0.614,0.063,0.34951,1.412,0.103,5,2004
3,104,104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,...,1.359,0.216,0.085,0.671,0.075,0.3398,1.0669,0.112,5,2004
4,131,131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,...,1.199,0.205,0.079,0.689,0.072,0.47797,1.0669,0.104,6,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4258,106724,106724,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL,863,R$/l,3.448,...,4.220,0.401,0.045,3.047,0.097,2.8599,3.3481,0.032,6,2019
4259,106751,106751,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL S10,1277,R$/l,3.574,...,4.320,0.451,0.047,3.123,0.111,2.885,3.491,0.036,6,2019
4260,106778,106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,...,4.999,0.429,0.044,3.713,0.097,3.52,4.0892,0.026,6,2019
4261,106805,106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,...,89.900,17.679,0.091,49.214,5.071,40.19,72,0.103,6,2019
4262,106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019

In [42]:
postos_sp.reset_index(drop=True)

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,...,1.150,0.198,0.111,0.57,0.056,0.4271,1.4123,0.098,5,2004
1,50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,...,1.150,0.19,0.108,0.576,0.05,0.43204,0.9724,0.087,5,2004
2,77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,...,1.199,0.209,0.086,0.614,0.063,0.34951,1.412,0.103,5,2004
3,104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,...,1.359,0.216,0.085,0.671,0.075,0.3398,1.0669,0.112,5,2004
4,131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,...,1.199,0.205,0.079,0.689,0.072,0.47797,1.0669,0.104,6,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4258,106724,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL,863,R$/l,3.448,0.156,...,4.220,0.401,0.045,3.047,0.097,2.8599,3.3481,0.032,6,2019
4259,106751,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL S10,1277,R$/l,3.574,0.169,...,4.320,0.451,0.047,3.123,0.111,2.885,3.491,0.036,6,2019
4260,106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,...,4.999,0.429,0.044,3.713,0.097,3.52,4.0892,0.026,6,2019
4261,106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,...,89.900,17.679,0.091,49.214,5.071,40.19,72,0.103,6,2019
4262,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019

In [43]:
# ainda não foi alterado, precisamos usar o atributo/parâmetro inplace=True
postos_sp

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
23,23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,...,1.150,0.198,0.111,0.57,0.056,0.4271,1.4123,0.098,5,2004
50,50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,...,1.150,0.19,0.108,0.576,0.05,0.43204,0.9724,0.087,5,2004
77,77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,...,1.199,0.209,0.086,0.614,0.063,0.34951,1.412,0.103,5,2004
104,104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,...,1.359,0.216,0.085,0.671,0.075,0.3398,1.0669,0.112,5,2004
131,131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,...,1.199,0.205,0.079,0.689,0.072,0.47797,1.0669,0.104,6,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106724,106724,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL,863,R$/l,3.448,0.156,...,4.220,0.401,0.045,3.047,0.097,2.8599,3.3481,0.032,6,2019
106751,106751,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL S10,1277,R$/l,3.574,0.169,...,4.320,0.451,0.047,3.123,0.111,2.885,3.491,0.036,6,2019
106778,106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,...,4.999,0.429,0.044,3.713,0.097,3.52,4.0892,0.026,6,2019
106805,106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,...,89.900,17.679,0.091,49.214,5.071,40.19,72,0.103,6,2019
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019

In [44]:
postos_sp.reset_index(drop=True, inplace=True)

In [45]:
postos_sp

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,...,1.150,0.198,0.111,0.57,0.056,0.4271,1.4123,0.098,5,2004
1,50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,...,1.150,0.19,0.108,0.576,0.05,0.43204,0.9724,0.087,5,2004
2,77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,...,1.199,0.209,0.086,0.614,0.063,0.34951,1.412,0.103,5,2004
3,104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,...,1.359,0.216,0.085,0.671,0.075,0.3398,1.0669,0.112,5,2004
4,131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,...,1.199,0.205,0.079,0.689,0.072,0.47797,1.0669,0.104,6,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4258,106724,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL,863,R$/l,3.448,0.156,...,4.220,0.401,0.045,3.047,0.097,2.8599,3.3481,0.032,6,2019
4259,106751,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL S10,1277,R$/l,3.574,0.169,...,4.320,0.451,0.047,3.123,0.111,2.885,3.491,0.036,6,2019
4260,106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,...,4.999,0.429,0.044,3.713,0.097,3.52,4.0892,0.026,6,2019
4261,106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,...,89.900,17.679,0.091,49.214,5.071,40.19,72,0.103,6,2019
4262,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019

In [46]:
# ALTERNATIVA MUITO COMUM
postos_sp = data.query('ESTADO == "SAO PAULO"').reset_index(drop=True)

In [47]:
postos_sp

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,...,1.150,0.198,0.111,0.57,0.056,0.4271,1.4123,0.098,5,2004
1,50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,...,1.150,0.19,0.108,0.576,0.05,0.43204,0.9724,0.087,5,2004
2,77,2004-05-23,2004-05-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4077,R$/l,0.823,0.071,...,1.199,0.209,0.086,0.614,0.063,0.34951,1.412,0.103,5,2004
3,104,2004-05-30,2004-06-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4073,R$/l,0.887,0.075,...,1.359,0.216,0.085,0.671,0.075,0.3398,1.0669,0.112,5,2004
4,131,2004-06-06,2004-06-12,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4082,R$/l,0.894,0.071,...,1.199,0.205,0.079,0.689,0.072,0.47797,1.0669,0.104,6,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4258,106724,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL,863,R$/l,3.448,0.156,...,4.220,0.401,0.045,3.047,0.097,2.8599,3.3481,0.032,6,2019
4259,106751,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,ÓLEO DIESEL S10,1277,R$/l,3.574,0.169,...,4.320,0.451,0.047,3.123,0.111,2.885,3.491,0.036,6,2019
4260,106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,...,4.999,0.429,0.044,3.713,0.097,3.52,4.0892,0.026,6,2019
4261,106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,...,89.900,17.679,0.091,49.214,5.071,40.19,72,0.103,6,2019
4262,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019

#### **Selecionando registros de postos do Rio de Janeiro com Preços acima de 2 reais**

In [48]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

In [49]:
data['ESTADO'] == 'RIO DE JANEIRO'

0         False
1         False
2         False
3         False
4         False
          ...
106818    False
106819    False
106820    False
106821    False
106822    False
Name: ESTADO, Length: 106823, dtype: bool

In [50]:
data['PREÇO MÉDIO REVENDA'] > 2.0

0         False
1         False
2         False
3         False
4         False
          ...
106818     True
106819     True
106820     True
106821     True
106822     True
Name: PREÇO MÉDIO REVENDA, Length: 106823, dtype: bool

In [52]:
selecao = (data['ESTADO'] == 'RIO DE JANEIRO') & (data['PREÇO MÉDIO REVENDA']) > 2.0
selecao

0         False
1         False
2         False
3         False
4         False
          ...
106818    False
106819    False
106820    False
106821    False
106822    False
Length: 106823, dtype: bool

Note que o resultado da seleção continua sendo uma _Series de booleans_ com o _mesmo número de linhas/amostras do DataFrame_, de modo que cada linha possuirá um valor booleano indicando se o posto é do Rio de Janeiro e o preço aferido do combustível é maior que 2 reais (True) ou não.

O símbolo **&** significa **AND** na comparação. Essa nomenclatura do python/pandas é diferente das nomenclaturas tradicionais (&&). <br/>
Similarmente:
- **|** representa o **OR** (não é ||)
- **~** representa o **NOT** (não é !)

In [53]:
data[selecao]

Empty DataFrame
Columns: [Unnamed: 0, DATA INICIAL, DATA FINAL, REGIÃO, ESTADO, PRODUTO, NÚMERO DE POSTOS PESQUISADOS, UNIDADE DE MEDIDA, PREÇO MÉDIO REVENDA, DESVIO PADRÃO REVENDA, PREÇO MÍNIMO REVENDA, PREÇO MÁXIMO REVENDA, MARGEM MÉDIA REVENDA, COEF DE VARIAÇÃO REVENDA, PREÇO MÉDIO DISTRIBUIÇÃO, DESVIO PADRÃO DISTRIBUIÇÃO, PREÇO MÍNIMO DISTRIBUIÇÃO, PREÇO MÁXIMO DISTRIBUIÇÃO, COEF DE VARIAÇÃO DISTRIBUIÇÃO, MÊS, ANO]
Index: []

[0 rows x 21 columns]

Alternativamente, poderíamos usar o método `query` para fazermos tal seleção. Porém, isso não é possível especificamente para esse caso, pois o rótulo da coluna 'PREÇO MÉDIO REVENDA' possui caracteres inválidos para o método (cedilha, acentos)

In [54]:
# Não funciona
# data.query('ESTADO=="RIO DE JANEIRO" and PREÇO MÉDIO REVENDA > 2')

In [55]:
data.query('ESTADO == "RIO DE JANEIRO" or ESTADO == "SAO PAULO"')

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
22,22,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,952,R$/l,1.098,0.154,...,1.890,0.312,0.140,0.786,0.173,0.326,1.263,0.22,5,2004
23,23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,...,1.150,0.198,0.111,0.57,0.056,0.4271,1.4123,0.098,5,2004
49,49,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,948,R$/l,1.092,0.157,...,1.499,0.284,0.144,0.808,0.175,0.3257,1.2921,0.217,5,2004
50,50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,...,1.150,0.19,0.108,0.576,0.05,0.43204,0.9724,0.087,5,2004
76,76,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,973,R$/l,1.103,0.140,...,1.589,0.281,0.127,0.822,0.166,0.38909,1.1859,0.202,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106778,106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,...,4.999,0.429,0.044,3.713,0.097,3.52,4.0892,0.026,6,2019
106799,106799,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GLP,221,R$/13Kg,65.010,5.812,...,79.000,17.475,0.089,47.535,3.934,39,58.2,0.083,6,2019
106805,106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,...,89.900,17.679,0.091,49.214,5.071,40.19,72,0.103,6,2019
106817,106817,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GNV,124,R$/m3,3.111,0.260,...,3.799,0.707,0.084,2.404,0.174,2.126,2.7909,0.072,6,2019
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019

**Aprofundando mais ainda**

A primeira comparação `(data['ESTADO'] == 'RIO DE JANEIRO')` checa, linha a linha (amostra a amostra) do DataFrame, quais são aquelas cujo o estado é RIO DE JANEIRO. Nenhuma averiguação de preços é feita nesse momento. Como resultado, temos uma Series de booleans que responde **apenas** a essa "pergunta" feita.

A segunda comparação `(data['PREÇO MÉDIO REVENDA'] > 2)` checa, linha a linha (amostra a amostra) do DataFrame, quais são os registro cujo preço do combustível é maior que 2 reais. Note que essa comparação checará os postos de **TODOS os estados**. Como resultado, temos uma Series de booleans que responde **apenas** a essa "pergunta" feita.

Por fim, as duas "perguntas" são unidas pelo AND (&) que retorna a "pergunta completa" que fizemos.

Alguns podem argumentar que tal abordagem é **ineficiente**, uma vez que, para cada condição ("pergunta"), estamos varrendo todas as linhas do DataFrame. <br/>
O Pandas _tenta otimizar_ isso ao máximo por de trás dos panos. Mas, de fato, de tivermos um dataset **muito grande** (centenas de milhares de linhas), tal abordagem se tornará _lenta_.

Assim, poderíamos fazer filtragem com múltiplos condicionais em partes:

In [56]:
selecao_1 = data['ESTADO'] == 'RIO DE JANEIRO'
postos_rj = data[selecao_1]
postos_rj

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
22,22,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,952,R$/l,1.098,0.154,...,1.890,0.312,0.140,0.786,0.173,0.326,1.263,0.22,5,2004
49,49,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,948,R$/l,1.092,0.157,...,1.499,0.284,0.144,0.808,0.175,0.3257,1.2921,0.217,5,2004
76,76,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,973,R$/l,1.103,0.140,...,1.589,0.281,0.127,0.822,0.166,0.38909,1.1859,0.202,5,2004
103,103,2004-05-30,2004-06-05,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,955,R$/l,1.149,0.156,...,1.599,0.3,0.136,0.849,0.188,0.3453,1.3667,0.221,5,2004
130,130,2004-06-06,2004-06-12,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,966,R$/l,1.165,0.154,...,1.599,0.254,0.132,0.911,0.198,0.4,1.3667,0.217,6,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106718,106718,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,ÓLEO DIESEL,212,R$/l,3.569,0.166,...,4.059,0.467,0.047,3.102,0.119,2.886,3.5162,0.038,6,2019
106745,106745,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,ÓLEO DIESEL S10,335,R$/l,3.697,0.187,...,4.389,0.5,0.051,3.197,0.127,2.9772,3.5388,0.04,6,2019
106772,106772,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,422,R$/l,4.928,0.165,...,5.859,0.538,0.033,4.39,0.097,4.2,4.618,0.022,6,2019
106799,106799,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GLP,221,R$/13Kg,65.010,5.812,...,79.000,17.475,0.089,47.535,3.934,39,58.2,0.083,6,2019
106817,106817,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GNV,124,R$/m3,3.111,0.260,...,3.799,0.707,0.084,2.404,0.174,2.126,2.7909,0.072,6,2019

In [57]:
selecao_2 = postos_rj['PREÇO MÉDIO REVENDA'] > 2.0
selecao_2

22        False
49        False
76        False
103       False
130       False
          ...
106718     True
106745     True
106772     True
106799     True
106817     True
Name: PREÇO MÉDIO REVENDA, Length: 4263, dtype: bool

In [58]:
postos_rj_preco_maior_que_2 = postos_rj[selecao_2]
postos_rj_preco_maior_que_2

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
2501,2501,2006-02-26,2006-03-04,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,881,R$/l,2.028,0.148,...,2.550,0.222,0.073,1.806,0.11,1.31,2.1358,0.061,2,2006
2528,2528,2006-03-05,2006-03-11,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,889,R$/l,2.125,0.149,...,2.550,0.286,0.070,1.839,0.117,1.438,2.2801,0.064,3,2006
2555,2555,2006-03-12,2006-03-18,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,902,R$/l,2.163,0.138,...,2.599,0.268,0.064,1.895,0.134,1.43,2.3454,0.071,3,2006
2582,2582,2006-03-19,2006-03-25,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,898,R$/l,2.166,0.146,...,2.568,0.231,0.067,1.935,0.14,1.438,2.2925,0.072,3,2006
2609,2609,2006-03-26,2006-04-01,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,890,R$/l,2.172,0.143,...,2.550,0.209,0.066,1.963,0.133,1.438,2.2513,0.068,3,2006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106718,106718,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,ÓLEO DIESEL,212,R$/l,3.569,0.166,...,4.059,0.467,0.047,3.102,0.119,2.886,3.5162,0.038,6,2019
106745,106745,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,ÓLEO DIESEL S10,335,R$/l,3.697,0.187,...,4.389,0.5,0.051,3.197,0.127,2.9772,3.5388,0.04,6,2019
106772,106772,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,422,R$/l,4.928,0.165,...,5.859,0.538,0.033,4.39,0.097,4.2,4.618,0.022,6,2019
106799,106799,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GLP,221,R$/13Kg,65.010,5.812,...,79.000,17.475,0.089,47.535,3.934,39,58.2,0.083,6,2019
106817,106817,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GNV,124,R$/m3,3.111,0.260,...,3.799,0.707,0.084,2.404,0.174,2.126,2.7909,0.072,6,2019

#### **Selecionando registros de postos de São Paulo ou do Rio de Janeiro com Gasolina Comum acima de 2 reais**

Podemos fazer a solução do "jeito mais lento", percorrendo o DataFrame inteiro _múltiplas vezes_:

In [59]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

In [60]:
selecao_1 = (data['ESTADO'] == 'SAO PAULO') | (data['ESTADO'] == 'RIO DE JANEIRO')
selecao_2 = (data['PRODUTO'] == 'GASOLINA COMUM')
selecao_3 = (data['PREÇO MÉDIO REVENDA'] > 2)

selecao_final = selecao_1 & selecao_2 & selecao_3

In [61]:
data_filtrado = data[selecao_final]
data_filtrado

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
12086,12086,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1071,R$/l,2.045,0.109,...,2.599,0.254,0.053,1.791,0.047,1.6363,1.9594,0.026,5,2004
12113,12113,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1055,R$/l,2.040,0.113,...,2.599,0.252,0.055,1.788,0.049,1.5943,1.99651,0.027,5,2004
12140,12140,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1091,R$/l,2.042,0.108,...,2.599,0.252,0.053,1.79,0.046,1.63596,2.2137,0.026,5,2004
12167,12167,2004-05-30,2004-06-05,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1055,R$/l,2.053,0.111,...,2.599,0.251,0.054,1.802,0.055,1.64,2.21425,0.031,5,2004
12194,12194,2004-06-06,2004-06-12,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1091,R$/l,2.063,0.107,...,2.599,0.247,0.052,1.816,0.054,1.64,2.32425,0.03,6,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106479,106479,2019-06-09,2019-06-15,SUDESTE,SAO PAULO,GASOLINA COMUM,1643,R$/l,4.210,0.177,...,4.992,0.425,0.042,3.785,0.096,3.52,4.1007,0.025,6,2019
106623,106623,2019-06-16,2019-06-22,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,418,R$/l,4.927,0.160,...,5.859,0.544,0.032,4.383,0.1,4.1972,4.6239,0.023,6,2019
106629,106629,2019-06-16,2019-06-22,SUDESTE,SAO PAULO,GASOLINA COMUM,1635,R$/l,4.168,0.177,...,5.199,0.443,0.042,3.725,0.096,3.502,4.0892,0.026,6,2019
106772,106772,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,422,R$/l,4.928,0.165,...,5.859,0.538,0.033,4.39,0.097,4.2,4.618,0.022,6,2019
106778,106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,...,4.999,0.429,0.044,3.713,0.097,3.52,4.0892,0.026,6,2019

In [62]:
print(data_filtrado['ESTADO'].unique())
print(data_filtrado['PRODUTO'].unique())

['RIO DE JANEIRO' 'SAO PAULO']
['GASOLINA COMUM']

<br/>

Alternativamente:

In [63]:
selecao_1 = (data['ESTADO'] == 'SAO PAULO') | (data['ESTADO'] == 'RIO DE JANEIRO')
postos_sp_rj = data[selecao_1]

#apenas registros de postos dos estados de SP e RJ
postos_sp_rj

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
22,22,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,952,R$/l,1.098,0.154,...,1.890,0.312,0.140,0.786,0.173,0.326,1.263,0.22,5,2004
23,23,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4047,R$/l,0.768,0.085,...,1.150,0.198,0.111,0.57,0.056,0.4271,1.4123,0.098,5,2004
49,49,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,948,R$/l,1.092,0.157,...,1.499,0.284,0.144,0.808,0.175,0.3257,1.2921,0.217,5,2004
50,50,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,ETANOL HIDRATADO,4066,R$/l,0.766,0.083,...,1.150,0.19,0.108,0.576,0.05,0.43204,0.9724,0.087,5,2004
76,76,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,ETANOL HIDRATADO,973,R$/l,1.103,0.140,...,1.589,0.281,0.127,0.822,0.166,0.38909,1.1859,0.202,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106778,106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,...,4.999,0.429,0.044,3.713,0.097,3.52,4.0892,0.026,6,2019
106799,106799,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GLP,221,R$/13Kg,65.010,5.812,...,79.000,17.475,0.089,47.535,3.934,39,58.2,0.083,6,2019
106805,106805,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GLP,1017,R$/13Kg,66.893,6.100,...,89.900,17.679,0.091,49.214,5.071,40.19,72,0.103,6,2019
106817,106817,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GNV,124,R$/m3,3.111,0.260,...,3.799,0.707,0.084,2.404,0.174,2.126,2.7909,0.072,6,2019
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019

In [64]:
selecao_2 = (postos_sp_rj ['PRODUTO'] == 'GASOLINA COMUM')
postos_sp_rj_gasolina = postos_sp_rj[selecao_2]
# apenas registros de postos dos estados de SP e RJ com GASOLINA COMUM
postos_sp_rj_gasolina

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
12086,12086,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1071,R$/l,2.045,0.109,...,2.599,0.254,0.053,1.791,0.047,1.6363,1.9594,0.026,5,2004
12087,12087,2004-05-09,2004-05-15,SUDESTE,SAO PAULO,GASOLINA COMUM,4107,R$/l,1.891,0.101,...,2.399,0.235,0.053,1.656,0.064,1.38,1.944,0.039,5,2004
12113,12113,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1055,R$/l,2.040,0.113,...,2.599,0.252,0.055,1.788,0.049,1.5943,1.99651,0.027,5,2004
12114,12114,2004-05-16,2004-05-22,SUDESTE,SAO PAULO,GASOLINA COMUM,4133,R$/l,1.888,0.101,...,2.220,0.233,0.053,1.655,0.063,1.38,1.9319,0.038,5,2004
12140,12140,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1091,R$/l,2.042,0.108,...,2.599,0.252,0.053,1.79,0.046,1.63596,2.2137,0.026,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106479,106479,2019-06-09,2019-06-15,SUDESTE,SAO PAULO,GASOLINA COMUM,1643,R$/l,4.210,0.177,...,4.992,0.425,0.042,3.785,0.096,3.52,4.1007,0.025,6,2019
106623,106623,2019-06-16,2019-06-22,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,418,R$/l,4.927,0.160,...,5.859,0.544,0.032,4.383,0.1,4.1972,4.6239,0.023,6,2019
106629,106629,2019-06-16,2019-06-22,SUDESTE,SAO PAULO,GASOLINA COMUM,1635,R$/l,4.168,0.177,...,5.199,0.443,0.042,3.725,0.096,3.502,4.0892,0.026,6,2019
106772,106772,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,422,R$/l,4.928,0.165,...,5.859,0.538,0.033,4.39,0.097,4.2,4.618,0.022,6,2019
106778,106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,...,4.999,0.429,0.044,3.713,0.097,3.52,4.0892,0.026,6,2019

In [65]:
selecao_3 = (postos_sp_rj_gasolina['PREÇO MÉDIO REVENDA'] > 2)
postos_sp_rj_gasolina_preco_maior_que_2 = postos_sp_rj_gasolina[selecao_3]
postos_sp_rj_gasolina_preco_maior_que_2

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
12086,12086,2004-05-09,2004-05-15,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1071,R$/l,2.045,0.109,...,2.599,0.254,0.053,1.791,0.047,1.6363,1.9594,0.026,5,2004
12113,12113,2004-05-16,2004-05-22,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1055,R$/l,2.040,0.113,...,2.599,0.252,0.055,1.788,0.049,1.5943,1.99651,0.027,5,2004
12140,12140,2004-05-23,2004-05-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1091,R$/l,2.042,0.108,...,2.599,0.252,0.053,1.79,0.046,1.63596,2.2137,0.026,5,2004
12167,12167,2004-05-30,2004-06-05,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1055,R$/l,2.053,0.111,...,2.599,0.251,0.054,1.802,0.055,1.64,2.21425,0.031,5,2004
12194,12194,2004-06-06,2004-06-12,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,1091,R$/l,2.063,0.107,...,2.599,0.247,0.052,1.816,0.054,1.64,2.32425,0.03,6,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106479,106479,2019-06-09,2019-06-15,SUDESTE,SAO PAULO,GASOLINA COMUM,1643,R$/l,4.210,0.177,...,4.992,0.425,0.042,3.785,0.096,3.52,4.1007,0.025,6,2019
106623,106623,2019-06-16,2019-06-22,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,418,R$/l,4.927,0.160,...,5.859,0.544,0.032,4.383,0.1,4.1972,4.6239,0.023,6,2019
106629,106629,2019-06-16,2019-06-22,SUDESTE,SAO PAULO,GASOLINA COMUM,1635,R$/l,4.168,0.177,...,5.199,0.443,0.042,3.725,0.096,3.502,4.0892,0.026,6,2019
106772,106772,2019-06-23,2019-06-29,SUDESTE,RIO DE JANEIRO,GASOLINA COMUM,422,R$/l,4.928,0.165,...,5.859,0.538,0.033,4.39,0.097,4.2,4.618,0.022,6,2019
106778,106778,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.142,0.183,...,4.999,0.429,0.044,3.713,0.097,3.52,4.0892,0.026,6,2019

#### **Selecionando registros dos anos de 2008, 2010 e 2012**

In [66]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

**ALTERNATIVA 1**

In [67]:
selecao = (data['ANO'] == 2008) | (data['ANO'] == 2010) | (data['ANO'] == 2012)
data[selecao]['ANO']

5098     2008
5099     2008
5100     2008
5101     2008
5102     2008
         ...
55754    2012
55755    2012
55756    2012
55757    2012
55758    2012
Name: ANO, Length: 19576, dtype: int64

**ALTERNATIVA 2**

In [68]:
lista_de_anos = [2008, 2010, 2012]

In [69]:
selecao = data['ANO'].isin(lista_de_anos) # retorna uma Series de booleanos
data[selecao]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
5098,5098,2008-01-06,2008-01-12,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,80,R$/l,1.806,0.082,...,1.950,0.29,0.045,1.516,0.061,1.3892,1.6157,0.04,1,2008
5099,5099,2008-01-06,2008-01-12,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,255,R$/l,1.616,0.100,...,1.899,0.293,0.062,1.323,0.05,1.2242,1.6173,0.038,1,2008
5100,5100,2008-01-06,2008-01-12,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,142,R$/l,1.581,0.095,...,1.850,0.278,0.060,1.303,0.073,1.14,1.45,0.056,1,2008
5101,5101,2008-01-06,2008-01-12,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,133,R$/l,1.831,0.046,...,1.910,0.382,0.025,1.449,0.044,1.3247,1.5514,0.03,1,2008
5102,5102,2008-01-06,2008-01-12,NORDESTE,ALAGOAS,ETANOL HIDRATADO,97,R$/l,1.699,0.098,...,1.999,0.199,0.058,1.5,0.062,1.39,1.7689,0.041,1,2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55754,55754,2012-12-30,2013-01-05,NORDESTE,RIO GRANDE DO NORTE,GNV,17,R$/m3,1.891,0.015,...,1.900,0.466,0.008,1.425,0.098,1.2657,1.4789,0.069,12,2012
55755,55755,2012-12-30,2013-01-05,SUL,RIO GRANDE DO SUL,GNV,34,R$/m3,1.980,0.040,...,2.140,0.566,0.020,1.414,0.028,1.3997,1.4608,0.02,12,2012
55756,55756,2012-12-30,2013-01-05,SUL,SANTA CATARINA,GNV,41,R$/m3,2.003,0.034,...,2.099,-,0.017,-,-,-,-,-,12,2012
55757,55757,2012-12-30,2013-01-05,SUDESTE,SAO PAULO,GNV,82,R$/m3,1.598,0.199,...,2.599,0.397,0.125,1.201,0.182,0.8354,1.535,0.152,12,2012
55758,55758,2012-12-30,2013-01-05,NORDESTE,SERGIPE,GNV,11,R$/m3,1.847,0.033,...,1.899,0.504,0.018,1.343,0.178,1.1253,1.543,0.133,12,2012

In [70]:
# ** ALTERNATIVA 3 **
lista_de_anos

[2008, 2010, 2012]

In [71]:
data.query('ANO in @lista_de_anos')

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
5098,5098,2008-01-06,2008-01-12,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,80,R$/l,1.806,0.082,...,1.950,0.29,0.045,1.516,0.061,1.3892,1.6157,0.04,1,2008
5099,5099,2008-01-06,2008-01-12,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,255,R$/l,1.616,0.100,...,1.899,0.293,0.062,1.323,0.05,1.2242,1.6173,0.038,1,2008
5100,5100,2008-01-06,2008-01-12,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,142,R$/l,1.581,0.095,...,1.850,0.278,0.060,1.303,0.073,1.14,1.45,0.056,1,2008
5101,5101,2008-01-06,2008-01-12,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,133,R$/l,1.831,0.046,...,1.910,0.382,0.025,1.449,0.044,1.3247,1.5514,0.03,1,2008
5102,5102,2008-01-06,2008-01-12,NORDESTE,ALAGOAS,ETANOL HIDRATADO,97,R$/l,1.699,0.098,...,1.999,0.199,0.058,1.5,0.062,1.39,1.7689,0.041,1,2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55754,55754,2012-12-30,2013-01-05,NORDESTE,RIO GRANDE DO NORTE,GNV,17,R$/m3,1.891,0.015,...,1.900,0.466,0.008,1.425,0.098,1.2657,1.4789,0.069,12,2012
55755,55755,2012-12-30,2013-01-05,SUL,RIO GRANDE DO SUL,GNV,34,R$/m3,1.980,0.040,...,2.140,0.566,0.020,1.414,0.028,1.3997,1.4608,0.02,12,2012
55756,55756,2012-12-30,2013-01-05,SUL,SANTA CATARINA,GNV,41,R$/m3,2.003,0.034,...,2.099,-,0.017,-,-,-,-,-,12,2012
55757,55757,2012-12-30,2013-01-05,SUDESTE,SAO PAULO,GNV,82,R$/m3,1.598,0.199,...,2.599,0.397,0.125,1.201,0.182,0.8354,1.535,0.152,12,2012
55758,55758,2012-12-30,2013-01-05,NORDESTE,SERGIPE,GNV,11,R$/m3,1.847,0.033,...,1.899,0.504,0.018,1.343,0.178,1.1253,1.543,0.133,12,2012

### **Iterando com DataFrames**

#### For-each `DataFrame.iterrows()` (LENTO ==> apenas indicado para iterar pequenos conjunto de dados)

In [72]:
data.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004

In [73]:
for index, row in data.head(10).iterrows():
  print(f'indice {index} ==> {row["ESTADO"]}')

indice 0 ==> DISTRITO FEDERAL
indice 1 ==> GOIAS
indice 2 ==> MATO GROSSO
indice 3 ==> MATO GROSSO DO SUL
indice 4 ==> ALAGOAS
indice 5 ==> BAHIA
indice 6 ==> CEARA
indice 7 ==> MARANHAO
indice 8 ==> PARAIBA
indice 9 ==> PERNAMBUCO

<h2>2. Preparação dos dados</h2>
<hr/>

In [74]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,3.690,0.818,0.018,2.756,0,2.756,2.756,0,6,2019
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,3.789,0.95,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,3.499,0.914,0.065,1.998,0,1.9981,1.9981,0,6,2019
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,3.699,1.179,0.001,2.518,0,2.5175,2.5175,0,6,2019

### 2.1 Removendo amostras com valores vazios (null / nan) no dataset

In [75]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 21 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Unnamed: 0                     106823 non-null  int64
 1   DATA INICIAL                   106823 non-null  object
 2   DATA FINAL                     106823 non-null  object
 3   REGIÃO                         106823 non-null  object
 4   ESTADO                         106823 non-null  object
 5   PRODUTO                        106823 non-null  object
 6   NÚMERO DE POSTOS PESQUISADOS   106823 non-null  int64
 7   UNIDADE DE MEDIDA              106823 non-null  object
 8   PREÇO MÉDIO REVENDA            106823 non-null  float64
 9   DESVIO PADRÃO REVENDA          106823 non-null  float64
 10  PREÇO MÍNIMO REVENDA           106823 non-null  float64
 11  PREÇO MÁXIMO REVENDA           106823 non-null  float64
 12  MARGEM MÉDIA REVENDA           106823 non-null  object
 13  COEF DE VARIAÇÃO REVENDA       106823 non-null  float64
 14  PREÇO MÉDIO DISTRIBUIÇÃO       106823 non-null  object
 15  DESVIO PADRÃO DISTRIBUIÇÃO     106823 non-null  object
 16  PREÇO MÍNIMO DISTRIBUIÇÃO      106823 non-null  object
 17  PREÇO MÁXIMO DISTRIBUIÇÃO      106823 non-null  object
 18  COEF DE VARIAÇÃO DISTRIBUIÇÃO  106823 non-null  object
 19  MÊS                            106823 non-null  int64
 20  ANO                            106823 non-null  int64
dtypes: float64(5), int64(4), object(12)
memory usage: 17.1+ MB

De um total de 106823 observações, **não há valores null** / nan para nenhum atributo. Mas, veremos que não é bem assim neste caso específico.<br/><br/>

### 2.2 Conversão de tipos de atributos

O pandas automaticamente reconhece os tipos de dados de cada coluna. <br/>
Porém, existem alguns atributos que estão com seus tipos errados: P. ex., "PREÇO MÉDIO DISTRIBUIÇÃO" deveria ser ```float64``` e não ```object```.<br/>
Nestes casos, muito provavelmente algumas amostras têm um string ao invés de um número para tais atributos. <br/>

Os atributos *"DATA INICIAL"* e *"DATA FINAL"* deveriam ser do tipo `datetime`.

Em outros casos, alguns **atributos categóricos** são ```objects```, mas poderiam ter o tipo ```category```, que é um tipo especial do pandas. <br/>
Este tipo é necessário para se utilizar algumas funções específicas do pandas. <br/>
**Não** converteremos para este tipo por ora.

In [76]:
data_pre = data.copy()

#### **Datas**
Como os atributos de data do datset já estão em um formato de data aceitável (YYYY-MM-DD), não precisamos forçar nenhuma conversão nesse sentido.

In [77]:
data_pre['DATA INICIAL'] = pd.to_datetime(data_pre['DATA INICIAL'])
data_pre['DATA FINAL'] = pd.to_datetime(data_pre['DATA FINAL' ])

In [78]:
data_pre.info

<bound method DataFrame.info of         Unnamed: 0 DATA INICIAL DATA FINAL        REGIÃO               ESTADO  \
0                0   2004-05-09 2004-05-15  CENTRO OESTE     DISTRITO FEDERAL
1                1   2004-05-09 2004-05-15  CENTRO OESTE                GOIAS
2                2   2004-05-09 2004-05-15  CENTRO OESTE          MATO GROSSO
3                3   2004-05-09 2004-05-15  CENTRO OESTE   MATO GROSSO DO SUL
4                4   2004-05-09 2004-05-15      NORDESTE              ALAGOAS
...            ...          ...        ...           ...                  ...
106818      106818   2019-06-23 2019-06-29      NORDESTE  RIO GRANDE DO NORTE
106819      106819   2019-06-23 2019-06-29           SUL    RIO GRANDE DO SUL
106820      106820   2019-06-23 2019-06-29           SUL       SANTA CATARINA
106821      106821   2019-06-23 2019-06-29       SUDESTE            SAO PAULO
106822      106822   2019-06-23 2019-06-29      NORDESTE              SERGIPE

                 PRODUTO  NÚMERO DE POSTOS PESQUISADOS UNIDADE DE MEDIDA  \
0       ETANOL HIDRATADO                           127              R$/l
1       ETANOL HIDRATADO                           387              R$/l
2       ETANOL HIDRATADO                           192              R$/l
3       ETANOL HIDRATADO                           162              R$/l
4       ETANOL HIDRATADO                           103              R$/l
...                  ...                           ...               ...
106818               GNV                             7             R$/m3
106819               GNV                            23             R$/m3
106820               GNV                            24             R$/m3
106821               GNV                            52             R$/m3
106822               GNV                             4             R$/m3

        PREÇO MÉDIO REVENDA  DESVIO PADRÃO REVENDA  ...  PREÇO MÁXIMO REVENDA  \
0                     1.288                  0.016  ...                 1.350
1                     1.162                  0.114  ...                 1.449
2                     1.389                  0.097  ...                 1.760
3                     1.262                  0.070  ...                 1.509
4                     1.181                  0.078  ...                 1.400
...                     ...                    ...  ...                   ...
106818                3.574                  0.065  ...                 3.690
106819                3.401                  0.129  ...                 3.789
106820                2.912                  0.190  ...                 3.499
106821                3.020                  0.229  ...                 3.490
106822                3.697                  0.005  ...                 3.699

        MARGEM MÉDIA REVENDA COEF DE VARIAÇÃO REVENDA  \
0                      0.463                    0.012
1                      0.399                    0.098
2                      0.419                    0.070
3                      0.432                    0.055
4                       0.24                    0.066
...                      ...                      ...
106818                 0.818                    0.018
106819                  0.95                    0.038
106820                 0.914                    0.065
106821                 0.646                    0.076
106822                 1.179                    0.001

        PREÇO MÉDIO DISTRIBUIÇÃO DESVIO PADRÃO DISTRIBUIÇÃO  \
0                          0.825                       0.11
1                          0.763                      0.088
2                           0.97                      0.095
3                           0.83                      0.119
4                          0.941                      0.077
...                          ...                        ...
106818                     2.756                          0
106819                     2.451                      0.402
106820                     1.998                          0
106821                     2.374                      0.165
106822                     2.518                          0

       PREÇO MÍNIMO DISTRIBUIÇÃO PREÇO MÁXIMO DISTRIBUIÇÃO  \
0                         0.4201                    0.9666
1                         0.5013                      1.05
2                         0.5614                     1.161
3                         0.5991                   1.22242
4                         0.7441                    1.0317
...                          ...                       ...
106818                     2.756                     2.756
106819                    1.9842                    2.8661
106820                    1.9981                    1.9981
106821                    2.0179                    2.5093
106822                    2.5175                    2.5175

       COEF DE VARIAÇÃO DISTRIBUIÇÃO MÊS   ANO
0                              0.133   5  2004
1                              0.115   5  2004
2                              0.098   5  2004
3                              0.143   5  2004
4                              0.082   5  2004
...                              ...  ..   ...
106818                             0   6  2019
106819                         0.164   6  2019
106820                             0   6  2019
106821                          0.07   6  2019
106822                             0   6  2019

[106823 rows x 21 columns]>

#### **Dados Numéricos**

In [79]:
# convertendo atributos/colunas para 'numeric'
for atributo in ['MARGEM MÉDIA REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO', 'DESVIO PADRÃO DISTRIBUIÇÃO', 'PREÇO MÍNIMO DISTRIBUIÇÃO', 'PREÇO MÁXIMO DISTRIBUIÇÃO']:
  # converte a coluna (de valores string) para um tipo numérico
  # Em caso de erro na conversão (p. ex., uma string que não representa um número), um valor vazio (null / nan) será
  # atribuido no lugar
  data_pre[atributo] = pd.to_numeric(data_pre[atributo], errors='coerce')

In [80]:
data_pre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 21 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Unnamed: 0                     106823 non-null  int64
 1   DATA INICIAL                   106823 non-null  datetime64[ns]
 2   DATA FINAL                     106823 non-null  datetime64[ns]
 3   REGIÃO                         106823 non-null  object
 4   ESTADO                         106823 non-null  object
 5   PRODUTO                        106823 non-null  object
 6   NÚMERO DE POSTOS PESQUISADOS   106823 non-null  int64
 7   UNIDADE DE MEDIDA              106823 non-null  object
 8   PREÇO MÉDIO REVENDA            106823 non-null  float64
 9   DESVIO PADRÃO REVENDA          106823 non-null  float64
 10  PREÇO MÍNIMO REVENDA           106823 non-null  float64
 11  PREÇO MÁXIMO REVENDA           106823 non-null  float64
 12  MARGEM MÉDIA REVENDA           103392 non-null  float64
 13  COEF DE VARIAÇÃO REVENDA       106823 non-null  float64
 14  PREÇO MÉDIO DISTRIBUIÇÃO       103423 non-null  float64
 15  DESVIO PADRÃO DISTRIBUIÇÃO     103423 non-null  float64
 16  PREÇO MÍNIMO DISTRIBUIÇÃO      103423 non-null  float64
 17  PREÇO MÁXIMO DISTRIBUIÇÃO      103423 non-null  float64
 18  COEF DE VARIAÇÃO DISTRIBUIÇÃO  106823 non-null  object
 19  MÊS                            106823 non-null  int64
 20  ANO                            106823 non-null  int64
dtypes: datetime64[ns](2), float64(10), int64(4), object(5)
memory usage: 17.1+ MB

<br/>

Note que temos vários valores ***null*** agora **após a *conversão de tipos***. Vamos checá-los com mais cuidado nos dados originais e preprocessados.

### 2.3 Limpeza de dados

In [81]:
mask = data_pre['PREÇO MÉDIO DISTRIBUIÇÃO'].isnull()

In [82]:
data_pre[mask]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
1903,1903,2005-09-25,2005-10-01,NORTE,PARA,ETANOL HIDRATADO,2,R$/l,1.694,0.283,...,2.090,NaN,0.167,NaN,NaN,NaN,NaN,-,9,2005
1958,1958,2005-10-09,2005-10-15,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.000,0.000,...,2.000,NaN,0.000,NaN,NaN,NaN,NaN,-,10,2005
2012,2012,2005-10-23,2005-10-29,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.277,0.023,...,2.290,NaN,0.010,NaN,NaN,NaN,NaN,-,10,2005
2497,2497,2006-02-26,2006-03-04,NORTE,RORAIMA,ETANOL HIDRATADO,11,R$/l,2.182,0.040,...,2.200,NaN,0.018,NaN,NaN,NaN,NaN,-,2,2006
3199,3199,2006-08-27,2006-09-02,NORTE,RORAIMA,ETANOL HIDRATADO,22,R$/l,2.285,0.068,...,2.300,NaN,0.030,NaN,NaN,NaN,NaN,-,8,2006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106664,106664,2019-06-16,2019-06-22,SUDESTE,MINAS GERAIS,GNV,5,R$/m3,3.445,0.147,...,3.699,NaN,0.043,NaN,NaN,NaN,NaN,-,6,2019
106666,106666,2019-06-16,2019-06-22,SUL,PARANA,GNV,7,R$/m3,3.132,0.295,...,3.890,NaN,0.094,NaN,NaN,NaN,NaN,-,6,2019
106811,106811,2019-06-23,2019-06-29,SUDESTE,ESPIRITO SANTO,GNV,4,R$/m3,3.299,0.005,...,3.299,NaN,0.002,NaN,NaN,NaN,NaN,-,6,2019
106813,106813,2019-06-23,2019-06-29,SUDESTE,MINAS GERAIS,GNV,6,R$/m3,3.548,0.100,...,3.699,NaN,0.028,NaN,NaN,NaN,NaN,-,6,2019
106815,106815,2019-06-23,2019-06-29,SUL,PARANA,GNV,1,R$/m3,3.290,0.000,...,3.290,NaN,0.000,NaN,NaN,NaN,NaN,-,6,2019

In [83]:
# Nos dados originais, quais eram os valores do PREÇO MÉDIO DISTRIBUIÇÃO dos registros que agora possuem valores NaN
data[mask]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
1903,1903,2005-09-25,2005-10-01,NORTE,PARA,ETANOL HIDRATADO,2,R$/l,1.694,0.283,...,2.090,-,0.167,-,-,-,-,-,9,2005
1958,1958,2005-10-09,2005-10-15,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.000,0.000,...,2.000,-,0.000,-,-,-,-,-,10,2005
2012,2012,2005-10-23,2005-10-29,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.277,0.023,...,2.290,-,0.010,-,-,-,-,-,10,2005
2497,2497,2006-02-26,2006-03-04,NORTE,RORAIMA,ETANOL HIDRATADO,11,R$/l,2.182,0.040,...,2.200,-,0.018,-,-,-,-,-,2,2006
3199,3199,2006-08-27,2006-09-02,NORTE,RORAIMA,ETANOL HIDRATADO,22,R$/l,2.285,0.068,...,2.300,-,0.030,-,-,-,-,-,8,2006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106664,106664,2019-06-16,2019-06-22,SUDESTE,MINAS GERAIS,GNV,5,R$/m3,3.445,0.147,...,3.699,-,0.043,-,-,-,-,-,6,2019
106666,106666,2019-06-16,2019-06-22,SUL,PARANA,GNV,7,R$/m3,3.132,0.295,...,3.890,-,0.094,-,-,-,-,-,6,2019
106811,106811,2019-06-23,2019-06-29,SUDESTE,ESPIRITO SANTO,GNV,4,R$/m3,3.299,0.005,...,3.299,-,0.002,-,-,-,-,-,6,2019
106813,106813,2019-06-23,2019-06-29,SUDESTE,MINAS GERAIS,GNV,6,R$/m3,3.548,0.100,...,3.699,-,0.028,-,-,-,-,-,6,2019
106815,106815,2019-06-23,2019-06-29,SUL,PARANA,GNV,1,R$/m3,3.290,0.000,...,3.290,-,0.000,-,-,-,-,-,6,2019

Várias amostras possuem a _string '-'_ em algumas colunas ao invés de um número de fato. Ou seja, não há aferições destes atributos para estas amostras. <br/>

<br/>

Poderíamos **preencher os valores NaN com um valor padrão**. Para isso, basta usar o método `.fillna`.

In [87]:
data_pre.fillna(0, inplace=True)
# data_pre_Fill = data_pre.fillna(0, inplace=True)

In [88]:
data_pre[mask]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
1903,1903,2005-09-25,2005-10-01,NORTE,PARA,ETANOL HIDRATADO,2,R$/l,1.694,0.283,...,2.090,0.0,0.167,0.0,0.0,0.0,0.0,-,9,2005
1958,1958,2005-10-09,2005-10-15,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.000,0.000,...,2.000,0.0,0.000,0.0,0.0,0.0,0.0,-,10,2005
2012,2012,2005-10-23,2005-10-29,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.277,0.023,...,2.290,0.0,0.010,0.0,0.0,0.0,0.0,-,10,2005
2497,2497,2006-02-26,2006-03-04,NORTE,RORAIMA,ETANOL HIDRATADO,11,R$/l,2.182,0.040,...,2.200,0.0,0.018,0.0,0.0,0.0,0.0,-,2,2006
3199,3199,2006-08-27,2006-09-02,NORTE,RORAIMA,ETANOL HIDRATADO,22,R$/l,2.285,0.068,...,2.300,0.0,0.030,0.0,0.0,0.0,0.0,-,8,2006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106664,106664,2019-06-16,2019-06-22,SUDESTE,MINAS GERAIS,GNV,5,R$/m3,3.445,0.147,...,3.699,0.0,0.043,0.0,0.0,0.0,0.0,-,6,2019
106666,106666,2019-06-16,2019-06-22,SUL,PARANA,GNV,7,R$/m3,3.132,0.295,...,3.890,0.0,0.094,0.0,0.0,0.0,0.0,-,6,2019
106811,106811,2019-06-23,2019-06-29,SUDESTE,ESPIRITO SANTO,GNV,4,R$/m3,3.299,0.005,...,3.299,0.0,0.002,0.0,0.0,0.0,0.0,-,6,2019
106813,106813,2019-06-23,2019-06-29,SUDESTE,MINAS GERAIS,GNV,6,R$/m3,3.548,0.100,...,3.699,0.0,0.028,0.0,0.0,0.0,0.0,-,6,2019
106815,106815,2019-06-23,2019-06-29,SUL,PARANA,GNV,1,R$/m3,3.290,0.000,...,3.290,0.0,0.000,0.0,0.0,0.0,0.0,-,6,2019

In [89]:
# retorna uma cópia do data frame 'data_pre' com todos os valores NaN das colunas:
# 'PREÇO MÉDIO DISTRIBUIÇÃO', 'DESVIO PADRÃO DISTRIBUIÇÃO', 'PREÇO MÍNIMO DISTRIBUIÇÃO' e 'PREÇO MÁXIMO DISTRIBUIÇÃO', respectivamente com
data_pre_fill = data_pre.fillna(value={
    'PREÇO MÉDIO DISTRIBUIÇÃO': 10,
    'DESVIO PADRÃO DISTRIBUIÇÃO': 20,
    'PREÇO MÍNIMO DISTRIBUIÇÃO': 30,
    'PREÇO MÁXIMO DISTRIBUIÇÃO': 'vazio'
})

In [90]:
data_pre_fill[mask]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
1903,1903,2005-09-25,2005-10-01,NORTE,PARA,ETANOL HIDRATADO,2,R$/l,1.694,0.283,...,2.090,0.0,0.167,0.0,0.0,0.0,0.0,-,9,2005
1958,1958,2005-10-09,2005-10-15,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.000,0.000,...,2.000,0.0,0.000,0.0,0.0,0.0,0.0,-,10,2005
2012,2012,2005-10-23,2005-10-29,NORTE,RORAIMA,ETANOL HIDRATADO,3,R$/l,2.277,0.023,...,2.290,0.0,0.010,0.0,0.0,0.0,0.0,-,10,2005
2497,2497,2006-02-26,2006-03-04,NORTE,RORAIMA,ETANOL HIDRATADO,11,R$/l,2.182,0.040,...,2.200,0.0,0.018,0.0,0.0,0.0,0.0,-,2,2006
3199,3199,2006-08-27,2006-09-02,NORTE,RORAIMA,ETANOL HIDRATADO,22,R$/l,2.285,0.068,...,2.300,0.0,0.030,0.0,0.0,0.0,0.0,-,8,2006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106664,106664,2019-06-16,2019-06-22,SUDESTE,MINAS GERAIS,GNV,5,R$/m3,3.445,0.147,...,3.699,0.0,0.043,0.0,0.0,0.0,0.0,-,6,2019
106666,106666,2019-06-16,2019-06-22,SUL,PARANA,GNV,7,R$/m3,3.132,0.295,...,3.890,0.0,0.094,0.0,0.0,0.0,0.0,-,6,2019
106811,106811,2019-06-23,2019-06-29,SUDESTE,ESPIRITO SANTO,GNV,4,R$/m3,3.299,0.005,...,3.299,0.0,0.002,0.0,0.0,0.0,0.0,-,6,2019
106813,106813,2019-06-23,2019-06-29,SUDESTE,MINAS GERAIS,GNV,6,R$/m3,3.548,0.100,...,3.699,0.0,0.028,0.0,0.0,0.0,0.0,-,6,2019
106815,106815,2019-06-23,2019-06-29,SUL,PARANA,GNV,1,R$/m3,3.290,0.000,...,3.290,0.0,0.000,0.0,0.0,0.0,0.0,-,6,2019

<br/>

Por mais que a função `fillna` seja interessante e útil em muitos casos, no problema em questão estamos interessados em analisar precisamente, p. ex., o **'PREÇO MÉDIO DISTRIBUIÇÃO'**.<br/>
A fim de não termos valores _sintéticos_ gerados pelo `fillna`, que possam atrapalhar nossa análise, iremos **remover (drop) todas as amostras que possuem qualquer valor NaN** para quaisquer atributos/colunas. <br/>

Para isso, basta utilizarmos o método `dropna`.

In [92]:
# remove, no próprio dataframe, todas as linhas/registros com valores NaN (vazios) em quaisquer colunas/atributos.
data_pre.dropna(inplace=True)

In [93]:
data_pre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 21 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Unnamed: 0                     106823 non-null  int64
 1   DATA INICIAL                   106823 non-null  datetime64[ns]
 2   DATA FINAL                     106823 non-null  datetime64[ns]
 3   REGIÃO                         106823 non-null  object
 4   ESTADO                         106823 non-null  object
 5   PRODUTO                        106823 non-null  object
 6   NÚMERO DE POSTOS PESQUISADOS   106823 non-null  int64
 7   UNIDADE DE MEDIDA              106823 non-null  object
 8   PREÇO MÉDIO REVENDA            106823 non-null  float64
 9   DESVIO PADRÃO REVENDA          106823 non-null  float64
 10  PREÇO MÍNIMO REVENDA           106823 non-null  float64
 11  PREÇO MÁXIMO REVENDA           106823 non-null  float64
 12  MARGEM MÉDIA REVENDA           106823 non-null  float64
 13  COEF DE VARIAÇÃO REVENDA       106823 non-null  float64
 14  PREÇO MÉDIO DISTRIBUIÇÃO       106823 non-null  float64
 15  DESVIO PADRÃO DISTRIBUIÇÃO     106823 non-null  float64
 16  PREÇO MÍNIMO DISTRIBUIÇÃO      106823 non-null  float64
 17  PREÇO MÁXIMO DISTRIBUIÇÃO      106823 non-null  float64
 18  COEF DE VARIAÇÃO DISTRIBUIÇÃO  106823 non-null  object
 19  MÊS                            106823 non-null  int64
 20  ANO                            106823 non-null  int64
dtypes: datetime64[ns](2), float64(10), int64(4), object(5)
memory usage: 17.1+ MB

Nosso data frame agora, após essa _limpeza_, ficou mais enxuto, contentdo 103392 registros frente aos 106823 registros originais. <br/>

Essas são apenas algumas das possíveis _técnicas de limpeza de dados_. Outras estratégias, p. ex., **confiam na detecção de outliers**, que não veremos neste curso.

#### **Salvando o Dataset Preprocessado**

In [97]:
data_pre.to_csv('/content/GasPricesinBrazil_2004-2019.csv', index=False)

<h2>3. Estatísticas Descritivas</h2>
<hr/>

In [98]:
data_final = pd.read_csv('/content/GasPricesinBrazil_2004-2019.csv')

In [99]:
data_final

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,3.690,0.818,0.018,2.756,0.000,2.7560,2.75600,0,6,2019
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,3.789,0.950,0.038,2.451,0.402,1.9842,2.86610,0.164,6,2019
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,3.499,0.914,0.065,1.998,0.000,1.9981,1.99810,0,6,2019
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.50930,0.07,6,2019
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,3.699,1.179,0.001,2.518,0.000,2.5175,2.51750,0,6,2019

O Pandas fornecem algumas funções/métodos ue computam certas estatísticas descritivas.

`describe`: exibe várias **estatísticas descritivas** para os _atributos_ de um dataframe ou para uma _Series_.

In [100]:
data_final.describe()

,Unnamed: 0,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,MÊS,ANO
count,106823.00000,106823.000000,106823.000000,106823.000000,106823.000000,106823.000000,106823.000000,106823.000000,106823.000000,106823.000000,106823.000000,106823.000000,106823.000000,106823.000000
mean,53411.00000,233.770976,10.870780,0.657227,9.416038,12.537731,2.153682,0.045418,8.285580,0.541599,7.177677,9.491878,6.484006,2011.802271
std,30837.28824,403.282519,17.752533,1.349169,15.092193,20.841497,4.322093,0.025066,13.469061,1.240934,11.566862,15.771757,3.443391,4.391530
min,0.00000,1.000000,0.766000,0.000000,0.590000,0.999000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2004.000000
25%,26705.50000,42.000000,2.072000,0.072000,1.900000,2.310000,0.271000,0.029000,1.745000,0.045000,1.628000,1.894500,4.000000,2008.000000
50%,53411.00000,104.000000,2.718000,0.114000,2.510000,2.999000,0.376000,0.041000,2.303000,0.074000,2.190000,2.474200,6.000000,2012.000000
75%,80116.50000,243.000000,3.752000,0.191000,3.499000,4.150000,0.546000,0.058000,3.265000,0.146000,3.098050,3.469300,9.000000,2016.000000
max,106822.00000,4167.000000,99.357000,10.748000,90.000000,120.000000,36.847000,0.395000,83.137000,18.385000,83.000000,94.500000,12.000000,2019.000000

In [101]:
data_final['PREÇO MÉDIO REVENDA'].describe()

count    106823.000000
mean         10.870780
std          17.752533
min           0.766000
25%           2.072000
50%           2.718000
75%           3.752000
max          99.357000
Name: PREÇO MÉDIO REVENDA, dtype: float64

<br/>

Como o resultado do `describe` de um _dataframe_ é outro _dataframe_, podemos filtrar apenas algumas colunas.

In [102]:
data_final.describe()['PREÇO MÉDIO REVENDA']

count    106823.000000
mean         10.870780
std          17.752533
min           0.766000
25%           2.072000
50%           2.718000
75%           3.752000
max          99.357000
Name: PREÇO MÉDIO REVENDA, dtype: float64

In [103]:
stats = data_final.describe()
stats

,Unnamed: 0,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,MÊS,ANO
count,106823.00000,106823.000000,106823.000000,106823.000000,106823.000000,106823.000000,106823.000000,106823.000000,106823.000000,106823.000000,106823.000000,106823.000000,106823.000000,106823.000000
mean,53411.00000,233.770976,10.870780,0.657227,9.416038,12.537731,2.153682,0.045418,8.285580,0.541599,7.177677,9.491878,6.484006,2011.802271
std,30837.28824,403.282519,17.752533,1.349169,15.092193,20.841497,4.322093,0.025066,13.469061,1.240934,11.566862,15.771757,3.443391,4.391530
min,0.00000,1.000000,0.766000,0.000000,0.590000,0.999000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2004.000000
25%,26705.50000,42.000000,2.072000,0.072000,1.900000,2.310000,0.271000,0.029000,1.745000,0.045000,1.628000,1.894500,4.000000,2008.000000
50%,53411.00000,104.000000,2.718000,0.114000,2.510000,2.999000,0.376000,0.041000,2.303000,0.074000,2.190000,2.474200,6.000000,2012.000000
75%,80116.50000,243.000000,3.752000,0.191000,3.499000,4.150000,0.546000,0.058000,3.265000,0.146000,3.098050,3.469300,9.000000,2016.000000
max,106822.00000,4167.000000,99.357000,10.748000,90.000000,120.000000,36.847000,0.395000,83.137000,18.385000,83.000000,94.500000,12.000000,2019.000000

In [104]:
stats[['PREÇO MÉDIO REVENDA', 'PREÇO MÁXIMO REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO']]

       PREÇO MÉDIO REVENDA  PREÇO MÁXIMO REVENDA  PREÇO MÉDIO DISTRIBUIÇÃO
count        106823.000000         106823.000000             106823.000000
mean             10.870780             12.537731                  8.285580
std              17.752533             20.841497                 13.469061
min               0.766000              0.999000                  0.000000
25%               2.072000              2.310000                  1.745000
50%               2.718000              2.999000                  2.303000
75%               3.752000              4.150000                  3.265000
max              99.357000            120.000000                 83.137000

In [105]:
data_final[['PREÇO MÉDIO REVENDA', 'PREÇO MÁXIMO REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO']].describe()

       PREÇO MÉDIO REVENDA  PREÇO MÁXIMO REVENDA  PREÇO MÉDIO DISTRIBUIÇÃO
count        106823.000000         106823.000000             106823.000000
mean             10.870780             12.537731                  8.285580
std              17.752533             20.841497                 13.469061
min               0.766000              0.999000                  0.000000
25%               2.072000              2.310000                  1.745000
50%               2.718000              2.999000                  2.303000
75%               3.752000              4.150000                  3.265000
max              99.357000            120.000000                 83.137000

**Acessando apenas algumas estatísticas**

In [106]:
stats

,Unnamed: 0,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,MÊS,ANO
count,106823.00000,106823.000000,106823.000000,106823.000000,106823.000000,106823.000000,106823.000000,106823.000000,106823.000000,106823.000000,106823.000000,106823.000000,106823.000000,106823.000000
mean,53411.00000,233.770976,10.870780,0.657227,9.416038,12.537731,2.153682,0.045418,8.285580,0.541599,7.177677,9.491878,6.484006,2011.802271
std,30837.28824,403.282519,17.752533,1.349169,15.092193,20.841497,4.322093,0.025066,13.469061,1.240934,11.566862,15.771757,3.443391,4.391530
min,0.00000,1.000000,0.766000,0.000000,0.590000,0.999000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2004.000000
25%,26705.50000,42.000000,2.072000,0.072000,1.900000,2.310000,0.271000,0.029000,1.745000,0.045000,1.628000,1.894500,4.000000,2008.000000
50%,53411.00000,104.000000,2.718000,0.114000,2.510000,2.999000,0.376000,0.041000,2.303000,0.074000,2.190000,2.474200,6.000000,2012.000000
75%,80116.50000,243.000000,3.752000,0.191000,3.499000,4.150000,0.546000,0.058000,3.265000,0.146000,3.098050,3.469300,9.000000,2016.000000
max,106822.00000,4167.000000,99.357000,10.748000,90.000000,120.000000,36.847000,0.395000,83.137000,18.385000,83.000000,94.500000,12.000000,2019.000000

In [107]:
stats.loc[['min', 'max', 'mean']]

,Unnamed: 0,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,MÊS,ANO
min,0.0,1.000000,0.76600,0.000000,0.590000,0.999000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,1.000000,2004.000000
max,106822.0,4167.000000,99.35700,10.748000,90.000000,120.000000,36.847000,0.395000,83.13700,18.385000,83.000000,94.500000,12.000000,2019.000000
mean,53411.0,233.770976,10.87078,0.657227,9.416038,12.537731,2.153682,0.045418,8.28558,0.541599,7.177677,9.491878,6.484006,2011.802271

In [108]:
stats.loc[['min', 'max', 'mean'], 'PREÇO MÉDIO REVENDA']

min      0.76600
max     99.35700
mean    10.87078
Name: PREÇO MÉDIO REVENDA, dtype: float64

In [109]:
stats.loc[['min', 'max', 'mean'], ['PREÇO MÉDIO REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO']]

      PREÇO MÉDIO REVENDA  PREÇO MÉDIO DISTRIBUIÇÃO
min               0.76600                   0.00000
max              99.35700                  83.13700
mean             10.87078                   8.28558

<br/>

`mean`, `std`, `min`, etc: cada uma das estatísticas do `describe` podem ser computadas individualmente:

In [110]:
data_final.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004

#### Qual é o menor preço mínimo de revenda?

In [111]:
data_final['PREÇO MÍNIMO REVENDA'].min()

0.59

#### Qual é a média e desvio padrão dos preços mínimos de revenda?

In [112]:
mean = data_final['PREÇO MÍNIMO REVENDA'].mean()
std = data_final['PREÇO MÍNIMO REVENDA'].std()

print(f'A média dos preços mínimos de revenda é {mean:.2f} +- {std:.2f}')

A média dos preços mínimos de revenda é 9.42 +- 15.09

#### Quais são os estados considerados?

In [113]:
data_final['ESTADO']

0            DISTRITO FEDERAL
1                       GOIAS
2                 MATO GROSSO
3          MATO GROSSO DO SUL
4                     ALAGOAS
                 ...
106818    RIO GRANDE DO NORTE
106819      RIO GRANDE DO SUL
106820         SANTA CATARINA
106821              SAO PAULO
106822                SERGIPE
Name: ESTADO, Length: 106823, dtype: object

In [114]:
data_final['ESTADO'].unique()

array(['DISTRITO FEDERAL', 'GOIAS', 'MATO GROSSO', 'MATO GROSSO DO SUL',
       'ALAGOAS', 'BAHIA', 'CEARA', 'MARANHAO', 'PARAIBA', 'PERNAMBUCO',
       'PIAUI', 'RIO GRANDE DO NORTE', 'SERGIPE', 'ACRE', 'AMAPA',
       'AMAZONAS', 'PARA', 'RONDONIA', 'RORAIMA', 'TOCANTINS',
       'ESPIRITO SANTO', 'MINAS GERAIS', 'RIO DE JANEIRO', 'SAO PAULO',
       'PARANA', 'RIO GRANDE DO SUL', 'SANTA CATARINA'], dtype=object)

In [115]:
sorted(data_final['ESTADO'].unique())

['ACRE',
 'ALAGOAS',
 'AMAPA',
 'AMAZONAS',
 'BAHIA',
 'CEARA',
 'DISTRITO FEDERAL',
 'ESPIRITO SANTO',
 'GOIAS',
 'MARANHAO',
 'MATO GROSSO',
 'MATO GROSSO DO SUL',
 'MINAS GERAIS',
 'PARA',
 'PARAIBA',
 'PARANA',
 'PERNAMBUCO',
 'PIAUI',
 'RIO DE JANEIRO',
 'RIO GRANDE DO NORTE',
 'RIO GRANDE DO SUL',
 'RONDONIA',
 'RORAIMA',
 'SANTA CATARINA',
 'SAO PAULO',
 'SERGIPE',
 'TOCANTINS']

#### Quantos registros (aferições) cada estado possui?

`.value_counts()`:  Conta a frequência dos valores de uma dada variável (de preferência, _categórica_).

In [117]:
data_final['ESTADO'].value_counts() # retorna em ordem decrescente, a quantidade de registros/linhas para cada estado

ESTADO
PARAIBA                4263
BAHIA                  4263
CEARA                  4263
RIO GRANDE DO SUL      4263
RIO DE JANEIRO         4263
SAO PAULO              4263
PERNAMBUCO             4262
RIO GRANDE DO NORTE    4262
SANTA CATARINA         4262
MINAS GERAIS           4261
ESPIRITO SANTO         4260
SERGIPE                4259
PARANA                 4251
ALAGOAS                4250
MATO GROSSO DO SUL     4246
MATO GROSSO            4037
AMAZONAS               3889
GOIAS                  3663
PIAUI                  3548
MARANHAO               3499
PARA                   3497
DISTRITO FEDERAL       3483
TOCANTINS              3483
ACRE                   3480
RONDONIA               3479
RORAIMA                3471
AMAPA                  3403
Name: count, dtype: int64

In [118]:
data_final['ESTADO'].value_counts().to_frame() # converte uma Series para um DataFrame

                     count
ESTADO
PARAIBA               4263
BAHIA                 4263
CEARA                 4263
RIO GRANDE DO SUL     4263
RIO DE JANEIRO        4263
SAO PAULO             4263
PERNAMBUCO            4262
RIO GRANDE DO NORTE   4262
SANTA CATARINA        4262
MINAS GERAIS          4261
ESPIRITO SANTO        4260
SERGIPE               4259
PARANA                4251
ALAGOAS               4250
MATO GROSSO DO SUL    4246
MATO GROSSO           4037
AMAZONAS              3889
GOIAS                 3663
PIAUI                 3548
MARANHAO              3499
PARA                  3497
DISTRITO FEDERAL      3483
TOCANTINS             3483
ACRE                  3480
RONDONIA              3479
RORAIMA               3471
AMAPA                 3403

<h2>4. Executando funções para cada item de um DataFrame ou Series</h2>
<hr/>

Uma alternativa ao `for-loop` que vimos anteriormente e que é _lento_, é usarmos _funções próprias do pandas_ que **aplicam/mapeiam uma dada função a todos os elementos de um DataFrame ou Series**, retornando novos elementos "transformados".

<img src='./imagens/apply_map_applymap.png' width=300/>


Fonte: https://towardsdatascience.com/introduction-to-pandas-apply-applymap-and-map-5d3e044e93ff

In [119]:
df = pd.DataFrame({ 'A': [1, 2, 3, 4],
                    'B': [10, 20, 30, 40],
                    'C': [100, 200, 300, 400]},
                     index=['Linha 1', 'Linha 2', 'Linha 3', 'Linha 4'])

In [120]:
df

         A   B    C
Linha 1  1  10  100
Linha 2  2  20  200
Linha 3  3  30  300
Linha 4  4  40  400

`apply()`: usado para aplicar uma função ao longo de um eixo de um DataFrame ou em valores de uma Series.

<img src='./imagens/pandas_axis.jpg' width=500/>

Fonte: https://www.allthesnippets.com/browse/pandas/df_axis.html

In [123]:
def nossa_soma(series):
  return series.sum() # retorna a soma de todos os valores de uma linha

In [125]:
df['SOMA(A, B, C)'] = df.apply(nossa_soma, axis=1)
df

         A   B    C  SOMA(A, B, C)
Linha 1  1  10  100            111
Linha 2  2  20  200            222
Linha 3  3  30  300            333
Linha 4  4  40  400            444

<img src='./imagens/apply_axis_1.png' width=250/>

In [126]:
df.loc['Linha 5'] = df.apply(nossa_soma, axis=0)
df

          A    B     C  SOMA(A, B, C)
Linha 1   1   10   100            111
Linha 2   2   20   200            222
Linha 3   3   30   300            333
Linha 4   4   40   400            444
Linha 5  10  100  1000           1110

<img src='./imagens/apply_axis_0.png' width=250/>

##### Usando `lambda` functions

In [128]:
df ['MEDIA(A, B, C)'] = df[['A', 'B', 'C']].apply(lambda series: series.mean(), axis=1)
df

          A    B     C  SOMA(A, B, C)  MEDIA(A, B, C)
Linha 1   1   10   100            111            37.0
Linha 2   2   20   200            222            74.0
Linha 3   3   30   300            333           111.0
Linha 4   4   40   400            444           148.0
Linha 5  10  100  1000           1110           370.0

In [129]:
# aplica a lambda function abaixo par cada elemento da coluna
df['C * 2'] = df['C'].apply(lambda x: x * 2)
df

          A    B     C  SOMA(A, B, C)  MEDIA(A, B, C)  C * 2
Linha 1   1   10   100            111            37.0    200
Linha 2   2   20   200            222            74.0    400
Linha 3   3   30   300            333           111.0    600
Linha 4   4   40   400            444           148.0    800
Linha 5  10  100  1000           1110           370.0   2000

<img src='./imagens/apply_axis_1_mean.png' width=350/>

<br/>

`applymap()`: usado para aplicar uma função para **cada elemento** (_element-wise_) de um DataFrame.

In [130]:
df = pd.DataFrame({ 'A': [1, 2, 3, 4],
                    'B': [10, 20, 30, 40],
                    'C': [100, 200, 300, 400]},
                     index=['Linha 1', 'Linha 2', 'Linha 3', 'Linha 4'])
df

         A   B    C
Linha 1  1  10  100
Linha 2  2  20  200
Linha 3  3  30  300
Linha 4  4  40  400

In [131]:
#retorna um novo dataframe com todos os elementos ao quadrado.
#poderíamos usar uma função ao invés de uma lambda function
df.applymap(lambda x: x ** 2)

/tmp/ipython-input-659774109.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x: x ** 2)

          A     B       C
Linha 1   1   100   10000
Linha 2   4   400   40000
Linha 3   9   900   90000
Linha 4  16  1600  160000

In [132]:
df

         A   B    C
Linha 1  1  10  100
Linha 2  2  20  200
Linha 3  3  30  300
Linha 4  4  40  400

<br/>

`map()`: usado para aplicar uma função para **cada elemento** (_element-wise_) de uma _Series_.

In [133]:
nomes = pd.Series(['João', 'Maria', 'Alice', 'Pedro'])
nomes

0     João
1    Maria
2    Alice
3    Pedro
dtype: object

In [134]:
# retorna uma nova Series com todos os nomes com letras maiúsculas.
# poderíamos usar uma função ao invés de uma lambda function
nomes.map(lambda x: x.upper())

0     JOÃO
1    MARIA
2    ALICE
3    PEDRO
dtype: object

In [135]:
nomes

0     João
1    Maria
2    Alice
3    Pedro
dtype: object

In [136]:
# O Pandas já fornece uma série de métodos para manipulação de strings.
# Assim, poderíamos usar o código abaixo para obeter o mesmo resultado
nomes.str.upper()

0     JOÃO
1    MARIA
2    ALICE
3    PEDRO
dtype: object

<h2>5. Agrupamento</h2>
<hr/>

In [137]:
data_final.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004

`groupby`: Usado para criar **grupo de elementos** (e.x., baseado nos valores de um atributo). <br/>
**Funções** podem então ser aplicadas para os _elementos de cada grupo_, de modo que os **resultados de cada grupo são combinados**.

In [139]:
grupos = data_final.groupby('REGIÃO')
grupos

In [140]:
grupos.groups

{'CENTRO OESTE': [0, 1, 2, 3, 27, 28, 29, 30, 54, 55, 56, 57, 81, 82, 83, 84, 108, 109, 110, 111, 135, 136, 137, 138, 162, 163, 164, 165, 189, 190, 191, 192, 216, 217, 218, 219, 243, 244, 245, 246, 270, 271, 272, 273, 297, 298, 299, 300, 324, 325, 326, 327, 351, 352, 353, 354, 378, 379, 380, 381, 405, 406, 407, 408, 432, 433, 434, 435, 459, 460, 461, 462, 486, 487, 488, 489, 513, 514, 515, 516, 540, 541, 542, 543, 567, 568, 569, 570, 594, 595, 596, 597, 621, 622, 623, 624, 648, 649, 650, 651, ...], 'NORDESTE': [4, 5, 6, 7, 8, 9, 10, 11, 12, 31, 32, 33, 34, 35, 36, 37, 38, 39, 58, 59, 60, 61, 62, 63, 64, 65, 66, 85, 86, 87, 88, 89, 90, 91, 92, 93, 112, 113, 114, 115, 116, 117, 118, 119, 120, 139, 140, 141, 142, 143, 144, 145, 146, 147, 166, 167, 168, 169, 170, 171, 172, 173, 174, 193, 194, 195, 196, 197, 198, 199, 200, 201, 220, 221, 222, 223, 224, 225, 226, 227, 228, 247, 248, 249, 250, 251, 252, 253, 254, 255, 274, 275, 276, 277, 278, 279, 280, 281, 282, 301, ...], 'NORTE': [13, 14, 15, 16, 17, 18, 19, 40, 41, 42, 43, 44, 45, 46, 67, 68, 69, 70, 71, 72, 73, 94, 95, 96, 97, 98, 99, 100, 121, 122, 123, 124, 125, 126, 127, 148, 149, 150, 151, 152, 153, 154, 175, 176, 177, 178, 179, 180, 181, 202, 203, 204, 205, 206, 207, 208, 229, 230, 231, 232, 233, 234, 235, 256, 257, 258, 259, 260, 261, 262, 283, 284, 285, 286, 287, 288, 289, 310, 311, 312, 313, 314, 315, 316, 337, 338, 339, 340, 341, 342, 343, 364, 365, 366, 367, 368, 369, 370, 391, 392, ...], 'SUDESTE': [20, 21, 22, 23, 47, 48, 49, 50, 74, 75, 76, 77, 101, 102, 103, 104, 128, 129, 130, 131, 155, 156, 157, 158, 182, 183, 184, 185, 209, 210, 211, 212, 236, 237, 238, 239, 263, 264, 265, 266, 290, 291, 292, 293, 317, 318, 319, 320, 344, 345, 346, 347, 371, 372, 373, 374, 398, 399, 400, 401, 425, 426, 427, 428, 452, 453, 454, 455, 479, 480, 481, 482, 506, 507, 508, 509, 533, 534, 535, 536, 560, 561, 562, 563, 587, 588, 589, 590, 614, 615, 616, 617, 641, 642, 643, 644, 668, 669, 670, 671, ...], 'SUL': [24, 25, 26, 51, 52, 53, 78, 79, 80, 105, 106, 107, 132, 133, 134, 159, 160, 161, 186, 187, 188, 213, 214, 215, 240, 241, 242, 267, 268, 269, 294, 295, 296, 321, 322, 323, 348, 349, 350, 375, 376, 377, 402, 403, 404, 429, 430, 431, 456, 457, 458, 483, 484, 485, 510, 511, 512, 537, 538, 539, 564, 565, 566, 591, 592, 593, 618, 619, 620, 645, 646, 647, 672, 673, 674, 699, 700, 701, 726, 727, 728, 753, 754, 755, 780, 781, 782, 807, 808, 809, 834, 835, 836, 861, 862, 863, 888, 889, 890, 915, ...]}

In [141]:
grupos.indices

{'CENTRO OESTE': array([     0,      1,      2, ..., 106791, 106792, 106812]),
 'NORDESTE': array([     4,      5,      6, ..., 106816, 106818, 106822]),
 'NORTE': array([    13,     14,     15, ..., 106802, 106803, 106807]),
 'SUDESTE': array([    20,     21,     22, ..., 106813, 106817, 106821]),
 'SUL': array([    24,     25,     26, ..., 106815, 106819, 106820])}

In [142]:
grupos.get_group('CENTRO OESTE')

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
27,27,2004-05-16,2004-05-22,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,144,R$/l,1.271,0.039,...,1.300,0.448,0.031,0.823,0.111,0.4094,1.19310,0.135,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106787,106787,2019-06-23,2019-06-29,CENTRO OESTE,DISTRITO FEDERAL,GLP,42,R$/13Kg,73.452,4.875,...,95.000,21.509,0.066,51.943,7.877,44.0000,62.82000,0.152,6,2019
106789,106789,2019-06-23,2019-06-29,CENTRO OESTE,GOIAS,GLP,209,R$/13Kg,71.968,5.381,...,85.000,15.044,0.075,56.924,4.285,45.5700,61.60000,0.075,6,2019
106791,106791,2019-06-23,2019-06-29,CENTRO OESTE,MATO GROSSO,GLP,95,R$/13Kg,96.691,6.835,...,115.000,19.789,0.071,76.902,8.846,61.1500,90.00000,0.115,6,2019
106792,106792,2019-06-23,2019-06-29,CENTRO OESTE,MATO GROSSO DO SUL,GLP,115,R$/13Kg,72.297,8.054,...,99.000,16.707,0.111,55.590,5.109,47.0000,72.00000,0.092,6,2019
106812,106812,2019-06-23,2019-06-29,CENTRO OESTE,MATO GROSSO DO SUL,GNV,2,R$/m3,2.934,0.049,...,2.968,0.901,0.017,2.033,0.259,1.8500,2.21610,0.127,6,2019

In [144]:
# descreva para nós algumas estatísticas descritivas para as observaçoes de cada grupo
grupos.describe()

             Unnamed: 0                                                       \
                  count          mean           std   min       25%      50%
REGIÃO
CENTRO OESTE    15429.0  53417.968955  30938.517860   0.0  26021.00  54240.0
NORDESTE        36869.0  53538.276248  30636.581838   4.0  27645.00  53027.0
NORTE           24702.0  52805.662214  31594.475085  13.0  23848.25  54009.5
SUDESTE         17047.0  53749.005104  30386.889753  20.0  28766.50  52829.0
SUL             12776.0  53754.692001  30391.714995  24.0  28743.75  52859.5

                                 NÚMERO DE POSTOS PESQUISADOS              \
                   75%       max                        count        mean
REGIÃO
CENTRO OESTE  80018.00  106812.0                      15429.0  137.263983
NORDESTE      80098.00  106822.0                      36869.0  123.194364
NORTE         80299.50  106807.0                      24702.0   66.249899
SUDESTE       80048.50  106821.0                      17047.0  713.297002
SUL           80059.75  106820.0                      12776.0  353.486146

              ...   MÊS            ANO                                         \
              ...   75%   max    count         mean       std     min     25%
REGIÃO        ...
CENTRO OESTE  ...  9.00  12.0  15429.0  2011.862532  4.352302  2004.0  2008.0
NORDESTE      ...  9.00  12.0  36869.0  2011.777699  4.404509  2004.0  2008.0
NORTE         ...  9.00  12.0  24702.0  2011.832524  4.386504  2004.0  2008.0
SUDESTE       ...  9.00  12.0  17047.0  2011.775796  4.399684  2004.0  2008.0
SUL           ...  9.25  12.0  12776.0  2011.777239  4.399609  2004.0  2008.0


                 50%     75%     max
REGIÃO
CENTRO OESTE  2012.0  2016.0  2019.0
NORDESTE      2012.0  2016.0  2019.0
NORTE         2012.0  2016.0  2019.0
SUDESTE       2012.0  2016.0  2019.0
SUL           2012.0  2016.0  2019.0

[5 rows x 112 columns]

In [149]:
grupos.mean()

TypeError: agg function failed [how->mean,dtype->object]

In [150]:
grupos.min()

,Unnamed: 0,DATA INICIAL,DATA FINAL,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
REGIÃO,,,,,,,,,,,,,,,,,,,,
CENTRO OESTE,0,2004-05-09,2004-05-15,DISTRITO FEDERAL,ETANOL HIDRATADO,1,R$/13Kg,1.097,0.0,0.87,1.099,0.0,0.0,0.0,0.0,0.0,0.0,-,1,2004
NORDESTE,4,2004-05-09,2004-05-15,ALAGOAS,ETANOL HIDRATADO,1,R$/13Kg,0.975,0.0,0.79,0.999,0.0,0.0,0.0,0.0,0.0,0.0,-,1,2004
NORTE,13,2004-05-09,2004-05-15,ACRE,ETANOL HIDRATADO,1,R$/13Kg,1.219,0.0,1.05,1.219,0.0,0.0,0.0,0.0,0.0,0.0,-,1,2004
SUDESTE,20,2004-05-09,2004-05-15,ESPIRITO SANTO,ETANOL HIDRATADO,1,R$/13Kg,0.766,0.0,0.59,1.099,0.0,0.0,0.0,0.0,0.0,0.0,-,1,2004
SUL,24,2004-05-09,2004-05-15,PARANA,ETANOL HIDRATADO,1,R$/13Kg,0.922,0.0,0.73,1.199,0.0,0.0,0.0,0.0,0.0,0.0,-,1,2004

In [151]:
data_final.groupby('REGIÃO').min()

,Unnamed: 0,DATA INICIAL,DATA FINAL,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
REGIÃO,,,,,,,,,,,,,,,,,,,,
CENTRO OESTE,0,2004-05-09,2004-05-15,DISTRITO FEDERAL,ETANOL HIDRATADO,1,R$/13Kg,1.097,0.0,0.87,1.099,0.0,0.0,0.0,0.0,0.0,0.0,-,1,2004
NORDESTE,4,2004-05-09,2004-05-15,ALAGOAS,ETANOL HIDRATADO,1,R$/13Kg,0.975,0.0,0.79,0.999,0.0,0.0,0.0,0.0,0.0,0.0,-,1,2004
NORTE,13,2004-05-09,2004-05-15,ACRE,ETANOL HIDRATADO,1,R$/13Kg,1.219,0.0,1.05,1.219,0.0,0.0,0.0,0.0,0.0,0.0,-,1,2004
SUDESTE,20,2004-05-09,2004-05-15,ESPIRITO SANTO,ETANOL HIDRATADO,1,R$/13Kg,0.766,0.0,0.59,1.099,0.0,0.0,0.0,0.0,0.0,0.0,-,1,2004
SUL,24,2004-05-09,2004-05-15,PARANA,ETANOL HIDRATADO,1,R$/13Kg,0.922,0.0,0.73,1.199,0.0,0.0,0.0,0.0,0.0,0.0,-,1,2004

<br/>

Também podemos ter agrupamentos por mais de um atributo.

In [152]:
data_final.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004

In [ ]:
# Qual é o preço médio de cada do Produto (Combustível) para cada Região?

In [154]:
grupos = data_final.groupby(['REGIÃO', 'PRODUTO'])
grupos

In [155]:
grupos.groups

{('CENTRO OESTE', 'ETANOL HIDRATADO'): [0, 1, 2, 3, 27, 28, 29, 30, 54, 55, 56, 57, 81, 82, 83, 84, 108, 109, 110, 111, 135, 136, 137, 138, 162, 163, 164, 165, 189, 190, 191, 192, 216, 217, 218, 219, 243, 244, 245, 246, 270, 271, 272, 273, 297, 298, 299, 300, 324, 325, 326, 327, 351, 352, 353, 354, 378, 379, 380, 381, 405, 406, 407, 408, 432, 433, 434, 435, 459, 460, 461, 462, 486, 487, 488, 489, 513, 514, 515, 516, 540, 541, 542, 543, 567, 568, 569, 570, 594, 595, 596, 597, 621, 622, 623, 624, 648, 649, 650, 651, ...], ('CENTRO OESTE', 'GASOLINA COMUM'): [12064, 12065, 12066, 12067, 12091, 12092, 12093, 12094, 12118, 12119, 12120, 12121, 12145, 12146, 12147, 12148, 12172, 12173, 12174, 12175, 12199, 12200, 12201, 12202, 12226, 12227, 12228, 12229, 12253, 12254, 12255, 12256, 12280, 12281, 12282, 12283, 12307, 12308, 12309, 12310, 12334, 12335, 12336, 12337, 12361, 12362, 12363, 12364, 12388, 12389, 12390, 12391, 12415, 12416, 12417, 12418, 12442, 12443, 12444, 12445, 12469, 12470, 12471, 12472, 12496, 12497, 12498, 12499, 12523, 12524, 12525, 12526, 12550, 12551, 12552, 12553, 12577, 12578, 12579, 12580, 12604, 12605, 12606, 12607, 12631, 12632, 12633, 12634, 12658, 12659, 12660, 12661, 12685, 12686, 12687, 12688, 12712, 12713, 12714, 12715, ...], ('CENTRO OESTE', 'GLP'): [24132, 24133, 24134, 24135, 24159, 24160, 24161, 24162, 24186, 24187, 24188, 24189, 24213, 24214, 24215, 24216, 24240, 24241, 24242, 24243, 24267, 24268, 24269, 24270, 24294, 24295, 24296, 24297, 24321, 24322, 24323, 24324, 24348, 24349, 24350, 24351, 24375, 24376, 24377, 24378, 24402, 24403, 24404, 24405, 24429, 24430, 24431, 24432, 24456, 24457, 24458, 24459, 24483, 24484, 24485, 24486, 24510, 24511, 24512, 24513, 24537, 24538, 24539, 24540, 24564, 24565, 24566, 24567, 24591, 24592, 24593, 24594, 24618, 24619, 24620, 24621, 24645, 24646, 24647, 24648, 24672, 24673, 24674, 24675, 24699, 24700, 24701, 24702, 24726, 24727, 24728, 24729, 24753, 24754, 24755, 24756, 24780, 24781, 24782, 24783, ...], ('CENTRO OESTE', 'GNV'): [36196, 36211, 36226, 36241, 36256, 36271, 36286, 36301, 36316, 36331, 36346, 36361, 36377, 36393, 36409, 36425, 36441, 36457, 36473, 36489, 36505, 36521, 36537, 36553, 36569, 36585, 36601, 36617, 36633, 36649, 36665, 36681, 36697, 36713, 36729, 36745, 36761, 36777, 36793, 36809, 36825, 36841, 36857, 36873, 36889, 36905, 36921, 36937, 36953, 36969, 36985, 37001, 37017, 37033, 37049, 37065, 37081, 37097, 37113, 37129, 37145, 37161, 37177, 37193, 37209, 37225, 37242, 37257, 37258, 37274, 37290, 37307, 37322, 37338, 37353, 37368, 37383, 37399, 37415, 37430, 37446, 37462, 37478, 37494, 37510, 37526, 37542, 37558, 37574, 37590, 37606, 37621, 37637, 37653, 37669, 37686, 37702, 37718, 37734, 37750, ...], ('CENTRO OESTE', 'ÓLEO DIESEL'): [43547, 43548, 43549, 43550, 43574, 43575, 43576, 43577, 43601, 43602, 43603, 43604, 43628, 43629, 43630, 43631, 43655, 43656, 43657, 43658, 43682, 43683, 43684, 43685, 43709, 43710, 43711, 43712, 43736, 43737, 43738, 43739, 43763, 43764, 43765, 43766, 43790, 43791, 43792, 43793, 43817, 43818, 43819, 43820, 43844, 43845, 43846, 43847, 43871, 43872, 43873, 43874, 43898, 43899, 43900, 43901, 43925, 43926, 43927, 43928, 43952, 43953, 43954, 43955, 43979, 43980, 43981, 43982, 44006, 44007, 44008, 44009, 44033, 44034, 44035, 44036, 44060, 44061, 44062, 44063, 44087, 44088, 44089, 44090, 44114, 44115, 44116, 44117, 44141, 44142, 44143, 44144, 44168, 44169, 44170, 44171, 44195, 44196, 44197, 44198, ...], ('CENTRO OESTE', 'ÓLEO DIESEL S10'): [55672, 55674, 55819, 55821, 55822, 55967, 55969, 55971, 55972, 56119, 56121, 56123, 56124, 56272, 56274, 56276, 56277, 56425, 56427, 56429, 56430, 56577, 56579, 56581, 56582, 56729, 56731, 56733, 56734, 56882, 56884, 56886, 56887, 57035, 57037, 57039, 57040, 57187, 57189, 57191, 57192, 57339, 57341, 57343, 57344, 57490, 57492, 57494, 57495, 57642, 57644, 57646, 57647, 57795, 57797, 57799, 57800, 57947, 57949, 57951, 57952, 58099, 58101, 58103, 58104, 58251, 58253, 58255, 58256, 58402, 58404, 58406, 58407, 58554, 58556, 58558, 58559, 58706, 58708, 58710, 58711, 58858, 58860, 58862, 58863, 59011, 59013, 59015, 59016, 59163, 59165, 59167, 59168, 59315, 59317, 59319, 59320, 59468, 59470, 59472, ...], ('NORDESTE', 'ETANOL HIDRATADO'): [4, 5, 6, 7, 8, 9, 10, 11, 12, 31, 32, 33, 34, 35, 36, 37, 38, 39, 58, 59, 60, 61, 62, 63, 64, 65, 66, 85, 86, 87, 88, 89, 90, 91, 92, 93, 112, 113, 114, 115, 116, 117, 118, 119, 120, 139, 140, 141, 142, 143, 144, 145, 146, 147, 166, 167, 168, 169, 170, 171, 172, 173, 174, 193, 194, 195, 196, 197, 198, 199, 200, 201, 220, 221, 222, 223, 224, 225, 226, 227, 228, 247, 248, 249, 250, 251, 252, 253, 254, 255, 274, 275, 276, 277, 278, 279, 280, 281, 282, 301, ...], ('NORDESTE', 'GASOLINA COMUM'): [12068, 12069, 12070, 12071, 12072, 12073, 12074, 12075, 12076, 12095, 12096, 12097, 12098, 12099, 12100, 12101, 12102, 12103, 12122, 12123, 12124, 12125, 12126, 12127, 12128, 12129, 12130, 12149, 12150, 12151, 12152, 12153, 12154, 12155, 12156, 12157, 12176, 12177, 12178, 12179, 12180, 12181, 12182, 12183, 12184, 12203, 12204, 12205, 12206, 12207, 12208, 12209, 12210, 12211, 12230, 12231, 12232, 12233, 12234, 12235, 12236, 12237, 12238, 12257, 12258, 12259, 12260, 12261, 12262, 12263, 12264, 12265, 12284, 12285, 12286, 12287, 12288, 12289, 12290, 12291, 12292, 12311, 12312, 12313, 12314, 12315, 12316, 12317, 12318, 12319, 12338, 12339, 12340, 12341, 12342, 12343, 12344, 12345, 12346, 12365, ...], ('NORDESTE', 'GLP'): [24136, 24137, 24138, 24139, 24140, 24141, 24142, 24143, 24144, 24163, 24164, 24165, 24166, 24167, 24168, 24169, 24170, 24171, 24190, 24191, 24192, 24193, 24194, 24195, 24196, 24197, 24198, 24217, 24218, 24219, 24220, 24221, 24222, 24223, 24224, 24225, 24244, 24245, 24246, 24247, 24248, 24249, 24250, 24251, 24252, 24271, 24272, 24273, 24274, 24275, 24276, 24277, 24278, 24279, 24298, 24299, 24300, 24301, 24302, 24303, 24304, 24305, 24306, 24325, 24326, 24327, 24328, 24329, 24330, 24331, 24332, 24333, 24352, 24353, 24354, 24355, 24356, 24357, 24358, 24359, 24360, 24379, 24380, 24381, 24382, 24383, 24384, 24385, 24386, 24387, 24406, 24407, 24408, 24409, 24410, 24411, 24412, 24413, 24414, 24433, ...], ('NORDESTE', 'GNV'): [36197, 36198, 36199, 36200, 36201, 36202, 36203, 36212, 36213, 36214, 36215, 36216, 36217, 36218, 36227, 36228, 36229, 36230, 36231, 36232, 36233, 36242, 36243, 36244, 36245, 36246, 36247, 36248, 36257, 36258, 36259, 36260, 36261, 36262, 36263, 36272, 36273, 36274, 36275, 36276, 36277, 36278, 36287, 36288, 36289, 36290, 36291, 36292, 36293, 36302, 36303, 36304, 36305, 36306, 36307, 36308, 36317, 36318, 36319, 36320, 36321, 36322, 36323, 36332, 36333, 36334, 36335, 36336, 36337, 36338, 36347, 36348, 36349, 36350, 36351, 36352, 36353, 36362, 36363, 36364, 36365, 36366, 36367, 36368, 36369, 36378, 36379, 36380, 36381, 36382, 36383, 36384, 36385, 36394, 36395, 36396, 36397, 36398, 36399, 36400, ...], ('NORDESTE', 'ÓLEO DIESEL'): [43551, 43552, 43553, 43554, 43555, 43556, 43557, 43558, 43559, 43578, 43579, 43580, 43581, 43582, 43583, 43584, 43585, 43586, 43605, 43606, 43607, 43608, 43609, 43610, 43611, 43612, 43613, 43632, 43633, 43634, 43635, 43636, 43637, 43638, 43639, 43640, 43659, 43660, 43661, 43662, 43663, 43664, 43665, 43666, 43667, 43686, 43687, 43688, 43689, 43690, 43691, 43692, 43693, 43694, 43713, 43714, 43715, 43716, 43717, 43718, 43719, 43720, 43721, 43740, 43741, 43742, 43743, 43744, 43745, 43746, 43747, 43748, 43767, 43768, 43769, 43770, 43771, 43772, 43773, 43774, 43775, 43794, 43795, 43796, 43797, 43798, 43799, 43800, 43801, 43802, 43821, 43822, 43823, 43824, 43825, 43826, 43827, 43828, 43829, 43848, ...], ('NORDESTE', 'ÓLEO DIESEL S10'): [55669, 55670, 55673, 55677, 55679, 55685, 55814, 55816, 55817, 55820, 55825, 55827, 55828, 55830, 55835, 55962, 55965, 55966, 55970, 55975, 55977, 55978, 55980, 55986, 56114, 56117, 56118, 56122, 56127, 56129, 56130, 56132, 56138, 56267, 56270, 56271, 56275, 56280, 56282, 56283, 56285, 56291, 56420, 56423, 56424, 56428, 56433, 56435, 56436, 56438, 56444, 56572, 56575, 56576, 56580, 56585, 56587, 56588, 56590, 56596, 56724, 56727, 56728, 56732, 56737, 56739, 56740, 56742, 56748, 56877, 56880, 56881, 56885, 56890, 56892, 56893, 56895, 56901, 57030, 57033, 57034, 57038, 57043, 57045, 57046, 57048, 57054, 57182, 57185, 57186, 57190, 57195, 57197, 57198, 57200, 57206, 57334, 57337, 57338, 57342, ...], ('NORTE', 'ETANOL HIDRATADO'): [13, 14, 15, 16, 17, 18, 19, 40, 41, 42, 43, 44, 45, 46, 67, 68, 69, 70, 71, 72, 73, 94, 95, 96, 97, 98, 99, 100, 121, 122, 123, 124, 125, 126, 127, 148, 149, 150, 151, 152, 153, 154, 175, 176, 177, 178, 179, 180, 181, 202, 203, 204, 205, 206, 207, 208, 229, 230, 231, 232, 233, 234, 235, 256, 257, 258, 259, 260, 261, 262, 283, 284, 285, 286, 287, 288, 289, 310, 311, 312, 313, 314, 315, 316, 337, 338, 339, 340, 341, 342, 343, 364, 365, 366, 367, 368, 369, 370, 391, 392, ...], ('NORTE', 'GASOLINA COMUM'): [12077, 12078, 12079, 12080, 12081, 12082, 12083, 12104, 12105, 12106, 12107, 12108, 12109, 12110, 12131, 12132, 12133, 12134, 12135, 12136, 12137, 12158, 12159, 12160, 12161, 12162, 12163, 12164, 12185, 12186, 12187, 12188, 12189, 12190, 12191, 12212, 12213, 12214, 12215, 12216, 12217, 12218, 12239, 12240, 12241, 12242, 12243, 12244, 12245, 12266, 12267, 12268, 12269, 12270, 12271, 12272, 12293, 12294, 12295, 12296, 12297, 12298, 12299, 12320, 12321, 12322, 12323, 12324, 12325, 12326, 12347, 12348, 12349, 12350, 12351, 12352, 12353, 12374, 12375, 12376, 12377, 12378, 12379, 12380, 12401, 12402, 12403, 12404, 12405, 12406, 12407, 12428, 12429, 12430, 12431, 12432, 12433, 12434, 12455, 12456, ...], ('NORTE', 'GLP'): [24145, 24146, 24147, 24148, 24149, 24150, 24151, 24172, 24173, 24174, 24175, 24176, 24177, 24178, 24199, 24200, 24201, 24202, 24203, 24204, 24205, 24226, 24227, 24228, 24229, 24230, 24231, 24232, 24253, 24254, 24255, 24256, 24257, 24258, 24259, 24280, 24281, 24282, 24283, 24284, 24285, 24286, 24307, 24308, 24309, 24310, 24311, 24312, 24313, 24334, 24335, 24336, 24337, 24338, 24339, 24340, 24361, 24362, 24363, 24364, 24365, 24366, 24367, 24388, 24389, 24390, 24391, 24392, 24393, 24394, 24415, 24416, 24417, 24418, 24419, 24420, 24421, 24442, 24443, 24444, 24445, 24446, 24447, 24448, 24469, 24470, 24471, 24472, 24473, 24474, 24475, 24496, 24497, 24498, 24499, 24500, 24501, 24502, 24523, 24524, ...], ('NORTE', 'GNV'): [37234, 37266, 37299, 37391, 37407, 37438, 37454, 37470, 37486, 37502, 37518, 37534, 37550, 37566, 37582, 37598, 37629, 37645, 37661, 37678, 37694, 37710, 37726, 37742, 37758, 37774, 37790, 37806, 37822, 37838, 37854, 37870, 37887, 37904, 37921, 37938, 37955, 37972, 37989, 38006, 38023, 38040, 38057, 38074, 38091, 38123, 38140, 38156, 38173, 38190, 38207, 38224, 38241, 38258, 38275, 38292, 38309, 38326, 38342, 38359, 38376, 38392, 38409, 38426, 38443, 38460, 38477, 38510, 38559, 38592, 38609, 38626, 38643, 38660, 38693, 38710, 38727, 38760, 38793, 38826, 38859, 38892, 38972, 39021, 39069, 39134, 39183, 39200, 39234, 39251, 39284, 39301, 39334, 39351, 39384, 39401, 39435, 39452, 39486, 39502, ...], ('NORTE', 'ÓLEO DIESEL'): [43560, 43561, 43562, 43563, 43564, 43565, 43566, 43587, 43588, 43589, 43590, 43591, 43592, 43593, 43614, 43615, 43616, 43617, 43618, 43619, 43620, 43641, 43642, 43643, 43644, 43645, 43646, 43647, 43668, 43669, 43670, 43671, 43672, 43673, 43674, 43695, 43696, 43697, 43698, 43699, 43700, 43701, 43722, 43723, 43724, 43725, 43726, 43727, 43728, 43749, 43750, 43751, 43752, 43753, 43754, 43755, 43776, 43777, 43778, 43779, 43780, 43781, 43782, 43803, 43804, 43805, 43806, 43807, 43808, 43809, 43830, 43831, 43832, 43833, 43834, 43835, 43836, 43857, 43858, 43859, 43860, 43861, 43862, 43863, 43884, 43885, 43886, 43887, 43888, 43889, 43890, 43911, 43912, 43913, 43914, 43915, 43916, 43917, 43938, 43939, ...], ('NORTE', 'ÓLEO DIESEL S10'): [55676, 55682, 55686, 55813, 55815, 55824, 55832, 55836, 55963, 55964, 55974, 55982, 55983, 55987, 56113, 56115, 56116, 56126, 56134, 56135, 56139, 56266, 56268, 56269, 56279, 56287, 56288, 56292, 56419, 56421, 56422, 56432, 56440, 56441, 56445, 56571, 56573, 56574, 56584, 56592, 56593, 56597, 56723, 56725, 56726, 56736, 56744, 56745, 56749, 56876, 56878, 56879, 56889, 56897, 56898, 56902, 57029, 57031, 57032, 57042, 57050, 57051, 57055, 57181, 57183, 57184, 57194, 57202, 57203, 57207, 57333, 57335, 57336, 57346, 57354, 57355, 57359, 57484, 57486, 57487, 57497, 57505, 57506, 57510, 57636, 57638, 57639, 57649, 57657, 57658, 57662, 57789, 57791, 57792, 57802, 57810, 57811, 57815, 57941, 57943, ...], ('SUDESTE', 'ETANOL HIDRATADO'): [20, 21, 22, 23, 47, 48, 49, 50, 74, 75, 76, 77, 101, 102, 103, 104, 128, 129, 130, 131, 155, 156, 157, 158, 182, 183, 184, 185, 209, 210, 211, 212, 236, 237, 238, 239, 263, 264, 265, 266, 290, 291, 292, 293, 317, 318, 319, 320, 344, 345, 346, 347, 371, 372, 373, 374, 398, 399, 400, 401, 425, 426, 427, 428, 452, 453, 454, 455, 479, 480, 481, 482, 506, 507, 508, 509, 533, 534, 535, 536, 560, 561, 562, 563, 587, 588, 589, 590, 614, 615, 616, 617, 641, 642, 643, 644, 668, 669, 670, 671, ...], ('SUDESTE', 'GASOLINA COMUM'): [12084, 12085, 12086, 12087, 12111, 12112, 12113, 12114, 12138, 12139, 12140, 12141, 12165, 12166, 12167, 12168, 12192, 12193, 12194, 12195, 12219, 12220, 12221, 12222, 12246, 12247, 12248, 12249, 12273, 12274, 12275, 12276, 12300, 12301, 12302, 12303, 12327, 12328, 12329, 12330, 12354, 12355, 12356, 12357, 12381, 12382, 12383, 12384, 12408, 12409, 12410, 12411, 12435, 12436, 12437, 12438, 12462, 12463, 12464, 12465, 12489, 12490, 12491, 12492, 12516, 12517, 12518, 12519, 12543, 12544, 12545, 12546, 12570, 12571, 12572, 12573, 12597, 12598, 12599, 12600, 12624, 12625, 12626, 12627, 12651, 12652, 12653, 12654, 12678, 12679, 12680, 12681, 12705, 12706, 12707, 12708, 12732, 12733, 12734, 12735, ...], ('SUDESTE', 'GLP'): [24152, 24153, 24154, 24155, 24179, 24180, 24181, 24182, 24206, 24207, 24208, 24209, 24233, 24234, 24235, 24236, 24260, 24261, 24262, 24263, 24287, 24288, 24289, 24290, 24314, 24315, 24316, 24317, 24341, 24342, 24343, 24344, 24368, 24369, 24370, 24371, 24395, 24396, 24397, 24398, 24422, 24423, 24424, 24425, 24449, 24450, 24451, 24452, 24476, 24477, 24478, 24479, 24503, 24504, 24505, 24506, 24530, 24531, 24532, 24533, 24557, 24558, 24559, 24560, 24584, 24585, 24586, 24587, 24611, 24612, 24613, 24614, 24638, 24639, 24640, 24641, 24665, 24666, 24667, 24668, 24692, 24693, 24694, 24695, 24719, 24720, 24721, 24722, 24746, 24747, 24748, 24749, 24773, 24774, 24775, 24776, 24800, 24801, 24802, 24803, ...], ('SUDESTE', 'GNV'): [36204, 36205, 36206, 36207, 36219, 36220, 36221, 36222, 36234, 36235, 36236, 36237, 36249, 36250, 36251, 36252, 36264, 36265, 36266, 36267, 36279, 36280, 36281, 36282, 36294, 36295, 36296, 36297, 36309, 36310, 36311, 36312, 36324, 36325, 36326, 36327, 36339, 36340, 36341, 36342, 36354, 36355, 36356, 36357, 36370, 36371, 36372, 36373, 36386, 36387, 36388, 36389, 36402, 36403, 36404, 36405, 36418, 36419, 36420, 36421, 36434, 36435, 36436, 36437, 36450, 36451, 36452, 36453, 36466, 36467, 36468, 36469, 36482, 36483, 36484, 36485, 36498, 36499, 36500, 36501, 36514, 36515, 36516, 36517, 36530, 36531, 36532, 36533, 36546, 36547, 36548, 36549, 36562, 36563, 36564, 36565, 36578, 36579, 36580, 36581, ...], ('SUDESTE', 'ÓLEO DIESEL'): [43567, 43568, 43569, 43570, 43594, 43595, 43596, 43597, 43621, 43622, 43623, 43624, 43648, 43649, 43650, 43651, 43675, 43676, 43677, 43678, 43702, 43703, 43704, 43705, 43729, 43730, 43731, 43732, 43756, 43757, 43758, 43759, 43783, 43784, 43785, 43786, 43810, 43811, 43812, 43813, 43837, 43838, 43839, 43840, 43864, 43865, 43866, 43867, 43891, 43892, 43893, 43894, 43918, 43919, 43920, 43921, 43945, 43946, 43947, 43948, 43972, 43973, 43974, 43975, 43999, 44000, 44001, 44002, 44026, 44027, 44028, 44029, 44053, 44054, 44055, 44056, 44080, 44081, 44082, 44083, 44107, 44108, 44109, 44110, 44134, 44135, 44136, 44137, 44161, 44162, 44163, 44164, 44188, 44189, 44190, 44191, 44215, 44216, 44217, 44218, ...], ('SUDESTE', 'ÓLEO DIESEL S10'): [55671, 55675, 55680, 55684, 55818, 55823, 55829, 55834, 55968, 55973, 55979, 55985, 56120, 56125, 56131, 56137, 56273, 56278, 56284, 56290, 56426, 56431, 56437, 56443, 56578, 56583, 56589, 56595, 56730, 56735, 56741, 56747, 56883, 56888, 56894, 56900, 57036, 57041, 57047, 57053, 57188, 57193, 57199, 57205, 57340, 57345, 57351, 57357, 57491, 57496, 57502, 57508, 57643, 57648, 57654, 57660, 57796, 57801, 57807, 57813, 57948, 57953, 57959, 57965, 58100, 58105, 58111, 58117, 58252, 58257, 58263, 58269, 58403, 58408, 58414, 58420, 58555, 58560, 58566, 58572, 58707, 58712, 58718, 58724, 58859, 58864, 58870, 58876, 59012, 59017, 59023, 59029, 59164, 59169, 59175, 59181, 59316, 59321, 59327, 59333, ...], ('SUL', 'ETANOL HIDRATADO'): [24, 25, 26, 51, 52, 53, 78, 79, 80, 105, 106, 107, 132, 133, 134, 159, 160, 161, 186, 187, 188, 213, 214, 215, 240, 241, 242, 267, 268, 269, 294, 295, 296, 321, 322, 323, 348, 349, 350, 375, 376, 377, 402, 403, 404, 429, 430, 431, 456, 457, 458, 483, 484, 485, 510, 511, 512, 537, 538, 539, 564, 565, 566, 591, 592, 593, 618, 619, 620, 645, 646, 647, 672, 673, 674, 699, 700, 701, 726, 727, 728, 753, 754, 755, 780, 781, 782, 807, 808, 809, 834, 835, 836, 861, 862, 863, 888, 889, 890, 915, ...], ('SUL', 'GASOLINA COMUM'): [12088, 12089, 12090, 12115, 12116, 12117, 12142, 12143, 12144, 12169, 12170, 12171, 12196, 12197, 12198, 12223, 12224, 12225, 12250, 12251, 12252, 12277, 12278, 12279, 12304, 12305, 12306, 12331, 12332, 12333, 12358, 12359, 12360, 12385, 12386, 12387, 12412, 12413, 12414, 12439, 12440, 12441, 12466, 12467, 12468, 12493, 12494, 12495, 12520, 12521, 12522, 12547, 12548, 12549, 12574, 12575, 12576, 12601, 12602, 12603, 12628, 12629, 12630, 12655, 12656, 12657, 12682, 12683, 12684, 12709, 12710, 12711, 12736, 12737, 12738, 12763, 12764, 12765, 12790, 12791, 12792, 12817, 12818, 12819, 12844, 12845, 12846, 12871, 12872, 12873, 12898, 12899, 12900, 12925, 12926, 12927, 12952, 12953, 12954, 12979, ...], ('SUL', 'GLP'): [24156, 24157, 24158, 24183, 24184, 24185, 24210, 24211, 24212, 24237, 24238, 24239, 24264, 24265, 24266, 24291, 24292, 24293, 24318, 24319, 24320, 24345, 24346, 24347, 24372, 24373, 24374, 24399, 24400, 24401, 24426, 24427, 24428, 24453, 24454, 24455, 24480, 24481, 24482, 24507, 24508, 24509, 24534, 24535, 24536, 24561, 24562, 24563, 24588, 24589, 24590, 24615, 24616, 24617, 24642, 24643, 24644, 24669, 24670, 24671, 24696, 24697, 24698, 24723, 24724, 24725, 24750, 24751, 24752, 24777, 24778, 24779, 24804, 24805, 24806, 24831, 24832, 24833, 24858, 24859, 24860, 24885, 24886, 24887, 24912, 24913, 24914, 24939, 24940, 24941, 24966, 24967, 24968, 24993, 24994, 24995, 25020, 25021, 25022, 25047, ...], ('SUL', 'GNV'): [36208, 36209, 36210, 36223, 36224, 36225, 36238, 36239, 36240, 36253, 36254, 36255, 36268, 36269, 36270, 36283, 36284, 36285, 36298, 36299, 36300, 36313, 36314, 36315, 36328, 36329, 36330, 36343, 36344, 36345, 36358, 36359, 36360, 36374, 36375, 36376, 36390, 36391, 36392, 36406, 36407, 36408, 36422, 36423, 36424, 36438, 36439, 36440, 36454, 36455, 36456, 36470, 36471, 36472, 36486, 36487, 36488, 36502, 36503, 36504, 36518, 36519, 36520, 36534, 36535, 36536, 36550, 36551, 36552, 36566, 36567, 36568, 36582, 36583, 36584, 36598, 36599, 36600, 36614, 36615, 36616, 36630, 36631, 36632, 36646, 36647, 36648, 36662, 36663, 36664, 36678, 36679, 36680, 36694, 36695, 36696, 36710, 36711, 36712, 36726, ...], ('SUL', 'ÓLEO DIESEL'): [43571, 43572, 43573, 43598, 43599, 43600, 43625, 43626, 43627, 43652, 43653, 43654, 43679, 43680, 43681, 43706, 43707, 43708, 43733, 43734, 43735, 43760, 43761, 43762, 43787, 43788, 43789, 43814, 43815, 43816, 43841, 43842, 43843, 43868, 43869, 43870, 43895, 43896, 43897, 43922, 43923, 43924, 43949, 43950, 43951, 43976, 43977, 43978, 44003, 44004, 44005, 44030, 44031, 44032, 44057, 44058, 44059, 44084, 44085, 44086, 44111, 44112, 44113, 44138, 44139, 44140, 44165, 44166, 44167, 44192, 44193, 44194, 44219, 44220, 44

In [156]:
grupos.mean()

TypeError: agg function failed [how->mean,dtype->object]

In [159]:
grupos['PREÇO MÉDIO REVENDA'].describe()

                                count       mean        std     min       25%  \
REGIÃO       PRODUTO
CENTRO OESTE ETANOL HIDRATADO  3140.0   2.135950   0.561154   1.162   1.71600
             GASOLINA COMUM    3140.0   3.078123   0.616315   1.936   2.66800
             GLP               3137.0  48.181149  15.189152  28.791  37.34000
             GNV               1523.0   2.004153   0.457802   1.097   1.59900
             ÓLEO DIESEL       3140.0   2.481534   0.627607   1.435   2.03300
             ÓLEO DIESEL S10   1349.0   3.241185   0.433797   2.212   2.82000
NORDESTE     ETANOL HIDRATADO  7064.0   2.322075   0.605121   1.181   1.82500
             GASOLINA COMUM    7065.0   3.002337   0.641163   1.949   2.58400
             GLP               7061.0  42.221312  11.654978  28.367  33.59800
             GNV               5575.0   1.925318   0.555183   0.975   1.60300
             ÓLEO DIESEL       7065.0   2.347550   0.606381   1.313   1.90000
             ÓLEO DIESEL S10   3039.0   3.041957   0.442555   2.130   2.60000
NORTE        ETANOL HIDRATADO  5404.0   2.530796   0.655421   1.226   2.04600
             GASOLINA COMUM    5494.0   3.149212   0.640964   1.995   2.70525
             GLP               5494.0  47.174539  14.477296  28.086  36.50925
             GNV                457.0   2.000190   0.602366   1.219   1.39900
             ÓLEO DIESEL       5494.0   2.569905   0.650350   1.450   2.08800
             ÓLEO DIESEL S10   2359.0   3.310619   0.533966   2.172   2.87800
SUDESTE      ETANOL HIDRATADO  3140.0   2.164832   0.652355   0.766   1.69275
             GASOLINA COMUM    3140.0   3.000565   0.698573   1.888   2.50200
             GLP               3139.0  42.077813  11.522013  28.026  33.63850
             GNV               3136.0   1.779684   0.507284   0.996   1.47300
             ÓLEO DIESEL       3140.0   2.339699   0.588641   1.356   1.87600
             ÓLEO DIESEL S10   1352.0   3.054425   0.419618   2.180   2.64700
SUL          ETANOL HIDRATADO  2354.0   2.268864   0.703567   0.922   1.72100
             GASOLINA COMUM    2355.0   2.973136   0.624032   1.961   2.54300
             GLP               2355.0  43.535465  11.628193  29.440  34.82450
             GNV               2343.0   1.907944   0.500694   1.168   1.51200
             ÓLEO DIESEL       2355.0   2.332862   0.528454   1.374   1.95100
             ÓLEO DIESEL S10   1014.0   2.981745   0.366952   2.140   2.66300

                                   50%       75%     max
REGIÃO       PRODUTO
CENTRO OESTE ETANOL HIDRATADO   2.0010   2.47900   3.999
             GASOLINA COMUM     2.8560   3.46025   4.963
             GLP               42.8570  55.90500  99.357
             GNV                1.9550   2.35250   3.890
             ÓLEO DIESEL        2.2455   3.01900   4.162
             ÓLEO DIESEL S10    3.2640   3.58400   4.200
NORDESTE     ETANOL HIDRATADO   2.1880   2.67550   3.927
             GASOLINA COMUM     2.7420   3.42500   4.951
             GLP               37.5750  48.18300  79.630
             GNV                1.8210   2.16850   3.811
             ÓLEO DIESEL        2.0820   2.87300   4.114
             ÓLEO DIESEL S10    3.0870   3.33800   4.069
NORTE        ETANOL HIDRATADO   2.3430   2.93525   4.459
             GASOLINA COMUM     2.9320   3.57975   5.362
             GLP               42.4535  54.63575  87.270
             GNV                1.8500   2.30000   4.020
             ÓLEO DIESEL        2.3340   3.08000   4.774
             ÓLEO DIESEL S10    3.3070   3.65300   4.878
SUDESTE      ETANOL HIDRATADO   2.0435   2.57200   4.115
             GASOLINA COMUM     2.7930   3.45150   5.119
             GLP               38.2660  49.25100  79.192
             GNV                1.6940   2.00300   3.594
             ÓLEO DIESEL        2.0825   2.82500   3.994
             ÓLEO DIESEL S10    3.0900   3.38600   4.080
SUL          ETANOL HIDRATADO   2.1140   2.60325   4.287
             GASOLINA COMUM     2.7320   3.34350   4.953
             GLP               40.0470  51.41250  72.088
             GNV                1.8000   2.19250   3.499
             ÓLEO DIESEL        2.0900   2.78550   3.800
             ÓLEO DIESEL S10    2.9910   3.25400   3.815

<br/>

`.agg`: **agrega (roda)** uma série de funções para os elementos de um dataframe ou de grupos de um dataframe.

In [161]:
df = pd.DataFrame([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [None, None, None]],
                  columns=['A', 'B', 'C'])
df

     A    B    C
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0
3  NaN  NaN  NaN

In [163]:
df.agg([sum, min]) # ignora o NaN

/tmp/ipython-input-478521018.py:1: FutureWarning: The provided callable <built-in function sum> is currently using Series.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.agg([sum, min]) # ignora o NaN
/tmp/ipython-input-478521018.py:1: FutureWarning: The provided callable <built-in function min> is currently using Series.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.agg([sum, min]) # ignora o NaN

        A     B     C
sum  12.0  15.0  18.0
min   1.0   2.0   3.0

In [164]:
grupos = data_final.groupby('REGIÃO')
grupos

In [165]:
# Computa o menor e maior valor do 'PREÇO MÉDIO REVENDA' para cada região (grupo)
grupos['PREÇO MÉDIO REVENDA'].agg([min, max])

/tmp/ipython-input-2265528623.py:2: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  grupos['PREÇO MÉDIO REVENDA'].agg([min, max])
/tmp/ipython-input-2265528623.py:2: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  grupos['PREÇO MÉDIO REVENDA'].agg([min, max])

                min     max
REGIÃO
CENTRO OESTE  1.097  99.357
NORDESTE      0.975  79.630
NORTE         1.219  87.270
SUDESTE       0.766  79.192
SUL           0.922  72.088

<h2>6. Ordenação</h2>
<hr/>

In [166]:
notas = pd.DataFrame({
    'nome': ['João', 'Maria', 'José', 'Alice'],
    'idade': [20, 21, 19, 20],
    'nota_final': [5.0, 10.0, 6.0, 10.0]
})
notas

    nome  idade  nota_final
0   João     20         5.0
1  Maria     21        10.0
2   José     19         6.0
3  Alice     20        10.0

`.sort_values()`: ordena valores ao longo de um eixo.

In [167]:
notas.sort_values(by='nota_final')

    nome  idade  nota_final
0   João     20         5.0
2   José     19         6.0
1  Maria     21        10.0
3  Alice     20        10.0

Por padrão, o método retorna uma cópia dos dados ordenados em **ordem crescente (ascendente)**. Podemos alterar isso pelo argumento `ascending`.

In [173]:
notas.sort_values(by='nota_final', ascending=False)

    nome  idade  nota_final
1  Maria     21        10.0
3  Alice     20        10.0
2   José     19         6.0
0   João     20         5.0

<br/>

Podemos ordenar a partir de **mais de uma coluna**:

In [174]:
notas.sort_values(by=['nota_final', 'nome'], ascending=[False, True])

    nome  idade  nota_final
3  Alice     20        10.0
1  Maria     21        10.0
2   José     19         6.0
0   João     20         5.0

Ordena os registros, primeiramente, pela coluna 'nota_final' em **ordem descrente**. <br/>
Então, reordena os registros _"empatados"_, ou seja, com a **mesma nota final**, em _ordem alfabética_ (ordem crescente).

<br/>

Note que o dataframe original **não foi alterado** após a ordenação.

In [175]:
notas

    nome  idade  nota_final
0   João     20         5.0
1  Maria     21        10.0
2   José     19         6.0
3  Alice     20        10.0

Para alterá-lo, use o argumento `inplace=True`:

In [176]:
notas.sort_values(by=['nota_final', 'nome'], ascending=[False, True], inplace=True)

In [177]:
notas

    nome  idade  nota_final
3  Alice     20        10.0
1  Maria     21        10.0
2   José     19         6.0
0   João     20         5.0

<h2>7. Exercícios</h2>
<hr/>

In [178]:
data_final

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,3.690,0.818,0.018,2.756,0.000,2.7560,2.75600,0,6,2019
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,3.789,0.950,0.038,2.451,0.402,1.9842,2.86610,0.164,6,2019
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,3.499,0.914,0.065,1.998,0.000,1.9981,1.99810,0,6,2019
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.50930,0.07,6,2019
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,3.699,1.179,0.001,2.518,0.000,2.5175,2.51750,0,6,2019

Vamos aplicar os conceitos que vimos em alguns exercícios. <br/>
Para isso, utilizaremos o dataset de _preços de combustíveis no Brasil_.

Como há apenas medições de janeiro a junho para o ano de 2019, resolvemos **remover os dados** deste ano da análise.

In [179]:
data_final.query('ANO != 2019')

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103064,103064,2018-12-30,2019-01-05,NORDESTE,RIO GRANDE DO NORTE,GNV,10,R$/m3,3.465,0.060,...,3.590,0.759,0.017,2.706,0.000,2.7059,2.70590,0,12,2018
103065,103065,2018-12-30,2019-01-05,SUL,RIO GRANDE DO SUL,GNV,16,R$/m3,3.402,0.103,...,3.499,1.296,0.030,2.106,0.249,1.8775,2.37240,0.118,12,2018
103066,103066,2018-12-30,2019-01-05,SUL,SANTA CATARINA,GNV,15,R$/m3,2.944,0.124,...,3.199,0.670,0.042,2.274,0.283,1.8738,2.27400,0.124,12,2018
103067,103067,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,GNV,41,R$/m3,2.353,0.451,...,3.429,0.467,0.192,1.886,0.250,1.6400,2.33200,0.133,12,2018
103068,103068,2018-12-30,2019-01-05,NORDESTE,SERGIPE,GNV,2,R$/m3,3.649,0.000,...,3.649,0.000,0.000,0.000,0.000,0.0000,0.00000,-,12,2018

Note que temos um novo dataframe com 99739 linhas, mas com índices fora desse intervalo. <br/>
Acontece que os registros mantiveram seus índices originais após a query. <br/>

Para resetar os índices de _0 a num_linhas-1_, basta usarmos o método `.reset_index()`.

In [180]:
df = data_final.query('ANO != 2019')

In [181]:
df

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103064,103064,2018-12-30,2019-01-05,NORDESTE,RIO GRANDE DO NORTE,GNV,10,R$/m3,3.465,0.060,...,3.590,0.759,0.017,2.706,0.000,2.7059,2.70590,0,12,2018
103065,103065,2018-12-30,2019-01-05,SUL,RIO GRANDE DO SUL,GNV,16,R$/m3,3.402,0.103,...,3.499,1.296,0.030,2.106,0.249,1.8775,2.37240,0.118,12,2018
103066,103066,2018-12-30,2019-01-05,SUL,SANTA CATARINA,GNV,15,R$/m3,2.944,0.124,...,3.199,0.670,0.042,2.274,0.283,1.8738,2.27400,0.124,12,2018
103067,103067,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,GNV,41,R$/m3,2.353,0.451,...,3.429,0.467,0.192,1.886,0.250,1.6400,2.33200,0.133,12,2018
103068,103068,2018-12-30,2019-01-05,NORDESTE,SERGIPE,GNV,2,R$/m3,3.649,0.000,...,3.649,0.000,0.000,0.000,0.000,0.0000,0.00000,-,12,2018

### 7.1 Qual a proporção de postos pesquisados para cada combustível em cada região

In [182]:
grupos = df.groupby('PRODUTO')
grupos

In [184]:
grupos['REGIÃO'].value_counts().to_frame()

                               count
PRODUTO          REGIÃO
ETANOL HIDRATADO NORDESTE       6839
                 NORTE          5244
                 CENTRO OESTE   3040
                 SUDESTE        3040
                 SUL            2279
GASOLINA COMUM   NORDESTE       6840
                 NORTE          5319
                 CENTRO OESTE   3040
                 SUDESTE        3040
                 SUL            2280
GLP              NORDESTE       6836
                 NORTE          5319
                 SUDESTE        3039
                 CENTRO OESTE   3037
                 SUL            2280
GNV              NORDESTE       5398
                 SUDESTE        3036
                 SUL            2269
                 CENTRO OESTE   1493
                 NORTE           444
ÓLEO DIESEL      NORDESTE       6840
                 NORTE          5319
                 CENTRO OESTE   3040
                 SUDESTE        3040
                 SUL            2280
ÓLEO DIESEL S10  NORDESTE       2814
                 NORTE          2184
                 SUDESTE        1252
                 CENTRO OESTE   1249
                 SUL             939

### 7.2 Como os preços da Gasolina Comum em São Paulo variaram em 2018?

In [190]:
gasolina_sp_2018 = df.query('PRODUTO == "GASOLINA COMUM" and ESTADO == "SAO PAULO" and ANO == 2018')
gasolina_sp_2018.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
95351,95351,2018-01-07,2018-01-13,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,3.988,0.156,...,4.599,0.411,0.039,3.577,0.104,2.990,3.9510,0.029,1,2018
95502,95502,2018-01-14,2018-01-20,SUDESTE,SAO PAULO,GASOLINA COMUM,1648,R$/l,4.002,0.155,...,4.499,0.412,0.039,3.590,0.102,2.990,3.9014,0.028,1,2018
95654,95654,2018-01-21,2018-01-27,SUDESTE,SAO PAULO,GASOLINA COMUM,1648,R$/l,4.006,0.160,...,4.899,0.410,0.040,3.596,0.102,2.990,3.9014,0.028,1,2018
95806,95806,2018-01-28,2018-02-03,SUDESTE,SAO PAULO,GASOLINA COMUM,1644,R$/l,4.019,0.156,...,4.699,0.423,0.039,3.596,0.107,2.924,3.9537,0.03,1,2018
95958,95958,2018-02-04,2018-02-10,SUDESTE,SAO PAULO,GASOLINA COMUM,1646,R$/l,4.004,0.157,...,4.597,0.416,0.039,3.588,0.102,2.990,3.9537,0.028,2,2018

In [191]:
gasolina_sp_2018.shape

(52, 21)

#### **Estatísticas Descritivas**

In [192]:
gasolina_sp_2018.describe()

,Unnamed: 0,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,MÊS,ANO
count,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.000000,52.00000,52.000000,52.000000,52.0
mean,99196.096154,1610.211538,4.202769,0.175500,3.671500,4.975750,0.442481,0.041750,3.760288,0.109654,3.31295,4.139454,6.615385,2018.0
std,2279.595314,213.627432,0.180672,0.017955,0.163808,0.211198,0.063271,0.003965,0.163664,0.010712,0.26684,0.195897,3.470627,0.0
min,95351.000000,102.000000,3.970000,0.150000,3.369000,4.499000,0.366000,0.034000,3.563000,0.087000,2.92400,3.887500,1.000000,2018.0
25%,97281.250000,1639.000000,4.008000,0.159750,3.499000,4.899000,0.404500,0.039000,3.620250,0.102000,2.99000,3.965775,4.000000,2018.0
50%,99196.500000,1642.000000,4.202000,0.173000,3.679000,4.999000,0.421500,0.040000,3.756500,0.108000,3.35000,4.095500,7.000000,2018.0
75%,101116.250000,1644.000000,4.336250,0.189000,3.784000,5.099000,0.470250,0.044000,3.862250,0.116250,3.53250,4.259000,9.250000,2018.0
max,103025.000000,1649.000000,4.512000,0.216000,3.969000,5.299000,0.640000,0.051000,4.085000,0.144000,3.76000,4.551000,12.000000,2018.0

In [194]:
gasolina_sp_2018['PREÇO MÉDIO REVENDA'].describe().to_frame()

       PREÇO MÉDIO REVENDA
count            52.000000
mean              4.202769
std               0.180672
min               3.970000
25%               4.008000
50%               4.202000
75%               4.336250
max               4.512000

### 7.3 Como os preços da Gasolina Comum e do Etanol em São Paulo variaram em 2018?

In [195]:
df.query('PRODUTO == "GASOLINA COMUM" or PRODUTO == "ETANOL HIDRATADO" and ESTADO == "SAO PAULO" and ANO == 2018')

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
12064,12064,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,GASOLINA COMUM,128,R$/l,2.029,0.007,...,2.070,0.318,0.003,1.711,0.020,1.65100,1.7427,0.012,5,2004
12065,12065,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,GASOLINA COMUM,395,R$/l,2.025,0.062,...,2.220,0.296,0.031,1.729,0.036,1.66430,1.9150,0.021,5,2004
12066,12066,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,GASOLINA COMUM,194,R$/l,2.358,0.066,...,2.540,0.472,0.028,1.886,0.068,1.75000,2.0713,0.036,5,2004
12067,12067,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,GASOLINA COMUM,166,R$/l,2.120,0.075,...,2.440,0.325,0.035,1.795,0.033,1.70701,1.9703,0.018,5,2004
12068,12068,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,GASOLINA COMUM,106,R$/l,2.090,0.034,...,2.159,0.350,0.016,1.740,0.042,1.67890,1.9180,0.024,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103023,103023,2018-12-30,2019-01-05,NORTE,RORAIMA,GASOLINA COMUM,13,R$/l,4.058,0.013,...,4.080,0.537,0.003,3.521,0.099,3.41500,3.6852,0.028,12,2018
103024,103024,2018-12-30,2019-01-05,SUL,SANTA CATARINA,GASOLINA COMUM,252,R$/l,4.055,0.138,...,4.490,0.361,0.034,3.694,0.108,3.46000,3.8970,0.029,12,2018
103025,103025,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,GASOLINA COMUM,1643,R$/l,4.113,0.201,...,4.999,0.503,0.049,3.610,0.100,3.35000,3.9585,0.028,12,2018
103026,103026,2018-12-30,2019-01-05,NORDESTE,SERGIPE,GASOLINA COMUM,42,R$/l,4.377,0.081,...,4.595,0.447,0.019,3.930,0.048,3.83320,3.9828,0.012,12,2018
103027,103027,2018-12-30,2019-01-05,NORTE,TOCANTINS,GASOLINA COMUM,46,R$/l,4.571,0.311,...,6.290,0.673,0.068,3.898,0.042,3.78000,3.9570,0.011,12,2018

In [197]:
lista_de_estados = ["GASOLINA COMUM", "ETANOL HIDRATADO"]
df.query('PRODUTO in @lista_de_estados and ESTADO == "SAO PAULO" and ANO == 2018')

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
95270,95270,2018-01-07,2018-01-13,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1664,R$/l,2.833,0.139,...,3.399,0.338,0.049,2.495,0.092,2.1842,2.8833,0.037,1,2018
95351,95351,2018-01-07,2018-01-13,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,3.988,0.156,...,4.599,0.411,0.039,3.577,0.104,2.9900,3.9510,0.029,1,2018
95421,95421,2018-01-14,2018-01-20,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1661,R$/l,2.868,0.134,...,3.399,0.331,0.047,2.537,0.087,2.2600,2.8471,0.034,1,2018
95502,95502,2018-01-14,2018-01-20,SUDESTE,SAO PAULO,GASOLINA COMUM,1648,R$/l,4.002,0.155,...,4.499,0.412,0.039,3.590,0.102,2.9900,3.9014,0.028,1,2018
95573,95573,2018-01-21,2018-01-27,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1662,R$/l,2.874,0.135,...,3.399,0.324,0.047,2.550,0.095,1.6900,2.9722,0.037,1,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102724,102724,2018-12-16,2018-12-22,SUDESTE,SAO PAULO,GASOLINA COMUM,1637,R$/l,4.129,0.201,...,5.099,0.490,0.049,3.639,0.110,3.3500,3.9892,0.03,12,2018
102793,102793,2018-12-23,2018-12-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1662,R$/l,2.644,0.163,...,3.699,0.305,0.062,2.339,0.094,2.0067,2.7443,0.04,12,2018
102874,102874,2018-12-23,2018-12-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,4.129,0.201,...,4.999,0.484,0.049,3.645,0.107,3.3500,3.9892,0.029,12,2018
102944,102944,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1661,R$/l,2.643,0.161,...,3.699,0.303,0.061,2.340,0.097,1.9072,2.7957,0.041,12,2018
103025,103025,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,GASOLINA COMUM,1643,R$/l,4.113,0.201,...,4.999,0.503,0.049,3.610,0.100,3.3500,3.9585,0.028,12,2018

In [200]:
gasolina_etanol_sp_2018 = df.query('PRODUTO in ["GASOLINA COMUM", "ETANOL HIDRATADO"] and ESTADO == "SAO PAULO" and ANO == 2018')
gasolina_etanol_sp_2018

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
95270,95270,2018-01-07,2018-01-13,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1664,R$/l,2.833,0.139,...,3.399,0.338,0.049,2.495,0.092,2.1842,2.8833,0.037,1,2018
95351,95351,2018-01-07,2018-01-13,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,3.988,0.156,...,4.599,0.411,0.039,3.577,0.104,2.9900,3.9510,0.029,1,2018
95421,95421,2018-01-14,2018-01-20,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1661,R$/l,2.868,0.134,...,3.399,0.331,0.047,2.537,0.087,2.2600,2.8471,0.034,1,2018
95502,95502,2018-01-14,2018-01-20,SUDESTE,SAO PAULO,GASOLINA COMUM,1648,R$/l,4.002,0.155,...,4.499,0.412,0.039,3.590,0.102,2.9900,3.9014,0.028,1,2018
95573,95573,2018-01-21,2018-01-27,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1662,R$/l,2.874,0.135,...,3.399,0.324,0.047,2.550,0.095,1.6900,2.9722,0.037,1,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102724,102724,2018-12-16,2018-12-22,SUDESTE,SAO PAULO,GASOLINA COMUM,1637,R$/l,4.129,0.201,...,5.099,0.490,0.049,3.639,0.110,3.3500,3.9892,0.03,12,2018
102793,102793,2018-12-23,2018-12-29,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1662,R$/l,2.644,0.163,...,3.699,0.305,0.062,2.339,0.094,2.0067,2.7443,0.04,12,2018
102874,102874,2018-12-23,2018-12-29,SUDESTE,SAO PAULO,GASOLINA COMUM,1641,R$/l,4.129,0.201,...,4.999,0.484,0.049,3.645,0.107,3.3500,3.9892,0.029,12,2018
102944,102944,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,ETANOL HIDRATADO,1661,R$/l,2.643,0.161,...,3.699,0.303,0.061,2.340,0.097,1.9072,2.7957,0.041,12,2018
103025,103025,2018-12-30,2019-01-05,SUDESTE,SAO PAULO,GASOLINA COMUM,1643,R$/l,4.113,0.201,...,4.999,0.503,0.049,3.610,0.100,3.3500,3.9585,0.028,12,2018

In [201]:
# considerando os preços do etanol e da gasolina juntos, teremos essas estatísticas descritivas
gasolina_etanol_sp_2018['PREÇO MÉDIO REVENDA'].describe().to_frame()

       PREÇO MÉDIO REVENDA
count           104.000000
mean              3.457337
std               0.766239
min               2.393000
25%               2.726000
50%               3.431000
75%               4.199000
max               4.512000

In [202]:
gasolina_etanol_sp_2018.groupby('PRODUTO')['PREÇO MÉDIO REVENDA'].describe()

,count,mean,std,min,25%,50%,75%,max
PRODUTO,,,,,,,,
ETANOL HIDRATADO,52.0,2.711904,0.141365,2.393,2.6315,2.720,2.83825,2.892
GASOLINA COMUM,52.0,4.202769,0.180672,3.970,4.0080,4.202,4.33625,4.512

<h2>8. Assuntos para continuar os estudos</h2>
<hr/>

- join
- concat
- plot
- data cleaning