In [ ]:
import pandas as pd
import numpy as np 
df_vendas = pd.read_csv("vendas_tech.csv",low_memory=False)#encoding='latin1  #se tive ralgm erro sep=";") = seperador 
df_vendedores = pd.read_excel('gerentes_lojas.xlsx')
display(df_vendas)

/tmp/ipykernel_21612/2336693548.py:3: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_vendas = pd.read_csv("vendas_tech.csv")

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

In [8]:
display(df_vendas)
display(df_vendas.sample(15))
display(df_vendas.shape)
display(list(df_vendas.columns))
display(df_vendas.info())
display(df_vendas.describe())

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
7532,7533,2023-12-09,Recife,iPhone 14,5500.0,1,Cliente_17648,NaN
36327,36328,2024-02-27,Curitiba,Teclado Mecânico,250.0,1,Cliente_7460,NaN
87539,87540,2024-02-13,Curitiba,Notebook Dell,3500.0,1,Cliente_13037,NaN
15355,15356,2024-02-08,Curitiba,"Monitor 27""",1200.0,1,Cliente_10262,NaN
28990,28991,2023-02-05,Recife,"Monitor 27""",1200.0,1,Cliente_10499,NaN
46225,46226,2023-01-18,Salvador,Cabo HDMI,40.0,3,Cliente_17388,NaN
85218,85219,2024-02-02,Rio de Janeiro,Cabo HDMI,40.0,10,Cliente_3933,NaN
96699,96700,2024-07-25,Recife,Smartphone Samsung,2200.0,1,Cliente_21254,NaN
38602,38603,2023-03-01,Curitiba,Cabo HDMI,40.0,1,Cliente_19788,NaN
64794,64795,2024-03-02,Recife,Teclado Mecânico,250.0,1,Cliente_9149,NaN
6562,6563,2023-10-05,Rio de Janeiro,Smartphone Samsung,2200.0,2,Cliente_22478,NaN
65320,65321,2024-08-19,Belo Horizonte,Mouse Gamer,120.0,2,Cliente_14778,NaN
44790,44791,2024-07-18,Recife,Smartphone Samsung,2200.0,1,Cliente_28901,NaN
37035,37036,2024-03-01,Recife,Cabo HDMI,40.0,1,Cliente_3336,NaN
30295,30296,2024-07-29,Belo Horizonte,Mouse Gamer,120.0,1,Cliente_23912,NaN

(100100, 8)

['ID_Pedido',
 'Data',
 'Loja',
 'Produto',
 'Preco_Unitario',
 'Qtd',
 'Cliente',
 'Data_Base']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100100 entries, 0 to 100099
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100100 non-null  int64
 1   Data            100100 non-null  object
 2   Loja            98099 non-null   object
 3   Produto         100100 non-null  object
 4   Preco_Unitario  100100 non-null  float64
 5   Qtd             100100 non-null  int64
 6   Cliente         100100 non-null  object
 7   Data_Base       1 non-null       object
dtypes: float64(1), int64(2), object(5)
memory usage: 6.1+ MB

None

           ID_Pedido  Preco_Unitario            Qtd
count  100100.000000   100100.000000  100100.000000
mean    50004.810180     2000.204595       1.499101
std     28866.872543     1841.050733       1.241605
min         1.000000       40.000000       1.000000
25%     25008.750000      120.000000       1.000000
50%     50004.500000     1200.000000       1.000000
75%     75002.250000     3200.000000       1.000000
max    100000.000000     5500.000000      10.000000

In [ ]:



#tratamneto de dados
#display(df_vendas['loja'])
#df_novo = df_vendas[['Loja','Cliente']]
#display(df_vendas[["Loja","Cliente" ]]) 

#colunas
df_analise = df_vendas.drop(columns={"Data_Base"})

#nulos
df_analise = df_analise.dropna()


# df_analise = df_analise .dropna() #exclui todas linhas vazias 
df_analise["Loja"] = df_analise["Loja"].fillna('Online')
# tipos de dados 
df_analise ['Data'] = pd.to_datetime(df_analise['Data'], format="%Y-%m-%d")
#padronização
df_analise["Loja"] = df_analise["Loja"].str.strip()
df_analise["Loja"] = df_analise["Loja"].str.title()
#encadeamento 


#duplicatas 
df_analise = df_analise.drop_duplicates(subset=['ID_Pedido'])



display(df_analise)
display(df_analise.info())

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
5,6,2023-03-11,São Paulo,Cabo HDMI,40.0,1,Cliente_24809
...,...,...,...,...,...,...,...
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732
99996,99997,2024-08-28,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_25058
99997,99998,2024-03-18,Curitiba,Smartphone Samsung,2200.0,2,Cliente_28864
99998,99999,2023-11-04,Porto Alegre,iPhone 14,5500.0,1,Cliente_4205
99999,100000,2024-06-15,Curitiba,Teclado Mecânico,250.0,1,Cliente_12237

<class 'pandas.core.frame.DataFrame'>
Index: 97999 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Pedido       97999 non-null  int64
 1   Data            97999 non-null  datetime64[ns]
 2   Loja            97999 non-null  object
 3   Produto         97999 non-null  object
 4   Preco_Unitario  97999 non-null  float64
 5   Qtd             97999 non-null  int64
 6   Cliente         97999 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(3)
memory usage: 6.0+ MB

None

In [75]:
#criar novas colunas 




#faturamento 
df_analise['Faturamento'] = df_analise['Qtd'] * df_analise["Preco_Unitario"]

#forma de venda 
df_analise ['forma_de_venda'] = np.where(df_analise['Loja']=='online','Online', 'Presencial')


#regiao
display(df_analise['Loja'].unique()) 
#def definir_regiao(loja):
dic_regioes ={
        'São Paulo' : "Sudeste",
        'Belo Horizonte': "Sudeste",
        'Online': "online",
        'Rio De Janeiro': "Sudeste",
        'Salvador': "Nordeste",
        'Recife': "Nordeste",
        'Curitiba' : "sul",
        'Porto Alegre': "Sul",
    }
    #return dic_regioes[loja]
df_analise["Região"] = df_analise["Loja"].map(dic_regioes)
display(df_analise)
display(df_analise.isna().sum())

array(['Belo Horizonte', 'Salvador', 'Curitiba', 'Porto Alegre', 'Recife',
       'São Paulo', 'Rio De Janeiro'], dtype=object)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,forma_de_venda,Regiao,Faturamento,Região
0,12848,2023-01-01,Belo Horizonte,Cabo HDMI,40.0,1,Cliente_4327,Presencial,Sudeste,40.0,Sudeste
1,93303,2023-01-01,Belo Horizonte,Cabo HDMI,40.0,1,Cliente_11142,Presencial,Sudeste,40.0,Sudeste
2,95393,2023-01-01,Salvador,Cabo HDMI,40.0,1,Cliente_23137,Presencial,Nordeste,40.0,Nordeste
3,97659,2023-01-01,Curitiba,Cabo HDMI,40.0,1,Cliente_58,Presencial,sul,40.0,sul
4,37130,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_22886,Presencial,Sul,40.0,Sul
...,...,...,...,...,...,...,...,...,...,...,...
97994,43207,2024-12-30,Belo Horizonte,Notebook Dell,3500.0,2,Cliente_15893,Presencial,Sudeste,7000.0,Sudeste
97995,40137,2024-12-30,Recife,Notebook Dell,3500.0,2,Cliente_11509,Presencial,Nordeste,7000.0,Nordeste
97996,60794,2024-12-30,Rio De Janeiro,Smartphone Samsung,2200.0,5,Cliente_9964,Presencial,Sudeste,11000.0,Sudeste
97997,35192,2024-12-30,Salvador,iPhone 14,5500.0,2,Cliente_7615,Presencial,Nordeste,11000.0,Nordeste
97998,86379,2024-12-30,Salvador,iPhone 14,5500.0,2,Cliente_25166,Presencial,Nordeste,11000.0,Nordeste

ID_Pedido         0
Data              0
Loja              0
Produto           0
Preco_Unitario    0
Qtd               0
Cliente           0
forma_de_venda    0
Regiao            0
Faturamento       0
Região            0
dtype: int64

In [61]:
#analise de dados -> filtrar
df_analise =  df_analise.sort_values(by=["Data","Faturamento"], ascending=False)

df_analise =  df_analise.reset_index(drop=True)
#.loc: id do peddido
id_pedido = 4
loja = df_analise.loc[3,"Loja"]
produto =  df_analise.loc[3,"Produto"]
cliente =  df_analise.loc[3,"Cliente"]

print(loja,produto,cliente)

#.iloc -> por posicao 
id_pedido = 4 
loja = df_analise.iloc[3,2]
produto = df_analise.iloc[3,3]
cliente = df_analise.iloc[3,6]
print(loja,produto,cliente)
display(df_analise)
#exportar pedaços de dados

KeyError: 'Faturamento'

In [76]:
# analisar -> filtrar

df_analise = df_analise.sort_values(by=["Data", "Faturamento"])
df_analise = df_analise.reset_index(drop=True)

#.loc: id do pedido -> por nome da coluna e por nome da linha
id_pedido = 4

loja = df_analise.loc[df_analise["ID_Pedido"]==4, "Loja"].values[0]
produto = df_analise.loc[df_analise["ID_Pedido"]==4, "Produto"].values[0]
cliente = df_analise.loc[df_analise["ID_Pedido"]==4, "Cliente"].values[0]
#print(loja)
#print(produto)
#print(cliente)

#.iloc -> por posicao
id_pedido = 4
loja = df_analise.iloc[3, 2]
produto = df_analise.iloc[3, 3] 
cliente = df_analise.iloc[3, 6]

#print(loja, produto, cliente)

# condicional
df_id_pedido_4 = df_analise[df_analise["ID_Pedido"]==4]
# exportar pedaços da base
df_vendas_sp = df_analise[df_analise["Loja"]=="São Paulo"]
df_vendas_sp.to_csv("Vendas_SP.csv", index=False)

# exportar as vendas de 2024
df_vendas_2024 = df_analise[df_analise["Data"]>="2024-01-01"]
#df_vendas_2024 = df_analise[df_analise["Data"]dt.year==2024]


# duplas condições
df_vendas_HDMI_SUL = df_analise[(df_analise["Produto"]=="Cabo HDMI") & (df_analise["Região"]=="Sul")]

display(df_vendas_HDMI_SUL)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,forma_de_venda,Regiao,Faturamento,Região
4,37130,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_22886,Presencial,Sul,40.0,Sul
8,1700,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_14435,Presencial,Sul,40.0,Sul
11,70138,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_9348,Presencial,Sul,40.0,Sul
13,49140,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_24445,Presencial,Sul,40.0,Sul
14,35599,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_18680,Presencial,Sul,40.0,Sul
...,...,...,...,...,...,...,...,...,...,...,...
97726,55240,2024-12-29,Porto Alegre,Cabo HDMI,40.0,1,Cliente_3518,Presencial,Sul,40.0,Sul
97728,70148,2024-12-29,Porto Alegre,Cabo HDMI,40.0,1,Cliente_10174,Presencial,Sul,40.0,Sul
97874,75695,2024-12-30,Porto Alegre,Cabo HDMI,40.0,1,Cliente_29587,Presencial,Sul,40.0,Sul
97883,64473,2024-12-30,Porto Alegre,Cabo HDMI,40.0,2,Cliente_11598,Presencial,Sul,80.0,Sul
97885,47774,2024-12-30,Porto Alegre,Cabo HDMI,40.0,2,Cliente_14363,Presencial,Sul,80.0,Sul

In [92]:
# analises por agrupamento
# display(df_analise)

# ranking de faturamento por loja
analise_lojas = df_analise[["Loja", "Faturamento"]].groupby("Loja").sum()
analise_lojas = analise_lojas.sort_values(by="Faturamento", ascending=False)
analise_lojas = analise_lojas.reset_index()
analise_lojas["Faturamento"] = analise_lojas["Faturamento"].map("R${:,.2f}".format)
display(analise_lojas)

# ranking de produtos que mais venderam no online
df_vendas_online = df_analise[df_analise["Loja"]=="Online"]
analise_produtos_online = df_vendas_online[["Produto", "Qtd"]].groupby("Produto").sum()
analise_produtos_online = analise_produtos_online.sort_values(by="Qtd", ascending=False)
analise_produtos_online = analise_produtos_online.rename(columns={"Qtd": "Vendas Totais"}) # alterar nome de coluna
display(analise_produtos_online)

# analise de rankind por loja e por produto
# quais produtos venderam mais em cada uma das lojas
analise_produtos_em_lojas = df_analise[["Loja", "Produto", "Qtd"]].groupby(["Loja", "Produto"]).sum()

# quais lojas mais venderam os produtos
analise_lojas_em_produtos = df_analise[["Loja", "Produto", "Qtd"]].groupby(["Produto", "Loja"]).sum()

with pd.option_context("display.max_rows", None):
    display(analise_produtos_em_lojas)
    display(analise_lojas_em_produtos)

             Loja      Faturamento
0        Salvador  R$42,300,610.00
1  Rio De Janeiro  R$42,294,720.00
2          Recife  R$42,190,390.00
3       São Paulo  R$42,090,690.00
4  Belo Horizonte  R$41,714,890.00
5    Porto Alegre  R$41,678,460.00
6        Curitiba  R$41,121,720.00

Empty DataFrame
Columns: [Vendas Totais]
Index: []

                                    Qtd
Loja           Produto
Belo Horizonte Cabo HDMI           2636
               Monitor 27"         2625
               Mouse Gamer         2465
               Notebook Dell       2654
               Notebook HP         2775
               Smartphone Samsung  2597
               Teclado Mecânico    2609
               iPhone 14           2478
Curitiba       Cabo HDMI           2698
               Monitor 27"         2626
               Mouse Gamer         2600
               Notebook Dell       2517
               Notebook HP         2529
               Smartphone Samsung  2444
               Teclado Mecânico    2742
               iPhone 14           2652
Porto Alegre   Cabo HDMI           2571
               Monitor 27"         2655
               Mouse Gamer         2611
               Notebook Dell       2770
               Notebook HP         2511
               Smartphone Samsung  2603
               Teclado Mecânico    2598
               iPhone 14           2540
Recife         Cabo HDMI           2534
               Monitor 27"         2647
               Mouse Gamer         2639
               Notebook Dell       2566
               Notebook HP         2651
               Smartphone Samsung  2660
               Teclado Mecânico    2775
               iPhone 14           2652
Rio De Janeiro Cabo HDMI           2747
               Monitor 27"         2798
               Mouse Gamer         2652
               Notebook Dell       2534
               Notebook HP         2614
               Smartphone Samsung  2626
               Teclado Mecânico    2548
               iPhone 14           2702
Salvador       Cabo HDMI           2566
               Monitor 27"         2545
               Mouse Gamer         2711
               Notebook Dell       2512
               Notebook HP         2785
               Smartphone Samsung  2627
               Teclado Mecânico    2579
               iPhone 14           2671
São Paulo      Cabo HDMI           2649
               Monitor 27"         2796
               Mouse Gamer         2714
               Notebook Dell       2535
               Notebook HP         2592
               Smartphone Samsung  2476
               Teclado Mecânico    2589
               iPhone 14           2735

                                    Qtd
Produto            Loja
Cabo HDMI          Belo Horizonte  2636
                   Curitiba        2698
                   Porto Alegre    2571
                   Recife          2534
                   Rio De Janeiro  2747
                   Salvador        2566
                   São Paulo       2649
Monitor 27"        Belo Horizonte  2625
                   Curitiba        2626
                   Porto Alegre    2655
                   Recife          2647
                   Rio De Janeiro  2798
                   Salvador        2545
                   São Paulo       2796
Mouse Gamer        Belo Horizonte  2465
                   Curitiba        2600
                   Porto Alegre    2611
                   Recife          2639
                   Rio De Janeiro  2652
                   Salvador        2711
                   São Paulo       2714
Notebook Dell      Belo Horizonte  2654
                   Curitiba        2517
                   Porto Alegre    2770
                   Recife          2566
                   Rio De Janeiro  2534
                   Salvador        2512
                   São Paulo       2535
Notebook HP        Belo Horizonte  2775
                   Curitiba        2529
                   Porto Alegre    2511
                   Recife          2651
                   Rio De Janeiro  2614
                   Salvador        2785
                   São Paulo       2592
Smartphone Samsung Belo Horizonte  2597
                   Curitiba        2444
                   Porto Alegre    2603
                   Recife          2660
                   Rio De Janeiro  2626
                   Salvador        2627
                   São Paulo       2476
Teclado Mecânico   Belo Horizonte  2609
                   Curitiba        2742
                   Porto Alegre    2598
                   Recife          2775
                   Rio De Janeiro  2548
                   Salvador        2579
                   São Paulo       2589
iPhone 14          Belo Horizonte  2478
                   Curitiba        2652
                   Porto Alegre    2540
                   Recife          2652
                   Rio De Janeiro  2702
                   Salvador        2671
                   São Paulo       2735

In [95]:
display(df_analise.head())

# quais gerentes bateram a meta em janeiro de 2023
df_meta = df_analise[(df_analise["Data"].dt.year==2023) & (df_analise["Data"].dt.month==1)]

df_meta = df_meta[["Loja", "Faturamento"]].groupby("Loja", as_index=False).sum()

df_meta = df_meta.merge(df_gerentes, on="Loja", how="left")
df_meta["Bateu Meta"] = np.where(df_meta["Faturamento"] >= df_meta["Meta_Mensal"], "Sim", "Não")
display(df_meta)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,forma_de_venda,Regiao,Faturamento,Região
0,12848,2023-01-01,Belo Horizonte,Cabo HDMI,40.0,1,Cliente_4327,Presencial,Sudeste,40.0,Sudeste
1,93303,2023-01-01,Belo Horizonte,Cabo HDMI,40.0,1,Cliente_11142,Presencial,Sudeste,40.0,Sudeste
2,95393,2023-01-01,Salvador,Cabo HDMI,40.0,1,Cliente_23137,Presencial,Nordeste,40.0,Nordeste
3,97659,2023-01-01,Curitiba,Cabo HDMI,40.0,1,Cliente_58,Presencial,sul,40.0,sul
4,37130,2023-01-01,Porto Alegre,Cabo HDMI,40.0,1,Cliente_22886,Presencial,Sul,40.0,Sul

NameError: name 'df_gerentes' is not defined

In [96]:
df_analise["Mes-Ano"] = df_analise["Data"].dt.to_period("M")
df_vendas_mes = df_analise[["Mes-Ano", "Faturamento"]].groupby("Mes-Ano").sum()
df_vendas_mes.plot()
display(df_vendas_mes)

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.