In [45]:
# Aula 3
import pandas as pd

In [46]:
# carregando dataset corretamente ==> neste caso usa o separador ';'.
# It seems the separator is not ';', let's try to read the file without specifying a separator first to inspect the header.
data = pd.read_csv('./sample_data/GasPricesinBrazil_2004-2019.csv', sep=';')

In [47]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127.0,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5.0,2004.0
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387.0,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5.0,2004.0
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192.0,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5.0,2004.0
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162.0,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5.0,2004.0
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103.0,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5.0,2004.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59899,59899,2013-07-14,2013-07-20,SUDESTE,ESPIRITO SANTO,ÓLEO DIESEL,161.0,R$/l,2.348,0.068,...,2.480,0.286,0.029,2.062,0.052,1.9708,2.1885,0.025,7.0,2013.0
59900,59900,2013-07-14,2013-07-20,CENTRO OESTE,GOIAS,ÓLEO DIESEL,229.0,R$/l,2.316,0.075,...,2.499,0.229,0.032,2.087,0.049,1.9894,2.189,0.023,7.0,2013.0
59901,59901,2013-07-14,2013-07-20,NORDESTE,MARANHAO,ÓLEO DIESEL,131.0,R$/l,2.273,0.075,...,2.610,0.199,0.033,2.074,0.048,1.9649,2.1537,0.023,7.0,2013.0
59902,59902,2013-07-14,2013-07-20,CENTRO OESTE,MATO GROSSO,ÓLEO DIESEL,111.0,R$/l,2.586,0.101,...,2.900,0.33,0.039,2.256,0.068,2.0528,2.39,0.03,7.0,2013.0
59903,59903,2013-07-14,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59904 entries, 0 to 59903
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     59904 non-null  int64
 1   DATA INICIAL                   59904 non-null  object
 2   DATA FINAL                     59904 non-null  object
 3   REGIÃO                         59903 non-null  object
 4   ESTADO                         59903 non-null  object
 5   PRODUTO                        59903 non-null  object
 6   NÚMERO DE POSTOS PESQUISADOS   59903 non-null  float64
 7   UNIDADE DE MEDIDA              59903 non-null  object
 8   PREÇO MÉDIO REVENDA            59903 non-null  float64
 9   DESVIO PADRÃO REVENDA          59903 non-null  float64
 10  PREÇO MÍNIMO REVENDA           59903 non-null  float64
 11  PREÇO MÁXIMO REVENDA           59903 non-null  float64
 12  MARGEM MÉDIA REVENDA           59903 non-null  object
 13  COEF DE VARIAÇÃO REVENDA       59903 non-null  float64
 14  PREÇO MÉDIO DISTRIBUIÇÃO       59903 non-null  object
 15  DESVIO PADRÃO DISTRIBUIÇÃO     59903 non-null  object
 16  PREÇO MÍNIMO DISTRIBUIÇÃO      59903 non-null  object
 17  PREÇO MÁXIMO DISTRIBUIÇÃO      59903 non-null  object
 18  COEF DE VARIAÇÃO DISTRIBUIÇÃO  59903 non-null  object
 19  MÊS                            59903 non-null  float64
 20  ANO                            59903 non-null  float64
dtypes: float64(8), int64(1), object(12)
memory usage: 9.6+ MB

In [49]:
data_pre = data.copy()

In [50]:
# Converte date columns to datetime objects
data_pre['DATA INICIAL'] = pd.to_datetime(data_pre['DATA INICIAL'], errors='coerce')
data_pre['DATA FINAL'] = pd.to_datetime(data_pre['DATA FINAL'], errors='coerce')

In [51]:
# convertendo atributos/colunas para 'numeric'
for atributo in ['MARGEM MÉDIA REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO', 'DESVIO PADRÃO DISTRIBUIÇÃO', 'PREÇO MÍNIMO DISTRIBUIÇÃO', 'PREÇO MÁXIMO DISTRIBUIÇÃO', 'COEF DE VARIAÇÃO DISTRIBUIÇÃO']:
  # converte a coluna (de valores string) para um tipo númerico
  # Em caso de erro na conversão (p. ex., uma string que não representa um número), um valor vazio (null / nan) será
  # atribuído no lugar
  data_pre[atributo] = pd.to_numeric(data_pre[atributo], errors='coerce')

In [52]:
data_pre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59904 entries, 0 to 59903
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     59904 non-null  int64
 1   DATA INICIAL                   59904 non-null  datetime64[ns]
 2   DATA FINAL                     59903 non-null  datetime64[ns]
 3   REGIÃO                         59903 non-null  object
 4   ESTADO                         59903 non-null  object
 5   PRODUTO                        59903 non-null  object
 6   NÚMERO DE POSTOS PESQUISADOS   59903 non-null  float64
 7   UNIDADE DE MEDIDA              59903 non-null  object
 8   PREÇO MÉDIO REVENDA            59903 non-null  float64
 9   DESVIO PADRÃO REVENDA          59903 non-null  float64
 10  PREÇO MÍNIMO REVENDA           59903 non-null  float64
 11  PREÇO MÁXIMO REVENDA           59903 non-null  float64
 12  MARGEM MÉDIA REVENDA           58727 non-null  float64
 13  COEF DE VARIAÇÃO REVENDA       59903 non-null  float64
 14  PREÇO MÉDIO DISTRIBUIÇÃO       58747 non-null  float64
 15  DESVIO PADRÃO DISTRIBUIÇÃO     58747 non-null  float64
 16  PREÇO MÍNIMO DISTRIBUIÇÃO      58747 non-null  float64
 17  PREÇO MÁXIMO DISTRIBUIÇÃO      58747 non-null  float64
 18  COEF DE VARIAÇÃO DISTRIBUIÇÃO  58747 non-null  float64
 19  MÊS                            59903 non-null  float64
 20  ANO                            59903 non-null  float64
dtypes: datetime64[ns](2), float64(14), int64(1), object(4)
memory usage: 9.6+ MB

Limpeza #2

In [53]:
mask = data_pre['PREÇO MÉDIO DISTRIBUIÇÃO'].isnull()

In [54]:
data_pre[mask]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
1903,1903,2005-09-25,2005-10-01,NORTE,PARA,ETANOL HIDRATADO,2.0,R$/l,1.694,0.283,...,2.090,NaN,0.167,NaN,NaN,NaN,NaN,NaN,9.0,2005.0
1958,1958,2005-10-09,2005-10-15,NORTE,RORAIMA,ETANOL HIDRATADO,3.0,R$/l,2.000,0.000,...,2.000,NaN,0.000,NaN,NaN,NaN,NaN,NaN,10.0,2005.0
2012,2012,2005-10-23,2005-10-29,NORTE,RORAIMA,ETANOL HIDRATADO,3.0,R$/l,2.277,0.023,...,2.290,NaN,0.010,NaN,NaN,NaN,NaN,NaN,10.0,2005.0
2497,2497,2006-02-26,2006-03-04,NORTE,RORAIMA,ETANOL HIDRATADO,11.0,R$/l,2.182,0.040,...,2.200,NaN,0.018,NaN,NaN,NaN,NaN,NaN,2.0,2006.0
3199,3199,2006-08-27,2006-09-02,NORTE,RORAIMA,ETANOL HIDRATADO,22.0,R$/l,2.285,0.068,...,2.300,NaN,0.030,NaN,NaN,NaN,NaN,NaN,8.0,2006.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59852,59852,2013-07-07,2013-07-13,CENTRO OESTE,GOIAS,GNV,1.0,R$/m3,2.190,0.000,...,2.190,NaN,0.000,NaN,NaN,NaN,NaN,NaN,7.0,2013.0
59853,59853,2013-07-07,2013-07-13,CENTRO OESTE,MATO GROSSO,GNV,3.0,R$/m3,1.857,0.277,...,1.970,NaN,0.149,NaN,NaN,NaN,NaN,NaN,7.0,2013.0
59854,59854,2013-07-07,2013-07-13,CENTRO OESTE,MATO GROSSO DO SUL,GNV,3.0,R$/m3,1.961,0.020,...,1.989,NaN,0.010,NaN,NaN,NaN,NaN,NaN,7.0,2013.0
59857,59857,2013-07-07,2013-07-13,SUL,PARANA,GNV,9.0,R$/m3,1.739,0.090,...,1.899,NaN,0.052,NaN,NaN,NaN,NaN,NaN,7.0,2013.0
59903,59903,2013-07-14,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [55]:
# Nos dados originais, quais eram os valores do PREÇO MÉDIO DISTRIBUIÇÃO dos registros que agora possuem valores NaN
data[mask]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
1903,1903,2005-09-25,2005-10-01,NORTE,PARA,ETANOL HIDRATADO,2.0,R$/l,1.694,0.283,...,2.090,-,0.167,-,-,-,-,-,9.0,2005.0
1958,1958,2005-10-09,2005-10-15,NORTE,RORAIMA,ETANOL HIDRATADO,3.0,R$/l,2.000,0.000,...,2.000,-,0.000,-,-,-,-,-,10.0,2005.0
2012,2012,2005-10-23,2005-10-29,NORTE,RORAIMA,ETANOL HIDRATADO,3.0,R$/l,2.277,0.023,...,2.290,-,0.010,-,-,-,-,-,10.0,2005.0
2497,2497,2006-02-26,2006-03-04,NORTE,RORAIMA,ETANOL HIDRATADO,11.0,R$/l,2.182,0.040,...,2.200,-,0.018,-,-,-,-,-,2.0,2006.0
3199,3199,2006-08-27,2006-09-02,NORTE,RORAIMA,ETANOL HIDRATADO,22.0,R$/l,2.285,0.068,...,2.300,-,0.030,-,-,-,-,-,8.0,2006.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59852,59852,2013-07-07,2013-07-13,CENTRO OESTE,GOIAS,GNV,1.0,R$/m3,2.190,0.000,...,2.190,-,0.000,-,-,-,-,-,7.0,2013.0
59853,59853,2013-07-07,2013-07-13,CENTRO OESTE,MATO GROSSO,GNV,3.0,R$/m3,1.857,0.277,...,1.970,-,0.149,-,-,-,-,-,7.0,2013.0
59854,59854,2013-07-07,2013-07-13,CENTRO OESTE,MATO GROSSO DO SUL,GNV,3.0,R$/m3,1.961,0.020,...,1.989,-,0.010,-,-,-,-,-,7.0,2013.0
59857,59857,2013-07-07,2013-07-13,SUL,PARANA,GNV,9.0,R$/m3,1.739,0.090,...,1.899,-,0.052,-,-,-,-,-,7.0,2013.0
59903,59903,2013-07-14,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59904 entries, 0 to 59903
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     59904 non-null  int64
 1   DATA INICIAL                   59904 non-null  object
 2   DATA FINAL                     59904 non-null  object
 3   REGIÃO                         59903 non-null  object
 4   ESTADO                         59903 non-null  object
 5   PRODUTO                        59903 non-null  object
 6   NÚMERO DE POSTOS PESQUISADOS   59903 non-null  float64
 7   UNIDADE DE MEDIDA              59903 non-null  object
 8   PREÇO MÉDIO REVENDA            59903 non-null  float64
 9   DESVIO PADRÃO REVENDA          59903 non-null  float64
 10  PREÇO MÍNIMO REVENDA           59903 non-null  float64
 11  PREÇO MÁXIMO REVENDA           59903 non-null  float64
 12  MARGEM MÉDIA REVENDA           59903 non-null  object
 13  COEF DE VARIAÇÃO REVENDA       59903 non-null  float64
 14  PREÇO MÉDIO DISTRIBUIÇÃO       59903 non-null  object
 15  DESVIO PADRÃO DISTRIBUIÇÃO     59903 non-null  object
 16  PREÇO MÍNIMO DISTRIBUIÇÃO      59903 non-null  object
 17  PREÇO MÁXIMO DISTRIBUIÇÃO      59903 non-null  object
 18  COEF DE VARIAÇÃO DISTRIBUIÇÃO  59903 non-null  object
 19  MÊS                            59903 non-null  float64
 20  ANO                            59903 non-null  float64
dtypes: float64(8), int64(1), object(12)
memory usage: 9.6+ MB

In [57]:
# Retorna uma cópia do data frame 'data_pre' com todos os valores NaN de todas as colunas agora preenchidos com 0.
# Para alterar o próprio data frame, use o argumento 'inplace=True'.
data_pre_fill = data_pre.fillna(0)
data_pre_fill

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15 00:00:00,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127.0,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5.0,2004.0
1,1,2004-05-09,2004-05-15 00:00:00,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387.0,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5.0,2004.0
2,2,2004-05-09,2004-05-15 00:00:00,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192.0,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5.0,2004.0
3,3,2004-05-09,2004-05-15 00:00:00,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162.0,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5.0,2004.0
4,4,2004-05-09,2004-05-15 00:00:00,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103.0,R$/l,1.181,0.078,...,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5.0,2004.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59899,59899,2013-07-14,2013-07-20 00:00:00,SUDESTE,ESPIRITO SANTO,ÓLEO DIESEL,161.0,R$/l,2.348,0.068,...,2.480,0.286,0.029,2.062,0.052,1.9708,2.18850,0.025,7.0,2013.0
59900,59900,2013-07-14,2013-07-20 00:00:00,CENTRO OESTE,GOIAS,ÓLEO DIESEL,229.0,R$/l,2.316,0.075,...,2.499,0.229,0.032,2.087,0.049,1.9894,2.18900,0.023,7.0,2013.0
59901,59901,2013-07-14,2013-07-20 00:00:00,NORDESTE,MARANHAO,ÓLEO DIESEL,131.0,R$/l,2.273,0.075,...,2.610,0.199,0.033,2.074,0.048,1.9649,2.15370,0.023,7.0,2013.0
59902,59902,2013-07-14,2013-07-20 00:00:00,CENTRO OESTE,MATO GROSSO,ÓLEO DIESEL,111.0,R$/l,2.586,0.101,...,2.900,0.330,0.039,2.256,0.068,2.0528,2.39000,0.030,7.0,2013.0
59903,59903,2013-07-14,0,0,0,0,0.0,0,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.0000,0.00000,0.000,0.0,0.0

In [58]:
data_pre_fill[mask] # valores que eram NaN, agora são 0

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
1903,1903,2005-09-25,2005-10-01 00:00:00,NORTE,PARA,ETANOL HIDRATADO,2.0,R$/l,1.694,0.283,...,2.090,0.0,0.167,0.0,0.0,0.0,0.0,0.0,9.0,2005.0
1958,1958,2005-10-09,2005-10-15 00:00:00,NORTE,RORAIMA,ETANOL HIDRATADO,3.0,R$/l,2.000,0.000,...,2.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,10.0,2005.0
2012,2012,2005-10-23,2005-10-29 00:00:00,NORTE,RORAIMA,ETANOL HIDRATADO,3.0,R$/l,2.277,0.023,...,2.290,0.0,0.010,0.0,0.0,0.0,0.0,0.0,10.0,2005.0
2497,2497,2006-02-26,2006-03-04 00:00:00,NORTE,RORAIMA,ETANOL HIDRATADO,11.0,R$/l,2.182,0.040,...,2.200,0.0,0.018,0.0,0.0,0.0,0.0,0.0,2.0,2006.0
3199,3199,2006-08-27,2006-09-02 00:00:00,NORTE,RORAIMA,ETANOL HIDRATADO,22.0,R$/l,2.285,0.068,...,2.300,0.0,0.030,0.0,0.0,0.0,0.0,0.0,8.0,2006.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59852,59852,2013-07-07,2013-07-13 00:00:00,CENTRO OESTE,GOIAS,GNV,1.0,R$/m3,2.190,0.000,...,2.190,0.0,0.000,0.0,0.0,0.0,0.0,0.0,7.0,2013.0
59853,59853,2013-07-07,2013-07-13 00:00:00,CENTRO OESTE,MATO GROSSO,GNV,3.0,R$/m3,1.857,0.277,...,1.970,0.0,0.149,0.0,0.0,0.0,0.0,0.0,7.0,2013.0
59854,59854,2013-07-07,2013-07-13 00:00:00,CENTRO OESTE,MATO GROSSO DO SUL,GNV,3.0,R$/m3,1.961,0.020,...,1.989,0.0,0.010,0.0,0.0,0.0,0.0,0.0,7.0,2013.0
59857,59857,2013-07-07,2013-07-13 00:00:00,SUL,PARANA,GNV,9.0,R$/m3,1.739,0.090,...,1.899,0.0,0.052,0.0,0.0,0.0,0.0,0.0,7.0,2013.0
59903,59903,2013-07-14,0,0,0,0,0.0,0,0.000,0.000,...,0.000,0.0,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [59]:
# retorna uma cópia do data frame 'data_pre' com todos os valores NaN das colunas:
# 'PREÇO MÉDIO DISTRIBUIÇÃO', 'DESVIO PADRÃO DISTRIBUIÇÃO', 'PREÇO MÍNIMO DISTRIBUIÇÃO' E 'MÉDIO MÁXIMO DISTRIBUIÇÃO', respectivamente,
data_pre_fill = data_pre.fillna(value={
    'PREÇO MÉDIO DISTRIBUIÇÃO': 10,
    'DESVIO PADRÃO DISTRIBUIÇÃO': 20,
    'PREÇO MÍNIMO DISTRIBUIÇÃO': 30,
    'PREÇO MÁXIMO DISTRIBUIÇÃO': 'vazio'
})

In [60]:
data_pre_fill[mask]

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
1903,1903,2005-09-25,2005-10-01,NORTE,PARA,ETANOL HIDRATADO,2.0,R$/l,1.694,0.283,...,2.090,NaN,0.167,10.0,20.0,30.0,vazio,NaN,9.0,2005.0
1958,1958,2005-10-09,2005-10-15,NORTE,RORAIMA,ETANOL HIDRATADO,3.0,R$/l,2.000,0.000,...,2.000,NaN,0.000,10.0,20.0,30.0,vazio,NaN,10.0,2005.0
2012,2012,2005-10-23,2005-10-29,NORTE,RORAIMA,ETANOL HIDRATADO,3.0,R$/l,2.277,0.023,...,2.290,NaN,0.010,10.0,20.0,30.0,vazio,NaN,10.0,2005.0
2497,2497,2006-02-26,2006-03-04,NORTE,RORAIMA,ETANOL HIDRATADO,11.0,R$/l,2.182,0.040,...,2.200,NaN,0.018,10.0,20.0,30.0,vazio,NaN,2.0,2006.0
3199,3199,2006-08-27,2006-09-02,NORTE,RORAIMA,ETANOL HIDRATADO,22.0,R$/l,2.285,0.068,...,2.300,NaN,0.030,10.0,20.0,30.0,vazio,NaN,8.0,2006.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59852,59852,2013-07-07,2013-07-13,CENTRO OESTE,GOIAS,GNV,1.0,R$/m3,2.190,0.000,...,2.190,NaN,0.000,10.0,20.0,30.0,vazio,NaN,7.0,2013.0
59853,59853,2013-07-07,2013-07-13,CENTRO OESTE,MATO GROSSO,GNV,3.0,R$/m3,1.857,0.277,...,1.970,NaN,0.149,10.0,20.0,30.0,vazio,NaN,7.0,2013.0
59854,59854,2013-07-07,2013-07-13,CENTRO OESTE,MATO GROSSO DO SUL,GNV,3.0,R$/m3,1.961,0.020,...,1.989,NaN,0.010,10.0,20.0,30.0,vazio,NaN,7.0,2013.0
59857,59857,2013-07-07,2013-07-13,SUL,PARANA,GNV,9.0,R$/m3,1.739,0.090,...,1.899,NaN,0.052,10.0,20.0,30.0,vazio,NaN,7.0,2013.0
59903,59903,2013-07-14,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,10.0,20.0,30.0,vazio,NaN,NaN,NaN

In [61]:
# remove, no próprio dataframe, todas as linhas/registros com valores NaN (vazios) em quaisquer colunas colunas/atributos.
data_pre.dropna(inplace=True)

In [62]:
data_pre.info()

<class 'pandas.core.frame.DataFrame'>
Index: 58727 entries, 0 to 59902
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     58727 non-null  int64
 1   DATA INICIAL                   58727 non-null  datetime64[ns]
 2   DATA FINAL                     58727 non-null  datetime64[ns]
 3   REGIÃO                         58727 non-null  object
 4   ESTADO                         58727 non-null  object
 5   PRODUTO                        58727 non-null  object
 6   NÚMERO DE POSTOS PESQUISADOS   58727 non-null  float64
 7   UNIDADE DE MEDIDA              58727 non-null  object
 8   PREÇO MÉDIO REVENDA            58727 non-null  float64
 9   DESVIO PADRÃO REVENDA          58727 non-null  float64
 10  PREÇO MÍNIMO REVENDA           58727 non-null  float64
 11  PREÇO MÁXIMO REVENDA           58727 non-null  float64
 12  MARGEM MÉDIA REVENDA           58727 non-null  float64
 13  COEF DE VARIAÇÃO REVENDA       58727 non-null  float64
 14  PREÇO MÉDIO DISTRIBUIÇÃO       58727 non-null  float64
 15  DESVIO PADRÃO DISTRIBUIÇÃO     58727 non-null  float64
 16  PREÇO MÍNIMO DISTRIBUIÇÃO      58727 non-null  float64
 17  PREÇO MÁXIMO DISTRIBUIÇÃO      58727 non-null  float64
 18  COEF DE VARIAÇÃO DISTRIBUIÇÃO  58727 non-null  float64
 19  MÊS                            58727 non-null  float64
 20  ANO                            58727 non-null  float64
dtypes: datetime64[ns](2), float64(14), int64(1), object(4)
memory usage: 9.9+ MB

In [80]:
data_pre.to_csv('./sample_data/GasPricesinBrazil_2004-2019_preprocessado_final.csv', index=False)

In [81]:
data_final = pd.read_csv('./sample_data/GasPricesinBrazil_2004-2019_preprocessado_final.csv')

In [84]:
data_final

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127.0,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5.0,2004.0
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387.0,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5.0,2004.0
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192.0,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5.0,2004.0
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162.0,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5.0,2004.0
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103.0,R$/l,1.181,0.078,...,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5.0,2004.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58722,59898,2013-07-14,2013-07-20,CENTRO OESTE,DISTRITO FEDERAL,ÓLEO DIESEL,76.0,R$/l,2.418,0.009,...,2.429,0.301,0.004,2.117,0.007,2.0923,2.12900,0.003,7.0,2013.0
58723,59899,2013-07-14,2013-07-20,SUDESTE,ESPIRITO SANTO,ÓLEO DIESEL,161.0,R$/l,2.348,0.068,...,2.480,0.286,0.029,2.062,0.052,1.9708,2.18850,0.025,7.0,2013.0
58724,59900,2013-07-14,2013-07-20,CENTRO OESTE,GOIAS,ÓLEO DIESEL,229.0,R$/l,2.316,0.075,...,2.499,0.229,0.032,2.087,0.049,1.9894,2.18900,0.023,7.0,2013.0
58725,59901,2013-07-14,2013-07-20,NORDESTE,MARANHAO,ÓLEO DIESEL,131.0,R$/l,2.273,0.075,...,2.610,0.199,0.033,2.074,0.048,1.9649,2.15370,0.023,7.0,2013.0
58726,59902,2013-07-14,2013-07-20,CENTRO OESTE,MATO GROSSO,ÓLEO DIESEL,111.0,R$/l,2.586,0.101,...,2.900,0.330,0.039,2.256,0.068,2.0528,2.39000,0.030,7.0,2013.0

In [78]:
data_final.describe()

,Unnamed: 0,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
count,58727.000000,58727.000000,58727.000000,58727.000000,58727.000000,58727.000000,58727.000000,58727.00000,58727.000000,58727.000000,58727.000000,58727.000000,58727.000000,58727.000000,58727.000000
mean,29748.530965,285.825293,9.371255,0.489191,8.232061,10.665276,1.736627,0.04520,7.634628,0.469332,6.596442,8.706689,0.050521,6.448874,2008.481346
std,17317.075401,470.287448,14.115257,0.847697,12.275430,16.151678,2.902321,0.02411,11.373681,0.897704,9.764306,13.099588,0.045797,3.423970,2.707264
min,0.000000,1.000000,0.766000,0.000000,0.590000,0.999000,0.001000,0.00000,0.506000,0.000000,0.325700,0.599200,0.000000,1.000000,2004.000000
25%,14766.500000,59.000000,1.850000,0.063000,1.719000,2.090000,0.241000,0.02900,1.592000,0.042000,1.415000,1.768000,0.020000,4.000000,2006.000000
50%,29495.000000,122.000000,2.236000,0.099000,2.050000,2.500000,0.341000,0.04200,1.959000,0.068000,1.840000,2.120000,0.033000,6.000000,2008.000000
75%,44979.500000,307.000000,2.828000,0.173000,2.650000,3.180000,0.518000,0.05900,2.414000,0.160000,2.300000,2.610100,0.069000,9.000000,2011.000000
max,59902.000000,4167.000000,50.836000,5.971000,45.000000,63.000000,15.273000,0.26200,42.026000,8.239000,41.070000,48.000000,0.780000,12.000000,2013.000000

In [88]:
data_final['PREÇO MÉDIO REVENDA'].describe()

count    58727.000000
mean         9.371255
std         14.115257
min          0.766000
25%          1.850000
50%          2.236000
75%          2.828000
max         50.836000
Name: PREÇO MÉDIO REVENDA, dtype: float64

In [89]:
data_final.describe()['PREÇO MÉDIO REVENDA']

count    58727.000000
mean         9.371255
std         14.115257
min          0.766000
25%          1.850000
50%          2.236000
75%          2.828000
max         50.836000
Name: PREÇO MÉDIO REVENDA, dtype: float64

In [90]:
stats = data_final.describe()
stats

,Unnamed: 0,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
count,58727.000000,58727.000000,58727.000000,58727.000000,58727.000000,58727.000000,58727.000000,58727.00000,58727.000000,58727.000000,58727.000000,58727.000000,58727.000000,58727.000000,58727.000000
mean,29748.530965,285.825293,9.371255,0.489191,8.232061,10.665276,1.736627,0.04520,7.634628,0.469332,6.596442,8.706689,0.050521,6.448874,2008.481346
std,17317.075401,470.287448,14.115257,0.847697,12.275430,16.151678,2.902321,0.02411,11.373681,0.897704,9.764306,13.099588,0.045797,3.423970,2.707264
min,0.000000,1.000000,0.766000,0.000000,0.590000,0.999000,0.001000,0.00000,0.506000,0.000000,0.325700,0.599200,0.000000,1.000000,2004.000000
25%,14766.500000,59.000000,1.850000,0.063000,1.719000,2.090000,0.241000,0.02900,1.592000,0.042000,1.415000,1.768000,0.020000,4.000000,2006.000000
50%,29495.000000,122.000000,2.236000,0.099000,2.050000,2.500000,0.341000,0.04200,1.959000,0.068000,1.840000,2.120000,0.033000,6.000000,2008.000000
75%,44979.500000,307.000000,2.828000,0.173000,2.650000,3.180000,0.518000,0.05900,2.414000,0.160000,2.300000,2.610100,0.069000,9.000000,2011.000000
max,59902.000000,4167.000000,50.836000,5.971000,45.000000,63.000000,15.273000,0.26200,42.026000,8.239000,41.070000,48.000000,0.780000,12.000000,2013.000000

In [91]:
stats[['PREÇO MÉDIO REVENDA', 'PREÇO MÁXIMO REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO']]

       PREÇO MÉDIO REVENDA  PREÇO MÁXIMO REVENDA  PREÇO MÉDIO DISTRIBUIÇÃO
count         58727.000000          58727.000000              58727.000000
mean              9.371255             10.665276                  7.634628
std              14.115257             16.151678                 11.373681
min               0.766000              0.999000                  0.506000
25%               1.850000              2.090000                  1.592000
50%               2.236000              2.500000                  1.959000
75%               2.828000              3.180000                  2.414000
max              50.836000             63.000000                 42.026000

In [93]:
data_final[['PREÇO MÉDIO REVENDA', 'PREÇO MÁXIMO REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO']].describe()

       PREÇO MÉDIO REVENDA  PREÇO MÁXIMO REVENDA  PREÇO MÉDIO DISTRIBUIÇÃO
count         58727.000000          58727.000000              58727.000000
mean              9.371255             10.665276                  7.634628
std              14.115257             16.151678                 11.373681
min               0.766000              0.999000                  0.506000
25%               1.850000              2.090000                  1.592000
50%               2.236000              2.500000                  1.959000
75%               2.828000              3.180000                  2.414000
max              50.836000             63.000000                 42.026000

In [94]:
stats

,Unnamed: 0,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
count,58727.000000,58727.000000,58727.000000,58727.000000,58727.000000,58727.000000,58727.000000,58727.00000,58727.000000,58727.000000,58727.000000,58727.000000,58727.000000,58727.000000,58727.000000
mean,29748.530965,285.825293,9.371255,0.489191,8.232061,10.665276,1.736627,0.04520,7.634628,0.469332,6.596442,8.706689,0.050521,6.448874,2008.481346
std,17317.075401,470.287448,14.115257,0.847697,12.275430,16.151678,2.902321,0.02411,11.373681,0.897704,9.764306,13.099588,0.045797,3.423970,2.707264
min,0.000000,1.000000,0.766000,0.000000,0.590000,0.999000,0.001000,0.00000,0.506000,0.000000,0.325700,0.599200,0.000000,1.000000,2004.000000
25%,14766.500000,59.000000,1.850000,0.063000,1.719000,2.090000,0.241000,0.02900,1.592000,0.042000,1.415000,1.768000,0.020000,4.000000,2006.000000
50%,29495.000000,122.000000,2.236000,0.099000,2.050000,2.500000,0.341000,0.04200,1.959000,0.068000,1.840000,2.120000,0.033000,6.000000,2008.000000
75%,44979.500000,307.000000,2.828000,0.173000,2.650000,3.180000,0.518000,0.05900,2.414000,0.160000,2.300000,2.610100,0.069000,9.000000,2011.000000
max,59902.000000,4167.000000,50.836000,5.971000,45.000000,63.000000,15.273000,0.26200,42.026000,8.239000,41.070000,48.000000,0.780000,12.000000,2013.000000

In [95]:
stats.loc[['min', 'max', 'mean']]

,Unnamed: 0,NÚMERO DE POSTOS PESQUISADOS,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,PREÇO MÍNIMO REVENDA,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
min,0.000000,1.000000,0.766000,0.000000,0.590000,0.999000,0.001000,0.0000,0.506000,0.000000,0.325700,0.599200,0.000000,1.000000,2004.000000
max,59902.000000,4167.000000,50.836000,5.971000,45.000000,63.000000,15.273000,0.2620,42.026000,8.239000,41.070000,48.000000,0.780000,12.000000,2013.000000
mean,29748.530965,285.825293,9.371255,0.489191,8.232061,10.665276,1.736627,0.0452,7.634628,0.469332,6.596442,8.706689,0.050521,6.448874,2008.481346

In [97]:
stats.loc[['min', 'max', 'mean'], 'PREÇO MÉDIO REVENDA']

min      0.766000
max     50.836000
mean     9.371255
Name: PREÇO MÉDIO REVENDA, dtype: float64

In [98]:
stats.loc[['min', 'max', 'mean'], ['PREÇO MÉDIO REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO']]

      PREÇO MÉDIO REVENDA  PREÇO MÉDIO DISTRIBUIÇÃO
min              0.766000                  0.506000
max             50.836000                 42.026000
mean             9.371255                  7.634628

In [99]:
data_final.head()

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127.0,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5.0,2004.0
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387.0,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5.0,2004.0
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192.0,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5.0,2004.0
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162.0,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5.0,2004.0
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103.0,R$/l,1.181,0.078,...,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5.0,2004.0

In [101]:
data_final['PREÇO MÍNIMO REVENDA'].min()

0.59

In [104]:
mean = data_final['PREÇO MÍNIMO REVENDA'].mean()
std = data_final['PREÇO MÍNIMO REVENDA'].std()

print(f'A média dos preços mínimos de revenda é {mean:.2f} +- {std:.2f}')

A média dos preços mínimos de revenda é 8.23 +- 12.28

In [105]:
data_final['ESTADO']

0          DISTRITO FEDERAL
1                     GOIAS
2               MATO GROSSO
3        MATO GROSSO DO SUL
4                   ALAGOAS
                ...
58722      DISTRITO FEDERAL
58723        ESPIRITO SANTO
58724                 GOIAS
58725              MARANHAO
58726           MATO GROSSO
Name: ESTADO, Length: 58727, dtype: object

In [106]:
data_final['ESTADO'].unique()

array(['DISTRITO FEDERAL', 'GOIAS', 'MATO GROSSO', 'MATO GROSSO DO SUL',
       'ALAGOAS', 'BAHIA', 'CEARA', 'MARANHAO', 'PARAIBA', 'PERNAMBUCO',
       'PIAUI', 'RIO GRANDE DO NORTE', 'SERGIPE', 'ACRE', 'AMAPA',
       'AMAZONAS', 'PARA', 'RONDONIA', 'RORAIMA', 'TOCANTINS',
       'ESPIRITO SANTO', 'MINAS GERAIS', 'RIO DE JANEIRO', 'SAO PAULO',
       'PARANA', 'RIO GRANDE DO SUL', 'SANTA CATARINA'], dtype=object)

In [107]:
sorted(data_final['ESTADO'].unique())

['ACRE',
 'ALAGOAS',
 'AMAPA',
 'AMAZONAS',
 'BAHIA',
 'CEARA',
 'DISTRITO FEDERAL',
 'ESPIRITO SANTO',
 'GOIAS',
 'MARANHAO',
 'MATO GROSSO',
 'MATO GROSSO DO SUL',
 'MINAS GERAIS',
 'PARA',
 'PARAIBA',
 'PARANA',
 'PERNAMBUCO',
 'PIAUI',
 'RIO DE JANEIRO',
 'RIO GRANDE DO NORTE',
 'RIO GRANDE DO SUL',
 'RONDONIA',
 'RORAIMA',
 'SANTA CATARINA',
 'SAO PAULO',
 'SERGIPE',
 'TOCANTINS']

In [109]:
data_final['ESTADO'].value_counts() # retorna em ordem decrescente, a quantidade de registros/linhas para cada estado

ESTADO
BAHIA                  2405
PERNAMBUCO             2404
SAO PAULO              2404
RIO DE JANEIRO         2403
MINAS GERAIS           2403
PARAIBA                2402
SERGIPE                2399
RIO GRANDE DO SUL      2397
SANTA CATARINA         2387
ALAGOAS                2383
RIO GRANDE DO NORTE    2367
ESPIRITO SANTO         2348
MATO GROSSO DO SUL     2310
CEARA                  2309
PARANA                 2264
MATO GROSSO            2120
AMAZONAS               2035
GOIAS                  1936
PIAUI                  1936
PARA                   1929
ACRE                   1926
MARANHAO               1923
TOCANTINS              1916
RORAIMA                1914
RONDONIA               1904
DISTRITO FEDERAL       1861
AMAPA                  1742
Name: count, dtype: int64

In [110]:
data_final['ESTADO'].value_counts().to_frame() # converte uma Series para um DataFrame

                     count
ESTADO
BAHIA                 2405
PERNAMBUCO            2404
SAO PAULO             2404
RIO DE JANEIRO        2403
MINAS GERAIS          2403
PARAIBA               2402
SERGIPE               2399
RIO GRANDE DO SUL     2397
SANTA CATARINA        2387
ALAGOAS               2383
RIO GRANDE DO NORTE   2367
ESPIRITO SANTO        2348
MATO GROSSO DO SUL    2310
CEARA                 2309
PARANA                2264
MATO GROSSO           2120
AMAZONAS              2035
GOIAS                 1936
PIAUI                 1936
PARA                  1929
ACRE                  1926
MARANHAO              1923
TOCANTINS             1916
RORAIMA               1914
RONDONIA              1904
DISTRITO FEDERAL      1861
AMAPA                 1742