# 🧠 DESAFIOS (SEM RESPOSTA)
Faça tudo usando Pandas:
🔹 Desafio 1 – Faturamento total
Calcule o faturamento total considerando preço × quantidade.
🔹 Desafio 2 – Faturamento por loja
Descubra o faturamento total de cada loja.
Ordene do maior para o menor.
🔹 Desafio 3 – Top 3 lojas
Mostre as 3 lojas que mais faturaram.

Desafio 4 – Produtos mais vendidos
Descubra os 5 produtos mais vendidos em quantidade.
🔹 Desafio 5 – Faturamento por categoria
Calcule o faturamento total por categoria de produto.
🔹 Desafio 6 – Melhor mês de vendas
Descubra qual mês teve o maior faturamento.

🔹 Desafio EXTRA 🚀
Crie uma nova coluna chamada valor_total
Exporte um CSV chamado vendas_com_faturamento.csv

In [71]:
# 1) Importar a biblioteca
import pandas as pd



# 2) Ler o arquivo CSV
df_produtos = pd.read_csv("/home/youx/tudo_sobre_dados/comandos.basicos_ipynb/data/input/produtos.csv")
df_vendas = pd.read_csv("data/input/vendas_2025.csv")
df_lojas = pd.read_csv("data/input/lojas.csv")

In [ ]:

df_vendas['Faturamento'] = df_vendas['quantidade'] * df_produtos['preco']
df_lojas

   id_loja    nome_loja          cidade estado  Faturamento
0        1  Loja Centro       São Paulo     SP       7000.0
1        2   Loja Norte  Rio de Janeiro     RJ        400.0
2        3     Loja Sul  Belo Horizonte     MG        900.0
3        4   Loja Leste        Curitiba     PR        450.0

In [73]:
df_produtos

   id_produto        nome_produto    categoria  preco
0         101            Notebook  Eletrônicos   3500
1         102               Mouse  Eletrônicos     80
2         103  Cadeira Escritório       Móveis    900
3         104             Teclado  Eletrônicos    150
4         105     Mesa Escritório       Móveis   1200

In [92]:
faturamento_por_loja = df_lojas.groupby('nome_loja')['Faturamento'].sum()
faturamento_por_loja

nome_loja
Loja Centro    7000.0
Loja Leste      450.0
Loja Norte      400.0
Loja Sul        900.0
Name: Faturamento, dtype: float64

In [109]:
# Ordenar do maior para o menor faturamento
faturamento_por_loja = faturamento_por_loja.sort_values(ascending=False)


# Mostrar as 5 lojas com maior faturamento
display(faturamento_por_loja.head(5))

nome_loja
Loja Centro    7000.0
Loja Sul        900.0
Loja Leste      450.0
Loja Norte      400.0
Name: Faturamento, dtype: float64

In [76]:

df_vendas

   id_venda        data  id_loja  id_produto  quantidade
0         1  2025-01-05        1         101           2
1         2  2025-01-06        1         102           5
2         3  2025-01-10        2         103           1
3         4  2025-01-12        3         104           3
4         5  2025-02-01        4         105           2
5         6  2025-02-03        2         101           1
6         7  2025-02-10        3         102           4
7         8  2025-03-15        1         103           2
8         9  2025-03-18        4         104           6
9        10  2025-03-20        2         105           1

In [77]:
produtos_mais_vendidos = (
    df_vendas
    .groupby("id_produto")["quantidade"]
    .sum()
)

In [78]:
produtos_mais_vendidos = produtos_mais_vendidos.sort_values(ascending=False)
produtos_mais_vendidos

id_produto
102    9
104    9
101    3
103    3
105    3
Name: quantidade, dtype: int64

In [79]:
df_lojas

   id_loja    nome_loja          cidade estado  Faturamento
0        1  Loja Centro       São Paulo     SP       7000.0
1        2   Loja Norte  Rio de Janeiro     RJ        400.0
2        3     Loja Sul  Belo Horizonte     MG        900.0
3        4   Loja Leste        Curitiba     PR        450.0

In [107]:
faturamento_por_mes = (
    df_vendas
    .groupby(df_vendas["data"].dt.month)["Faturamento"]
    .sum()
)
faturamento_por_mes

data
1    8750.0
2    2400.0
3       0.0
Name: Faturamento, dtype: float64

   id_venda       data  id_loja  id_produto  quantidade  Faturamento
0         1 2025-01-05        1         101           2       7000.0
1         2 2025-01-06        1         102           5        400.0
2         3 2025-01-10        2         103           1        900.0
3         4 2025-01-12        3         104           3        450.0
4         5 2025-02-01        4         105           2       2400.0
5         6 2025-02-03        2         101           1          NaN
6         7 2025-02-10        3         102           4          NaN
7         8 2025-03-15        1         103           2          NaN
8         9 2025-03-18        4         104           6          NaN
9        10 2025-03-20        2         105           1          NaN