In [51]:
# Aula 3
import pandas as pd

In [52]:
# carregando dataset corretamente ==> neste caso usa o separador ';'.
# It seems the separator is not ';', let's try to read the file without specifying a separator first to inspect the header.
data = pd.read_csv('./sample_data/GasPricesinBrazil_2004-2019.csv')

In [53]:
data

,Unnamed: 0.1,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,...,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,...,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,...,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,...,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103387,106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,...,3.690,0.818,0.018,2.756,0.000,2.7560,2.75600,0.000,6,2019
103388,106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,...,3.789,0.950,0.038,2.451,0.402,1.9842,2.86610,0.164,6,2019
103389,106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,...,3.499,0.914,0.065,1.998,0.000,1.9981,1.99810,0.000,6,2019
103390,106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.50930,0.070,6,2019
103391,106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,...,3.699,1.179,0.001,2.518,0.000,2.5175,2.51750,0.000,6,2019

In [54]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103392 entries, 0 to 103391
Data columns (total 22 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Unnamed: 0.1                   103392 non-null  int64
 1   Unnamed: 0                     103392 non-null  int64
 2   DATA INICIAL                   103392 non-null  object
 3   DATA FINAL                     103392 non-null  object
 4   REGIÃO                         103392 non-null  object
 5   ESTADO                         103392 non-null  object
 6   PRODUTO                        103392 non-null  object
 7   NÚMERO DE POSTOS PESQUISADOS   103392 non-null  int64
 8   UNIDADE DE MEDIDA              103392 non-null  object
 9   PREÇO MÉDIO REVENDA            103392 non-null  float64
 10  DESVIO PADRÃO REVENDA          103392 non-null  float64
 11  PREÇO MÍNIMO REVENDA           103392 non-null  float64
 12  PREÇO MÁXIMO REVENDA           103392 non-null  float64
 13  MARGEM MÉDIA REVENDA           103392 non-null  float64
 14  COEF DE VARIAÇÃO REVENDA       103392 non-null  float64
 15  PREÇO MÉDIO DISTRIBUIÇÃO       103392 non-null  float64
 16  DESVIO PADRÃO DISTRIBUIÇÃO     103392 non-null  float64
 17  PREÇO MÍNIMO DISTRIBUIÇÃO      103392 non-null  float64
 18  PREÇO MÁXIMO DISTRIBUIÇÃO      103392 non-null  float64
 19  COEF DE VARIAÇÃO DISTRIBUIÇÃO  103392 non-null  float64
 20  MÊS                            103392 non-null  int64
 21  ANO                            103392 non-null  int64
dtypes: float64(11), int64(5), object(6)
memory usage: 17.4+ MB

In [55]:
data_pre = data.copy()

In [56]:
# Converte date columns to datetime objects
data_pre['DATA INICIAL'] = pd.to_datetime(data_pre['DATA INICIAL'])
data_pre['DATA FINAL'] = pd.to_datetime(data_pre['DATA FINAL'])

In [57]:
# convertendo atributos/colunas para 'numeric'
for atributo in ['MARGEM MÉDIA REVENDA', 'PREÇO MÉDIO DISTRIBUIÇÃO', 'DESVIO PADRÃO DISTRIBUIÇÃO', 'PREÇO MÍNIMO DISTRIBUIÇÃO', 'PREÇO MÁXIMO DISTRIBUIÇÃO', 'COEF DE VARIAÇÃO DISTRIBUIÇÃO']:
  # converte a coluna (de valores string) para um tipo númerico
  # Em caso de erro na conversão (p. ex., uma string que não representa um número), um valor vazio (null / nan) será
  # atribuído no lugar
  data_pre[atributo] = pd.to_numeric(data_pre[atributo], errors='coerce')

In [58]:
data_pre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103392 entries, 0 to 103391
Data columns (total 22 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Unnamed: 0.1                   103392 non-null  int64
 1   Unnamed: 0                     103392 non-null  int64
 2   DATA INICIAL                   103392 non-null  datetime64[ns]
 3   DATA FINAL                     103392 non-null  datetime64[ns]
 4   REGIÃO                         103392 non-null  object
 5   ESTADO                         103392 non-null  object
 6   PRODUTO                        103392 non-null  object
 7   NÚMERO DE POSTOS PESQUISADOS   103392 non-null  int64
 8   UNIDADE DE MEDIDA              103392 non-null  object
 9   PREÇO MÉDIO REVENDA            103392 non-null  float64
 10  DESVIO PADRÃO REVENDA          103392 non-null  float64
 11  PREÇO MÍNIMO REVENDA           103392 non-null  float64
 12  PREÇO MÁXIMO REVENDA           103392 non-null  float64
 13  MARGEM MÉDIA REVENDA           103392 non-null  float64
 14  COEF DE VARIAÇÃO REVENDA       103392 non-null  float64
 15  PREÇO MÉDIO DISTRIBUIÇÃO       103392 non-null  float64
 16  DESVIO PADRÃO DISTRIBUIÇÃO     103392 non-null  float64
 17  PREÇO MÍNIMO DISTRIBUIÇÃO      103392 non-null  float64
 18  PREÇO MÁXIMO DISTRIBUIÇÃO      103392 non-null  float64
 19  COEF DE VARIAÇÃO DISTRIBUIÇÃO  103392 non-null  float64
 20  MÊS                            103392 non-null  int64
 21  ANO                            103392 non-null  int64
dtypes: datetime64[ns](2), float64(11), int64(5), object(4)
memory usage: 17.4+ MB

Limpeza #2

In [59]:
mask = data_pre['PREÇO MÉDIO DISTRIBUIÇÃO'].isnull()

In [60]:
data_pre[mask]

Empty DataFrame
Columns: [Unnamed: 0.1, Unnamed: 0, DATA INICIAL, DATA FINAL, REGIÃO, ESTADO, PRODUTO, NÚMERO DE POSTOS PESQUISADOS, UNIDADE DE MEDIDA, PREÇO MÉDIO REVENDA, DESVIO PADRÃO REVENDA, PREÇO MÍNIMO REVENDA, PREÇO MÁXIMO REVENDA, MARGEM MÉDIA REVENDA, COEF DE VARIAÇÃO REVENDA, PREÇO MÉDIO DISTRIBUIÇÃO, DESVIO PADRÃO DISTRIBUIÇÃO, PREÇO MÍNIMO DISTRIBUIÇÃO, PREÇO MÁXIMO DISTRIBUIÇÃO, COEF DE VARIAÇÃO DISTRIBUIÇÃO, MÊS, ANO]
Index: []

[0 rows x 22 columns]

In [61]:
# Nos dados originais, quais eram os valores do PREÇO MÉDIO DISTRIBUIÇÃO dos registros que agora possuem valores NaN
data[mask]

Empty DataFrame
Columns: [Unnamed: 0.1, Unnamed: 0, DATA INICIAL, DATA FINAL, REGIÃO, ESTADO, PRODUTO, NÚMERO DE POSTOS PESQUISADOS, UNIDADE DE MEDIDA, PREÇO MÉDIO REVENDA, DESVIO PADRÃO REVENDA, PREÇO MÍNIMO REVENDA, PREÇO MÁXIMO REVENDA, MARGEM MÉDIA REVENDA, COEF DE VARIAÇÃO REVENDA, PREÇO MÉDIO DISTRIBUIÇÃO, DESVIO PADRÃO DISTRIBUIÇÃO, PREÇO MÍNIMO DISTRIBUIÇÃO, PREÇO MÁXIMO DISTRIBUIÇÃO, COEF DE VARIAÇÃO DISTRIBUIÇÃO, MÊS, ANO]
Index: []

[0 rows x 22 columns]

In [62]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103392 entries, 0 to 103391
Data columns (total 22 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Unnamed: 0.1                   103392 non-null  int64
 1   Unnamed: 0                     103392 non-null  int64
 2   DATA INICIAL                   103392 non-null  object
 3   DATA FINAL                     103392 non-null  object
 4   REGIÃO                         103392 non-null  object
 5   ESTADO                         103392 non-null  object
 6   PRODUTO                        103392 non-null  object
 7   NÚMERO DE POSTOS PESQUISADOS   103392 non-null  int64
 8   UNIDADE DE MEDIDA              103392 non-null  object
 9   PREÇO MÉDIO REVENDA            103392 non-null  float64
 10  DESVIO PADRÃO REVENDA          103392 non-null  float64
 11  PREÇO MÍNIMO REVENDA           103392 non-null  float64
 12  PREÇO MÁXIMO REVENDA           103392 non-null  float64
 13  MARGEM MÉDIA REVENDA           103392 non-null  float64
 14  COEF DE VARIAÇÃO REVENDA       103392 non-null  float64
 15  PREÇO MÉDIO DISTRIBUIÇÃO       103392 non-null  float64
 16  DESVIO PADRÃO DISTRIBUIÇÃO     103392 non-null  float64
 17  PREÇO MÍNIMO DISTRIBUIÇÃO      103392 non-null  float64
 18  PREÇO MÁXIMO DISTRIBUIÇÃO      103392 non-null  float64
 19  COEF DE VARIAÇÃO DISTRIBUIÇÃO  103392 non-null  float64
 20  MÊS                            103392 non-null  int64
 21  ANO                            103392 non-null  int64
dtypes: float64(11), int64(5), object(6)
memory usage: 17.4+ MB

In [63]:
# Retorna uma cópia do data frame 'data_pre' com todos os valores NaN de todas as colunas agora preenchidos com 0.
# Para alterar o próprio data frame, use o argumento 'inplace=True'.
data_pre_fill = data_pre.fillna(0)
data_pre_fill

,Unnamed: 0.1,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,...,1.350,0.463,0.012,0.825,0.110,0.4201,0.96660,0.133,5,2004
1,1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05000,0.115,5,2004
2,2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,...,1.760,0.419,0.070,0.970,0.095,0.5614,1.16100,0.098,5,2004
3,3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,...,1.509,0.432,0.055,0.830,0.119,0.5991,1.22242,0.143,5,2004
4,4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,...,1.400,0.240,0.066,0.941,0.077,0.7441,1.03170,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103387,106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,...,3.690,0.818,0.018,2.756,0.000,2.7560,2.75600,0.000,6,2019
103388,106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,...,3.789,0.950,0.038,2.451,0.402,1.9842,2.86610,0.164,6,2019
103389,106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,...,3.499,0.914,0.065,1.998,0.000,1.9981,1.99810,0.000,6,2019
103390,106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.50930,0.070,6,2019
103391,106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,...,3.699,1.179,0.001,2.518,0.000,2.5175,2.51750,0.000,6,2019

In [64]:
data_pre_fill[mask] # valores que eram NaN, agora são 0

Empty DataFrame
Columns: [Unnamed: 0.1, Unnamed: 0, DATA INICIAL, DATA FINAL, REGIÃO, ESTADO, PRODUTO, NÚMERO DE POSTOS PESQUISADOS, UNIDADE DE MEDIDA, PREÇO MÉDIO REVENDA, DESVIO PADRÃO REVENDA, PREÇO MÍNIMO REVENDA, PREÇO MÁXIMO REVENDA, MARGEM MÉDIA REVENDA, COEF DE VARIAÇÃO REVENDA, PREÇO MÉDIO DISTRIBUIÇÃO, DESVIO PADRÃO DISTRIBUIÇÃO, PREÇO MÍNIMO DISTRIBUIÇÃO, PREÇO MÁXIMO DISTRIBUIÇÃO, COEF DE VARIAÇÃO DISTRIBUIÇÃO, MÊS, ANO]
Index: []

[0 rows x 22 columns]

In [65]:
# retorna uma cópia do data frame 'data_pre' com todos os valores NaN das colunas:
# 'PREÇO MÉDIO DISTRIBUIÇÃO', 'DESVIO PADRÃO DISTRIBUIÇÃO', 'PREÇO MÍNIMO DISTRIBUIÇÃO' E 'MÉDIO MÁXIMO DISTRIBUIÇÃO', respectivamente,
data_pre_fill = data_pre.fillna(value={
    'PREÇO MÉDIO DISTRIBUIÇÃO': 10,
    'DESVIO PADRÃO DISTRIBUIÇÃO': 20,
    'PREÇO MÍNIMO DISTRIBUIÇÃO': 30,
    'PREÇO MÁXIMO DISTRIBUIÇÃO': 'vazio'
})

In [66]:
data_pre_fill[mask]

Empty DataFrame
Columns: [Unnamed: 0.1, Unnamed: 0, DATA INICIAL, DATA FINAL, REGIÃO, ESTADO, PRODUTO, NÚMERO DE POSTOS PESQUISADOS, UNIDADE DE MEDIDA, PREÇO MÉDIO REVENDA, DESVIO PADRÃO REVENDA, PREÇO MÍNIMO REVENDA, PREÇO MÁXIMO REVENDA, MARGEM MÉDIA REVENDA, COEF DE VARIAÇÃO REVENDA, PREÇO MÉDIO DISTRIBUIÇÃO, DESVIO PADRÃO DISTRIBUIÇÃO, PREÇO MÍNIMO DISTRIBUIÇÃO, PREÇO MÁXIMO DISTRIBUIÇÃO, COEF DE VARIAÇÃO DISTRIBUIÇÃO, MÊS, ANO]
Index: []

[0 rows x 22 columns]

In [67]:
# remove, no próprio dataframe, todas as linhas/registros com valores NaN (vazios) em quaisquer colunas colunas/atributos.
data_pre.dropna(inplace=True)

In [68]:
data_pre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103392 entries, 0 to 103391
Data columns (total 22 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Unnamed: 0.1                   103392 non-null  int64
 1   Unnamed: 0                     103392 non-null  int64
 2   DATA INICIAL                   103392 non-null  datetime64[ns]
 3   DATA FINAL                     103392 non-null  datetime64[ns]
 4   REGIÃO                         103392 non-null  object
 5   ESTADO                         103392 non-null  object
 6   PRODUTO                        103392 non-null  object
 7   NÚMERO DE POSTOS PESQUISADOS   103392 non-null  int64
 8   UNIDADE DE MEDIDA              103392 non-null  object
 9   PREÇO MÉDIO REVENDA            103392 non-null  float64
 10  DESVIO PADRÃO REVENDA          103392 non-null  float64
 11  PREÇO MÍNIMO REVENDA           103392 non-null  float64
 12  PREÇO MÁXIMO REVENDA           103392 non-null  float64
 13  MARGEM MÉDIA REVENDA           103392 non-null  float64
 14  COEF DE VARIAÇÃO REVENDA       103392 non-null  float64
 15  PREÇO MÉDIO DISTRIBUIÇÃO       103392 non-null  float64
 16  DESVIO PADRÃO DISTRIBUIÇÃO     103392 non-null  float64
 17  PREÇO MÍNIMO DISTRIBUIÇÃO      103392 non-null  float64
 18  PREÇO MÁXIMO DISTRIBUIÇÃO      103392 non-null  float64
 19  COEF DE VARIAÇÃO DISTRIBUIÇÃO  103392 non-null  float64
 20  MÊS                            103392 non-null  int64
 21  ANO                            103392 non-null  int64
dtypes: datetime64[ns](2), float64(11), int64(5), object(4)
memory usage: 17.4+ MB

In [69]:
data_pre.to_csv('./sample_data/GasPricesinBrazil_2004-2019.csv')