In [36]:
# Aula 3
import pandas as pd

In [4]:
# carregando dataset corretamente ==> neste caso usa o separador ';'.
data = pd.read_csv('./sample_data/GasPricesinBrazil_2004-2019.csv', sep=";")

In [20]:
data

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106818,106818,2019-06-23,2019-06-29,NORDESTE,RIO GRANDE DO NORTE,GNV,7,R$/m3,3.574,0.065,...,3.690,0.818,0.018,2.756,0,2.756,2.756,0,6,2019
106819,106819,2019-06-23,2019-06-29,SUL,RIO GRANDE DO SUL,GNV,23,R$/m3,3.401,0.129,...,3.789,0.95,0.038,2.451,0.402,1.9842,2.8661,0.164,6,2019
106820,106820,2019-06-23,2019-06-29,SUL,SANTA CATARINA,GNV,24,R$/m3,2.912,0.190,...,3.499,0.914,0.065,1.998,0,1.9981,1.9981,0,6,2019
106821,106821,2019-06-23,2019-06-29,SUDESTE,SAO PAULO,GNV,52,R$/m3,3.020,0.229,...,3.490,0.646,0.076,2.374,0.165,2.0179,2.5093,0.07,6,2019
106822,106822,2019-06-23,2019-06-29,NORDESTE,SERGIPE,GNV,4,R$/m3,3.697,0.005,...,3.699,1.179,0.001,2.518,0,2.5175,2.5175,0,6,2019

In [6]:
# Mostra as 5 primeiras linhas do dataframe
#data.head()

# Mostra as 10 primeiras linhas do dataframe
data.head(10)

,Unnamed: 0,DATA INICIAL,DATA FINAL,REGIÃO,ESTADO,PRODUTO,NÚMERO DE POSTOS PESQUISADOS,UNIDADE DE MEDIDA,PREÇO MÉDIO REVENDA,DESVIO PADRÃO REVENDA,...,PREÇO MÁXIMO REVENDA,MARGEM MÉDIA REVENDA,COEF DE VARIAÇÃO REVENDA,PREÇO MÉDIO DISTRIBUIÇÃO,DESVIO PADRÃO DISTRIBUIÇÃO,PREÇO MÍNIMO DISTRIBUIÇÃO,PREÇO MÁXIMO DISTRIBUIÇÃO,COEF DE VARIAÇÃO DISTRIBUIÇÃO,MÊS,ANO
0,0,2004-05-09,2004-05-15,CENTRO OESTE,DISTRITO FEDERAL,ETANOL HIDRATADO,127,R$/l,1.288,0.016,...,1.350,0.463,0.012,0.825,0.11,0.4201,0.9666,0.133,5,2004
1,1,2004-05-09,2004-05-15,CENTRO OESTE,GOIAS,ETANOL HIDRATADO,387,R$/l,1.162,0.114,...,1.449,0.399,0.098,0.763,0.088,0.5013,1.05,0.115,5,2004
2,2,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO,ETANOL HIDRATADO,192,R$/l,1.389,0.097,...,1.760,0.419,0.070,0.97,0.095,0.5614,1.161,0.098,5,2004
3,3,2004-05-09,2004-05-15,CENTRO OESTE,MATO GROSSO DO SUL,ETANOL HIDRATADO,162,R$/l,1.262,0.070,...,1.509,0.432,0.055,0.83,0.119,0.5991,1.22242,0.143,5,2004
4,4,2004-05-09,2004-05-15,NORDESTE,ALAGOAS,ETANOL HIDRATADO,103,R$/l,1.181,0.078,...,1.400,0.24,0.066,0.941,0.077,0.7441,1.0317,0.082,5,2004
5,5,2004-05-09,2004-05-15,NORDESTE,BAHIA,ETANOL HIDRATADO,408,R$/l,1.383,0.132,...,2.050,0.426,0.095,0.957,0.128,0.5686,1.35,0.134,5,2004
6,6,2004-05-09,2004-05-15,NORDESTE,CEARA,ETANOL HIDRATADO,278,R$/l,1.453,0.218,...,1.950,0.353,0.150,1.1,0.068,0.7332,1.294,0.062,5,2004
7,7,2004-05-09,2004-05-15,NORDESTE,MARANHAO,ETANOL HIDRATADO,105,R$/l,1.631,0.158,...,2.000,0.515,0.097,1.116,0.091,0.9923,1.36183,0.082,5,2004
8,8,2004-05-09,2004-05-15,NORDESTE,PARAIBA,ETANOL HIDRATADO,125,R$/l,1.284,0.130,...,1.699,0.353,0.101,0.931,0.072,0.7577,1.2972,0.077,5,2004
9,9,2004-05-09,2004-05-15,NORDESTE,PERNAMBUCO,ETANOL HIDRATADO,423,R$/l,1.224,0.141,...,1.700,0.277,0.115,0.947,0.091,0.5643,1.3541,0.096,5,2004

In [7]:
# Aula 4
# Vídeo Curso #04
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106823 entries, 0 to 106822
Data columns (total 21 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Unnamed: 0                     106823 non-null  int64
 1   DATA INICIAL                   106823 non-null  object
 2   DATA FINAL                     106823 non-null  object
 3   REGIÃO                         106823 non-null  object
 4   ESTADO                         106823 non-null  object
 5   PRODUTO                        106823 non-null  object
 6   NÚMERO DE POSTOS PESQUISADOS   106823 non-null  int64
 7   UNIDADE DE MEDIDA              106823 non-null  object
 8   PREÇO MÉDIO REVENDA            106823 non-null  float64
 9   DESVIO PADRÃO REVENDA          106823 non-null  float64
 10  PREÇO MÍNIMO REVENDA           106823 non-null  float64
 11  PREÇO MÁXIMO REVENDA           106823 non-null  float64
 12  MARGEM MÉDIA REVENDA           106823 non-null  object
 13  COEF DE VARIAÇÃO REVENDA       106823 non-null  float64
 14  PREÇO MÉDIO DISTRIBUIÇÃO       106823 non-null  object
 15  DESVIO PADRÃO DISTRIBUIÇÃO     106823 non-null  object
 16  PREÇO MÍNIMO DISTRIBUIÇÃO      106823 non-null  object
 17  PREÇO MÁXIMO DISTRIBUIÇÃO      106823 non-null  object
 18  COEF DE VARIAÇÃO DISTRIBUIÇÃO  106823 non-null  object
 19  MÊS                            106823 non-null  int64
 20  ANO                            106823 non-null  int64
dtypes: float64(5), int64(4), object(12)
memory usage: 17.1+ MB

In [8]:
# Aula 5
# Diz qual o tipo da variável
type(data)

pandas.core.frame.DataFrame

In [12]:
# Mostra a forma da variável
data.shape

(106823, 21)

In [13]:
print(f'O Data Frame possui {data.shape[0]} linhas/observações/registros e {data.shape[1]} colunas/atributos/variáveis.')

O Data Frame possui 106823 linhas/observações/registros e 21 colunas/atributos/variáveis.

In [17]:
# Criando um DataFrame

personagens_df = pd.DataFrame({
    'nome': ['Luke Skywalker', 'Yoda', 'Palpatine'],
    'idade': [16, 1000, 70],
    'peso': [70.5, 15.2, 60.1],
    'eh jedi': [True, True, False]} # o nome das colunas podem ter espaçoes
)

In [18]:
# Printa o DataFrame criado a cima
personagens_df

             nome  idade  peso  eh jedi
0  Luke Skywalker     16  70.5     True
1            Yoda   1000  15.2     True
2       Palpatine     70  60.1    False

In [19]:
# Diz as inforrmações sobre o DataFrame
personagens_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   nome     3 non-null      object
 1   idade    3 non-null      int64
 2   peso     3 non-null      float64
 3   eh jedi  3 non-null      bool
dtypes: bool(1), float64(1), int64(1), object(1)
memory usage: 207.0+ bytes

In [21]:
# Printa o dicionário
personagens_df.columns

Index(['nome', 'idade', 'peso', 'eh jedi'], dtype='object')

In [22]:
# Mostra o tipo de "personagens"
type(personagens_df.columns)

pandas.core.indexes.base.Index

In [23]:
# Mostra a lista criada com a variável "personagens"
list(personagens_df.columns)

['nome', 'idade', 'peso', 'eh jedi']

In [24]:
# Mostra o DataFrame normal de personagens_df
personagens_df

             nome  idade  peso  eh jedi
0  Luke Skywalker     16  70.5     True
1            Yoda   1000  15.2     True
2       Palpatine     70  60.1    False

In [26]:
personagens_df_renomeado = personagens_df.rename(columns={
    'nome': 'Nome Completo', # renomeia a coluna de nome 'nome] para 'Nome Completo'
    'idade': 'Idade'
})

In [27]:
# Mostra o DataFrame com as alterações feitas acima
personagens_df_renomeado

    Nome Completo  Idade  peso  eh jedi
0  Luke Skywalker     16  70.5     True
1            Yoda   1000  15.2     True
2       Palpatine     70  60.1    False

In [28]:
# Mostra o DataFrame original sem algterações
personagens_df

             nome  idade  peso  eh jedi
0  Luke Skywalker     16  70.5     True
1            Yoda   1000  15.2     True
2       Palpatine     70  60.1    False

In [29]:
# Coloca as alterações no DataFrame original
personagens_df.rename(columns={'nome': 'Nome Completo', 'idade': 'Idade'}, inplace=True)

In [30]:
# Mostra o DataFrame original com as alterações
personagens_df

    Nome Completo  Idade  peso  eh jedi
0  Luke Skywalker     16  70.5     True
1            Yoda   1000  15.2     True
2       Palpatine     70  60.1    False

In [34]:
# Retorna a lista de "personagens_df"
personagens_df.columns

Index(['NOME', 'IDADE', 'PESO', 'EH JEDI'], dtype='object')

In [33]:
# Muda o nome dos dicionários do DataFrame "personagens"
personagens_df.columns = ['NOME', 'IDADE', 'PESO', 'EH JEDI']

In [ ]:
personagens_df

             NOME  IDADE  PESO  EH JEDI
0  Luke Skywalker     16  70.5     True
1            Yoda   1000  15.2     True
2       Palpatine     70  60.1    False