## Importação das Bibliotecas

In [1]:
import numpy as np
import pandas as pd
import plotly.express as px

In [2]:
df = pd.read_csv('tips.csv')

In [3]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

## 1. Gráfico de Barras

In [5]:
df_agrupado_pelo_dia = df.groupby('day').agg({ 'total_bill': np.mean }).reset_index()

/tmp/ipykernel_21302/3619961275.py:1: FutureWarning: The provided callable <function mean at 0x76bd21cbfb50> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df_agrupado_pelo_dia = df.groupby('day').agg({ 'total_bill': np.mean }).reset_index()

In [6]:
df_agrupado_pelo_dia_e_sexo

NameError: name 'df_agrupado_pelo_dia_e_sexo' is not defined

In [ ]:
px.bar(df_agrupado_pelo_dia, x= 'day', y=('total_bill'))

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'day=%{x}<br>total_bill=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '',
              'orientation': 'v',
              'showlegend': False,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['Fri', 'Sat', 'Sun', 'Thur'], dtype=object),
              'xaxis': 'x',
              'y': {'bdata': 'oLW94M0mMUDkDwc8/nA0QClcj8L1aDVAzoLsLMiuMUA=', 'dtype': 'f8'},
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'day'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'total_bill'}}}
})

In [ ]:
df_agrupado_pelo_dia_e_sexo = df.groupby(['day','sex'], sort=False).agg({'total_bill': np.sum}).reset_index()

/tmp/ipykernel_11272/2819425906.py:1: FutureWarning:

The provided callable <function sum at 0x794f7d5d2950> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.

In [ ]:
df_agrupado_pelo_dia_e_sexo

    day     sex  total_bill
0   Sun  Female      357.70
1   Sun    Male     1269.46
2   Sat    Male     1227.35
3   Sat  Female      551.05
4  Thur    Male      561.44
5  Thur  Female      534.89
6   Fri    Male      198.57
7   Fri  Female      127.31

In [ ]:
px.bar(df_agrupado_pelo_dia_e_sexo, x='day', y='total_bill', color='sex', barmode='group')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'alignmentgroup': 'True',
              'hovertemplate': 'sex=Female<br>day=%{x}<br>total_bill=%{y}<extra></extra>',
              'legendgroup': 'Female',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': 'Female',
              'offsetgroup': 'Female',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['Sun', 'Sat', 'Thur', 'Fri'], dtype=object),
              'xaxis': 'x',
              'y': {'bdata': 'MzMzMzNbdkBmZmZmZjiBQIXrUbget4BApHA9CtfTX0A=', 'dtype': 'f8'},
              'yaxis': 'y'},
             {'alignmentgroup': 'True',
              'hovertemplate': 'sex=Male<br>day=%{x}<br>total_bill=%{y}<extra></extra>',
              'legendgroup': 'Male',
              'marker': {'color': '#EF553B', 'pattern': {'shape': ''}},
              'name': 'Male',
              'offsetgroup': 'Male',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['Sun', 'Sat', 'Thur', 'Fri'], dtype=object),
              'xaxis': 'x',
              'y': {'bdata': 'pHA9CtfVk0BmZmZmZi2TQOtRuB6Fi4FACtejcD3SaEA=', 'dtype': 'f8'},
              'yaxis': 'y'}],
    'layout': {'barmode': 'group',
               'legend': {'title': {'text': 'sex'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'day'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'total_bill'}}}
})

In [ ]:
px.bar(df_agrupado_pelo_dia_e_sexo, x='total_bill', y='day', color='sex', barmode='group', orientation='h')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'alignmentgroup': 'True',
              'hovertemplate': 'sex=Female<br>total_bill=%{x}<br>day=%{y}<extra></extra>',
              'legendgroup': 'Female',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': 'Female',
              'offsetgroup': 'Female',
              'orientation': 'h',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': {'bdata': 'MzMzMzNbdkBmZmZmZjiBQIXrUbget4BApHA9CtfTX0A=', 'dtype': 'f8'},
              'xaxis': 'x',
              'y': array(['Sun', 'Sat', 'Thur', 'Fri'], dtype=object),
              'yaxis': 'y'},
             {'alignmentgroup': 'True',
              'hovertemplate': 'sex=Male<br>total_bill=%{x}<br>day=%{y}<extra></extra>',
              'legendgroup': 'Male',
              'marker': {'color': '#EF553B', 'pattern': {'shape': ''}},
              'name': 'Male',
              'offsetgroup': 'Male',
              'orientation': 'h',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': {'bdata': 'pHA9CtfVk0BmZmZmZi2TQOtRuB6Fi4FACtejcD3SaEA=', 'dtype': 'f8'},
              'xaxis': 'x',
              'y': array(['Sun', 'Sat', 'Thur', 'Fri'], dtype=object),
              'yaxis': 'y'}],
    'layout': {'barmode': 'group',
               'legend': {'title': {'text': 'sex'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'total_bill'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'day'}}}
})

## Gráfico de Dispersão

In [ ]:
px.scatter(df, x='total_bill', y='tip', color='day',hover_name='time')

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': '<b>%{hovertext}</b><br><br>day=Sun<br>total_bill=%{x}<br>tip=%{y}<extra></extra>',
              'hovertext': array(['Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
                                  'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
                                  'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
                                  'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
                                  'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
                                  'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
                                  'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
                                  'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
                                  'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
                                  'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
                                  'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner'],
                                 dtype=object),
              'legendgroup': 'Sun',
              'marker': {'color': '#636efa', 'symbol': 'circle'},
              'mode': 'markers',
              'name': 'Sun',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': {'bdata': ('PQrXo3D9MECuR+F6FK4kQMP1KFyPAj' ... 'ZmZiYyQJqZmZmZGTdA4XoUrkdhL0A='),
                    'dtype': 'f8'},
              'xaxis': 'x',
              'y': {'bdata': ('KVyPwvUo8D+PwvUoXI/6PwAAAAAAAA' ... 'AAAAAMQAAAAAAAABBAAAAAAAAA+D8='),
                    'dtype': 'f8'},
              'yaxis': 'y'},
             {'hovertemplate': '<b>%{hovertext}</b><br><br>day=Sat<br>total_bill=%{x}<br>tip=%{y}<extra></extra>',
              'hovertext': array(['Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
                                  'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
                                  'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
                                  'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
                                  'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
                                  'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
                                  'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
                                  'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
                                  'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
                                  'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
                                  'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
                                  'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
                                  'Dinner', 'Dinner', 'Dinner'], dtype=object),
              'legendgroup': 'Sat',
              'marker': {'color': '#EF553B', 'symbol': 'circle'},
              'mode': 'markers',
              'name': 'Sat',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': {'bdata': ('ZmZmZmamNEDsUbgehesxQArXo3A9Sj' ... 'fhehQuO0DsUbgehas2QFK4HoXr0TFA'),
                    'dtype': 'f8'},
              'xaxis': 'x',
              'y': {'bdata': ('zczMzMzMCkBSuB6F61EQQAAAAAAAAA' ... 'AAAAAAAEAAAAAAAAAAQAAAAAAAAPw/'),
                    'dtype': 'f8'},
              'yaxis': 'y'},
             {'hovertemplate': ('<b>%{hovertext}</b><br><br>day' ... '{x}<br>tip=%{y}<extra></extra>'),
              'hovertext': array(['Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch',
                                  'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch',
                                  'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch',
                                  'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch',
                                  'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch',
                                  'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch',
                                  'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch',
                                  'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Dinner'], dtype=object),
              'legendgroup': 'Thur',
              'marker': {'color': '#00cc96', 'symbol': 'circle'},
              'mode': 'markers',
              'name': 'Thur',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': {'bdata': ('MzMzMzMzO0DD9Shcj8I2QArXo3A9Sj' ... 'SuhzRAuB6F61F4MEBI4XoUrscyQA=='),
                    'dtype': 'f8'},
              'xaxis': 'x',
              'y': {'bdata': ('AAAAAAAAEEAAAAAAAAAIQK5H4XoUrg' ... 'AAABBA16NwPQrXCUAAAAAAAAAIQA=='),
                    'dtype': 'f8'},
              'yaxis': 'y'},
             {'hovertemplate': '<b>%{hovertext}</b><br><br>day=Fri<br>total_bill=%{x}<br>tip=%{y}<extra></extra>',
              'hovertext': array(['Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner',
                                  'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Dinner', 'Lunch', 'Lunch',
                                  'Lunch', 'Lunch', 'Lunch', 'Lunch', 'Lunch'], dtype=object),
              'legendgroup': 'Fri',
              'marker': {'color': '#ab63fa', 'symbol': 'circle'},
              'mode': 'markers',
              'name': 'Fri',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': {'bdata': ('uB6F61H4PEA9CtejcH02QAAAAAAAAB' ... 'A9CtcqQIXrUbgeRTBArkfhehQuJEA='),
                    'dtype': 'f8'},
              'xaxis': 'x',
              'y': {'bdata': ('AAAAAAAACEAAAAAAAAAMQAAAAAAAAP' ... 'oUrkf5PwAAAAAAAARAAAAAAAAAAEA='),
                    'dtype': 'f8'},
              'yaxis': 'y'}],
    'layout': {'legend': {'title': {'text': 'day'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'total_bill'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'tip'}}}
})

## Gráfico de Pizza

In [ ]:
quantidade_pedidos_por_dia = df['day'].value_counts()

In [ ]:
quantidade_pedidos_por_dia

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [ ]:
quantidade_pedidos_por_dia.index

Index(['Sat', 'Sun', 'Thur', 'Fri'], dtype='object', name='day')

In [ ]:
quantidade_pedidos_por_dia.values

array([87, 76, 62, 19])

In [ ]:
px.pie(quantidade_pedidos_por_dia, names=quantidade_pedidos_por_dia.index, values=quantidade_pedidos_por_dia.values)

NameError: name 'px' is not defined